import { useState, useMemo } from "react";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Search, BookOpen, FlaskConical, Wrench, Beaker, ShieldCheck, Bookmark, BookmarkCheck, Download, FileText, Building2 } from "lucide-react";
import { referenceLibrary, sectionLabels, departments, type ReferenceEntry } from "@/lib/referenceLibraryData";
import jsPDF from "jspdf";

const sectionIcons: Record<string, React.ReactNode> = {
  'protocols': <FileText className="h-4 w-4" />,
  'test-principles': <FlaskConical className="h-4 w-4" />,
  'instruments': <Wrench className="h-4 w-4" />,
  'reagents': <Beaker className="h-4 w-4" />,
  'quality-control': <ShieldCheck className="h-4 w-4" />,
};

function generateEntryPdf(entry: ReferenceEntry) {
  const doc = new jsPDF();
  let y = 20;
  const margin = 20;
  const pageWidth = 170;

  const addLine = (text: string, fontSize = 10, bold = false) => {
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", bold ? "bold" : "normal");
    const lines = doc.splitTextToSize(text, pageWidth);
    if (y + lines.length * (fontSize * 0.5) > 280) {
      doc.addPage();
      y = 20;
    }
    doc.text(lines, margin, y);
    y += lines.length * (fontSize * 0.45) + 3;
  };

  const addSection = (title: string) => {
    y += 4;
    addLine(title, 12, true);
    y += 1;
  };

  addLine(entry.title, 16, true);
  addLine(`Department: ${entry.department} | Section: ${sectionLabels[entry.section]}`, 10);
  y += 2;
  addLine(entry.description, 10);

  if (entry.principle) { addSection("Principle"); addLine(entry.principle); }
  if (entry.mechanism) { addSection("Mechanism"); addLine(entry.mechanism); }
  if (entry.clinicalSignificance) { addSection("Clinical Significance"); addLine(entry.clinicalSignificance); }
  if (entry.normalRanges) { addSection("Normal Ranges"); addLine(entry.normalRanges); }
  if (entry.equipment?.length) { addSection("Equipment"); entry.equipment.forEach(e => addLine(`• ${e}`)); }
  if (entry.reagents?.length) { addSection("Reagents"); entry.reagents.forEach(r => addLine(`• ${r}`)); }
  if (entry.composition?.length) { addSection("Composition"); entry.composition.forEach(c => addLine(`• ${c}`)); }
  if (entry.procedure?.length) { addSection("Procedure"); entry.procedure.forEach((s, i) => addLine(`${i + 1}. ${s}`)); }
  if (entry.operatingProcedure?.length) { addSection("Operating Procedure"); entry.operatingProcedure.forEach((s, i) => addLine(`${i + 1}. ${s}`)); }
  if (entry.expectedResults) { addSection("Expected Results"); addLine(entry.expectedResults); }
  if (entry.commonErrors?.length) { addSection("Common Errors"); entry.commonErrors.forEach(e => addLine(`• ${e}`)); }
  if (entry.components?.length) { addSection("Components"); entry.components.forEach(c => addLine(`• ${c}`)); }
  if (entry.calibration) { addSection("Calibration"); addLine(entry.calibration); }
  if (entry.maintenance?.length) { addSection("Maintenance"); entry.maintenance.forEach(m => addLine(`• ${m}`)); }
  if (entry.troubleshooting?.length) { addSection("Troubleshooting"); entry.troubleshooting.forEach(t => addLine(`• ${t}`)); }
  if (entry.storageConditions) { addSection("Storage"); addLine(entry.storageConditions); }
  if (entry.shelfLife) { addLine(`Shelf Life: ${entry.shelfLife}`); }
  if (entry.safetyPrecautions?.length) { addSection("Safety Precautions"); entry.safetyPrecautions.forEach(s => addLine(`• ${s}`)); }
  if (entry.limitations?.length) { addSection("Limitations"); entry.limitations.forEach(l => addLine(`• ${l}`)); }
  if (entry.qcNotes?.length) { addSection("Quality Control Notes"); entry.qcNotes.forEach(q => addLine(`• ${q}`)); }
  if (entry.references?.length) { addSection("References"); entry.references.forEach(r => addLine(`• ${r}`)); }

  y += 6;
  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.text(`Generated by MicroID Reference Library • ${new Date().toLocaleDateString()}`, margin, 288);

  doc.save(`${entry.title.replace(/\s+/g, "_")}.pdf`);
}

function ReferenceEntryCard({ entry, isBookmarked, onToggleBookmark }: {
  entry: ReferenceEntry;
  isBookmarked: boolean;
  onToggleBookmark: () => void;
}) {
  return (
    <AccordionItem value={entry.id} className="border rounded-lg mb-3 overflow-hidden">
      <AccordionTrigger className="px-4 py-3 hover:no-underline hover:bg-muted/50">
        <div className="flex items-start gap-3 text-left flex-1">
          <div className="mt-0.5">{sectionIcons[entry.section]}</div>
          <div className="flex-1 min-w-0">
            <div className="font-semibold text-sm">{entry.title}</div>
            <div className="flex items-center gap-2 mt-1 flex-wrap">
              <Badge variant="outline" className="text-xs">{entry.department}</Badge>
              <Badge variant="secondary" className="text-xs">{sectionLabels[entry.section]}</Badge>
            </div>
          </div>
        </div>
      </AccordionTrigger>
      <AccordionContent className="px-4 pb-4">
        <div className="space-y-4">
          <p className="text-sm text-muted-foreground">{entry.description}</p>

          {entry.principle && (
            <div>
              <h4 className="text-sm font-semibold mb-1">Principle</h4>
              <p className="text-sm text-muted-foreground">{entry.principle}</p>
            </div>
          )}
          {entry.mechanism && (
            <div>
              <h4 className="text-sm font-semibold mb-1">Mechanism</h4>
              <p className="text-sm text-muted-foreground">{entry.mechanism}</p>
            </div>
          )}
          {entry.clinicalSignificance && (
            <div>
              <h4 className="text-sm font-semibold mb-1">Clinical Significance</h4>
              <p className="text-sm text-muted-foreground">{entry.clinicalSignificance}</p>
            </div>
          )}
          {entry.normalRanges && (
            <div>
              <h4 className="text-sm font-semibold mb-1">Reference Ranges</h4>
              <p className="text-sm text-muted-foreground">{entry.normalRanges}</p>
            </div>
          )}
          {entry.equipment && entry.equipment.length > 0 && (
            <div>
              <h4 className="text-sm font-semibold mb-1">Equipment</h4>
              <ul className="text-sm text-muted-foreground list-disc list-inside space-y-0.5">
                {entry.equipment.map((e, i) => <li key={i}>{e}</li>)}
              </ul>
            </div>
          )}
          {entry.reagents && entry.reagents.length > 0 && (
            <div>
              <h4 className="text-sm font-semibold mb-1">Reagents</h4>
              <ul className="text-sm text-muted-foreground list-disc list-inside space-y-0.5">
                {entry.reagents.map((r, i) => <li key={i}>{r}</li>)}
              </ul>
            </div>
          )}
          {entry.composition && entry.composition.length > 0 && (
            <div>
              <h4 className="text-sm font-semibold mb-1">Composition</h4>
              <ul className="text-sm text-muted-foreground list-disc list-inside space-y-0.5">
                {entry.composition.map((c, i) => <li key={i}>{c}</li>)}
              </ul>
            </div>
          )}
          {entry.components && entry.components.length > 0 && (
            <div>
              <h4 className="text-sm font-semibold mb-1">Components</h4>
              <ul className="text-sm text-muted-foreground list-disc list-inside space-y-0.5">
                {entry.components.map((c, i) => <li key={i}>{c}</li>)}
              </ul>
            </div>
          )}
          {entry.procedure && entry.procedure.length > 0 && (
            <div>
              <h4 className="text-sm font-semibold mb-1">Procedure</h4>
              <ol className="text-sm text-muted-foreground list-decimal list-inside space-y-1">
                {entry.procedure.map((s, i) => <li key={i}>{s}</li>)}
              </ol>
            </div>
          )}
          {entry.operatingProcedure && entry.operatingProcedure.length > 0 && (
            <div>
              <h4 className="text-sm font-semibold mb-1">Operating Procedure</h4>
              <ol className="text-sm text-muted-foreground list-decimal list-inside space-y-1">
                {entry.operatingProcedure.map((s, i) => <li key={i}>{s}</li>)}
              </ol>
            </div>
          )}
          {entry.expectedResults && (
            <div>
              <h4 className="text-sm font-semibold mb-1">Expected Results</h4>
              <p className="text-sm text-muted-foreground">{entry.expectedResults}</p>
            </div>
          )}
          {entry.commonErrors && entry.commonErrors.length > 0 && (
            <div>
              <h4 className="text-sm font-semibold mb-1">Common Errors</h4>
              <ul className="text-sm text-muted-foreground list-disc list-inside space-y-0.5">
                {entry.commonErrors.map((e, i) => <li key={i}>{e}</li>)}
              </ul>
            </div>
          )}
          {entry.calibration && (
            <div>
              <h4 className="text-sm font-semibold mb-1">Calibration</h4>
              <p className="text-sm text-muted-foreground">{entry.calibration}</p>
            </div>
          )}
          {entry.maintenance && entry.maintenance.length > 0 && (
            <div>
              <h4 className="text-sm font-semibold mb-1">Maintenance</h4>
              <ul className="text-sm text-muted-foreground list-disc list-inside space-y-0.5">
                {entry.maintenance.map((m, i) => <li key={i}>{m}</li>)}
              </ul>
            </div>
          )}
          {entry.troubleshooting && entry.troubleshooting.length > 0 && (
            <div>
              <h4 className="text-sm font-semibold mb-1">Troubleshooting</h4>
              <ul className="text-sm text-muted-foreground list-disc list-inside space-y-0.5">
                {entry.troubleshooting.map((t, i) => <li key={i}>{t}</li>)}
              </ul>
            </div>
          )}
          {entry.storageConditions && (
            <div>
              <h4 className="text-sm font-semibold mb-1">Storage Conditions</h4>
              <p className="text-sm text-muted-foreground">{entry.storageConditions}</p>
            </div>
          )}
          {entry.shelfLife && (
            <div>
              <h4 className="text-sm font-semibold mb-1">Shelf Life</h4>
              <p className="text-sm text-muted-foreground">{entry.shelfLife}</p>
            </div>
          )}
          {entry.safetyPrecautions && entry.safetyPrecautions.length > 0 && (
            <div>
              <h4 className="text-sm font-semibold mb-1">Safety Precautions</h4>
              <ul className="text-sm text-muted-foreground list-disc list-inside space-y-0.5">
                {entry.safetyPrecautions.map((s, i) => <li key={i}>{s}</li>)}
              </ul>
            </div>
          )}
          {entry.limitations && entry.limitations.length > 0 && (
            <div>
              <h4 className="text-sm font-semibold mb-1">Limitations</h4>
              <ul className="text-sm text-muted-foreground list-disc list-inside space-y-0.5">
                {entry.limitations.map((l, i) => <li key={i}>{l}</li>)}
              </ul>
            </div>
          )}
          {entry.qcNotes && entry.qcNotes.length > 0 && (
            <div>
              <h4 className="text-sm font-semibold mb-1">Quality Control Notes</h4>
              <ul className="text-sm text-muted-foreground list-disc list-inside space-y-0.5">
                {entry.qcNotes.map((q, i) => <li key={i}>{q}</li>)}
              </ul>
            </div>
          )}
          {entry.references && entry.references.length > 0 && (
            <div>
              <h4 className="text-sm font-semibold mb-1">References</h4>
              <ul className="text-sm text-muted-foreground list-disc list-inside space-y-0.5">
                {entry.references.map((r, i) => <li key={i} className="italic">{r}</li>)}
              </ul>
            </div>
          )}

          <div className="flex gap-2 pt-2 border-t">
            <Button size="sm" variant="outline" onClick={onToggleBookmark} className="gap-1.5">
              {isBookmarked ? <BookmarkCheck className="h-3.5 w-3.5" /> : <Bookmark className="h-3.5 w-3.5" />}
              {isBookmarked ? "Bookmarked" : "Bookmark"}
            </Button>
            <Button size="sm" variant="outline" onClick={() => generateEntryPdf(entry)} className="gap-1.5">
              <Download className="h-3.5 w-3.5" />
              Download PDF
            </Button>
          </div>
        </div>
      </AccordionContent>
    </AccordionItem>
  );
}

export default function ReferenceLibrary() {
  const [search, setSearch] = useState("");
  const [selectedDept, setSelectedDept] = useState<string>("all");
  const [activeTab, setActiveTab] = useState("protocols");
  const [bookmarks, setBookmarks] = useState<Set<string>>(() => {
    try {
      const saved = localStorage.getItem("microid-ref-bookmarks");
      return saved ? new Set(JSON.parse(saved)) : new Set();
    } catch { return new Set(); }
  });
  const [showBookmarksOnly, setShowBookmarksOnly] = useState(false);

  const toggleBookmark = (id: string) => {
    setBookmarks(prev => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id); else next.add(id);
      localStorage.setItem("microid-ref-bookmarks", JSON.stringify([...next]));
      return next;
    });
  };

  const filtered = useMemo(() => {
    return referenceLibrary.filter(entry => {
      if (showBookmarksOnly && !bookmarks.has(entry.id)) return false;
      if (entry.section !== activeTab) return false;
      if (selectedDept !== "all" && entry.department !== selectedDept) return false;
      if (search) {
        const q = search.toLowerCase();
        return (
          entry.title.toLowerCase().includes(q) ||
          entry.description.toLowerCase().includes(q) ||
          entry.department.toLowerCase().includes(q) ||
          entry.tags?.some(t => t.toLowerCase().includes(q))
        );
      }
      return true;
    });
  }, [search, selectedDept, activeTab, bookmarks, showBookmarksOnly]);

  const sectionCounts = useMemo(() => {
    const counts: Record<string, number> = {};
    Object.keys(sectionLabels).forEach(s => {
      counts[s] = referenceLibrary.filter(e => e.section === s).length;
    });
    return counts;
  }, []);

  return (
    <div className="min-h-screen flex flex-col bg-background">
      <Header />
      <main className="flex-1 container py-6 space-y-6">
        <div className="space-y-2">
          <div className="flex items-center gap-3">
            <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary text-primary-foreground">
              <BookOpen className="h-5 w-5" />
            </div>
            <div>
              <h1 className="text-2xl font-bold tracking-tight">Laboratory Reference Library</h1>
              <p className="text-sm text-muted-foreground">
                Validated protocols aligned with NABL, ICMR, ISO 15189, CLSI & WHO standards
              </p>
            </div>
          </div>
        </div>

        {/* Filters */}
        <Card>
          <CardContent className="pt-4 pb-4">
            <div className="flex flex-col sm:flex-row gap-3">
              <div className="relative flex-1">
                <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                <Input
                  placeholder="Search protocols, tests, instruments..."
                  value={search}
                  onChange={e => setSearch(e.target.value)}
                  className="pl-9"
                />
              </div>
              <Select value={selectedDept} onValueChange={setSelectedDept}>
                <SelectTrigger className="w-full sm:w-[200px]">
                  <Building2 className="h-4 w-4 mr-2" />
                  <SelectValue placeholder="Department" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Departments</SelectItem>
                  {departments.map(d => (
                    <SelectItem key={d} value={d}>{d}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
              <Button
                variant={showBookmarksOnly ? "default" : "outline"}
                onClick={() => setShowBookmarksOnly(!showBookmarksOnly)}
                className="gap-1.5"
              >
                <BookmarkCheck className="h-4 w-4" />
                Bookmarks ({bookmarks.size})
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* Tabs */}
        <Tabs value={activeTab} onValueChange={setActiveTab}>
          <TabsList className="w-full flex flex-wrap h-auto gap-1 bg-transparent p-0">
            {Object.entries(sectionLabels).map(([key, label]) => (
              <TabsTrigger
                key={key}
                value={key}
                className="gap-1.5 data-[state=active]:bg-primary data-[state=active]:text-primary-foreground"
              >
                {sectionIcons[key]}
                <span className="hidden sm:inline">{label}</span>
                <span className="sm:hidden">{label.split(' ')[0]}</span>
                <Badge variant="secondary" className="ml-1 text-xs h-5 px-1.5">{sectionCounts[key]}</Badge>
              </TabsTrigger>
            ))}
          </TabsList>

          {Object.keys(sectionLabels).map(section => (
            <TabsContent key={section} value={section} className="mt-4">
              {filtered.length === 0 ? (
                <Card>
                  <CardContent className="py-12 text-center">
                    <Search className="h-10 w-10 mx-auto text-muted-foreground mb-3" />
                    <p className="text-muted-foreground">No entries found. Try adjusting your filters.</p>
                  </CardContent>
                </Card>
              ) : (
                <Accordion type="multiple" className="space-y-0">
                  {filtered.map(entry => (
                    <ReferenceEntryCard
                      key={entry.id}
                      entry={entry}
                      isBookmarked={bookmarks.has(entry.id)}
                      onToggleBookmark={() => toggleBookmark(entry.id)}
                    />
                  ))}
                </Accordion>
              )}
            </TabsContent>
          ))}
        </Tabs>

        {/* Source Attribution */}
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-sm">Validated Sources</CardTitle>
            <CardDescription className="text-xs">All content aligned with official laboratory standards</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap gap-2">
              {['NABL', 'ICMR', 'ISO 15189', 'CLSI', 'WHO', 'BIS', 'FSSAI'].map(src => (
                <Badge key={src} variant="outline" className="text-xs">{src}</Badge>
              ))}
            </div>
          </CardContent>
        </Card>
      </main>
      <Footer />
    </div>
  );
}
