// Additional organisms following Bergey's Manual of Systematic Bacteriology
// These are merged into the main database at runtime

import type { Organism } from "./organismData";

export const additionalOrganisms: Organism[] = [
  // ==================== GRAM POSITIVE COCCI (additional) ====================
  {
    id: "staph-lugdunensis",
    name: "Staphylococcus lugdunensis",
    genus: "Staphylococcus",
    species: "lugdunensis",
    gramStain: "Gram Positive",
    shape: "Cocci",
    arrangement: "Clusters",
    oxygen: "Facultative Anaerobe",
    pathogenic: true,
    habitat: "Human skin (perineal, inguinal)",
    diseases: ["Endocarditis (aggressive)", "Skin infections", "Bone/joint infections", "Prosthetic device infections"],
    characteristics: { catalase: "Positive", oxidase: "Negative", motility: "Non-motile", coagulase: "Negative" },
    molecular: { genome: "2.6 Mb", gcContent: "33%", genes: "~2,400", notableGenes: ["fbl (fibrinogen-binding)", "vWbp (von Willebrand binding)"] },
    resistance: { intrinsic: [], acquired: ["Penicillin", "Oxacillin (rare)"], mechanism: "Beta-lactamase, rarely mecA" },
    treatment: ["Oxacillin/Nafcillin", "Vancomycin (if resistant)"],
    clinicalSignificance: "Coagulase-negative but behaves like S. aureus. Causes aggressive native valve endocarditis. Often misidentified as other CoNS.",
    labIdentification: ["Ornithine decarboxylase positive", "PYR positive", "Beta-hemolytic", "Tube coagulase may be weakly positive"],
    taxonomy: { domain: "Bacteria", phylum: "Bacillota", class: "Bacilli", order: "Staphylococcales", family: "Staphylococcaceae" },
  },
  {
    id: "staph-haemolyticus",
    name: "Staphylococcus haemolyticus",
    genus: "Staphylococcus",
    species: "haemolyticus",
    gramStain: "Gram Positive",
    shape: "Cocci",
    arrangement: "Clusters",
    oxygen: "Facultative Anaerobe",
    pathogenic: false,
    habitat: "Human skin",
    diseases: ["Catheter infections", "Bacteremia", "Prosthetic device infections"],
    characteristics: { catalase: "Positive", oxidase: "Negative", motility: "Non-motile", coagulase: "Negative" },
    molecular: { genome: "2.5 Mb", gcContent: "33%", genes: "~2,400", notableGenes: ["mecA", "vanA (rare)"] },
    resistance: { intrinsic: ["Penicillin (most)"], acquired: ["Methicillin", "Glycopeptides (rare)"], mechanism: "mecA, vanA gene acquisition" },
    treatment: ["Vancomycin", "Linezolid", "Daptomycin"],
    clinicalSignificance: "Second most commonly isolated CoNS after S. epidermidis. Highest rate of methicillin resistance among CoNS. Reported vancomycin resistance.",
    labIdentification: ["Coagulase negative", "Novobiocin susceptible", "Variable hemolysis"],
    taxonomy: { domain: "Bacteria", phylum: "Bacillota", class: "Bacilli", order: "Staphylococcales", family: "Staphylococcaceae" },
  },
  {
    id: "strep-mutans",
    name: "Streptococcus mutans",
    genus: "Streptococcus",
    species: "mutans",
    gramStain: "Gram Positive",
    shape: "Cocci",
    arrangement: "Chains",
    oxygen: "Facultative Anaerobe",
    pathogenic: true,
    habitat: "Human oral cavity",
    diseases: ["Dental caries", "Endocarditis"],
    characteristics: { catalase: "Negative", oxidase: "Negative", motility: "Non-motile", hemolysis: "Alpha or Gamma" },
    molecular: { genome: "2.0 Mb", gcContent: "36-37%", genes: "~1,900", notableGenes: ["gtfB/C/D (glucosyltransferases)", "spaP (adhesin)"] },
    resistance: { intrinsic: [], acquired: ["Erythromycin (some)"], mechanism: "erm genes" },
    treatment: ["Penicillin + Gentamicin (endocarditis)", "Fluoride prevention (caries)"],
    clinicalSignificance: "Primary causative agent of dental caries. Acid production from sucrose metabolism demineralizes enamel. Glucan production enables biofilm.",
    labIdentification: ["Mitis salivarius-bacitracin agar", "Optochin resistant", "Bile esculin negative"],
    taxonomy: { domain: "Bacteria", phylum: "Bacillota", class: "Bacilli", order: "Lactobacillales", family: "Streptococcaceae" },
  },
  {
    id: "strep-gallolyticus",
    name: "Streptococcus gallolyticus",
    genus: "Streptococcus",
    species: "gallolyticus (formerly bovis biotype I)",
    gramStain: "Gram Positive",
    shape: "Cocci",
    arrangement: "Chains",
    oxygen: "Facultative Anaerobe",
    pathogenic: true,
    habitat: "Human GI tract, ruminant GI tract",
    diseases: ["Endocarditis", "Bacteremia"],
    characteristics: { catalase: "Negative", oxidase: "Negative", motility: "Non-motile", hemolysis: "Alpha or Gamma" },
    molecular: { genome: "2.3 Mb", gcContent: "37%", genes: "~2,200", notableGenes: ["pil (pili)", "collagen-binding proteins"] },
    resistance: { intrinsic: [], acquired: ["Penicillin (rare)"], mechanism: "Altered PBPs" },
    treatment: ["Penicillin G", "Ceftriaxone", "Vancomycin"],
    clinicalSignificance: "Strong association with colorectal cancer and GI malignancy. All S. gallolyticus/bovis bacteremia requires colonoscopy to rule out colon cancer.",
    labIdentification: ["Group D antigen", "Bile esculin positive", "6.5% NaCl negative (unlike Enterococcus)"],
    taxonomy: { domain: "Bacteria", phylum: "Bacillota", class: "Bacilli", order: "Lactobacillales", family: "Streptococcaceae" },
  },
  {
    id: "aerococcus-urinae",
    name: "Aerococcus urinae",
    genus: "Aerococcus",
    species: "urinae",
    gramStain: "Gram Positive",
    shape: "Cocci",
    arrangement: "Clusters and tetrads",
    oxygen: "Facultative Anaerobe",
    pathogenic: true,
    habitat: "Human urinary tract",
    diseases: ["UTI (elderly)", "Endocarditis", "Bacteremia"],
    characteristics: { catalase: "Negative", oxidase: "Negative", motility: "Non-motile", hemolysis: "Alpha" },
    molecular: { genome: "1.9 Mb", gcContent: "37%", genes: "~1,800" },
    resistance: { intrinsic: ["TMP-SMX", "Sulfonamides"], acquired: ["Fluoroquinolones (rare)"], mechanism: "Inherent folate pathway" },
    treatment: ["Amoxicillin", "Nitrofurantoin (UTI)", "Penicillin + Gentamicin (endocarditis)"],
    clinicalSignificance: "Increasingly recognized UTI pathogen in elderly men. Often misidentified as Viridans streptococci or Enterococcus. Can cause destructive endocarditis.",
    labIdentification: ["Alpha-hemolytic", "Catalase negative", "LAP positive", "PYR variable", "MALDI-TOF recommended"],
    taxonomy: { domain: "Bacteria", phylum: "Bacillota", class: "Bacilli", order: "Lactobacillales", family: "Aerococcaceae" },
  },

  // ==================== GRAM POSITIVE BACILLI (additional) ====================
  {
    id: "nocardia-species",
    name: "Nocardia species",
    genus: "Nocardia",
    species: "asteroides complex/brasiliensis/etc.",
    gramStain: "Gram Positive",
    shape: "Bacilli",
    arrangement: "Branching filaments (beaded)",
    oxygen: "Obligate Aerobe",
    pathogenic: true,
    habitat: "Soil, decaying organic matter",
    diseases: ["Pulmonary nocardiosis", "Brain abscess", "Cutaneous nocardiosis", "Disseminated disease"],
    characteristics: { catalase: "Positive", oxidase: "Negative", motility: "Non-motile", acidFast: true },
    molecular: { genome: "6.0-9.0 Mb", gcContent: "64-72%", genes: "~5,500-8,000", notableGenes: ["erm (erythromycin resistance)"] },
    resistance: { intrinsic: [], acquired: ["Variable by species"], mechanism: "Species-specific resistance patterns" },
    treatment: ["TMP-SMX (first-line)", "Imipenem + amikacin (severe)", "Linezolid"],
    clinicalSignificance: "Weakly acid-fast branching filamentous bacterium. Often in immunocompromised (transplant, steroids, HIV). Brain abscess is a feared complication.",
    labIdentification: ["Modified acid-fast stain (weakly positive)", "Branching gram-positive filaments", "Slow growth (2-14 days)", "MALDI-TOF or 16S rRNA sequencing"],
    taxonomy: { domain: "Bacteria", phylum: "Actinomycetota", class: "Actinomycetes", order: "Mycobacteriales", family: "Nocardiaceae" },
  },
  {
    id: "actinomyces-israelii",
    name: "Actinomyces israelii",
    genus: "Actinomyces",
    species: "israelii",
    gramStain: "Gram Positive",
    shape: "Bacilli",
    arrangement: "Branching filaments (non-acid-fast)",
    oxygen: "Obligate Anaerobe",
    pathogenic: true,
    habitat: "Human oral cavity, GI tract, female genital tract",
    diseases: ["Cervicofacial actinomycosis", "Thoracic actinomycosis", "Abdominal/pelvic actinomycosis"],
    characteristics: { catalase: "Negative", oxidase: "Negative", motility: "Non-motile" },
    molecular: { genome: "3.2 Mb", gcContent: "69%", genes: "~2,700" },
    resistance: { intrinsic: ["Aminoglycosides", "Metronidazole"], acquired: ["Rare"], mechanism: "Generally susceptible" },
    treatment: ["Penicillin G (prolonged, 6-12 months)", "Amoxicillin", "Surgical drainage"],
    clinicalSignificance: "Causes chronic infection with 'sulfur granules' in draining sinuses. Associated with IUD use (pelvic). Not acid-fast (unlike Nocardia). Requires prolonged therapy.",
    labIdentification: ["Sulfur granules (gross/micro)", "Gram stain: branching non-acid-fast filaments", "Anaerobic culture (7-14 days)", "'Molar tooth' colonies"],
    taxonomy: { domain: "Bacteria", phylum: "Actinomycetota", class: "Actinomycetes", order: "Actinomycetales", family: "Actinomycetaceae" },
  },
  {
    id: "cutibacterium-acnes",
    name: "Cutibacterium acnes",
    genus: "Cutibacterium",
    species: "acnes (formerly Propionibacterium)",
    gramStain: "Gram Positive",
    shape: "Bacilli",
    arrangement: "Singles or short chains (diphtheroid-like)",
    oxygen: "Obligate Anaerobe",
    pathogenic: false,
    habitat: "Human skin (sebaceous glands)",
    diseases: ["Acne vulgaris", "Prosthetic joint infections", "Endocarditis (prosthetic valve)", "Post-surgical infections"],
    characteristics: { catalase: "Positive", oxidase: "Negative", motility: "Non-motile" },
    molecular: { genome: "2.5 Mb", gcContent: "60%", genes: "~2,300", notableGenes: ["lipase (GehA)", "CAMP factor", "hyaluronate lyase"] },
    resistance: { intrinsic: [], acquired: ["Clindamycin", "Erythromycin", "Tetracycline"], mechanism: "erm genes, tet genes" },
    treatment: ["Penicillin/amoxicillin (deep infections)", "Topical retinoids/benzoyl peroxide (acne)"],
    clinicalSignificance: "Most common anaerobic contaminant in blood cultures. True pathogen in prosthetic joint infections (shoulder). Slow growth delays diagnosis.",
    labIdentification: ["Anaerobic culture (5-14 days)", "Gram-positive diphtheroid rods", "Indole positive", "Catalase positive"],
    taxonomy: { domain: "Bacteria", phylum: "Actinomycetota", class: "Actinomycetes", order: "Propionibacteriales", family: "Propionibacteriaceae" },
  },
  {
    id: "erysipelothrix-rhusiopathiae",
    name: "Erysipelothrix rhusiopathiae",
    genus: "Erysipelothrix",
    species: "rhusiopathiae",
    gramStain: "Gram Positive",
    shape: "Bacilli",
    arrangement: "Singles or short chains (slender rods)",
    oxygen: "Facultative Anaerobe",
    pathogenic: true,
    habitat: "Animals (pigs, fish, poultry), soil",
    diseases: ["Erysipeloid (localized skin)", "Endocarditis", "Septicemia"],
    characteristics: { catalase: "Negative", oxidase: "Negative", motility: "Non-motile", h2s: "Positive (TSI)" },
    molecular: { genome: "1.8 Mb", gcContent: "36%", genes: "~1,700" },
    resistance: { intrinsic: ["Vancomycin", "Aminoglycosides"], acquired: ["Rare"], mechanism: "Intrinsically vancomycin resistant" },
    treatment: ["Penicillin G", "Ceftriaxone", "Fluoroquinolones"],
    clinicalSignificance: "Occupational disease of fishermen, butchers, veterinarians. Intrinsically resistant to vancomycin (important diagnostic feature). Produces H₂S.",
    labIdentification: ["Gram-positive slender rods", "Catalase negative", "H₂S positive on TSI", "Vancomycin resistant", "'Pipe cleaner' growth in gelatin"],
    taxonomy: { domain: "Bacteria", phylum: "Erysipelotrichota", class: "Erysipelotrichia", order: "Erysipelotrichales", family: "Erysipelotrichaceae" },
  },
  {
    id: "gardnerella-vaginalis",
    name: "Gardnerella vaginalis",
    genus: "Gardnerella",
    species: "vaginalis",
    gramStain: "Variable",
    shape: "Coccobacilli",
    arrangement: "Singles or pairs (pleomorphic)",
    oxygen: "Facultative Anaerobe",
    pathogenic: true,
    habitat: "Human vaginal tract",
    diseases: ["Bacterial vaginosis", "Bacteremia (rare)", "Neonatal infections (rare)"],
    characteristics: { catalase: "Negative", oxidase: "Negative", motility: "Non-motile" },
    molecular: { genome: "1.6 Mb", gcContent: "42%", genes: "~1,400", notableGenes: ["vly (vaginolysin)", "sialidase"] },
    resistance: { intrinsic: ["Sulfonamides"], acquired: ["Metronidazole (rare)"], mechanism: "Various" },
    treatment: ["Metronidazole (oral or vaginal)", "Clindamycin (vaginal)"],
    clinicalSignificance: "Key organism in bacterial vaginosis (polymicrobial). 'Clue cells' are pathognomonic. Fishy amine odor with KOH (whiff test). pH >4.5.",
    labIdentification: ["Clue cells on wet mount", "Whiff test positive", "Vaginal pH >4.5", "Gram stain: Nugent score"],
    taxonomy: { domain: "Bacteria", phylum: "Actinomycetota", class: "Actinomycetes", order: "Bifidobacteriales", family: "Bifidobacteriaceae" },
  },
  {
    id: "lactobacillus-species",
    name: "Lactobacillus species",
    genus: "Lactobacillus",
    species: "various",
    gramStain: "Gram Positive",
    shape: "Bacilli",
    arrangement: "Singles, chains, or palisades",
    oxygen: "Facultative Anaerobe",
    pathogenic: false,
    habitat: "Human GI and vaginal tract, fermented foods",
    diseases: ["Rarely pathogenic", "Endocarditis (rare)", "Bacteremia (rare, immunocompromised)"],
    characteristics: { catalase: "Negative", oxidase: "Negative", motility: "Non-motile" },
    molecular: { genome: "1.8-3.3 Mb", gcContent: "33-55%", genes: "~1,700-3,000" },
    resistance: { intrinsic: ["Vancomycin (most species)"], acquired: ["Rare"], mechanism: "D-alanine:D-lactate ligase" },
    treatment: ["Penicillin + Gentamicin (rare infections)"],
    clinicalSignificance: "Normal protective flora of vagina (maintains low pH). Probiotic use. Intrinsically vancomycin resistant but rarely pathogenic. Döderlein bacilli.",
    labIdentification: ["Gram-positive long rods", "Catalase negative", "Grows on MRS agar", "Acid from glucose"],
    taxonomy: { domain: "Bacteria", phylum: "Bacillota", class: "Bacilli", order: "Lactobacillales", family: "Lactobacillaceae" },
  },
  {
    id: "rhodococcus-equi",
    name: "Rhodococcus equi",
    genus: "Rhodococcus",
    species: "equi",
    gramStain: "Gram Positive",
    shape: "Coccobacilli",
    arrangement: "Pleomorphic (coccoid to rod)",
    oxygen: "Obligate Aerobe",
    pathogenic: true,
    habitat: "Soil, horses",
    diseases: ["Cavitary pneumonia (AIDS)", "Brain abscess", "Bacteremia"],
    characteristics: { catalase: "Positive", oxidase: "Negative", motility: "Non-motile", acidFast: true },
    molecular: { genome: "5.0 Mb", gcContent: "68%", genes: "~4,500", notableGenes: ["vapA (virulence)"] },
    resistance: { intrinsic: ["Penicillin", "Cephalosporins"], acquired: ["Rare"], mechanism: "Intracellular location" },
    treatment: ["Azithromycin + rifampin", "Vancomycin + imipenem (severe)"],
    clinicalSignificance: "Weakly acid-fast intracellular pathogen. Causes cavitary pneumonia in AIDS (mimics TB). Equine exposure is a risk factor. Partially acid-fast.",
    labIdentification: ["Salmon-pink/mucoid colonies", "Weakly acid-fast", "Equi factor (CAMP-like with R. equi and S. aureus)", "MALDI-TOF"],
    taxonomy: { domain: "Bacteria", phylum: "Actinomycetota", class: "Actinomycetes", order: "Mycobacteriales", family: "Nocardiaceae" },
  },

  // ==================== GRAM NEGATIVE ANAEROBES ====================
  {
    id: "bacteroides-fragilis",
    name: "Bacteroides fragilis",
    genus: "Bacteroides",
    species: "fragilis",
    gramStain: "Gram Negative",
    shape: "Bacilli",
    arrangement: "Singles (pleomorphic)",
    oxygen: "Obligate Anaerobe",
    pathogenic: true,
    habitat: "Human colon (normal flora)",
    diseases: ["Intra-abdominal abscess", "Peritonitis", "Bacteremia", "Brain abscess"],
    characteristics: { catalase: "Positive", oxidase: "Negative", motility: "Non-motile", capsule: true },
    molecular: { genome: "5.2 Mb", gcContent: "43%", genes: "~4,500", notableGenes: ["cfiA (carbapenemase)", "bftA (fragilysin)"] },
    resistance: { intrinsic: ["Aminoglycosides", "Many beta-lactams"], acquired: ["Clindamycin", "Moxifloxacin", "Carbapenems (rare)"], mechanism: "CfiA metallo-beta-lactamase, nim genes (metronidazole)" },
    treatment: ["Metronidazole", "Carbapenems", "Piperacillin-tazobactam", "Source control (surgery)"],
    clinicalSignificance: "Most common anaerobic pathogen. Polysaccharide capsule promotes abscess formation. Synergistic with aerobes. Increasing resistance is concerning.",
    labIdentification: ["Anaerobic culture on BBE agar", "Growth in 20% bile", "Catalase positive", "MALDI-TOF"],
    taxonomy: { domain: "Bacteria", phylum: "Bacteroidota", class: "Bacteroidia", order: "Bacteroidales", family: "Bacteroidaceae" },
  },
  {
    id: "prevotella-melaninogenica",
    name: "Prevotella melaninogenica",
    genus: "Prevotella",
    species: "melaninogenica",
    gramStain: "Gram Negative",
    shape: "Bacilli",
    arrangement: "Singles (short rods)",
    oxygen: "Obligate Anaerobe",
    pathogenic: true,
    habitat: "Human oral cavity, GI tract, vaginal tract",
    diseases: ["Aspiration pneumonia", "Lung abscess", "Periodontal disease", "Pelvic infections"],
    characteristics: { catalase: "Negative", oxidase: "Negative", motility: "Non-motile" },
    molecular: { genome: "3.1 Mb", gcContent: "41%", genes: "~2,700" },
    resistance: { intrinsic: ["Aminoglycosides"], acquired: ["Penicillin (beta-lactamase)"], mechanism: "CfxA beta-lactamase" },
    treatment: ["Metronidazole", "Amoxicillin-clavulanate", "Carbapenems"],
    clinicalSignificance: "Important in polymicrobial anaerobic infections. Black-pigmented colonies. Common in aspiration pneumonia and periodontal disease.",
    labIdentification: ["Black-pigmented colonies on blood agar", "Fluoresces brick red under UV", "Anaerobic growth"],
    taxonomy: { domain: "Bacteria", phylum: "Bacteroidota", class: "Bacteroidia", order: "Bacteroidales", family: "Prevotellaceae" },
  },
  {
    id: "fusobacterium-nucleatum",
    name: "Fusobacterium nucleatum",
    genus: "Fusobacterium",
    species: "nucleatum",
    gramStain: "Gram Negative",
    shape: "Bacilli",
    arrangement: "Fusiform (spindle-shaped, pointed ends)",
    oxygen: "Obligate Anaerobe",
    pathogenic: true,
    habitat: "Human oral cavity",
    diseases: ["Lemierre syndrome", "Periodontal disease", "Brain abscess", "Liver abscess"],
    characteristics: { catalase: "Negative", oxidase: "Negative", motility: "Non-motile", indole: "Positive" },
    molecular: { genome: "2.2 Mb", gcContent: "27%", genes: "~2,000", notableGenes: ["fadA (adhesin)", "fap2"] },
    resistance: { intrinsic: ["Aminoglycosides"], acquired: ["Rare"], mechanism: "Generally susceptible" },
    treatment: ["Penicillin G", "Metronidazole", "Clindamycin"],
    clinicalSignificance: "Causes Lemierre syndrome (septic thrombophlebitis of internal jugular vein). Associated with colorectal cancer. Key bridging organism in dental plaque.",
    labIdentification: ["Fusiform rods with pointed ends", "Indole positive", "Anaerobic culture", "'Breadcrumb' colonies"],
    taxonomy: { domain: "Bacteria", phylum: "Fusobacteriota", class: "Fusobacteriia", order: "Fusobacteriales", family: "Fusobacteriaceae" },
  },
  {
    id: "porphyromonas-gingivalis",
    name: "Porphyromonas gingivalis",
    genus: "Porphyromonas",
    species: "gingivalis",
    gramStain: "Gram Negative",
    shape: "Coccobacilli",
    arrangement: "Singles or pairs",
    oxygen: "Obligate Anaerobe",
    pathogenic: true,
    habitat: "Human oral cavity (subgingival)",
    diseases: ["Periodontitis", "Periapical abscess"],
    characteristics: { catalase: "Negative", oxidase: "Negative", motility: "Non-motile" },
    molecular: { genome: "2.3 Mb", gcContent: "48%", genes: "~2,000", notableGenes: ["gingipains (rgpA, rgpB, kgp)"] },
    resistance: { intrinsic: [], acquired: ["Rare"], mechanism: "Generally susceptible" },
    treatment: ["Metronidazole", "Amoxicillin-clavulanate", "Scaling and root planing"],
    clinicalSignificance: "Keystone pathogen of chronic periodontitis. Gingipains are major virulence factors. Linked to Alzheimer's disease (controversial). Black-pigmented anaerobe.",
    labIdentification: ["Black-pigmented colonies", "Fluoresces under UV", "Anaerobic culture", "Trypsin-like activity"],
    taxonomy: { domain: "Bacteria", phylum: "Bacteroidota", class: "Bacteroidia", order: "Bacteroidales", family: "Porphyromonadaceae" },
  },

  // ==================== GRAM NEGATIVE ENTEROBACTERIACEAE (additional) ====================
  {
    id: "cronobacter-sakazakii",
    name: "Cronobacter sakazakii",
    genus: "Cronobacter",
    species: "sakazakii (formerly Enterobacter sakazakii)",
    gramStain: "Gram Negative",
    shape: "Bacilli",
    arrangement: "Singles",
    oxygen: "Facultative Anaerobe",
    pathogenic: true,
    habitat: "Powdered infant formula, environment",
    diseases: ["Neonatal meningitis", "Necrotizing enterocolitis", "Bacteremia"],
    characteristics: { catalase: "Positive", oxidase: "Negative", motility: "Motile" },
    molecular: { genome: "4.4 Mb", gcContent: "57%", genes: "~4,200", notableGenes: ["ompA (adhesin/invasion)"] },
    resistance: { intrinsic: [], acquired: ["Ampicillin", "Cephalosporins (some)"], mechanism: "Beta-lactamases" },
    treatment: ["Ampicillin + Gentamicin (neonates)", "Carbapenems (resistant strains)"],
    clinicalSignificance: "Major pathogen of neonates through contaminated powdered infant formula. High mortality (40-80%). Yellow-pigmented colonies. FDA regulated.",
    labIdentification: ["Yellow-pigmented colonies", "MacConkey: lactose fermenter", "Chromogenic media (DFI)"],
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Enterobacterales", family: "Enterobacteriaceae" },
  },
  {
    id: "edwardsiella-tarda",
    name: "Edwardsiella tarda",
    genus: "Edwardsiella",
    species: "tarda",
    gramStain: "Gram Negative",
    shape: "Bacilli",
    arrangement: "Singles",
    oxygen: "Facultative Anaerobe",
    pathogenic: true,
    habitat: "Freshwater, fish, reptiles",
    diseases: ["Gastroenteritis", "Wound infections", "Bacteremia", "Liver abscess"],
    characteristics: { catalase: "Positive", oxidase: "Negative", motility: "Motile", h2s: "Positive", indole: "Positive" },
    molecular: { genome: "3.8 Mb", gcContent: "57%", genes: "~3,600" },
    resistance: { intrinsic: [], acquired: ["Rare"], mechanism: "Generally susceptible" },
    treatment: ["Fluoroquinolones", "TMP-SMX", "Third-gen cephalosporins"],
    clinicalSignificance: "Aquatic pathogen. Hepatobiliary infections in immunocompromised. Associated with exposure to fish/reptiles. Produces H₂S and indole.",
    labIdentification: ["H₂S positive", "Indole positive", "Lysine/ornithine positive", "Non-lactose fermenter"],
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Enterobacterales", family: "Hafniaceae" },
  },
  {
    id: "providencia-stuartii",
    name: "Providencia stuartii",
    genus: "Providencia",
    species: "stuartii",
    gramStain: "Gram Negative",
    shape: "Bacilli",
    arrangement: "Singles",
    oxygen: "Facultative Anaerobe",
    pathogenic: true,
    habitat: "Human intestine, hospital environment",
    diseases: ["Catheter-associated UTI", "Bacteremia", "Wound infections"],
    characteristics: { catalase: "Positive", oxidase: "Negative", motility: "Motile", urease: "Positive", indole: "Positive", lactoseFermenter: false },
    molecular: { genome: "4.3 Mb", gcContent: "41%", genes: "~4,000" },
    resistance: { intrinsic: ["Polymyxins", "Nitrofurantoin", "Tetracyclines"], acquired: ["Extended-spectrum cephalosporins", "Carbapenems"], mechanism: "AmpC, ESBLs, carbapenemases" },
    treatment: ["Carbapenems", "Fluoroquinolones", "TMP-SMX"],
    clinicalSignificance: "Common cause of catheter-associated UTI in long-term care facilities. Highly antibiotic resistant. Purple urine bag syndrome (PUBS) association.",
    labIdentification: ["NLF on MacConkey", "Urease positive", "Indole positive", "H₂S negative"],
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Enterobacterales", family: "Morganellaceae" },
  },
  {
    id: "pantoea-agglomerans",
    name: "Pantoea agglomerans",
    genus: "Pantoea",
    species: "agglomerans",
    gramStain: "Gram Negative",
    shape: "Bacilli",
    arrangement: "Singles",
    oxygen: "Facultative Anaerobe",
    pathogenic: false,
    habitat: "Plants, soil, water",
    diseases: ["Wound infections (plant thorn)", "Bacteremia (contaminated IV fluids)", "Joint infections"],
    characteristics: { catalase: "Positive", oxidase: "Negative", motility: "Motile", lactoseFermenter: true },
    molecular: { genome: "4.5 Mb", gcContent: "55%", genes: "~4,400" },
    resistance: { intrinsic: [], acquired: ["Rare"], mechanism: "Generally susceptible" },
    treatment: ["Third-gen cephalosporins", "Fluoroquinolones", "Carbapenems"],
    clinicalSignificance: "Plant-associated organism. Causes infections from plant thorn/splinter injuries (especially rose/palm thorn septic arthritis). Yellow pigment.",
    labIdentification: ["Yellow-pigmented colonies", "Lactose fermenter", "Motile"],
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Enterobacterales", family: "Erwiniaceae" },
  },

  // ==================== GRAM NEGATIVE NON-FERMENTERS (additional) ====================
  {
    id: "elizabethkingia-meningoseptica",
    name: "Elizabethkingia meningoseptica",
    genus: "Elizabethkingia",
    species: "meningoseptica (formerly Chryseobacterium)",
    gramStain: "Gram Negative",
    shape: "Bacilli",
    arrangement: "Singles (slender rods)",
    oxygen: "Obligate Aerobe",
    pathogenic: true,
    habitat: "Soil, water, hospital environment",
    diseases: ["Neonatal meningitis", "Bacteremia", "Pneumonia"],
    characteristics: { catalase: "Positive", oxidase: "Positive", motility: "Non-motile" },
    molecular: { genome: "4.0 Mb", gcContent: "36%", genes: "~3,700" },
    resistance: { intrinsic: ["Most beta-lactams", "Aminoglycosides", "Carbapenems"], acquired: ["Fluoroquinolones (some)"], mechanism: "Metallo-beta-lactamases, inherent resistance" },
    treatment: ["Vancomycin (unusual for Gram-negative)", "TMP-SMX", "Fluoroquinolones", "Rifampin"],
    clinicalSignificance: "Unusual Gram-negative that may respond to vancomycin. Causes neonatal meningitis. Highly resistant to typical Gram-negative antibiotics.",
    labIdentification: ["Pale yellow colonies", "Oxidase positive", "Indole positive", "Non-motile"],
    taxonomy: { domain: "Bacteria", phylum: "Bacteroidota", class: "Flavobacteriia", order: "Flavobacteriales", family: "Weeksellaceae" },
  },
  {
    id: "achromobacter-xylosoxidans",
    name: "Achromobacter xylosoxidans",
    genus: "Achromobacter",
    species: "xylosoxidans",
    gramStain: "Gram Negative",
    shape: "Bacilli",
    arrangement: "Singles",
    oxygen: "Obligate Aerobe",
    pathogenic: true,
    habitat: "Water, soil, hospital environment",
    diseases: ["Bacteremia", "Pneumonia (CF)", "UTI", "Meningitis"],
    characteristics: { catalase: "Positive", oxidase: "Positive", motility: "Motile (peritrichous)" },
    molecular: { genome: "6.8 Mb", gcContent: "65%", genes: "~6,200" },
    resistance: { intrinsic: ["Aminoglycosides", "Most cephalosporins"], acquired: ["Carbapenems", "TMP-SMX"], mechanism: "OXA-type beta-lactamases, efflux" },
    treatment: ["Piperacillin-tazobactam", "Meropenem", "TMP-SMX"],
    clinicalSignificance: "Emerging pathogen in cystic fibrosis. Intrinsically resistant to many antibiotics. Associated with contaminated chlorhexidine solutions.",
    labIdentification: ["Oxidase positive", "Peritrichous flagella (unusual for non-fermenter)", "NLF on MacConkey"],
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Betaproteobacteria", order: "Burkholderiales", family: "Alcaligenaceae" },
  },

  // ==================== HACEK GROUP ====================
  {
    id: "aggregatibacter-actinomycetemcomitans",
    name: "Aggregatibacter actinomycetemcomitans",
    genus: "Aggregatibacter",
    species: "actinomycetemcomitans",
    gramStain: "Gram Negative",
    shape: "Coccobacilli",
    arrangement: "Singles or pairs",
    oxygen: "Facultative Anaerobe",
    pathogenic: true,
    habitat: "Human oral cavity",
    diseases: ["Endocarditis (HACEK)", "Aggressive periodontitis", "Brain abscess"],
    characteristics: { catalase: "Positive", oxidase: "Negative", motility: "Non-motile" },
    molecular: { genome: "2.1 Mb", gcContent: "44%", genes: "~2,000", notableGenes: ["ltxA (leukotoxin)", "cdtABC"] },
    resistance: { intrinsic: [], acquired: ["Ampicillin (beta-lactamase, 25-30%)"], mechanism: "TEM/ROB beta-lactamases" },
    treatment: ["Ceftriaxone (endocarditis)", "Amoxicillin-clavulanate", "Fluoroquinolones"],
    clinicalSignificance: "HACEK group organism. Causes culture-negative endocarditis (slow growth). Associated with aggressive localized periodontitis in adolescents.",
    labIdentification: ["Slow growth (5-7 days)", "Star-shaped inner colony", "CO₂ requirement", "MALDI-TOF"],
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Pasteurellales", family: "Pasteurellaceae" },
  },
  {
    id: "eikenella-corrodens",
    name: "Eikenella corrodens",
    genus: "Eikenella",
    species: "corrodens",
    gramStain: "Gram Negative",
    shape: "Bacilli",
    arrangement: "Singles (slender rods)",
    oxygen: "Facultative Anaerobe",
    pathogenic: true,
    habitat: "Human oral cavity",
    diseases: ["Human bite infections", "Endocarditis (HACEK)", "Head and neck infections"],
    characteristics: { catalase: "Negative", oxidase: "Positive", motility: "Non-motile (twitching motility)" },
    molecular: { genome: "2.1 Mb", gcContent: "56%", genes: "~1,900" },
    resistance: { intrinsic: ["Clindamycin", "Metronidazole"], acquired: ["Rare"], mechanism: "Generally susceptible to beta-lactams" },
    treatment: ["Amoxicillin-clavulanate", "Ampicillin", "Fluoroquinolones"],
    clinicalSignificance: "HACEK organism. Associated with human bite wounds (clenched-fist injuries). 'Corrodes' into the agar. Bleach-like odor.",
    labIdentification: ["Corroding/pitting agar", "Bleach/hypochlorite odor", "Oxidase positive", "Slow growth"],
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Betaproteobacteria", order: "Neisseriales", family: "Neisseriaceae" },
  },
  {
    id: "kingella-kingae",
    name: "Kingella kingae",
    genus: "Kingella",
    species: "kingae",
    gramStain: "Gram Negative",
    shape: "Coccobacilli",
    arrangement: "Pairs or short chains",
    oxygen: "Facultative Anaerobe",
    pathogenic: true,
    habitat: "Human oropharynx (children)",
    diseases: ["Septic arthritis (children <4y)", "Osteomyelitis", "Endocarditis (HACEK)"],
    characteristics: { catalase: "Negative", oxidase: "Positive", motility: "Non-motile" },
    molecular: { genome: "2.0 Mb", gcContent: "47%", genes: "~1,900", notableGenes: ["rtxA (toxin)"] },
    resistance: { intrinsic: [], acquired: ["Rare"], mechanism: "Generally susceptible" },
    treatment: ["Ceftriaxone", "Ampicillin", "Penicillin G"],
    clinicalSignificance: "Most common cause of septic arthritis and osteomyelitis in children aged 6 months to 4 years. HACEK organism. Often culture-negative (inoculate into blood culture bottles).",
    labIdentification: ["Beta-hemolytic pitting colonies", "Inoculate joint fluid into blood culture bottles", "PCR (preferred)", "MALDI-TOF"],
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Betaproteobacteria", order: "Neisseriales", family: "Neisseriaceae" },
  },
  {
    id: "capnocytophaga-canimorsus",
    name: "Capnocytophaga canimorsus",
    genus: "Capnocytophaga",
    species: "canimorsus",
    gramStain: "Gram Negative",
    shape: "Bacilli",
    arrangement: "Fusiform (spindle-shaped)",
    oxygen: "Facultative Anaerobe",
    pathogenic: true,
    habitat: "Dog and cat saliva",
    diseases: ["Septicemia (dog/cat bites)", "Meningitis", "Endocarditis", "DIC"],
    characteristics: { catalase: "Positive", oxidase: "Positive", motility: "Gliding motility" },
    molecular: { genome: "2.6 Mb", gcContent: "36%", genes: "~2,300" },
    resistance: { intrinsic: ["Aminoglycosides (variable)"], acquired: ["Rare"], mechanism: "Generally susceptible" },
    treatment: ["Amoxicillin-clavulanate", "Penicillin G", "Carbapenems (severe)"],
    clinicalSignificance: "Fulminant sepsis from dog/cat bites in asplenic or immunocompromised patients. Can cause overwhelming purpura fulminans. Very slow growth.",
    labIdentification: ["Very slow growth (5-14 days)", "CO₂ required", "Fusiform gram-negative rods", "Oxidase positive"],
    taxonomy: { domain: "Bacteria", phylum: "Bacteroidota", class: "Flavobacteriia", order: "Flavobacteriales", family: "Flavobacteriaceae" },
  },

  // ==================== GRAM NEGATIVE OTHER (additional) ====================
  {
    id: "aeromonas-hydrophila",
    name: "Aeromonas hydrophila",
    genus: "Aeromonas",
    species: "hydrophila",
    gramStain: "Gram Negative",
    shape: "Bacilli",
    arrangement: "Singles",
    oxygen: "Facultative Anaerobe",
    pathogenic: true,
    habitat: "Freshwater, soil",
    diseases: ["Gastroenteritis", "Wound infections (water exposure)", "Necrotizing fasciitis", "Bacteremia"],
    characteristics: { catalase: "Positive", oxidase: "Positive", motility: "Motile (polar flagellum)", indole: "Positive" },
    molecular: { genome: "4.7 Mb", gcContent: "61%", genes: "~4,100", notableGenes: ["act (aerolysin)", "ast (enterotoxin)"] },
    resistance: { intrinsic: ["Ampicillin"], acquired: ["Cephalosporins (inducible)"], mechanism: "Chromosomal beta-lactamases" },
    treatment: ["Fluoroquinolones", "TMP-SMX", "Third-gen cephalosporins"],
    clinicalSignificance: "Waterborne pathogen. Medicinal leech therapy can introduce Aeromonas. Necrotizing fasciitis in immunocompromised after water exposure.",
    labIdentification: ["Oxidase positive", "Blood agar: beta-hemolytic", "MacConkey: LF (most)", "Grows on TCBS (yellow)"],
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Aeromonadales", family: "Aeromonadaceae" },
  },
  {
    id: "plesiomonas-shigelloides",
    name: "Plesiomonas shigelloides",
    genus: "Plesiomonas",
    species: "shigelloides",
    gramStain: "Gram Negative",
    shape: "Bacilli",
    arrangement: "Singles",
    oxygen: "Facultative Anaerobe",
    pathogenic: true,
    habitat: "Freshwater, shellfish",
    diseases: ["Gastroenteritis", "Bacteremia (immunocompromised)"],
    characteristics: { catalase: "Positive", oxidase: "Positive", motility: "Motile (lophotrichous flagella)" },
    molecular: { genome: "3.4 Mb", gcContent: "51%", genes: "~3,100" },
    resistance: { intrinsic: [], acquired: ["Rare"], mechanism: "Generally susceptible" },
    treatment: ["Usually self-limiting", "Fluoroquinolones", "TMP-SMX"],
    clinicalSignificance: "Waterborne/foodborne gastroenteritis. Only oxidase-positive member of Enterobacterales. Associated with travel and raw shellfish consumption.",
    labIdentification: ["Oxidase positive (unique for Enterobacterales)", "Non-lactose fermenter", "Inositol/ornithine decarboxylase positive"],
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Enterobacterales", family: "Enterobacteriaceae" },
  },

  // ==================== ACID-FAST BACILLI (additional) ====================
  {
    id: "mycobacterium-marinum",
    name: "Mycobacterium marinum",
    genus: "Mycobacterium",
    species: "marinum",
    gramStain: "Variable",
    shape: "Bacilli",
    arrangement: "Singles",
    oxygen: "Obligate Aerobe",
    pathogenic: true,
    habitat: "Freshwater and saltwater aquaria, fish",
    diseases: ["Fish tank granuloma", "Sporotrichoid skin lesions"],
    characteristics: { catalase: "Positive", oxidase: "Negative", motility: "Non-motile", acidFast: true },
    molecular: { genome: "6.6 Mb", gcContent: "65%", genes: "~5,400" },
    resistance: { intrinsic: ["Pyrazinamide", "Isoniazid (usually)"], acquired: ["Rare"], mechanism: "Generally susceptible to non-TB drugs" },
    treatment: ["Clarithromycin + ethambutol", "Doxycycline", "TMP-SMX"],
    clinicalSignificance: "Photochromogen (Runyon Group I). Grows at 30-33°C (not 37°C). Aquarium/fish handler's exposure. Sporotrichoid spread along lymphatics.",
    labIdentification: ["Acid-fast stain", "Growth at 30°C (not 37°C)", "Photochromogen (yellow in light)", "2-3 week growth"],
    taxonomy: { domain: "Bacteria", phylum: "Actinomycetota", class: "Actinomycetes", order: "Mycobacteriales", family: "Mycobacteriaceae" },
  },
  {
    id: "mycobacterium-kansasii",
    name: "Mycobacterium kansasii",
    genus: "Mycobacterium",
    species: "kansasii",
    gramStain: "Variable",
    shape: "Bacilli",
    arrangement: "Singles (long beaded rods)",
    oxygen: "Obligate Aerobe",
    pathogenic: true,
    habitat: "Water (municipal tap water)",
    diseases: ["Pulmonary disease (TB-like)", "Disseminated disease (AIDS)"],
    characteristics: { catalase: "Positive", oxidase: "Negative", motility: "Non-motile", acidFast: true },
    molecular: { genome: "6.4 Mb", gcContent: "66%", genes: "~5,500" },
    resistance: { intrinsic: ["Pyrazinamide"], acquired: ["Rifampin (rare)"], mechanism: "Generally susceptible to rifampin + ethambutol + isoniazid" },
    treatment: ["Rifampin + ethambutol + isoniazid (12-18 months)", "Azithromycin-based alternative"],
    clinicalSignificance: "Photochromogen (Runyon Group I). Most TB-like of all NTM. Good prognosis with treatment. Second most common NTM lung disease.",
    labIdentification: ["Acid-fast stain (cross-banded rods)", "Photochromogen", "Slow grower (2-4 weeks)", "Municipal water source"],
    taxonomy: { domain: "Bacteria", phylum: "Actinomycetota", class: "Actinomycetes", order: "Mycobacteriales", family: "Mycobacteriaceae" },
  },
  {
    id: "mycobacterium-abscessus",
    name: "Mycobacterium abscessus",
    genus: "Mycobacterium",
    species: "abscessus",
    gramStain: "Variable",
    shape: "Bacilli",
    arrangement: "Singles (short rods)",
    oxygen: "Obligate Aerobe",
    pathogenic: true,
    habitat: "Soil, water, contaminated medical equipment",
    diseases: ["Pulmonary disease (CF)", "Skin/soft tissue infections", "Post-surgical infections"],
    characteristics: { catalase: "Positive", oxidase: "Negative", motility: "Non-motile", acidFast: true },
    molecular: { genome: "5.1 Mb", gcContent: "64%", genes: "~4,900", notableGenes: ["erm(41) (inducible macrolide resistance)"] },
    resistance: { intrinsic: ["Most first-line TB drugs", "Cephalosporins"], acquired: ["Macrolides (inducible erm41)"], mechanism: "erm(41) gene – inducible clarithromycin resistance. Must perform extended incubation (14 days)" },
    treatment: ["Amikacin + imipenem + azithromycin (induction)", "Prolonged, difficult to cure"],
    clinicalSignificance: "Most drug-resistant NTM. Rapid grower. Nightmare pathogen in cystic fibrosis. Cure rates only 30-50%. Subspecies identification affects treatment.",
    labIdentification: ["Rapid grower (3-7 days)", "Acid-fast stain", "Inducible macrolide resistance testing (14-day incubation)", "MALDI-TOF or sequencing"],
    taxonomy: { domain: "Bacteria", phylum: "Actinomycetota", class: "Actinomycetes", order: "Mycobacteriales", family: "Mycobacteriaceae" },
  },
  {
    id: "mycobacterium-fortuitum",
    name: "Mycobacterium fortuitum",
    genus: "Mycobacterium",
    species: "fortuitum",
    gramStain: "Variable",
    shape: "Bacilli",
    arrangement: "Singles",
    oxygen: "Obligate Aerobe",
    pathogenic: true,
    habitat: "Soil, water, hospital environment",
    diseases: ["Skin/soft tissue infections", "Post-surgical wound infections", "Catheter infections"],
    characteristics: { catalase: "Positive", oxidase: "Negative", motility: "Non-motile", acidFast: true },
    molecular: { genome: "6.2 Mb", gcContent: "66%", genes: "~5,500" },
    resistance: { intrinsic: ["First-line TB drugs"], acquired: ["Variable"], mechanism: "Generally susceptible to amikacin, fluoroquinolones" },
    treatment: ["Amikacin + fluoroquinolone", "TMP-SMX", "Surgical debridement"],
    clinicalSignificance: "Rapidly growing NTM. Post-surgical infections (breast augmentation, LASIK). Does NOT have inducible macrolide resistance (unlike M. abscessus).",
    labIdentification: ["Rapid grower (3-5 days)", "Acid-fast stain", "Non-pigmented", "3-day arylsulfatase positive"],
    taxonomy: { domain: "Bacteria", phylum: "Actinomycetota", class: "Actinomycetes", order: "Mycobacteriales", family: "Mycobacteriaceae" },
  },

  // ==================== FUNGI (additional) ====================
  {
    id: "candida-glabrata",
    name: "Candida glabrata",
    genus: "Candida",
    species: "glabrata (Nakaseomyces glabratus)",
    gramStain: "Not Applicable",
    shape: "Yeast",
    arrangement: "Small yeast, NO pseudohyphae",
    oxygen: "Facultative Anaerobe",
    pathogenic: true,
    habitat: "Human GI and urogenital tract",
    diseases: ["Candidemia", "Vulvovaginal candidiasis", "UTI"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "12.3 Mb (haploid)", gcContent: "38%", genes: "~5,200", notableGenes: ["CDR1 (efflux)", "ERG11", "FKS1/FKS2"] },
    resistance: { intrinsic: ["Intrinsically less susceptible to fluconazole"], acquired: ["Fluconazole", "Echinocandins (FKS mutations)"], mechanism: "Upregulated CDR efflux pumps, ERG11 upregulation, FKS mutations" },
    treatment: ["Echinocandins (first-line)", "Amphotericin B (if echinocandin-resistant)"],
    clinicalSignificance: "Second most common cause of candidemia (after C. albicans). Increasing prevalence with azole prophylaxis. Does NOT form pseudohyphae. Haploid genome.",
    labIdentification: ["CHROMagar: dark pink/mauve", "Germ tube negative", "No pseudohyphae", "MALDI-TOF"],
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Saccharomycetes", order: "Saccharomycetales", family: "Saccharomycetaceae" },
  },
  {
    id: "candida-parapsilosis",
    name: "Candida parapsilosis",
    genus: "Candida",
    species: "parapsilosis",
    gramStain: "Not Applicable",
    shape: "Yeast",
    arrangement: "Yeast with pseudohyphae ('sage-brush')",
    oxygen: "Facultative Anaerobe",
    pathogenic: true,
    habitat: "Human skin, hospital environment",
    diseases: ["Candidemia (catheter-related)", "Endocarditis", "Endophthalmitis"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "13.1 Mb", gcContent: "38%", genes: "~5,700" },
    resistance: { intrinsic: ["Reduced echinocandin susceptibility (higher MICs)"], acquired: ["Fluconazole (rare)"], mechanism: "Natural FKS polymorphism reduces echinocandin activity" },
    treatment: ["Fluconazole (first-line)", "Echinocandins (higher doses may be needed)", "Catheter removal essential"],
    clinicalSignificance: "Third most common Candida in candidemia. Associated with catheter-related infections, TPN, prosthetic devices. Common in neonatal ICU. Biofilm on catheters.",
    labIdentification: ["CHROMagar: cream/pink", "Germ tube negative", "Pseudohyphae: 'sage brush' pattern", "MALDI-TOF"],
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Saccharomycetes", order: "Saccharomycetales", family: "Debaryomycetaceae" },
  },
  {
    id: "candida-tropicalis",
    name: "Candida tropicalis",
    genus: "Candida",
    species: "tropicalis",
    gramStain: "Not Applicable",
    shape: "Yeast",
    arrangement: "Yeast with pseudohyphae",
    oxygen: "Facultative Anaerobe",
    pathogenic: true,
    habitat: "Human GI tract",
    diseases: ["Candidemia", "Disseminated candidiasis (neutropenic patients)"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "14.5 Mb (diploid)", gcContent: "33%", genes: "~6,200" },
    resistance: { intrinsic: [], acquired: ["Fluconazole", "Echinocandins (rare)"], mechanism: "ERG11 mutations, CDR1 upregulation" },
    treatment: ["Echinocandins", "Fluconazole (if susceptible)", "Amphotericin B"],
    clinicalSignificance: "Second or third most common cause of candidemia in tropical regions. Strongly associated with hematological malignancies and neutropenia.",
    labIdentification: ["CHROMagar: dark blue", "Pseudohyphae present", "Sucrose fermenter", "MALDI-TOF"],
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Saccharomycetes", order: "Saccharomycetales", family: "Debaryomycetaceae" },
  },
  {
    id: "candida-krusei",
    name: "Candida krusei (Pichia kudriavzevii)",
    genus: "Candida",
    species: "krusei",
    gramStain: "Not Applicable",
    shape: "Yeast",
    arrangement: "Elongated yeast ('matchstick' pseudohyphae)",
    oxygen: "Aerobe",
    pathogenic: true,
    habitat: "Environment, human GI tract",
    diseases: ["Candidemia (neutropenic patients)", "Esophagitis"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "10.6 Mb", gcContent: "38%", genes: "~5,000" },
    resistance: { intrinsic: ["Fluconazole (inherently resistant)"], acquired: ["Voriconazole (reduced susceptibility)"], mechanism: "Intrinsic ERG11 resistance, efflux pumps" },
    treatment: ["Echinocandins (first-line)", "Voriconazole", "Amphotericin B"],
    clinicalSignificance: "Inherently fluconazole resistant. Emerges during fluconazole prophylaxis. Less virulent but difficult to treat. Important in cancer patients.",
    labIdentification: ["CHROMagar: rough pink/purple with white edge", "Elongated cells", "Fluconazole resistant on AST", "MALDI-TOF"],
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Saccharomycetes", order: "Saccharomycetales", family: "Pichiaceae" },
  },
  {
    id: "sporothrix-schenckii",
    name: "Sporothrix schenckii",
    genus: "Sporothrix",
    species: "schenckii",
    gramStain: "Not Applicable",
    shape: "Yeast",
    arrangement: "Cigar-shaped yeast (dimorphic)",
    oxygen: "Aerobe",
    pathogenic: true,
    habitat: "Soil, sphagnum moss, rose thorns, hay",
    diseases: ["Sporotrichosis (lymphocutaneous)", "Disseminated sporotrichosis (AIDS)"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "32 Mb", gcContent: "50%", genes: "~10,000" },
    resistance: { intrinsic: ["Echinocandins"], acquired: ["Rare"], mechanism: "Generally susceptible to azoles" },
    treatment: ["Itraconazole (lymphocutaneous)", "Amphotericin B (disseminated)", "Saturated potassium iodide (SSKI)"],
    clinicalSignificance: "Dimorphic fungus. 'Rose gardener's disease.' Inoculation through skin trauma. Sporotrichoid spread along lymphatics. Cigar-shaped yeast at 37°C.",
    labIdentification: ["Mold at 25°C: brown/black delicate colonies, 'rosette' conidia", "Yeast at 37°C: cigar-shaped budding yeast", "Dimorphism confirms ID"],
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Sordariomycetes", order: "Ophiostomatales", family: "Ophiostomataceae" },
  },
  {
    id: "talaromyces-marneffei",
    name: "Talaromyces marneffei",
    genus: "Talaromyces",
    species: "marneffei (formerly Penicillium marneffei)",
    gramStain: "Not Applicable",
    shape: "Yeast",
    arrangement: "Intracellular yeast with central septum (dimorphic)",
    oxygen: "Aerobe",
    pathogenic: true,
    habitat: "Bamboo rats, soil (Southeast Asia)",
    diseases: ["Disseminated talaromycosis", "Skin lesions (molluscum-like)"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "28.6 Mb", gcContent: "47%", genes: "~10,000" },
    resistance: { intrinsic: ["Echinocandins"], acquired: ["Rare"], mechanism: "Generally susceptible to azoles and amphotericin B" },
    treatment: ["Induction: amphotericin B", "Maintenance: itraconazole", "Lifelong suppression in AIDS"],
    clinicalSignificance: "Only dimorphic Penicillium/Talaromyces species. Endemic in Southeast Asia/Southern China. AIDS-defining in endemic areas. Distinctive central septum (not budding).",
    labIdentification: ["Mold at 25°C: red diffusible pigment (distinctive)", "Yeast at 37°C: intracellular with central septum", "Red pigment production is pathognomonic"],
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Eurotiomycetes", order: "Eurotiales", family: "Trichocomaceae" },
  },
  {
    id: "trichophyton-species",
    name: "Trichophyton species",
    genus: "Trichophyton",
    species: "rubrum/mentagrophytes/tonsurans/etc.",
    gramStain: "Not Applicable",
    shape: "Filamentous",
    arrangement: "Septate hyphae with micro/macroconidia",
    oxygen: "Aerobe",
    pathogenic: true,
    habitat: "Human skin, animals, soil",
    diseases: ["Tinea pedis", "Tinea corporis", "Tinea cruris", "Tinea unguium (onychomycosis)", "Tinea capitis"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "22-24 Mb", gcContent: "48-50%", genes: "~8,000" },
    resistance: { intrinsic: [], acquired: ["Terbinafine (T. rubrum, increasing)", "Azoles (rare)"], mechanism: "ERG1/squalene epoxidase mutations" },
    treatment: ["Terbinafine (oral for nail/scalp)", "Topical azoles (skin)", "Griseofulvin (tinea capitis children)"],
    clinicalSignificance: "Most common dermatophyte. T. rubrum: most common worldwide (tinea pedis, onychomycosis). T. tonsurans: most common tinea capitis in US/UK.",
    labIdentification: ["KOH/calcofluor (hyphae in skin/nail)", "Culture on SDA (1-3 weeks)", "Microconidia morphology", "Urease test", "In vitro hair perforation test"],
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Eurotiomycetes", order: "Onygenales", family: "Arthrodermataceae" },
  },
  {
    id: "fusarium-species",
    name: "Fusarium species",
    genus: "Fusarium",
    species: "solani/oxysporum/etc.",
    gramStain: "Not Applicable",
    shape: "Filamentous",
    arrangement: "Septate hyphae with banana-shaped macroconidia",
    oxygen: "Aerobe",
    pathogenic: true,
    habitat: "Soil, plants, water",
    diseases: ["Keratitis (contact lens)", "Onychomycosis", "Disseminated fusariosis", "Skin lesions"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "40-60 Mb", gcContent: "47-50%", genes: "~14,000-17,000" },
    resistance: { intrinsic: ["Echinocandins", "Most azoles except voriconazole"], acquired: ["Amphotericin B (variable)"], mechanism: "Broad intrinsic resistance" },
    treatment: ["Voriconazole or amphotericin B", "Surgical debridement", "Neutrophil recovery essential"],
    clinicalSignificance: "Second most common invasive mold (after Aspergillus). Uniquely can be blood culture positive (unlike most molds). Keratitis from contaminated contact lens solution.",
    labIdentification: ["Banana/canoe-shaped macroconidia (septate)", "Rapid growth", "Can grow in blood culture", "MALDI-TOF or sequencing"],
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Sordariomycetes", order: "Hypocreales", family: "Nectriaceae" },
  },

  // ==================== PARASITES (additional) ====================
  {
    id: "plasmodium-vivax",
    name: "Plasmodium vivax",
    genus: "Plasmodium",
    species: "vivax",
    gramStain: "Not Applicable",
    shape: "Protozoan",
    arrangement: "Intracellular (enlarged RBCs, Schüffner dots)",
    oxygen: "Aerobe",
    pathogenic: true,
    habitat: "Anopheles mosquitoes, human RBCs (reticulocytes)",
    diseases: ["Malaria (relapsing)", "Vivax malaria"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile in RBCs" },
    molecular: { genome: "27 Mb (14 chromosomes)", gcContent: "42%", genes: "~5,400", notableGenes: ["pvdbp (Duffy binding protein)", "pvmsp1", "pvcrt"] },
    resistance: { intrinsic: ["Primaquine (G6PD-deficient patients)"], acquired: ["Chloroquine (SE Asia, South America)"], mechanism: "Unknown mechanisms, pvcrt implicated" },
    treatment: ["Chloroquine + primaquine (radical cure of hypnozoites)", "ACT (chloroquine-resistant areas)"],
    clinicalSignificance: "Most geographically widespread malaria species. Forms hypnozoites (liver dormant stage) → relapses months/years later. Requires Duffy antigen for RBC invasion.",
    labIdentification: ["Thick/thin blood smears (enlarged RBCs, Schüffner dots, amoeboid trophozoites)", "RDT", "PCR"],
    taxonomy: { domain: "Eukaryota", phylum: "Apicomplexa", class: "Aconoidasida", order: "Haemosporida", family: "Plasmodiidae" },
  },
  {
    id: "babesia-microti",
    name: "Babesia microti",
    genus: "Babesia",
    species: "microti",
    gramStain: "Not Applicable",
    shape: "Protozoan",
    arrangement: "Intracellular ring forms ('Maltese cross')",
    oxygen: "Aerobe",
    pathogenic: true,
    habitat: "Ixodes scapularis ticks, white-footed mouse",
    diseases: ["Babesiosis", "Hemolytic anemia", "Transfusion-transmitted babesiosis"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "6.5 Mb", gcContent: "36%", genes: "~3,700" },
    resistance: { intrinsic: [], acquired: ["Atovaquone (rare mutations)"], mechanism: "Cytochrome b mutations" },
    treatment: ["Atovaquone + azithromycin (mild)", "Clindamycin + quinine (severe)", "Exchange transfusion (severe)"],
    clinicalSignificance: "Tick-borne. Can mimic malaria on blood smear. 'Maltese cross' tetrad form is pathognomonic (but rare). Severe in asplenic patients. Transfusion risk.",
    labIdentification: ["Blood smear (ring forms, 'Maltese cross' tetrads)", "PCR", "Serology (IFA)", "No hemozoin (unlike Plasmodium)"],
    taxonomy: { domain: "Eukaryota", phylum: "Apicomplexa", class: "Aconoidasida", order: "Piroplasmida", family: "Babesiidae" },
  },
  {
    id: "strongyloides-stercoralis",
    name: "Strongyloides stercoralis",
    genus: "Strongyloides",
    species: "stercoralis",
    gramStain: "Not Applicable",
    shape: "Protozoan",
    arrangement: "Rhabditiform and filariform larvae",
    oxygen: "Aerobe",
    pathogenic: true,
    habitat: "Soil (tropical/subtropical regions)",
    diseases: ["Strongyloidiasis", "Hyperinfection syndrome", "Disseminated strongyloidiasis"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Motile (larvae)" },
    molecular: { genome: "43 Mb", gcContent: "22%", genes: "~13,000" },
    resistance: { intrinsic: [], acquired: ["Ivermectin resistance (rare)"], mechanism: "Various" },
    treatment: ["Ivermectin (drug of choice)", "Albendazole (alternative)"],
    clinicalSignificance: "Unique autoinfection cycle → can persist decades. Hyperinfection in immunosuppressed (corticosteroids, HTLV-1). Must screen before starting immunosuppression.",
    labIdentification: ["Stool: rhabditiform larvae (not eggs)", "Stool culture (agar plate method)", "Serology", "Eosinophilia"],
    taxonomy: { domain: "Eukaryota", phylum: "Nematoda", class: "Chromadorea", order: "Rhabditida", family: "Strongyloididae" },
  },
  {
    id: "taenia-solium",
    name: "Taenia solium",
    genus: "Taenia",
    species: "solium",
    gramStain: "Not Applicable",
    shape: "Protozoan",
    arrangement: "Proglottids and scolex (tapeworm)",
    oxygen: "Anaerobe",
    pathogenic: true,
    habitat: "Pigs (intermediate host), humans (definitive/intermediate)",
    diseases: ["Taeniasis (intestinal)", "Neurocysticercosis", "Cysticercosis"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile (proglottids shed)" },
    molecular: { genome: "110 Mb", gcContent: "43%", genes: "~12,000" },
    resistance: { intrinsic: [], acquired: [], mechanism: "N/A" },
    treatment: ["Taeniasis: praziquantel or niclosamide", "Neurocysticercosis: albendazole + steroids + antiepileptics"],
    clinicalSignificance: "Humans are both definitive (intestinal tapeworm) and accidental intermediate host (cysticercosis). Neurocysticercosis is leading cause of epilepsy in endemic areas.",
    labIdentification: ["Stool: proglottids (7-13 uterine branches)", "Stool: eggs (round, striated shell)", "CT/MRI (neurocysticercosis: calcified cysts)", "Serology (EITB)"],
    taxonomy: { domain: "Eukaryota", phylum: "Platyhelminthes", class: "Cestoda", order: "Cyclophyllidea", family: "Taeniidae" },
  },
  {
    id: "schistosoma-mansoni",
    name: "Schistosoma mansoni",
    genus: "Schistosoma",
    species: "mansoni",
    gramStain: "Not Applicable",
    shape: "Protozoan",
    arrangement: "Adult worm pairs (male envelops female)",
    oxygen: "Aerobe",
    pathogenic: true,
    habitat: "Freshwater snails (Biomphalaria), humans",
    diseases: ["Schistosomiasis (intestinal)", "Hepatosplenic disease", "Portal hypertension", "Katayama fever"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Motile (cercariae in water)" },
    molecular: { genome: "363 Mb", gcContent: "34%", genes: "~11,000" },
    resistance: { intrinsic: [], acquired: ["Praziquantel (reduced susceptibility, rare)"], mechanism: "Various" },
    treatment: ["Praziquantel (single dose)", "Oxamniquine (alternative for S. mansoni)"],
    clinicalSignificance: "Blood fluke. Eggs deposited in mesenteric venules → granulomatous inflammation → hepatic fibrosis (Symmers pipestem fibrosis). Lateral-spined eggs.",
    labIdentification: ["Stool O&P: lateral-spined eggs", "Rectal biopsy (crushed tissue)", "Serology", "Eosinophilia"],
    taxonomy: { domain: "Eukaryota", phylum: "Platyhelminthes", class: "Trematoda", order: "Diplostomida", family: "Schistosomatidae" },
  },
  {
    id: "ascaris-lumbricoides",
    name: "Ascaris lumbricoides",
    genus: "Ascaris",
    species: "lumbricoides",
    gramStain: "Not Applicable",
    shape: "Protozoan",
    arrangement: "Large roundworm (20-35 cm adult)",
    oxygen: "Anaerobe",
    pathogenic: true,
    habitat: "Soil (fecal contamination), human intestine",
    diseases: ["Ascariasis", "Löffler syndrome (pulmonary)", "Intestinal obstruction", "Biliary obstruction"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Motile (adult worm)" },
    molecular: { genome: "273 Mb", gcContent: "38%", genes: "~14,000" },
    resistance: { intrinsic: [], acquired: ["Benzimidazoles (some populations)"], mechanism: "Beta-tubulin mutations" },
    treatment: ["Albendazole (single dose)", "Mebendazole", "Ivermectin"],
    clinicalSignificance: "Most common helminth infection worldwide (~800 million infected). Löffler syndrome: eosinophilic pneumonitis during larval migration through lungs.",
    labIdentification: ["Stool O&P: fertile/infertile eggs (mammillated shell)", "Worm passage in stool (large roundworm)", "Eosinophilia", "Chest X-ray (Löffler)"],
    taxonomy: { domain: "Eukaryota", phylum: "Nematoda", class: "Chromadorea", order: "Ascaridida", family: "Ascarididae" },
  },
  {
    id: "echinococcus-granulosus",
    name: "Echinococcus granulosus",
    genus: "Echinococcus",
    species: "granulosus",
    gramStain: "Not Applicable",
    shape: "Protozoan",
    arrangement: "Tiny tapeworm (3-6mm) with hydatid cysts",
    oxygen: "Anaerobe",
    pathogenic: true,
    habitat: "Dogs (definitive host), sheep/humans (intermediate)",
    diseases: ["Cystic echinococcosis (hydatid disease)", "Liver cysts", "Lung cysts"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile (cyst)" },
    molecular: { genome: "115 Mb", gcContent: "42%", genes: "~11,000" },
    resistance: { intrinsic: [], acquired: [], mechanism: "N/A" },
    treatment: ["PAIR (puncture, aspirate, inject, re-aspirate) + albendazole", "Surgical excision", "Albendazole alone (small cysts)"],
    clinicalSignificance: "Hydatid cysts grow slowly over years. Rupture can cause anaphylaxis. 'Daughter cysts' and 'hydatid sand' (protoscoleces). Surgical spillage must be avoided.",
    labIdentification: ["Imaging: cystic lesion with daughter cysts (CE classification)", "Serology (IgG)", "Do NOT aspirate without imaging first", "Protoscoleces in cyst fluid"],
    taxonomy: { domain: "Eukaryota", phylum: "Platyhelminthes", class: "Cestoda", order: "Cyclophyllidea", family: "Taeniidae" },
  },
  {
    id: "wuchereria-bancrofti",
    name: "Wuchereria bancrofti",
    genus: "Wuchereria",
    species: "bancrofti",
    gramStain: "Not Applicable",
    shape: "Protozoan",
    arrangement: "Microfilariae (sheathed) and adult worms",
    oxygen: "Aerobe",
    pathogenic: true,
    habitat: "Mosquitoes (Culex, Anopheles, Aedes)",
    diseases: ["Lymphatic filariasis", "Elephantiasis", "Tropical pulmonary eosinophilia"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Motile (microfilariae)" },
    molecular: { genome: "80 Mb", gcContent: "30%", genes: "~15,000" },
    resistance: { intrinsic: [], acquired: ["Rare"], mechanism: "N/A" },
    treatment: ["DEC (diethylcarbamazine)", "Ivermectin + albendazole (mass drug administration)", "Doxycycline (kills Wolbachia endosymbiont)"],
    clinicalSignificance: "Most common cause of lymphatic filariasis. Adult worms in lymphatic vessels → lymphedema → elephantiasis. Nocturnal periodicity of microfilariae (draw blood at night).",
    labIdentification: ["Thick blood smear at night (nocturnal periodicity)", "Sheathed microfilariae", "Circulating filarial antigen (ICT card)", "Ultrasound ('filarial dance sign')"],
    taxonomy: { domain: "Eukaryota", phylum: "Nematoda", class: "Chromadorea", order: "Rhabditida", family: "Onchocercidae" },
  },
];
