// Comprehensive archaea organism dataset
// Sources: NCBI Taxonomy, BacDive, SILVA, KEGG, Bergey's Manual
import type { Organism } from "./organismData";

export const archaeaOrganisms: Organism[] = [
  // ==================== METHANOGENS ====================
  {
    id: "methanobacterium-smithii",
    name: "Methanobrevibacter smithii",
    genus: "Methanobrevibacter",
    species: "smithii",
    gramStain: "Gram Positive",
    shape: "Archaeal",
    arrangement: "Short rods, often in pairs",
    oxygen: "Obligate Anaerobe",
    pathogenic: false,
    habitat: "Human large intestine (most abundant archaeon in human gut)",
    diseases: ["Generally commensal", "Potential association with obesity and IBS"],
    characteristics: { catalase: "Negative", oxidase: "Negative", motility: "Non-motile" },
    molecular: { genome: "1.85 Mb", gcContent: "31%", genes: "~1,800", notableGenes: ["mcr (methyl-coenzyme M reductase)", "fwd (formylmethanofuran dehydrogenase)", "adhesin-like proteins"] },
    resistance: { intrinsic: ["All standard antibiotics (pseudopeptidoglycan wall)"], acquired: [], mechanism: "Pseudopeptidoglycan cell wall lacks muramic acid (antibiotics targeting peptidoglycan are ineffective)" },
    treatment: ["Not typically treated", "Metronidazole (if necessary)", "Lovastatin (inhibits archaeal membrane synthesis)"],
    clinicalSignificance: "Most abundant human archaeal symbiont (~10^10 per gram feces). Consumes H2 from bacterial fermentation → enhances polysaccharide digestion. Possible role in obesity and metabolic syndrome.",
    labIdentification: ["Anaerobic culture with H2/CO2 atmosphere", "Methane production (gas chromatography)", "16S rRNA PCR (archaea-specific primers)", "Fluorescence microscopy (F420 autofluorescence at 420 nm)"],
    virulenceFactors: ["Adhesin-like proteins", "Enhanced fermentation efficiency (syntrophic interactions)"],
    epidemiology: "Present in ~95% of human guts. Most abundant methanogen in humans.",
    taxonomy: { domain: "Archaea", phylum: "Euryarchaeota", class: "Methanobacteria", order: "Methanobacteriales", family: "Methanobacteriaceae" },
  },
  {
    id: "methanosarcina-barkeri",
    name: "Methanosarcina barkeri",
    genus: "Methanosarcina",
    species: "barkeri",
    gramStain: "Variable",
    shape: "Archaeal",
    arrangement: "Irregular cocci in large aggregates/packets",
    oxygen: "Obligate Anaerobe",
    pathogenic: false,
    habitat: "Freshwater sediments, anaerobic digesters, rumen",
    diseases: ["Non-pathogenic"],
    characteristics: { catalase: "Negative", oxidase: "Negative", motility: "Non-motile" },
    molecular: { genome: "4.8 Mb", gcContent: "39%", genes: "~3,600", notableGenes: ["mcrBDCGA (methyl-coenzyme M reductase operon)", "ackA/pta (aceticlastic methanogenesis)"] },
    resistance: { intrinsic: ["Standard antibiotics"], acquired: [], mechanism: "Methanochondroitin cell wall" },
    treatment: ["Not pathogenic"],
    clinicalSignificance: "Model organism for methanogenesis research. Most metabolically versatile methanogen (utilizes H2/CO2, acetate, methanol, methylamines). Important in biofuel production and wastewater treatment.",
    labIdentification: ["Anaerobic culture (Hungate technique)", "Gas chromatography (methane)", "F420 fluorescence", "16S rRNA sequencing"],
    taxonomy: { domain: "Archaea", phylum: "Euryarchaeota", class: "Methanomicrobia", order: "Methanosarcinales", family: "Methanosarcinaceae" },
  },

  // ==================== HALOPHILES ====================
  {
    id: "halobacterium-salinarum",
    name: "Halobacterium salinarum",
    genus: "Halobacterium",
    species: "salinarum (NRC-1 strain widely studied)",
    gramStain: "Gram Negative",
    shape: "Archaeal",
    arrangement: "Rod-shaped, often pleomorphic at lower salt",
    oxygen: "Obligate Aerobe",
    pathogenic: false,
    habitat: "Hypersaline environments (salt lakes, solar salterns, salted fish)",
    diseases: ["Non-pathogenic", "Food spoilage of salted products (pink discoloration)"],
    characteristics: { catalase: "Positive", oxidase: "Positive", motility: "Motile (archaella)" },
    molecular: { genome: "2.57 Mb (chromosome + 2 megaplasmids)", gcContent: "68%", genes: "~2,600", notableGenes: ["bop (bacteriorhodopsin)", "hop (halorhodopsin)", "gas vesicle gene cluster"] },
    resistance: { intrinsic: ["Most antibiotics", "Penicillins", "Cephalosporins"], acquired: [], mechanism: "S-layer cell wall, no peptidoglycan" },
    treatment: ["Non-pathogenic"],
    clinicalSignificance: "Model extremophile. Contains bacteriorhodopsin (light-driven proton pump → purple membrane). Requires 3.5-5 M NaCl. Used in biotechnology (retinal proteins, bioenergy research).",
    labIdentification: ["Growth requires >3.5 M NaCl", "Red-pink colonies (carotenoids)", "Purple membrane (bacteriorhodopsin)", "Lyses in distilled water", "16S rRNA PCR"],
    taxonomy: { domain: "Archaea", phylum: "Euryarchaeota", class: "Halobacteria", order: "Halobacteriales", family: "Halobacteriaceae" },
  },

  // ==================== THERMOPHILES / HYPERTHERMOPHILES ====================
  {
    id: "sulfolobus-acidocaldarius",
    name: "Sulfolobus acidocaldarius",
    genus: "Sulfolobus",
    species: "acidocaldarius",
    gramStain: "Not Applicable",
    shape: "Archaeal",
    arrangement: "Irregular cocci (lobed)",
    oxygen: "Obligate Aerobe",
    pathogenic: false,
    habitat: "Acidic hot springs, volcanic pools (pH 2-3, 65-85°C)",
    diseases: ["Non-pathogenic"],
    characteristics: { catalase: "Positive", oxidase: "Variable", motility: "Non-motile" },
    molecular: { genome: "2.22 Mb", gcContent: "37%", genes: "~2,200", notableGenes: ["DNA repair genes (high UV/thermal tolerance)", "thermostable enzyme genes"] },
    resistance: { intrinsic: ["All standard antibiotics"], acquired: [], mechanism: "S-layer cell wall, unique lipid membrane (ether-linked isoprenoid)" },
    treatment: ["Non-pathogenic"],
    clinicalSignificance: "Model thermoacidophilic archaeon. Grows at 75-80°C, pH 2-3. Source of thermostable enzymes for biotechnology. CRISPR-Cas system first characterized in archaea.",
    labIdentification: ["Growth at 75-80°C, pH 2-3", "Sulfur metabolism", "S-layer proteins", "16S rRNA sequencing"],
    taxonomy: { domain: "Archaea", phylum: "Thermoproteota", class: "Thermoprotei", order: "Sulfolobales", family: "Sulfolobaceae" },
  },
  {
    id: "pyrococcus-furiosus",
    name: "Pyrococcus furiosus",
    genus: "Pyrococcus",
    species: "furiosus",
    gramStain: "Not Applicable",
    shape: "Archaeal",
    arrangement: "Irregular cocci with flagella",
    oxygen: "Obligate Anaerobe",
    pathogenic: false,
    habitat: "Marine hydrothermal vents (Vulcano Island, Italy)",
    diseases: ["Non-pathogenic"],
    characteristics: { catalase: "Variable", oxidase: "Not applicable", motility: "Motile (archaella, fastest archaeon)" },
    molecular: { genome: "1.91 Mb", gcContent: "41%", genes: "~2,100", notableGenes: ["Pfu DNA polymerase (proofreading PCR enzyme)", "hydrogenase genes", "ferredoxin"] },
    resistance: { intrinsic: ["All standard antibiotics"], acquired: [], mechanism: "No peptidoglycan" },
    treatment: ["Non-pathogenic"],
    clinicalSignificance: "Source of Pfu DNA polymerase (high-fidelity PCR enzyme). Optimal growth at 100°C. 'Rushing fireball' (translation of name). Key organism in thermophilic enzyme research.",
    labIdentification: ["Growth at 100°C (optimal), survives 103°C", "Anaerobic culture with elemental sulfur", "H2S production", "16S rRNA sequencing"],
    taxonomy: { domain: "Archaea", phylum: "Euryarchaeota", class: "Thermococci", order: "Thermococcales", family: "Thermococcaceae" },
  },
  {
    id: "thermus-aquaticus",
    name: "Thermus aquaticus",
    genus: "Thermus",
    species: "aquaticus",
    gramStain: "Gram Negative",
    shape: "Bacilli",
    arrangement: "Rods and filaments",
    oxygen: "Obligate Aerobe",
    pathogenic: false,
    habitat: "Hot springs (Yellowstone National Park), thermal effluents",
    diseases: ["Non-pathogenic"],
    characteristics: { catalase: "Positive", oxidase: "Positive", motility: "Non-motile" },
    molecular: { genome: "2.13 Mb", gcContent: "69%", genes: "~2,200", notableGenes: ["Taq DNA polymerase (PCR revolution)", "carotenoid synthesis genes"] },
    resistance: { intrinsic: ["Most antibiotics at growth temperature"], acquired: [], mechanism: "Thermostable membrane, deinococcus-thermus lineage" },
    treatment: ["Non-pathogenic"],
    clinicalSignificance: "Source of Taq DNA polymerase – revolutionized molecular biology (PCR). Nobel Prize to Kary Mullis (1993). Not strictly an archaeon (Deinococcota) but frequently studied alongside thermophiles.",
    labIdentification: ["Growth at 70-80°C", "Yellow-orange pigmented colonies", "Thermostable enzymes", "16S rRNA (Deinococcota phylum)"],
    taxonomy: { domain: "Bacteria", phylum: "Deinococcota", class: "Deinococci", order: "Thermales", family: "Thermaceae" },
  },

  // ==================== AMMONIA-OXIDIZING ARCHAEA ====================
  {
    id: "nitrosopumilus-maritimus",
    name: "Nitrosopumilus maritimus",
    genus: "Nitrosopumilus",
    species: "maritimus",
    gramStain: "Not Applicable",
    shape: "Archaeal",
    arrangement: "Small straight rods",
    oxygen: "Obligate Aerobe",
    pathogenic: false,
    habitat: "Marine water (most abundant organism in ocean)",
    diseases: ["Non-pathogenic"],
    characteristics: { catalase: "Variable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "1.65 Mb", gcContent: "34%", genes: "~1,800", notableGenes: ["amoA (ammonia monooxygenase)", "ureC (urease)"] },
    resistance: { intrinsic: ["Standard antibiotics"], acquired: [], mechanism: "S-layer, unique lipid membrane" },
    treatment: ["Non-pathogenic"],
    clinicalSignificance: "Most abundant organism in the ocean. Critical role in global nitrogen cycle (ammonia oxidation → nitrification). Thaumarchaeota are among Earth's most numerous organisms.",
    labIdentification: ["Ammonia oxidation measurement", "amoA gene PCR", "Chemolithoautotrophic growth", "16S rRNA sequencing"],
    taxonomy: { domain: "Archaea", phylum: "Nitrososphaerota", class: "Nitrososphaeria", order: "Nitrosopumilales", family: "Nitrosopumilaceae" },
  },

  // ==================== METHANOGENS (Additional) ====================
  {
    id: "methanosphaera-stadtmanae",
    name: "Methanosphaera stadtmanae",
    genus: "Methanosphaera",
    species: "stadtmanae",
    gramStain: "Gram Positive",
    shape: "Archaeal",
    arrangement: "Cocci, singles and pairs",
    oxygen: "Obligate Anaerobe",
    pathogenic: false,
    habitat: "Human intestinal tract",
    diseases: ["Non-pathogenic", "Potential association with IBD"],
    characteristics: { catalase: "Negative", oxidase: "Negative", motility: "Non-motile" },
    molecular: { genome: "1.77 Mb", gcContent: "28%", genes: "~1,500", notableGenes: ["mcr (methyl-coenzyme M reductase)", "mtaABC (methanol:CoM methyltransferase)"] },
    resistance: { intrinsic: ["Standard antibiotics (pseudopeptidoglycan)"], acquired: [], mechanism: "Pseudopeptidoglycan cell wall" },
    treatment: ["Not typically treated"],
    clinicalSignificance: "Second most abundant human gut archaeon after M. smithii. Unique: only reduces methanol with H2 (cannot use CO2 or acetate). Strong immunostimulatory properties (activates TLR2/NOD2). Potential IBD biomarker.",
    labIdentification: ["Strict anaerobic culture with methanol + H2", "Methane production", "Pseudopeptidoglycan (resists lysozyme)", "16S rRNA sequencing (archaea-specific)"],
    taxonomy: { domain: "Archaea", phylum: "Euryarchaeota", class: "Methanobacteria", order: "Methanobacteriales", family: "Methanobacteriaceae" },
  },
];
