// Comprehensive fungi organism dataset
// Sources: NCBI Taxonomy, CDC Fungal Diseases, PubMed, UniProt, KEGG
import type { Organism } from "./organismData";

export const fungiOrganisms: Organism[] = [
  // ==================== YEASTS ====================
  {
    id: "candida-auris",
    name: "Candida auris",
    genus: "Candida",
    species: "auris",
    gramStain: "Not Applicable",
    shape: "Yeast",
    arrangement: "Oval budding yeast",
    oxygen: "Facultative Anaerobe",
    pathogenic: true,
    habitat: "Healthcare environments, skin",
    diseases: ["Candidemia", "Wound infections", "Ear infections", "Multidrug-resistant invasive candidiasis"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "12.3 Mb", gcContent: "44.5%", genes: "~5,600", notableGenes: ["ERG11 (azole target)", "FKS1 (echinocandin target)", "CDR1/MDR1 (efflux pumps)"] },
    resistance: { intrinsic: ["Fluconazole (90% of isolates)"], acquired: ["Amphotericin B (30%)", "Echinocandins (5-10%)"], mechanism: "ERG11 mutations, FKS1 mutations, efflux pumps CDR1/MDR1" },
    treatment: ["Echinocandins (first-line)", "Amphotericin B (if echinocandin-resistant)", "Susceptibility testing essential"],
    clinicalSignificance: "Emerging multidrug-resistant fungal pathogen. CDC urgent threat. Difficult to identify by conventional methods. Causes nosocomial outbreaks. Persists on surfaces.",
    labIdentification: ["MALDI-TOF MS (most reliable)", "CHROMagar Candida Plus", "Sequencing of ITS/D1-D2 region", "Often misidentified as C. haemulonii by API/VITEK"],
    virulenceFactors: ["Biofilm formation", "Phospholipase production", "Proteinase secretion", "Thermotolerance (up to 42°C)", "Environmental persistence"],
    transmission: "Nosocomial transmission via contaminated surfaces, medical devices. Skin colonization. Healthcare-associated outbreaks",
    epidemiology: "First described in Japan (2009). Now reported in >40 countries. CDC urgent threat pathogen. High mortality (30-60%).",
    prevention: ["Contact precautions", "Enhanced environmental cleaning", "Chlorine-based disinfectants", "Surveillance screening"],
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Saccharomycetes", order: "Saccharomycetales", family: "Debaryomycetaceae" },
  },
  {
    id: "candida-glabrata",
    name: "Candida glabrata",
    genus: "Candida",
    species: "glabrata (Nakaseomyces glabrata)",
    gramStain: "Not Applicable",
    shape: "Yeast",
    arrangement: "Small oval yeast, no pseudohyphae",
    oxygen: "Facultative Anaerobe",
    pathogenic: true,
    habitat: "Human GI tract, urogenital tract",
    diseases: ["Candidemia", "Urinary tract infections", "Mucosal candidiasis", "Peritonitis"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "12.3 Mb", gcContent: "38.8%", genes: "~5,200", notableGenes: ["ERG11", "CDR1/CDR2/SNQ2 (efflux)", "FKS1/FKS2"] },
    resistance: { intrinsic: ["Reduced fluconazole susceptibility"], acquired: ["Fluconazole (15-25%)", "Echinocandins (3-10%)"], mechanism: "CDR1/CDR2 upregulation, FKS1/FKS2 mutations, ERG11 upregulation" },
    treatment: ["Echinocandins (first-line)", "Amphotericin B", "Voriconazole (if susceptible)"],
    clinicalSignificance: "Second most common Candida in bloodstream infections. Increasing incidence. Inherently less susceptible to azoles. Associated with azole prophylaxis.",
    labIdentification: ["CHROMagar (dark pink colonies)", "MALDI-TOF", "No pseudohyphae on cornmeal agar", "Trehalose assimilation positive"],
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Saccharomycetes", order: "Saccharomycetales", family: "Saccharomycetaceae" },
  },
  {
    id: "candida-tropicalis",
    name: "Candida tropicalis",
    genus: "Candida",
    species: "tropicalis",
    gramStain: "Not Applicable",
    shape: "Yeast",
    arrangement: "Oval yeast with pseudohyphae",
    oxygen: "Facultative Anaerobe",
    pathogenic: true,
    habitat: "Human GI tract, skin",
    diseases: ["Candidemia", "Disseminated candidiasis", "Peritonitis", "UTI"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "14.6 Mb", gcContent: "33.2%", genes: "~6,200", notableGenes: ["ERG11", "SAP genes", "ALS genes"] },
    resistance: { intrinsic: [], acquired: ["Fluconazole (10-15%)", "Echinocandins (rare)"], mechanism: "ERG11 mutations, efflux pumps" },
    treatment: ["Fluconazole (if susceptible)", "Echinocandins", "Amphotericin B"],
    clinicalSignificance: "Third most common Candida species. More virulent in neutropenic patients. Common in tropical/subtropical regions. Strong biofilm former.",
    labIdentification: ["CHROMagar (dark blue-metallic blue)", "Sucrose fermentation positive", "MALDI-TOF", "API 20C AUX"],
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Saccharomycetes", order: "Saccharomycetales", family: "Debaryomycetaceae" },
  },
  {
    id: "candida-parapsilosis",
    name: "Candida parapsilosis",
    genus: "Candida",
    species: "parapsilosis",
    gramStain: "Not Applicable",
    shape: "Yeast",
    arrangement: "Oval to elongated yeast",
    oxygen: "Facultative Anaerobe",
    pathogenic: true,
    habitat: "Human skin, environmental surfaces",
    diseases: ["Candidemia (neonatal)", "Catheter-related infections", "Endocarditis", "Wound infections"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "13.0 Mb", gcContent: "38.7%", genes: "~5,700", notableGenes: ["FKS1", "ERG11", "lipase genes"] },
    resistance: { intrinsic: ["Reduced echinocandin susceptibility (naturally higher MIC)"], acquired: ["Fluconazole (rare)"], mechanism: "Natural FKS1 polymorphism (P660A)" },
    treatment: ["Fluconazole (first-line)", "Amphotericin B", "Echinocandins (higher MICs)"],
    clinicalSignificance: "Common in neonatal ICU. Associated with parenteral nutrition, central lines. Biofilm on prosthetic devices. Hand carriage by HCWs.",
    labIdentification: ["CHROMagar (cream-white)", "Pseudohyphae on cornmeal (sage-like)", "MALDI-TOF"],
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Saccharomycetes", order: "Saccharomycetales", family: "Debaryomycetaceae" },
  },
  {
    id: "malassezia-furfur",
    name: "Malassezia furfur",
    genus: "Malassezia",
    species: "furfur",
    gramStain: "Not Applicable",
    shape: "Yeast",
    arrangement: "Round to oval yeast with lipid dependence",
    oxygen: "Aerobe",
    pathogenic: true,
    habitat: "Human skin (lipid-rich areas)",
    diseases: ["Pityriasis versicolor", "Seborrheic dermatitis", "Folliculitis", "Catheter-related fungemia (neonates)"],
    characteristics: { catalase: "Positive", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "9.0 Mb", gcContent: "55-66%", genes: "~4,200", notableGenes: ["lipase genes", "phospholipase genes"] },
    resistance: { intrinsic: [], acquired: [], mechanism: "N/A" },
    treatment: ["Topical azoles (pityriasis versicolor)", "Selenium sulfide shampoo", "Ketoconazole shampoo (seborrheic dermatitis)"],
    clinicalSignificance: "Lipophilic yeast, part of normal skin flora. Causes hypo/hyperpigmented patches. 'Spaghetti and meatballs' on KOH. Requires lipid supplementation for culture.",
    labIdentification: ["KOH: short hyphae + round yeast (spaghetti and meatballs)", "Culture requires olive oil overlay", "Wood's lamp: golden fluorescence", "MALDI-TOF"],
    taxonomy: { domain: "Eukaryota", phylum: "Basidiomycota", class: "Malasseziomycetes", order: "Malasseziales", family: "Malasseziaceae" },
  },

  // ==================== DIMORPHIC FUNGI ====================
  {
    id: "histoplasma-capsulatum",
    name: "Histoplasma capsulatum",
    genus: "Histoplasma",
    species: "capsulatum",
    gramStain: "Not Applicable",
    shape: "Dimorphic",
    arrangement: "Yeast (37°C) / Mold with tuberculate macroconidia (25°C)",
    oxygen: "Aerobe",
    pathogenic: true,
    habitat: "Soil enriched with bird/bat droppings (Ohio/Mississippi River valleys)",
    diseases: ["Pulmonary histoplasmosis", "Disseminated histoplasmosis", "Mediastinal fibrosis", "Pericarditis"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "33 Mb", gcContent: "42%", genes: "~9,300", notableGenes: ["CBP1 (calcium-binding)", "YPS3 (yeast-phase specific)"] },
    resistance: { intrinsic: [], acquired: ["Azole resistance (rare)"], mechanism: "ERG11 mutations" },
    treatment: ["Itraconazole (mild-moderate)", "Amphotericin B (severe/disseminated)", "12 months for disseminated in AIDS"],
    clinicalSignificance: "Most common endemic mycosis in US. Intracellular pathogen of macrophages. Small yeast (2-4 µm) within macrophages. Cave explorers, chicken farmers at risk.",
    labIdentification: ["Culture: tuberculate macroconidia (mold phase)", "GMS/PAS stain of tissue", "Urine/serum Histoplasma antigen (EIA)", "DNA probe", "MALDI-TOF"],
    virulenceFactors: ["Intracellular survival in macrophages", "CBP1 (calcium binding protein)", "Alpha-glucan (masking beta-glucan from immune recognition)", "Siderophores"],
    transmission: "Inhalation of microconidia from disturbed soil. Not person-to-person",
    epidemiology: "Endemic in Ohio/Mississippi River valleys (US), Central America, parts of Africa/Asia. ~500,000 infections/year in US. HIV/AIDS patients at high risk for dissemination.",
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Eurotiomycetes", order: "Onygenales", family: "Ajellomycetaceae" },
  },
  {
    id: "blastomyces-dermatitidis",
    name: "Blastomyces dermatitidis",
    genus: "Blastomyces",
    species: "dermatitidis",
    gramStain: "Not Applicable",
    shape: "Dimorphic",
    arrangement: "Large broad-based budding yeast (37°C) / Mold (25°C)",
    oxygen: "Aerobe",
    pathogenic: true,
    habitat: "Moist soil near waterways (Great Lakes, Ohio/Mississippi River valleys)",
    diseases: ["Pulmonary blastomycosis", "Cutaneous blastomycosis", "Disseminated blastomycosis", "Osteomyelitis"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "66.6 Mb", gcContent: "39%", genes: "~9,600", notableGenes: ["BAD1 (adhesin/immune modulator)", "DRK1 (dimorphism)"] },
    resistance: { intrinsic: [], acquired: [], mechanism: "N/A" },
    treatment: ["Itraconazole (mild-moderate)", "Amphotericin B (severe, CNS)", "Voriconazole (CNS blastomycosis)"],
    clinicalSignificance: "Broad-based budding yeast (8-15 µm) is diagnostic. 'Pilot wheel' appearance. Verrucous skin lesions can mimic squamous cell carcinoma.",
    labIdentification: ["KOH/calcofluor: broad-based budding yeast", "Culture: mold phase (lollipop conidia)", "DNA probe", "Urine antigen (cross-reacts with Histoplasma)"],
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Eurotiomycetes", order: "Onygenales", family: "Ajellomycetaceae" },
  },
  {
    id: "coccidioides-immitis",
    name: "Coccidioides immitis",
    genus: "Coccidioides",
    species: "immitis",
    gramStain: "Not Applicable",
    shape: "Dimorphic",
    arrangement: "Spherules with endospores (tissue) / Mold with arthroconidia (25°C)",
    oxygen: "Aerobe",
    pathogenic: true,
    habitat: "Arid desert soil (Southwestern US, Mexico, Central/South America)",
    diseases: ["Valley fever (coccidioidomycosis)", "Pulmonary coccidioidomycosis", "Disseminated coccidioidomycosis", "Meningitis"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "28.9 Mb", gcContent: "46%", genes: "~7,200", notableGenes: ["SOWgp (spherule outer wall glycoprotein)", "URE (urease)"] },
    resistance: { intrinsic: [], acquired: ["Azole resistance (rare)"], mechanism: "ERG11 mutations" },
    treatment: ["Fluconazole (mild pulmonary, meningitis)", "Itraconazole (skeletal)", "Amphotericin B (severe/disseminated)"],
    clinicalSignificance: "BSL-3 pathogen. Arthroconidia are highly infectious (10 spores can cause infection). Filipino and African American heritage have higher dissemination risk. Lifelong treatment for meningitis.",
    labIdentification: ["Spherules with endospores in tissue (pathognomonic)", "Culture: barrel-shaped arthroconidia (BIOHAZARD)", "DNA probe", "Serology: IgM (tube precipitin), IgG (complement fixation)"],
    virulenceFactors: ["Arthroconidia conversion to spherules", "SOWgp (immune modulation)", "Metalloproteinase (tissue invasion)", "Urease (tissue damage)"],
    transmission: "Inhalation of arthroconidia from disturbed soil. Not person-to-person. Earthquakes, dust storms increase risk",
    epidemiology: "Endemic in SW US (Arizona, California San Joaquin Valley), Mexico. ~150,000 infections/year in US. 60% asymptomatic.",
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Eurotiomycetes", order: "Onygenales", family: "Onygenaceae" },
  },
  {
    id: "talaromyces-marneffei",
    name: "Talaromyces marneffei",
    genus: "Talaromyces",
    species: "marneffei (formerly Penicillium marneffei)",
    gramStain: "Not Applicable",
    shape: "Dimorphic",
    arrangement: "Yeast with transverse septum (37°C) / Mold with red pigment (25°C)",
    oxygen: "Aerobe",
    pathogenic: true,
    habitat: "Bamboo rats, soil in Southeast Asia",
    diseases: ["Disseminated talaromycosis", "Skin lesions (molluscum-like)", "Pneumonia", "Hepatosplenomegaly"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "28.6 Mb", gcContent: "46.7%", genes: "~10,600", notableGenes: ["mp1p (mannoprotein)", "gasA/gasC (cell wall)"] },
    resistance: { intrinsic: [], acquired: [], mechanism: "N/A" },
    treatment: ["Amphotericin B (induction)", "Itraconazole (maintenance)", "Secondary prophylaxis until immune reconstitution"],
    clinicalSignificance: "Only dimorphic fungus that divides by fission (transverse septum), not budding. AIDS-defining illness in SE Asia. Diffuse skin lesions resemble molluscum contagiosum.",
    labIdentification: ["Yeast with central septum on Wright stain", "Red diffusible pigment at 25°C on SDA", "Culture (BSL-3 recommended)", "Histoplasma antigen cross-reaction"],
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Eurotiomycetes", order: "Eurotiales", family: "Trichocomaceae" },
  },
  {
    id: "sporothrix-schenckii",
    name: "Sporothrix schenckii",
    genus: "Sporothrix",
    species: "schenckii",
    gramStain: "Not Applicable",
    shape: "Dimorphic",
    arrangement: "Cigar-shaped yeast (37°C) / Mold with rosette conidia (25°C)",
    oxygen: "Aerobe",
    pathogenic: true,
    habitat: "Soil, decaying vegetation, sphagnum moss, rose thorns",
    diseases: ["Lymphocutaneous sporotrichosis", "Fixed cutaneous sporotrichosis", "Pulmonary sporotrichosis", "Disseminated sporotrichosis"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "32.3 Mb", gcContent: "48%", genes: "~10,300", notableGenes: ["gp70 (adhesin)", "melanin synthesis genes"] },
    resistance: { intrinsic: ["Fluconazole"], acquired: [], mechanism: "Intrinsic azole tolerance" },
    treatment: ["Itraconazole (lymphocutaneous)", "Potassium iodide (SSKI)", "Amphotericin B (disseminated)", "Terbinafine (alternative)"],
    clinicalSignificance: "'Rose gardener's disease'. Traumatic inoculation → nodular lymphangitis ascending along lymphatic drainage. Most common subcutaneous mycosis worldwide.",
    labIdentification: ["Culture: rosette/flower-like conidia (mold phase)", "Cigar-shaped yeast on tissue biopsy", "PAS/GMS staining", "Asteroid bodies in tissue"],
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Sordariomycetes", order: "Ophiostomatales", family: "Ophiostomataceae" },
  },

  // ==================== MOLDS ====================
  {
    id: "aspergillus-niger",
    name: "Aspergillus niger",
    genus: "Aspergillus",
    species: "niger",
    gramStain: "Not Applicable",
    shape: "Filamentous",
    arrangement: "Septate hyphae with black conidial heads",
    oxygen: "Obligate Aerobe",
    pathogenic: true,
    habitat: "Ubiquitous in soil, decaying vegetation",
    diseases: ["Otomycosis", "Aspergilloma", "Invasive aspergillosis (rare)", "Allergic bronchopulmonary aspergillosis"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "33.9 Mb", gcContent: "50.3%", genes: "~10,800", notableGenes: ["fwnA (melanin)", "citric acid synthesis genes"] },
    resistance: { intrinsic: [], acquired: ["Amphotericin B (some strains)"], mechanism: "Variable" },
    treatment: ["Voriconazole", "Amphotericin B", "Surgical debridement (aspergilloma)"],
    clinicalSignificance: "Most common cause of otomycosis. Industrial organism (citric acid production). Black colonies distinctive. Less virulent than A. fumigatus.",
    labIdentification: ["Black colonies on SDA", "Biseriate conidial heads", "Septate hyphae (45° branching)", "MALDI-TOF"],
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Eurotiomycetes", order: "Eurotiales", family: "Aspergillaceae" },
  },
  {
    id: "aspergillus-flavus",
    name: "Aspergillus flavus",
    genus: "Aspergillus",
    species: "flavus",
    gramStain: "Not Applicable",
    shape: "Filamentous",
    arrangement: "Septate hyphae with yellow-green conidial heads",
    oxygen: "Obligate Aerobe",
    pathogenic: true,
    habitat: "Soil, grain, peanuts, corn",
    diseases: ["Invasive aspergillosis", "Aspergillus sinusitis", "Keratitis", "Aflatoxicosis"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "36.8 Mb", gcContent: "48.4%", genes: "~12,600", notableGenes: ["aflR/aflS (aflatoxin regulation)", "cyp51A (azole target)"] },
    resistance: { intrinsic: [], acquired: ["Amphotericin B (some)"], mechanism: "cyp51A mutations" },
    treatment: ["Voriconazole", "Amphotericin B", "Posaconazole"],
    clinicalSignificance: "Second most common Aspergillus. Produces aflatoxins (most potent natural carcinogen → hepatocellular carcinoma). Most common Aspergillus in sinusitis.",
    labIdentification: ["Yellow-green colonies on SDA", "Uniseriate and biseriate conidial heads", "Aflatoxin detection (HPLC, ELISA)", "MALDI-TOF"],
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Eurotiomycetes", order: "Eurotiales", family: "Aspergillaceae" },
  },
  {
    id: "mucor-species",
    name: "Mucor species",
    genus: "Mucor",
    species: "spp.",
    gramStain: "Not Applicable",
    shape: "Filamentous",
    arrangement: "Broad aseptate (pauciseptate) hyphae with sporangia",
    oxygen: "Aerobe",
    pathogenic: true,
    habitat: "Soil, decaying organic matter, bread",
    diseases: ["Rhinocerebral mucormycosis", "Pulmonary mucormycosis", "Cutaneous mucormycosis", "GI mucormycosis"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "36-46 Mb", gcContent: "34-38%", genes: "~11,000-14,000" },
    resistance: { intrinsic: ["Voriconazole", "Echinocandins"], acquired: [], mechanism: "N/A" },
    treatment: ["Amphotericin B (liposomal, high dose)", "Posaconazole/isavuconazole", "Surgical debridement (essential)", "Iron chelation (deferasirox - adjunct)"],
    clinicalSignificance: "Rapidly progressive angioinvasive infection. Risk factors: DKA, neutropenia, deferoxamine, iron overload. Ribbon-like aseptate hyphae with 90° branching. Very high mortality (40-80%).",
    labIdentification: ["Broad pauciseptate hyphae on KOH/tissue", "Lid-like columella", "Rapid growth on SDA (fills plate in 3 days)", "Cannot identify to species by morphology alone"],
    virulenceFactors: ["Angioinvasion (vascular thrombosis/infarction)", "Spore coat protein (CotH)", "Iron acquisition via siderophores", "Thermotolerance"],
    taxonomy: { domain: "Eukaryota", phylum: "Mucoromycota", class: "Mucoromycetes", order: "Mucorales", family: "Mucoraceae" },
  },
  {
    id: "rhizopus-species",
    name: "Rhizopus species",
    genus: "Rhizopus",
    species: "spp. (R. arrhizus/oryzae most common)",
    gramStain: "Not Applicable",
    shape: "Filamentous",
    arrangement: "Broad aseptate hyphae with rhizoids and sporangia",
    oxygen: "Aerobe",
    pathogenic: true,
    habitat: "Soil, decaying fruits, bread",
    diseases: ["Rhinocerebral mucormycosis", "Pulmonary mucormycosis", "Disseminated mucormycosis"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "45.2 Mb", gcContent: "35%", genes: "~14,000", notableGenes: ["CotH (spore coat protein)", "FTR1 (iron permease)"] },
    resistance: { intrinsic: ["Voriconazole", "Echinocandins"], acquired: [], mechanism: "N/A" },
    treatment: ["Liposomal amphotericin B", "Isavuconazole", "Posaconazole", "Aggressive surgical debridement"],
    clinicalSignificance: "Most common cause of mucormycosis. Distinguishable from Mucor by rhizoids (root-like structures). DKA is #1 risk factor. Black eschar of palate/nose is classic finding.",
    labIdentification: ["Rhizoids at base of sporangiophores (key feature)", "Apophysate columella", "Broad aseptate hyphae in tissue", "MALDI-TOF"],
    taxonomy: { domain: "Eukaryota", phylum: "Mucoromycota", class: "Mucoromycetes", order: "Mucorales", family: "Rhizopodaceae" },
  },
  {
    id: "fusarium-species",
    name: "Fusarium species",
    genus: "Fusarium",
    species: "spp. (F. solani, F. oxysporum most common)",
    gramStain: "Not Applicable",
    shape: "Filamentous",
    arrangement: "Septate hyphae with canoe-shaped macroconidia",
    oxygen: "Aerobe",
    pathogenic: true,
    habitat: "Soil, plants, water systems",
    diseases: ["Keratitis (contact lens)", "Onychomycosis", "Disseminated fusariosis", "Skin infections"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "36-50 Mb", gcContent: "48-50%", genes: "~14,000-17,000" },
    resistance: { intrinsic: ["Most azoles", "Echinocandins"], acquired: ["Amphotericin B (some)"], mechanism: "Intrinsic multidrug resistance" },
    treatment: ["Voriconazole or posaconazole", "Amphotericin B", "Combination therapy often needed", "Source control (remove catheter, debride)"],
    clinicalSignificance: "Second most common invasive mold after Aspergillus. Characteristically causes positive blood cultures (unlike Aspergillus). Distinctive painful skin lesions (targetoid).",
    labIdentification: ["Banana/canoe-shaped macroconidia", "Purple-lavender colony color", "Blood culture positive (unlike Aspergillus)", "MALDI-TOF, sequencing"],
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Sordariomycetes", order: "Hypocreales", family: "Nectriaceae" },
  },

  // ==================== DERMATOPHYTES ====================
  {
    id: "trichophyton-rubrum",
    name: "Trichophyton rubrum",
    genus: "Trichophyton",
    species: "rubrum",
    gramStain: "Not Applicable",
    shape: "Filamentous",
    arrangement: "Septate hyphae with tear-drop microconidia",
    oxygen: "Aerobe",
    pathogenic: true,
    habitat: "Human skin, nails (anthropophilic)",
    diseases: ["Tinea pedis (athlete's foot)", "Tinea corporis (ringworm)", "Tinea unguium (onychomycosis)", "Tinea cruris (jock itch)"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "22.5 Mb", gcContent: "48%", genes: "~8,600", notableGenes: ["Subtilisins (proteases)", "Keratinase genes"] },
    resistance: { intrinsic: [], acquired: ["Terbinafine (increasing reports)"], mechanism: "Point mutations in squalene epoxidase gene" },
    treatment: ["Terbinafine (oral for nails)", "Topical azoles (skin)", "Griseofulvin", "Itraconazole"],
    clinicalSignificance: "Most common dermatophyte worldwide. Causes >70% of dermatophyte infections. Chronic infections. Produces red pigment on reverse of colony.",
    labIdentification: ["KOH: septate hyphae and arthroconidia", "SDA culture: white fluffy surface, red reverse", "Tear-drop microconidia along hyphae", "Urease negative (vs T. mentagrophytes)", "Dermatophyte test medium (DTM): red color change"],
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Eurotiomycetes", order: "Onygenales", family: "Arthrodermataceae" },
  },
  {
    id: "trichophyton-mentagrophytes",
    name: "Trichophyton mentagrophytes",
    genus: "Trichophyton",
    species: "mentagrophytes (interdigitale complex)",
    gramStain: "Not Applicable",
    shape: "Filamentous",
    arrangement: "Septate hyphae with round microconidia in clusters",
    oxygen: "Aerobe",
    pathogenic: true,
    habitat: "Humans, animals (zoophilic variants)",
    diseases: ["Tinea pedis", "Tinea corporis (inflammatory)", "Tinea barbae", "Kerion"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "22.6 Mb", gcContent: "48%", genes: "~8,500" },
    resistance: { intrinsic: [], acquired: ["Terbinafine (rare)"], mechanism: "Squalene epoxidase mutations" },
    treatment: ["Terbinafine", "Itraconazole", "Topical azoles", "Griseofulvin"],
    clinicalSignificance: "Causes more inflammatory infections than T. rubrum. Zoophilic strains from rodents, cats, dogs cause acute tinea corporis with kerion. Urease positive (differentiates from T. rubrum).",
    labIdentification: ["Round microconidia in grape-like clusters", "Spiral hyphae (in culture)", "Urease positive", "In vitro hair perforation test positive"],
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Eurotiomycetes", order: "Onygenales", family: "Arthrodermataceae" },
  },
  {
    id: "microsporum-canis",
    name: "Microsporum canis",
    genus: "Microsporum",
    species: "canis",
    gramStain: "Not Applicable",
    shape: "Filamentous",
    arrangement: "Septate hyphae with thick-walled spindle macroconidia",
    oxygen: "Aerobe",
    pathogenic: true,
    habitat: "Cats, dogs (zoophilic)",
    diseases: ["Tinea capitis (children)", "Tinea corporis", "Kerion"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "23.3 Mb", gcContent: "47%", genes: "~8,800" },
    resistance: { intrinsic: [], acquired: [], mechanism: "N/A" },
    treatment: ["Griseofulvin (tinea capitis)", "Terbinafine", "Itraconazole"],
    clinicalSignificance: "Most common cause of tinea capitis outside US. Fluoresces bright green under Wood's lamp (key diagnostic feature). Acquired from cats/dogs.",
    labIdentification: ["Wood's lamp: bright green fluorescence", "Thick-walled spindle-shaped macroconidia with >6 cells", "Yellow colony with fluffy white surface", "DTM positive"],
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Eurotiomycetes", order: "Onygenales", family: "Arthrodermataceae" },
  },
  {
    id: "epidermophyton-floccosum",
    name: "Epidermophyton floccosum",
    genus: "Epidermophyton",
    species: "floccosum",
    gramStain: "Not Applicable",
    shape: "Filamentous",
    arrangement: "Septate hyphae with smooth club-shaped macroconidia",
    oxygen: "Aerobe",
    pathogenic: true,
    habitat: "Humans (anthropophilic)",
    diseases: ["Tinea cruris (jock itch)", "Tinea pedis", "Tinea corporis"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "26.2 Mb", gcContent: "47%", genes: "~8,900" },
    resistance: { intrinsic: [], acquired: [], mechanism: "N/A" },
    treatment: ["Topical azoles", "Terbinafine", "Griseofulvin"],
    clinicalSignificance: "Only dermatophyte that does NOT infect hair. Causes skin and nail infections only. Anthropophilic. Smooth macroconidia in clusters (beaver tail shape).",
    labIdentification: ["Smooth club-shaped macroconidia in clusters", "NO microconidia (key feature)", "Khaki-green colony", "Does NOT infect hair (no hair perforation)"],
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Eurotiomycetes", order: "Onygenales", family: "Arthrodermataceae" },
  },

  // ==================== OTHER CLINICALLY SIGNIFICANT FUNGI ====================
  {
    id: "pneumocystis-jirovecii",
    name: "Pneumocystis jirovecii",
    genus: "Pneumocystis",
    species: "jirovecii (formerly carinii in humans)",
    gramStain: "Not Applicable",
    shape: "Yeast",
    arrangement: "Cysts (contain intracystic bodies) and trophic forms",
    oxygen: "Obligate Aerobe",
    pathogenic: true,
    habitat: "Human lungs (obligate)",
    diseases: ["Pneumocystis pneumonia (PCP/PJP)", "AIDS-defining illness"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "8.4 Mb", gcContent: "30%", genes: "~3,700", notableGenes: ["msg (major surface glycoprotein family)", "DHPS (sulfa target)"] },
    resistance: { intrinsic: [], acquired: ["TMP-SMX (DHPS mutations, rare clinical significance)"], mechanism: "DHPS gene mutations" },
    treatment: ["TMP-SMX (first-line)", "Pentamidine (IV, alternative)", "Atovaquone (mild)", "Corticosteroids if PaO2 <70 mmHg"],
    clinicalSignificance: "AIDS-defining illness when CD4 <200. Cannot be cultured. Classified as fungus by rRNA but lacks ergosterol. Bilateral ground-glass opacities on CT.",
    labIdentification: ["GMS stain (crushed ping-pong ball cysts)", "DFA with monoclonal antibodies", "Beta-D-glucan elevated", "PCR", "CANNOT be cultured"],
    virulenceFactors: ["MSG (major surface glycoprotein - antigenic variation)", "Beta-1,3-glucan in cyst wall", "Alveolar epithelial adhesion"],
    epidemiology: "Ubiquitous. Most people seropositive by age 4. Disease only in immunocompromised (CD4 <200, transplant, chronic steroids).",
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Pneumocystidomycetes", order: "Pneumocystidales", family: "Pneumocystidaceae" },
  },
  {
    id: "scedosporium-apiospermum",
    name: "Scedosporium apiospermum",
    genus: "Scedosporium",
    species: "apiospermum (Pseudallescheria boydii complex)",
    gramStain: "Not Applicable",
    shape: "Filamentous",
    arrangement: "Septate hyphae with single oval conidia",
    oxygen: "Aerobe",
    pathogenic: true,
    habitat: "Soil, polluted water, sewage",
    diseases: ["Mycetoma (eumycetoma)", "Disseminated infection (transplant)", "Pneumonia", "CNS infection"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "43.1 Mb", gcContent: "47%", genes: "~11,000" },
    resistance: { intrinsic: ["Amphotericin B"], acquired: [], mechanism: "Intrinsic amphotericin B resistance" },
    treatment: ["Voriconazole (first-line)", "Posaconazole", "Surgical debridement"],
    clinicalSignificance: "Near-drowning aspiration → pulmonary/CNS infection. Mycetoma (draining sinuses with white grains). Intrinsically resistant to amphotericin B (unlike Aspergillus).",
    labIdentification: ["Single oval conidia on conidiophores", "Graphium synanamorph (coremia)", "White to gray colony", "MALDI-TOF, sequencing"],
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Sordariomycetes", order: "Microascales", family: "Microascaceae" },
  },
];
