import jsPDF from "jspdf";
import type { Organism } from "./organismData";

export function generateOrganismPdf(organism: Organism) {
  const doc = new jsPDF();
  let y = 20;
  const margin = 20;
  const pageWidth = 170;

  const addLine = (text: string, fontSize = 10, bold = false) => {
    doc.setFontSize(fontSize);
    doc.setFont("helvetica", bold ? "bold" : "normal");
    const lines = doc.splitTextToSize(text, pageWidth);
    if (y + lines.length * (fontSize * 0.5) > 280) {
      doc.addPage();
      y = 20;
    }
    doc.text(lines, margin, y);
    y += lines.length * (fontSize * 0.45) + 3;
  };

  const addSection = (title: string) => {
    y += 4;
    addLine(title, 13, true);
    y += 1;
  };

  // Header
  addLine(organism.name, 18, true);
  addLine(`${organism.genus} ${organism.species}`, 11);
  y += 2;
  addLine(`${organism.gramStain} • ${organism.shape} • ${organism.arrangement}`, 10);
  addLine(`${organism.pathogenic ? "Pathogenic" : "Commensal"} • ${organism.oxygen}`, 10);

  // Overview
  addSection("Overview");
  addLine(`Habitat: ${organism.habitat}`);
  addLine(`Clinical Significance: ${organism.clinicalSignificance}`);

  // Characteristics
  addSection("Biochemical Characteristics");
  addLine(`Catalase: ${organism.characteristics.catalase} | Oxidase: ${organism.characteristics.oxidase}`);
  addLine(`Motility: ${organism.characteristics.motility}`);
  if (organism.characteristics.hemolysis) addLine(`Hemolysis: ${organism.characteristics.hemolysis}`);
  if (organism.characteristics.coagulase) addLine(`Coagulase: ${organism.characteristics.coagulase}`);

  // Diseases
  addSection("Associated Diseases");
  organism.diseases.forEach((d) => addLine(`• ${d}`));

  // Virulence
  if (organism.virulenceFactors?.length) {
    addSection("Virulence Factors");
    organism.virulenceFactors.forEach((v) => addLine(`• ${v}`));
  }

  // Resistance
  addSection("Antimicrobial Resistance");
  if (organism.resistance.intrinsic.length) addLine(`Intrinsic: ${organism.resistance.intrinsic.join(", ")}`);
  if (organism.resistance.acquired.length) addLine(`Acquired: ${organism.resistance.acquired.join(", ")}`);
  addLine(`Mechanism: ${organism.resistance.mechanism}`);

  // Treatment
  addSection("Treatment");
  organism.treatment.forEach((t) => addLine(`• ${t}`));

  // Molecular
  addSection("Molecular Data");
  addLine(`Genome: ${organism.molecular.genome} | GC Content: ${organism.molecular.gcContent}`);
  addLine(`Genes: ${organism.molecular.genes}`);
  if (organism.molecular.plasmids) addLine(`Plasmids: ${organism.molecular.plasmids}`);

  // Lab
  addSection("Lab Identification");
  organism.labIdentification.forEach((l) => addLine(`• ${l}`));

  // Footer
  y += 6;
  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.text(`Generated by MicroID • ${new Date().toLocaleDateString()}`, margin, 288);

  doc.save(`${organism.name.replace(/\s+/g, "_")}_profile.pdf`);
}
