// Extended organism data - merged with base data at runtime
export interface ExtendedOrganismData {
  virulenceFactors?: string[];
  transmission?: string;
  epidemiology?: string;
  prevention?: string[];
  incubationPeriod?: string;
  complications?: string[];
  cultureConditions?: string;
  taxonomy?: {
    domain: string;
    phylum: string;
    class: string;
    order: string;
    family: string;
  };
}

export const extendedData: Record<string, ExtendedOrganismData> = {
  // ==================== GRAM POSITIVE COCCI ====================
  // S. aureus, S. epidermidis, S. saprophyticus, S. pyogenes, S. pneumoniae,
  // S. agalactiae, Viridans, E. faecalis, E. faecium already have inline data

  // ==================== GRAM POSITIVE BACILLI ====================
  // B. anthracis and B. cereus already have inline data

  "listeria-monocytogenes": {
    virulenceFactors: ["Listeriolysin O (LLO – phagosome escape)", "ActA (actin-based motility, cell-to-cell spread)", "Internalin A (InlA – epithelial invasion)", "Internalin B (InlB – hepatocyte invasion)", "Phospholipase C (PlcA, PlcB)", "Metalloprotease (Mpl)"],
    transmission: "Foodborne (contaminated dairy, deli meats, soft cheeses, cantaloupe). Vertical transmission to fetus. Can grow at 4°C (cold enrichment)",
    epidemiology: "Worldwide. ~1,600 cases/year in US. High case-fatality rate (20-30%). Neonates, elderly, pregnant women, immunocompromised at highest risk.",
    prevention: ["Avoid unpasteurized dairy in pregnancy", "Proper food handling and refrigeration", "Recall surveillance for contaminated products", "Cook deli meats to steaming before consumption during pregnancy"],
    incubationPeriod: "Gastroenteritis: 24 hours. Invasive disease: 1-4 weeks (can be up to 70 days)",
    complications: ["Meningitis", "Brain abscess (rhombencephalitis)", "Spontaneous abortion", "Stillbirth", "Granulomatosis infantiseptica (neonatal)", "Septic shock"],
    cultureConditions: "Blood agar 37°C, 24-48h. Small beta-hemolytic colonies. Cold enrichment at 4°C (selective). Grows in 10% NaCl.",
    taxonomy: { domain: "Bacteria", phylum: "Bacillota", class: "Bacilli", order: "Bacillales", family: "Listeriaceae" },
  },
  "corynebacterium-diphtheriae": {
    virulenceFactors: ["Diphtheria toxin (AB toxin – inhibits EF-2, stops protein synthesis)", "Cord factor", "DtxR (iron-dependent regulation of toxin)", "Pili (adhesion)"],
    transmission: "Respiratory droplets, contact with skin lesions. Humans are only reservoir",
    epidemiology: "Near-elimination in developed countries due to vaccination. Still endemic in parts of Africa, Southeast Asia. Outbreaks in former Soviet states in 1990s.",
    prevention: ["DTaP vaccine (children)", "Tdap booster (adults)", "Td booster every 10 years", "Post-exposure prophylaxis (erythromycin + booster)"],
    incubationPeriod: "2-5 days (range 1-10 days)",
    complications: ["Myocarditis (leading cause of death)", "Peripheral neuritis (cranial nerve palsies)", "Airway obstruction (pseudomembrane)", "Renal failure"],
    cultureConditions: "Loeffler serum medium (enhances metachromatic granules), tellurite agar (selective, gray-black colonies), blood agar. 37°C, 24-48h.",
    taxonomy: { domain: "Bacteria", phylum: "Actinomycetota", class: "Actinomycetes", order: "Mycobacteriales", family: "Corynebacteriaceae" },
  },
  "clostridium-difficile": {
    virulenceFactors: ["Toxin A (TcdA – enterotoxin, causes fluid secretion and inflammation)", "Toxin B (TcdB – cytotoxin, 1000x more potent than TcdA)", "Binary toxin CDT (some strains, increases adherence)", "Spore formation (environmental persistence)", "Flagella (adhesion)"],
    transmission: "Fecal-oral via spores. Healthcare-associated (contaminated surfaces, hands). Community-associated increasing",
    epidemiology: "~500,000 infections/year in US, ~29,000 deaths. NAP1/BI/027 hypervirulent strain. Risk factors: antibiotics (fluoroquinolones, clindamycin, cephalosporins), age >65, hospitalization, PPI use.",
    prevention: ["Antimicrobial stewardship", "Contact precautions", "Hand washing with soap and water (spores resist alcohol)", "Environmental cleaning with bleach", "Bezlotoxumab (recurrent CDI prophylaxis)"],
    incubationPeriod: "Colonization to disease: usually during or within 4 weeks of antibiotic use",
    complications: ["Toxic megacolon", "Bowel perforation", "Sepsis", "Death (especially NAP1/027)", "Recurrence (20-30% after first episode)"],
    cultureConditions: "Anaerobic culture on CCFA (cycloserine-cefoxitin-fructose agar). 37°C, 48h. Horse stable odor. Fluoresces chartreuse under UV.",
    taxonomy: { domain: "Bacteria", phylum: "Bacillota", class: "Clostridia", order: "Eubacteriales", family: "Peptostreptococcaceae" },
  },
  "clostridium-perfringens": {
    virulenceFactors: ["Alpha toxin (phospholipase C/lecithinase – causes hemolysis, tissue necrosis)", "Theta toxin (perfringolysin O – pore-forming)", "Beta toxin (necrotizing)", "Enterotoxin (CPE – food poisoning)", "Epsilon toxin (necrotizing)", "Iota toxin (ADP-ribosyltransferase)"],
    transmission: "Endogenous (GI flora), wound contamination with soil. Foodborne (inadequately cooked meats, poultry)",
    epidemiology: "Ubiquitous in soil and GI tract. Type A: most common in human disease. ~1 million cases of foodborne illness/year in US.",
    prevention: ["Proper wound debridement", "Adequate food cooking and storage", "Rapid cooling of cooked food", "High-pressure oxygenation for gas gangrene"],
    incubationPeriod: "Gas gangrene: 6 hours to 3 days. Food poisoning: 6-24 hours",
    complications: ["Rapid death from gas gangrene", "Limb amputation", "DIC", "Septic shock", "Necrotizing enteritis (pigbel)"],
    cultureConditions: "Anaerobic culture, blood agar, 37°C, 18-24h. Double zone hemolysis. Stormy fermentation in litmus milk. Non-motile (unusual for Clostridium).",
    taxonomy: { domain: "Bacteria", phylum: "Bacillota", class: "Clostridia", order: "Eubacteriales", family: "Clostridiaceae" },
  },
  "clostridium-tetani": {
    virulenceFactors: ["Tetanospasmin (tetanus toxin – blocks GABA/glycine release from Renshaw cells, causing spastic paralysis)", "Tetanolysin (hemolysin, minor role)"],
    transmission: "Wound contamination with spores from soil, animal feces. Neonatal tetanus from contaminated umbilical stump",
    epidemiology: "Rare in developed countries (vaccination). ~34,000 deaths/year worldwide, mostly neonatal tetanus in developing countries.",
    prevention: ["DTaP vaccine (children)", "Td/Tdap boosters", "Wound management with TIG if inadequate vaccination", "Clean delivery practices (neonatal)"],
    incubationPeriod: "3-21 days (average 8 days). Shorter incubation = worse prognosis",
    complications: ["Respiratory failure (spasm of respiratory muscles)", "Autonomic instability", "Fractures from severe spasms", "Aspiration pneumonia", "Death (10-70% depending on form)"],
    cultureConditions: "Strict anaerobic culture on blood agar. 37°C, 48h+. Swarming growth. Terminal spore gives 'drumstick' appearance.",
    taxonomy: { domain: "Bacteria", phylum: "Bacillota", class: "Clostridia", order: "Eubacteriales", family: "Clostridiaceae" },
  },
  "clostridium-botulinum": {
    virulenceFactors: ["Botulinum toxin (most potent biological toxin known – blocks acetylcholine release at NMJ, causing flaccid paralysis)", "7 toxin types (A-G), types A, B, E most common in humans"],
    transmission: "Foodborne (improperly canned/preserved foods). Wound (injection drug use). Infant (honey, soil). Inhalation (bioterrorism)",
    epidemiology: "~150 cases/year in US (mostly infant botulism). Foodborne outbreaks from home canning. Type A: west of Mississippi. Type B: east.",
    prevention: ["Proper canning techniques (>121°C)", "No honey for infants <1 year", "Refrigeration of leftovers", "Wound care"],
    incubationPeriod: "Foodborne: 12-36 hours (range 6 hours to 10 days). Wound: 4-14 days. Infant: variable",
    complications: ["Respiratory failure (leading cause of death)", "Prolonged paralysis (weeks to months)", "Nosocomial infections during recovery"],
    cultureConditions: "Strict anaerobic culture on blood agar/egg yolk agar. 37°C (or 30°C for some types), 48h+. Subterminal spore (tennis racket).",
    taxonomy: { domain: "Bacteria", phylum: "Bacillota", class: "Clostridia", order: "Eubacteriales", family: "Clostridiaceae" },
  },

  // ==================== GRAM NEGATIVE BACILLI - ENTEROBACTERIACEAE ====================
  "e-coli": {
    virulenceFactors: ["Type 1 fimbriae (mannose-sensitive, UTI adhesion)", "P fimbriae (pyelonephritis)", "Shiga toxin (STEC/EHEC – Stx1, Stx2)", "Heat-labile toxin (LT, ETEC)", "Heat-stable toxin (ST, ETEC)", "Intimin (eae, EHEC/EPEC adhesion)", "Hemolysin (HlyA)", "K1 capsule (neonatal meningitis)", "Siderophores (iron acquisition)", "Type III secretion system"],
    transmission: "Varies by pathotype: fecal-oral (contaminated food/water), person-to-person, endogenous (UTI from GI flora)",
    epidemiology: "Most common cause of UTI worldwide. STEC O157:H7 causes ~63,000 illnesses/year in US. ESBL-producing E. coli increasing globally. Neonatal meningitis (K1 strains).",
    prevention: ["Proper food handling and cooking", "Hand hygiene", "Safe water supply", "Antimicrobial stewardship (ESBL prevention)"],
    incubationPeriod: "UTI: endogenous. ETEC: 1-3 days. EHEC: 1-8 days. EPEC: 1-3 days",
    complications: ["Hemolytic uremic syndrome (STEC – triad: hemolytic anemia, thrombocytopenia, renal failure)", "Urosepsis", "Neonatal meningitis (K1)", "Bacteremia", "Traveler's diarrhea (ETEC)"],
    cultureConditions: "MacConkey agar: pink lactose-fermenting colonies. EMB agar: metallic green sheen. 37°C, 18-24h. Sorbitol-MacConkey (SMAC) for O157:H7.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Enterobacterales", family: "Enterobacteriaceae" },
  },
  "klebsiella-pneumoniae": {
    virulenceFactors: ["Thick polysaccharide capsule (77 K-antigens, antiphagocytic)", "Lipopolysaccharide (LPS/endotoxin)", "Siderophores (enterobactin, aerobactin)", "Type 1 and type 3 fimbriae", "Hypermucoviscosity (rmpA, magA – hypervirulent strains)", "Biofilm formation"],
    transmission: "Healthcare-associated (ventilators, catheters, hands). Community-acquired (hypervirulent strains, especially in Asia)",
    epidemiology: "Third most common cause of nosocomial infections. CRKP is CDC urgent threat. Hypervirulent strains (hvKP) cause community-acquired liver abscess (endemic in East Asia).",
    prevention: ["Infection control practices", "Antimicrobial stewardship", "Active surveillance for CRE", "Contact precautions for resistant strains"],
    incubationPeriod: "Variable; hospital-acquired infections often after prolonged hospitalization",
    complications: ["Lung abscess", "Empyema", "Bacteremia", "Endophthalmitis (hypervirulent)", "Metastatic infections", "Treatment failure with resistant strains"],
    cultureConditions: "MacConkey agar: mucoid pink lactose-fermenting colonies. 37°C, 18-24h. String test positive for hypervirulent strains (>5mm string).",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Enterobacterales", family: "Enterobacteriaceae" },
  },
  "klebsiella-oxytoca": {
    virulenceFactors: ["Capsule", "OXY beta-lactamase (chromosomal)", "Tilivalline (cytotoxin causing hemorrhagic colitis)", "LPS", "Fimbriae"],
    transmission: "Healthcare-associated, endogenous GI flora",
    epidemiology: "Less common than K. pneumoniae. Can cause antibiotic-associated hemorrhagic colitis. Distinguished by indole positivity.",
    prevention: ["Antimicrobial stewardship", "Infection control practices"],
    incubationPeriod: "Variable",
    complications: ["Hemorrhagic colitis", "Bacteremia", "Sepsis"],
    cultureConditions: "MacConkey agar: mucoid pink lactose-fermenting colonies. 37°C, 18-24h.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Enterobacterales", family: "Enterobacteriaceae" },
  },
  "salmonella-enterica": {
    virulenceFactors: ["Type III secretion system (SPI-1: invasion, SPI-2: intracellular survival)", "Vi capsule (S. Typhi – antiphagocytic)", "Flagella (motility, invasion)", "LPS/endotoxin", "Enterotoxin", "Spv virulence plasmid"],
    transmission: "Fecal-oral: contaminated food (poultry, eggs, produce), water, animal contact (reptiles, amphibians). Person-to-person (typhoid)",
    epidemiology: "~1.35 million infections/year in US (non-typhoidal). 11-20 million typhoid cases/year globally. Eggs and poultry are leading vehicles.",
    prevention: ["Proper cooking of poultry/eggs", "Hand washing after animal contact", "Typhoid vaccines (Vi polysaccharide, Ty21a live oral)", "Safe water supply"],
    incubationPeriod: "Gastroenteritis: 6-72 hours (usually 12-36h). Typhoid: 5-21 days",
    complications: ["Bacteremia (5-10% of NTS)", "Osteomyelitis (especially sickle cell disease)", "Reactive arthritis", "Typhoid: intestinal perforation, hemorrhage", "Chronic carriage (gallbladder)"],
    cultureConditions: "MacConkey: colorless (non-lactose fermenter). XLD/Hektoen: H₂S producing colonies. 37°C, 18-24h. Blood culture for typhoid.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Enterobacterales", family: "Enterobacteriaceae" },
  },
  "salmonella-typhi": {
    virulenceFactors: ["Vi capsule (immune evasion, blocks complement)", "Type III secretion systems (SPI-1, SPI-2)", "Typhoid toxin (CdtB-PltA-PltB)", "Endotoxin (LPS)", "Biofilm formation in gallbladder"],
    transmission: "Fecal-oral, exclusively human-to-human. Contaminated water/food. Chronic carriers (1-4% become lifelong carriers)",
    epidemiology: "11-21 million cases/year, ~128,000-161,000 deaths globally. Endemic in South/Southeast Asia, Africa. XDR strains (H58 lineage) spreading from Pakistan.",
    prevention: ["Typhoid conjugate vaccine (TCV, WHO recommended)", "Vi polysaccharide vaccine", "Ty21a live oral vaccine", "Safe water/sanitation", "Chronic carrier treatment"],
    incubationPeriod: "5-21 days (usually 7-14 days)",
    complications: ["Intestinal perforation (2-3%)", "GI hemorrhage", "Hepatosplenomegaly", "Chronic gallbladder carriage", "Relapse (5-10%)", "Myocarditis"],
    cultureConditions: "MacConkey: colorless. SS agar/Hektoen: H₂S colonies. Blood culture positive first week, stool culture later. 37°C, 18-24h.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Enterobacterales", family: "Enterobacteriaceae" },
  },
  "shigella-species": {
    virulenceFactors: ["Type III secretion system (invasion of colonic epithelium)", "Shiga toxin (S. dysenteriae 1 – protein synthesis inhibition)", "IcsA/VirG (actin-based motility, cell-to-cell spread)", "Ipa proteins (invasion plasmid antigens)", "LPS/endotoxin"],
    transmission: "Fecal-oral, person-to-person (extremely low infectious dose: 10-100 organisms). Contaminated food/water",
    epidemiology: "~450,000 cases/year in US. Most common in children 1-4 years. S. sonnei most common in developed countries; S. flexneri in developing countries. Daycare outbreaks.",
    prevention: ["Hand hygiene", "Safe water/sanitation", "Food safety", "No vaccine (candidates in development)"],
    incubationPeriod: "1-3 days (range 12 hours to 7 days)",
    complications: ["HUS (S. dysenteriae 1)", "Bacteremia (rare)", "Seizures (children)", "Reactive arthritis (HLA-B27)", "Rectal prolapse"],
    cultureConditions: "MacConkey: colorless (NLF). XLD/Hektoen: non-H₂S producing colonies. 37°C, 18-24h. Non-motile (distinguishes from Salmonella).",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Enterobacterales", family: "Enterobacteriaceae" },
  },
  "proteus-mirabilis": {
    virulenceFactors: ["Urease (alkalinizes urine, struvite stone formation)", "Swarming motility (raft formation, catheter ascension)", "IgA protease", "Hemolysin (HpmA)", "Flagella", "Fimbriae (MR/P, PMF, UCA)"],
    transmission: "Endogenous (GI colonization), catheter-associated. Community-acquired UTI",
    epidemiology: "Third most common cause of UTI. Most common cause of catheter-associated UTI forming struvite stones. More common in elderly and catheterized patients.",
    prevention: ["Minimize catheter use", "Proper catheter care", "Acidification of urine (controversial)"],
    incubationPeriod: "UTI: 1-3 days after catheterization or ascending infection",
    complications: ["Struvite (staghorn) kidney stones", "Pyelonephritis", "Bacteremia", "Catheter encrustation and blockage"],
    cultureConditions: "Blood agar: characteristic swarming motility (concentric rings). MacConkey: NLF. 37°C, 18-24h. Fishy odor.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Enterobacterales", family: "Morganellaceae" },
  },
  "proteus-vulgaris": {
    virulenceFactors: ["Urease", "Fimbriae", "Hemolysin", "Flagella (swarming)"],
    transmission: "Endogenous, healthcare-associated",
    epidemiology: "Less common than P. mirabilis. More antibiotic resistant. Similar clinical presentations.",
    prevention: ["Catheter care", "Infection control"],
    incubationPeriod: "Variable",
    complications: ["Struvite stones", "Bacteremia", "Wound infection complications"],
    cultureConditions: "Blood agar: swarming. MacConkey: NLF. 37°C, 18-24h.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Enterobacterales", family: "Morganellaceae" },
  },
  "serratia-marcescens": {
    virulenceFactors: ["Prodigiosin (red pigment, cytotoxic)", "Lipase", "Gelatinase", "DNase", "Chitinase", "Metalloprotease", "Biofilm formation"],
    transmission: "Healthcare-associated. Contaminated IV solutions, respiratory equipment, hand lotion, soap. Endogenous from GI tract",
    epidemiology: "Important nosocomial pathogen. Outbreaks from contaminated solutions. Associated with IV drug use endocarditis.",
    prevention: ["Proper disinfection of solutions and equipment", "Infection control", "Antimicrobial stewardship"],
    incubationPeriod: "Variable; depends on source of infection",
    complications: ["Endocarditis (IVDU – tricuspid valve)", "Respiratory failure", "Bacteremia", "Osteomyelitis"],
    cultureConditions: "MacConkey: NLF or late LF. Blood agar: red pigment at 25°C (not at 37°C). 37°C, 18-24h.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Enterobacterales", family: "Yersiniaceae" },
  },
  "enterobacter-cloacae": {
    virulenceFactors: ["LPS/endotoxin", "Capsule", "Inducible AmpC beta-lactamase", "Biofilm formation", "Outer membrane proteins"],
    transmission: "Healthcare-associated, endogenous GI flora, contaminated IV fluids",
    epidemiology: "Important nosocomial pathogen. ESKAPE group. Derepressed AmpC mutants emerge during third-gen cephalosporin therapy (clinical failure in 20-30%).",
    prevention: ["Avoid third-gen cephalosporin monotherapy", "Infection control", "Antimicrobial stewardship"],
    incubationPeriod: "Variable",
    complications: ["Treatment failure from AmpC derepression", "Bacteremia", "Multi-organ infection"],
    cultureConditions: "MacConkey: mucoid pink LF colonies. 37°C, 18-24h.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Enterobacterales", family: "Enterobacteriaceae" },
  },
  "citrobacter-freundii": {
    virulenceFactors: ["LPS/endotoxin", "Inducible AmpC beta-lactamase", "Capsule", "Fimbriae"],
    transmission: "Healthcare-associated, endogenous GI flora",
    epidemiology: "Opportunistic nosocomial pathogen. Similar AmpC resistance pattern to Enterobacter.",
    prevention: ["Infection control", "Antimicrobial stewardship"],
    incubationPeriod: "Variable",
    complications: ["Neonatal meningitis", "Bacteremia", "Brain abscess"],
    cultureConditions: "MacConkey: NLF or late LF. H₂S positive on TSI. 37°C, 18-24h.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Enterobacterales", family: "Enterobacteriaceae" },
  },
  "morganella-morganii": {
    virulenceFactors: ["Urease", "Hemolysin", "Inducible AmpC beta-lactamase", "LPS"],
    transmission: "Healthcare-associated, endogenous GI flora",
    epidemiology: "Opportunistic pathogen in hospitalized patients. Intrinsically resistant to many antibiotics.",
    prevention: ["Infection control", "Appropriate antibiotic selection"],
    incubationPeriod: "Variable",
    complications: ["Bacteremia", "Wound complications", "Histamine production (scombroid-like fish poisoning)"],
    cultureConditions: "MacConkey: NLF. 37°C, 18-24h. Urease positive, indole positive.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Enterobacterales", family: "Morganellaceae" },
  },
  "yersinia-pestis": {
    virulenceFactors: ["F1 capsule antigen (antiphagocytic)", "Type III secretion system (Yops – block phagocytosis)", "Plasminogen activator (Pla – promotes dissemination)", "LPS", "Yersiniabactin siderophore", "Murine toxin"],
    transmission: "Flea bite (bubonic), respiratory droplets (pneumonic), direct contact with infected animals",
    epidemiology: "~1,000-2,000 cases/year globally. Endemic in Africa, Central Asia, Americas. US: Southwest states. Pneumonic plague is person-to-person transmissible.",
    prevention: ["Flea control", "Avoid contact with rodents", "Post-exposure prophylaxis (doxycycline or ciprofloxacin)", "No widely available vaccine"],
    incubationPeriod: "Bubonic: 2-8 days. Pneumonic: 1-3 days. Septicemic: 1-7 days",
    complications: ["DIC", "ARDS", "Gangrene ('Black Death')", "Death (pneumonic nearly 100% fatal untreated)", "Meningitis"],
    cultureConditions: "MacConkey/blood agar 37°C, 24-48h. Bipolar ('safety pin') staining. BSL-3 required. Slow growth.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Enterobacterales", family: "Yersiniaceae" },
  },
  "yersinia-enterocolitica": {
    virulenceFactors: ["Ail (attachment invasion locus)", "Inv (invasin)", "Yst (heat-stable enterotoxin)", "Type III secretion system (Yops)", "Yersiniabactin"],
    transmission: "Foodborne (undercooked pork, contaminated milk), contaminated water, contaminated blood transfusions",
    epidemiology: "Most common in Northern Europe and Canada. Children <5 most affected. Can mimic appendicitis. Cold enrichment enables detection.",
    prevention: ["Proper cooking of pork", "Pasteurization of milk", "Blood product screening"],
    incubationPeriod: "4-7 days (range 1-14 days)",
    complications: ["Mesenteric adenitis (pseudo-appendicitis)", "Reactive arthritis (HLA-B27)", "Erythema nodosum", "Septicemia (iron overload patients)", "Transfusion-related sepsis"],
    cultureConditions: "CIN agar: 'bull's eye' colonies. 37°C or cold enrichment at 4°C. 24-48h.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Enterobacterales", family: "Yersiniaceae" },
  },

  // ==================== GRAM NEGATIVE BACILLI - NON-FERMENTERS ====================
  "pseudomonas-aeruginosa": {
    virulenceFactors: ["Pyocyanin (blue-green pigment, generates reactive oxygen species)", "Pyoverdine (fluorescent siderophore)", "Exotoxin A (inhibits EF-2, like diphtheria toxin)", "Elastase (LasB)", "Phospholipase C", "Alginate (mucoid biofilm in CF lungs)", "Type III secretion system (ExoU, ExoS, ExoT, ExoY)", "Rhamnolipid", "Quorum sensing (Las/Rhl systems)"],
    transmission: "Environmental (water, soil, hospital surfaces). Not usually person-to-person except in CF patients. Contaminated equipment (ventilators, bronchoscopes)",
    epidemiology: "Third most common cause of nosocomial infections. Leading cause of ventilator-associated pneumonia. Chronic colonizer in cystic fibrosis. ESKAPE pathogen.",
    prevention: ["Infection control and environmental cleaning", "Minimize ventilator days", "Proper water system maintenance", "Antimicrobial stewardship", "Segregation of CF patients"],
    incubationPeriod: "Variable; often colonization precedes infection. Acute infections within days of exposure",
    complications: ["Chronic lung infection in CF", "Bacteremia (ecthyma gangrenosum)", "Malignant otitis externa", "Corneal ulceration (contact lens)", "Septic shock (high mortality 20-50%)"],
    cultureConditions: "Blood agar/MacConkey: NLF. Blue-green (pyocyanin) pigment. Grape-like/tortilla odor. Grows at 42°C. 37°C, 18-24h.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Pseudomonadales", family: "Pseudomonadaceae" },
  },
  "acinetobacter-baumannii": {
    virulenceFactors: ["OmpA (outer membrane protein – adhesion, apoptosis)", "Phospholipase D", "Capsular polysaccharide", "Biofilm formation", "LPS (lipooligosaccharide)", "Iron acquisition systems", "Type VI secretion system"],
    transmission: "Healthcare-associated. Survives on dry surfaces for weeks. Contaminated hands, equipment. Wound infections in military/disaster settings",
    epidemiology: "CDC urgent threat. CRAB (carbapenem-resistant A. baumannii) has limited treatment options. Increasing in ICUs worldwide. Associated with natural disasters and military wounds.",
    prevention: ["Contact precautions", "Environmental decontamination", "Antimicrobial stewardship", "Active surveillance cultures"],
    incubationPeriod: "Variable; colonization may precede infection",
    complications: ["Pan-drug resistance", "Ventilator-associated pneumonia with high mortality", "Bacteremia (30-75% mortality for CRAB)"],
    cultureConditions: "Blood agar/MacConkey: smooth, sometimes mucoid colonies. NLF on MacConkey. 37°C, 18-24h. Oxidase negative (distinguishes from Pseudomonas).",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Moraxellales", family: "Moraxellaceae" },
  },
  "stenotrophomonas-maltophilia": {
    virulenceFactors: ["L1 metallo-beta-lactamase (hydrolyzes carbapenems)", "L2 serine beta-lactamase", "SmeDEF efflux pump", "Biofilm formation", "LPS", "Extracellular enzymes"],
    transmission: "Healthcare-associated. Environmental (water, soil). Contaminated respiratory equipment. Not usually person-to-person",
    epidemiology: "Emerging nosocomial pathogen. Especially in ICU patients with malignancy, immunosuppression, or prolonged antibiotics. Intrinsically resistant to carbapenems.",
    prevention: ["Antimicrobial stewardship (avoid unnecessary carbapenems)", "Infection control", "Proper equipment sterilization"],
    incubationPeriod: "Variable",
    complications: ["Treatment-refractory bacteremia", "Pneumonia with high mortality in immunocompromised"],
    cultureConditions: "Blood agar/MacConkey, 37°C, 24-48h. Ammonia or lavender odor. Lavender-green colonies.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Xanthomonadales", family: "Xanthomonadaceae" },
  },
  "burkholderia-cepacia": {
    virulenceFactors: ["Cable pili (CblA – adhesion to CF epithelium)", "Exopolysaccharide (biofilm)", "Lipase", "Protease", "Siderophores", "Type III/VI secretion systems"],
    transmission: "Person-to-person (especially between CF patients). Environmental (contaminated solutions, soil). Nosocomial outbreaks",
    epidemiology: "Major pathogen in cystic fibrosis. 'Cepacia syndrome' = rapid decline with necrotizing pneumonia and sepsis. Strict segregation policies in CF clinics.",
    prevention: ["Strict segregation of colonized CF patients", "Environmental decontamination", "Infection control in CF clinics"],
    incubationPeriod: "Variable; colonization may be chronic or lead to acute syndrome",
    complications: ["Cepacia syndrome (rapid fatal decline)", "Chronic lung colonization", "Contraindication for lung transplantation at many centers"],
    cultureConditions: "BCSA selective agar, 37°C, 48-72h. Requires molecular methods for species identification within complex.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Betaproteobacteria", order: "Burkholderiales", family: "Burkholderiaceae" },
  },

  // ==================== GRAM NEGATIVE COCCI ====================
  "neisseria-meningitidis": {
    virulenceFactors: ["Polysaccharide capsule (13 serogroups, A/B/C/W/Y most common)", "Pili (adhesion, antigenic variation)", "PorA/PorB (outer membrane porins)", "Opa/Opc proteins (adhesion/invasion)", "IgA protease", "LOS (lipooligosaccharide – endotoxin)", "Factor H binding protein (immune evasion)"],
    transmission: "Respiratory droplets, close contact (household, dormitory, military). Nasopharyngeal carriage (5-10% healthy adults)",
    epidemiology: "Epidemic potential (especially serogroup A in 'meningitis belt' of sub-Saharan Africa). US: ~350 cases/year. Peaks in adolescents and college freshmen.",
    prevention: ["MenACWY conjugate vaccine (adolescents)", "MenB vaccine (college freshmen, outbreaks)", "Chemoprophylaxis for close contacts (rifampin, ciprofloxacin, or ceftriaxone)"],
    incubationPeriod: "2-10 days (usually 3-4 days)",
    complications: ["Waterhouse-Friderichsen syndrome (adrenal hemorrhage)", "DIC", "Purpura fulminans", "Deafness", "Neurological deficits", "Limb amputation", "Death (10-15% even with treatment)"],
    cultureConditions: "Chocolate agar, 37°C, 5-10% CO₂, 24-48h. Oxidase positive. Ferments glucose and maltose.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Betaproteobacteria", order: "Neisseriales", family: "Neisseriaceae" },
  },
  "neisseria-gonorrhoeae": {
    virulenceFactors: ["Pili (type IV, adhesion, antigenic/phase variation)", "Opa proteins (adhesion/invasion, antigenic variation)", "PorB (complement evasion, invasion)", "IgA protease", "LOS (lipooligosaccharide, molecular mimicry)", "Iron acquisition systems (transferrin-binding proteins)"],
    transmission: "Sexual contact (vaginal, anal, oral). Vertical (mother to neonate during birth – ophthalmia neonatorum)",
    epidemiology: "~87 million new cases/year globally. Second most common bacterial STI. CDC urgent threat due to rising antimicrobial resistance. Young adults (15-24) most affected.",
    prevention: ["Condom use", "Screening of high-risk populations", "Partner treatment", "Neonatal eye prophylaxis (erythromycin ointment)", "No vaccine available"],
    incubationPeriod: "2-5 days (range 1-14 days)",
    complications: ["PID (pelvic inflammatory disease)", "Ectopic pregnancy", "Infertility", "Disseminated gonococcal infection (dermatitis-arthritis syndrome)", "Fitz-Hugh-Curtis syndrome (perihepatitis)", "Ophthalmia neonatorum (can cause blindness)"],
    cultureConditions: "Chocolate agar or Thayer-Martin (selective), 37°C, 5-10% CO₂, 24-48h. Oxidase positive. Ferments glucose only.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Betaproteobacteria", order: "Neisseriales", family: "Neisseriaceae" },
  },
  "moraxella-catarrhalis": {
    virulenceFactors: ["BRO beta-lactamases (BRO-1, BRO-2)", "UspA1/UspA2 (adhesion, complement resistance)", "CopB (iron acquisition, complement resistance)", "LOS", "Biofilm formation"],
    transmission: "Respiratory droplets, endogenous colonization of upper respiratory tract",
    epidemiology: "Third most common cause of otitis media in children. Important cause of COPD exacerbations. >90% of strains produce beta-lactamase.",
    prevention: ["No vaccine available (candidates in development)", "Pneumococcal/influenza vaccines (reduce co-infections)"],
    incubationPeriod: "Variable; colonization often precedes infection",
    complications: ["Chronic otitis media", "COPD exacerbation", "Sinusitis complications (rare orbital/intracranial)"],
    cultureConditions: "Blood agar/chocolate agar, 37°C, 24-48h. Hockey puck colonies (slide across agar). Oxidase positive.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Moraxellales", family: "Moraxellaceae" },
  },

  // ==================== GRAM NEGATIVE CURVED/SPIRAL ====================
  "helicobacter-pylori": {
    virulenceFactors: ["CagA (oncoprotein injected via T4SS – cell signaling disruption)", "VacA (vacuolating cytotoxin – apoptosis, immune modulation)", "Urease (neutralizes stomach acid, creates alkaline microenvironment)", "BabA/SabA (adhesins)", "Flagella (motility in mucus)", "LPS (low immunogenicity)"],
    transmission: "Person-to-person (oral-oral, fecal-oral). Intrafamilial transmission common. Acquired in childhood",
    epidemiology: "Infects ~50% of world population. Prevalence >80% in developing countries. WHO Group 1 carcinogen. Decreasing in developed countries with improved sanitation.",
    prevention: ["Improved sanitation", "Treatment of infected individuals", "No vaccine available (candidates in development)"],
    incubationPeriod: "Weeks to months before symptoms; many remain asymptomatic lifelong",
    complications: ["Peptic ulcer disease (10-15% of infected)", "Gastric adenocarcinoma (1-3% of infected)", "MALT lymphoma", "Vitamin B12 deficiency", "Iron deficiency anemia"],
    cultureConditions: "Microaerophilic conditions (5% O₂, 10% CO₂), 37°C, 5-7 days. Columbia agar with blood. Very slow growth.",
    taxonomy: { domain: "Bacteria", phylum: "Campylobacterota", class: "Epsilonproteobacteria", order: "Campylobacterales", family: "Helicobacteraceae" },
  },
  "campylobacter-jejuni": {
    virulenceFactors: ["Cytolethal distending toxin (CDT – DNase activity)", "Flagella (motility, adhesion, invasion)", "CiaB (invasion-associated protein)", "LOS (lipooligosaccharide – molecular mimicry with gangliosides → Guillain-Barré)", "Capsule"],
    transmission: "Foodborne (undercooked poultry, unpasteurized milk), contaminated water, animal contact (puppies, kittens)",
    epidemiology: "Most common bacterial cause of diarrhea in developed countries. 1.5 million infections/year in US. Poultry is leading vehicle. More common in summer.",
    prevention: ["Proper cooking of poultry", "Avoid cross-contamination", "Pasteurization of milk", "Hand hygiene after animal contact"],
    incubationPeriod: "2-5 days (range 1-10 days)",
    complications: ["Guillain-Barré syndrome (1 in 1,000 – most common identified trigger)", "Reactive arthritis", "Bacteremia (immunocompromised)", "Miller-Fisher syndrome"],
    cultureConditions: "Microaerophilic (5% O₂, 10% CO₂), 42°C (thermophilic), Campy-BAP or Skirrow media, 48-72h. Darting/corkscrew motility.",
    taxonomy: { domain: "Bacteria", phylum: "Campylobacterota", class: "Epsilonproteobacteria", order: "Campylobacterales", family: "Campylobacteraceae" },
  },
  "vibrio-cholerae": {
    virulenceFactors: ["Cholera toxin (CT – AB₅ toxin, activates adenylate cyclase, massive cAMP → watery diarrhea)", "Toxin-coregulated pilus (TCP – colonization factor)", "ToxR/ToxT (regulatory cascade)", "Neuraminidase", "Mucinase", "RTX toxin"],
    transmission: "Fecal-oral via contaminated water (sewage). Contaminated seafood. Person-to-person rare but possible",
    epidemiology: "7th pandemic (O1 El Tor biotype) ongoing since 1961. Major outbreaks in Haiti (2010), Yemen (2016-present). O1 and O139 serogroups cause epidemics.",
    prevention: ["Safe water supply and sanitation", "Oral cholera vaccines (Shanchol, Euvichol)", "Proper sewage treatment", "Hand hygiene"],
    incubationPeriod: "12 hours to 5 days (usually 2-3 days)",
    complications: ["Severe dehydration and hypovolemic shock (can lose 1L/hour)", "Metabolic acidosis", "Hypokalemia", "Renal failure", "Death within hours if untreated"],
    cultureConditions: "TCBS agar: flat yellow colonies. Alkaline peptone water enrichment (pH 8.6). 37°C, 18-24h. Oxidase positive.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Vibrionales", family: "Vibrionaceae" },
  },
  "vibrio-vulnificus": {
    virulenceFactors: ["RtxA1 (cytotoxin)", "VvhA (hemolysin/cytolysin)", "Capsular polysaccharide", "Metalloprotease (VvpE)", "Phospholipase", "Siderophores (vulnibactin)"],
    transmission: "Wound exposure to warm seawater. Consumption of raw/undercooked shellfish (especially oysters)",
    epidemiology: "~100 cases/year in US. >50% mortality in septicemia. Major risk factors: liver disease, hemochromatosis, immunosuppression.",
    prevention: ["Avoid raw shellfish with liver disease", "Wound protection in seawater", "Rapid medical attention for wound infections"],
    incubationPeriod: "Wound: 12 hours to days. Primary septicemia: 1-3 days",
    complications: ["Necrotizing fasciitis", "Septic shock", "Death (50% in septicemia)", "Limb amputation"],
    cultureConditions: "TCBS agar: green colonies (non-sucrose fermenting). Blood agar. 37°C, 18-24h. Halophilic.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Vibrionales", family: "Vibrionaceae" },
  },
  "vibrio-parahaemolyticus": {
    virulenceFactors: ["Thermostable direct hemolysin (TDH – Kanagawa positive)", "TDH-related hemolysin (TRH)", "Type III secretion systems (T3SS1, T3SS2)", "Lateral flagella (swarming)"],
    transmission: "Consumption of raw/undercooked seafood (especially shellfish). Wound exposure to seawater",
    epidemiology: "Leading cause of seafood-associated gastroenteritis worldwide. Most common in Japan (sashimi). US: Gulf Coast states.",
    prevention: ["Proper cooking of seafood", "Avoid raw shellfish", "Refrigeration of seafood"],
    incubationPeriod: "4-96 hours (usually 12-24 hours)",
    complications: ["Wound infections", "Septicemia (rare, immunocompromised)"],
    cultureConditions: "TCBS agar: blue-green colonies (non-sucrose fermenting). Halophilic. 37°C, 18-24h.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Vibrionales", family: "Vibrionaceae" },
  },

  // ==================== SPIROCHETES ====================
  "treponema-pallidum": {
    virulenceFactors: ["Outer membrane proteins (TprK – antigenic variation)", "Tp0751 (adhesin, host cell attachment)", "Hyaluronidase (tissue penetration)", "Rare outer membrane proteins (immune evasion)", "Ability to cross blood-brain and placental barriers"],
    transmission: "Sexual contact (vaginal, anal, oral). Vertical (transplacental – congenital syphilis). Blood transfusion (rare). Direct contact with chancre",
    epidemiology: "Rising globally. ~130,000 cases/year in US (2022). MSM disproportionately affected. Congenital syphilis rising alarmingly. Co-infection with HIV common.",
    prevention: ["Condom use", "Partner notification and treatment", "Prenatal screening", "PrEP does not prevent syphilis"],
    incubationPeriod: "Primary syphilis: 10-90 days (average 21 days). Secondary: 4-10 weeks after primary",
    complications: ["Tertiary syphilis (gummas, cardiovascular: aortitis)", "Neurosyphilis (tabes dorsalis, general paresis)", "Congenital syphilis (Hutchinson teeth, saddle nose, saber shins)", "Jarisch-Herxheimer reaction during treatment"],
    cultureConditions: "Cannot be cultured in vitro. Darkfield microscopy from chancre. Rabbit infectivity test (research only).",
    taxonomy: { domain: "Bacteria", phylum: "Spirochaetota", class: "Spirochaetia", order: "Spirochaetales", family: "Treponemataceae" },
  },
  "borrelia-burgdorferi": {
    virulenceFactors: ["OspA (tick midgut adhesion)", "OspC (early mammalian infection, complement evasion)", "VlsE (variable major protein-like sequence – antigenic variation)", "Decorin-binding proteins (DbpA/B – tissue attachment)", "BmpA (arthritis-associated)"],
    transmission: "Tick bite (Ixodes scapularis in eastern US, I. pacificus in western US). Requires tick attachment >36-48 hours. Deer and white-footed mice are reservoir hosts",
    epidemiology: "Most common vector-borne disease in US (~476,000 estimated cases/year). Northeast and upper Midwest endemic. Peak: May-September.",
    prevention: ["Tick avoidance (repellents, protective clothing)", "Tick checks within 24 hours", "Prophylactic doxycycline (single dose for ≥36h attached Ixodes tick)", "Landscaping modifications"],
    incubationPeriod: "Early localized (erythema migrans): 3-30 days. Early disseminated: weeks to months. Late: months to years",
    complications: ["Lyme arthritis (large joint, especially knee)", "Lyme carditis (AV block)", "Neuroborreliosis (Bell's palsy, meningitis)", "Post-treatment Lyme disease syndrome"],
    cultureConditions: "BSK (Barbour-Stoenner-Kelly) medium. Very slow growth (12-24h doubling). Not routine clinical testing.",
    taxonomy: { domain: "Bacteria", phylum: "Spirochaetota", class: "Spirochaetia", order: "Spirochaetales", family: "Borreliaceae" },
  },
  "leptospira-interrogans": {
    virulenceFactors: ["LipL32 (most abundant outer membrane protein)", "LigA/LigB (adhesins)", "Hemolysin (sphingomyelinase)", "Endotoxin-like activity of LPS", "Motility (periplasmic flagella – tissue penetration)"],
    transmission: "Contact with water/soil contaminated by urine of infected animals (rats, dogs, cattle). Through skin abrasions or mucous membranes. Occupational risk (farmers, sewage workers)",
    epidemiology: "Most widespread zoonosis globally. >1 million cases/year, ~60,000 deaths. Associated with flooding. Endemic in tropical regions.",
    prevention: ["Avoid contaminated water", "Protective clothing/footwear", "Doxycycline prophylaxis (high-risk exposure)", "Animal vaccination"],
    incubationPeriod: "2-30 days (usually 7-12 days)",
    complications: ["Weil's disease (icteric leptospirosis: jaundice, renal failure, hemorrhage – 10% mortality)", "Pulmonary hemorrhage", "Aseptic meningitis", "Uveitis"],
    cultureConditions: "EMJH (Ellinghausen-McCullough-Johnson-Harris) medium. 30°C, weeks to months. Very slow growth. Darkfield microscopy.",
    taxonomy: { domain: "Bacteria", phylum: "Spirochaetota", class: "Spirochaetia", order: "Leptospirales", family: "Leptospiraceae" },
  },

  // ==================== GRAM NEGATIVE BACILLI - OTHER ====================
  "haemophilus-influenzae": {
    virulenceFactors: ["Type b capsule (PRP – polyribosilribitol phosphate, antiphagocytic)", "IgA protease", "LOS (lipooligosaccharide)", "Pili (adhesion)", "Outer membrane proteins (P2, P5)", "Biofilm formation"],
    transmission: "Respiratory droplets. Nasopharyngeal colonization precedes invasive disease",
    epidemiology: "Hib vaccine reduced invasive disease by >99% in developed countries. Non-typeable H. influenzae (NTHi) now causes more mucosal disease. ~25% produce beta-lactamase.",
    prevention: ["Hib conjugate vaccine (routine childhood immunization)", "Rifampin prophylaxis for close contacts (invasive Hib, children <4)"],
    incubationPeriod: "Variable; usually 2-4 days for invasive disease",
    complications: ["Meningitis sequelae (hearing loss, neurological deficits)", "Epiglottitis (airway emergency)", "Subdural empyema", "Septic arthritis"],
    cultureConditions: "Chocolate agar (heated blood releases X and V factors), 37°C, 5-10% CO₂, 24-48h. Satellite phenomenon near S. aureus on blood agar.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Pasteurellales", family: "Pasteurellaceae" },
  },
  "haemophilus-ducreyi": {
    virulenceFactors: ["LspA1/LspA2 (immunoevasion – inhibit phagocytosis)", "DsrA (serum resistance)", "Hemolysin", "Fimbriae-like structures", "Outer membrane proteins"],
    transmission: "Sexual contact. Direct contact with genital ulcers. Enhances HIV transmission",
    epidemiology: "Endemic in Africa, Southeast Asia, Caribbean. Rare in US/Europe. Declining globally due to syndromic STI management.",
    prevention: ["Condom use", "STI screening and treatment", "Circumcision (reduces risk)"],
    incubationPeriod: "3-7 days (range 1-21 days)",
    complications: ["Inguinal lymphadenopathy (buboes, may rupture)", "Phimosis", "Urethral fistula", "Increased HIV acquisition"],
    cultureConditions: "Specialized media (Mueller-Hinton chocolate agar with IsoVitaleX and vancomycin). 33°C, 5% CO₂, 48-72h. Difficult to culture.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Pasteurellales", family: "Pasteurellaceae" },
  },
  "bordetella-pertussis": {
    virulenceFactors: ["Pertussis toxin (PT – ADP-ribosylates Gi protein, causes lymphocytosis)", "Filamentous hemagglutinin (FHA – adhesion)", "Pertactin (PRN – adhesion/invasion)", "Adenylate cyclase toxin (ACT – impairs immune cells)", "Tracheal cytotoxin (ciliated cell damage)", "Dermonecrotic toxin", "BvgAS two-component system (virulence regulation)"],
    transmission: "Respiratory droplets. Highly contagious (attack rate 80-90% in susceptible contacts). Humans are only host",
    epidemiology: "Resurgent despite vaccination. US: 10,000-50,000 cases/year. Infant deaths most common <3 months. Waning immunity from acellular vaccine (DTaP) is a factor.",
    prevention: ["DTaP vaccine (children, 5 doses)", "Tdap booster (adolescents/adults)", "Tdap in pregnancy (third trimester, each pregnancy)", "Post-exposure prophylaxis (azithromycin)", "Cocooning strategy"],
    incubationPeriod: "7-10 days (range 5-21 days)",
    complications: ["Pneumonia (secondary bacterial)", "Seizures", "Encephalopathy", "Apnea (infants)", "Death (mostly infants <3 months)", "Rib fractures (severe coughing)"],
    cultureConditions: "Bordet-Gengou (potato blood glycerol agar) or Regan-Lowe (charcoal-blood agar). 37°C, 5-7 days. Mercury-drop colonies. Very fastidious.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Betaproteobacteria", order: "Burkholderiales", family: "Alcaligenaceae" },
  },
  "legionella-pneumophila": {
    virulenceFactors: ["Dot/Icm type IV secretion system (creates Legionella-containing vacuole in macrophages)", "Mip (macrophage infectivity potentiator)", "Flagella (motility)", "Iron acquisition (siderophores)", "Effector proteins (>300, hijack host cell processes)"],
    transmission: "Inhalation of contaminated water aerosols (cooling towers, showers, hot tubs, misters). NOT person-to-person",
    epidemiology: "~10,000 cases/year in US (likely underreported). Risk factors: age >50, smoking, immunosuppression, chronic lung disease. Outbreaks from contaminated building water systems.",
    prevention: ["Water system management (temperature >60°C or <20°C)", "Disinfection of cooling towers", "Regular water testing in healthcare facilities", "Legionella risk assessments"],
    incubationPeriod: "Legionnaires' disease: 2-10 days (usually 5-6 days). Pontiac fever: 24-48 hours",
    complications: ["Respiratory failure", "Renal failure", "Multi-organ failure", "Death (5-30%, higher in nosocomial)"],
    cultureConditions: "BCYE agar (buffered charcoal yeast extract with L-cysteine and iron). 37°C, 3-5 days. Requires L-cysteine for growth. Does NOT grow on standard media.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Legionellales", family: "Legionellaceae" },
  },
  "brucella-species": {
    virulenceFactors: ["LPS (non-classical, low endotoxic activity)", "VirB type IV secretion system", "BvrR/BvrS (two-component regulatory system)", "Cyclic β-1,2-glucan", "Superoxide dismutase (intracellular survival)"],
    transmission: "Unpasteurized dairy products, direct contact with infected animals (cattle, goats, pigs, dogs), inhalation (highly infectious aerosol)",
    epidemiology: "Worldwide, most common in Mediterranean, Middle East, Central Asia, Latin America. B. melitensis (goats) most virulent. Occupational risk: farmers, veterinarians, slaughterhouse workers.",
    prevention: ["Pasteurization of dairy", "Animal vaccination (S19, RB51)", "Protective equipment for animal workers", "No human vaccine approved in most countries"],
    incubationPeriod: "1-4 weeks (can be months)",
    complications: ["Chronic relapsing disease", "Spondylitis (vertebral osteomyelitis)", "Endocarditis (major cause of death)", "Neurobrucellosis", "Orchitis/epididymitis"],
    cultureConditions: "Blood culture: prolonged incubation (4+ weeks). Blood agar with 5-10% CO₂ (B. abortus). 37°C. BSL-3 required. Tiny, smooth, non-hemolytic colonies.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Alphaproteobacteria", order: "Hyphomicrobiales", family: "Brucellaceae" },
  },
  "francisella-tularensis": {
    virulenceFactors: ["Francisella pathogenicity island (FPI – Type VI-like secretion system)", "IglC (intracellular growth locus)", "Capsule", "LPS (atypical, low immunostimulatory)", "Acid phosphatase", "Iron acquisition systems"],
    transmission: "Tick bite, deer fly bite, contact with infected animals (rabbits), inhalation, contaminated water. Highly infectious (10-50 organisms)",
    epidemiology: "US: ~200 cases/year, mainly Arkansas, Missouri, Oklahoma. Category A bioterrorism agent. Type A (tularensis) more virulent than Type B (holarctica).",
    prevention: ["Tick/fly avoidance", "Gloves when handling animals", "No FDA-approved vaccine (live vaccine strain used for lab workers)", "Post-exposure doxycycline"],
    incubationPeriod: "3-5 days (range 1-14 days)",
    complications: ["Pneumonic tularemia (from inhalation or hematogenous spread)", "Meningitis", "Pericarditis", "Osteomyelitis", "Death (5-15% untreated ulceroglandular, 30-60% pneumonic)"],
    cultureConditions: "Requires cysteine-enriched media (chocolate agar, Thayer-Martin). 37°C, 48-72h. BSL-3 required. DO NOT attempt routine culture without BSL-3.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Thiotrichales", family: "Francisellaceae" },
  },
  "pasteurella-multocida": {
    virulenceFactors: ["Capsule (types A, B, D, E, F)", "LPS", "Neuraminidase", "Hyaluronidase", "Toxin A (P. multocida toxigenic strains)", "Adhesins (fimbriae)", "Iron acquisition systems"],
    transmission: "Animal bites (cats >70% wound infection rate, dogs 20-30%). Animal scratches. Respiratory infection from close animal contact",
    epidemiology: "Most common organism in cat/dog bite wounds. ~300,000 ER visits/year in US for animal bites. Cat bites are deeper (penetrating to bone/joint).",
    prevention: ["Wound cleaning after animal bites", "Prophylactic antibiotics for cat bites (especially hand/face)", "Tetanus prophylaxis", "Avoid provoking animals"],
    incubationPeriod: "Usually <24 hours for wound infections (notably rapid onset)",
    complications: ["Tenosynovitis", "Osteomyelitis (cat bites penetrate periosteum)", "Septic arthritis", "Bacteremia", "Meningitis (in immunocompromised or neonates)"],
    cultureConditions: "Blood agar: gray, smooth, non-hemolytic colonies. Does NOT grow on MacConkey. 37°C, 24h. Indole positive, oxidase positive.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Pasteurellales", family: "Pasteurellaceae" },
  },
  "bartonella-henselae": {
    virulenceFactors: ["BadA (Bartonella adhesin A – adhesion, angiogenesis)", "VirB/VirD4 type IV secretion system", "Bep effector proteins", "Deformin (stimulates endothelial proliferation)", "Trimeric autotransporter adhesins"],
    transmission: "Cat scratch or bite. Cat fleas (Ctenocephalides felis) vector between cats. Cats are reservoir (bacteremic for months). Fleas carry B. henselae",
    epidemiology: "Most common in children/young adults. ~22,000 cases/year in US. Higher in warm, humid climates (more fleas). Peak: fall/winter (kitten season).",
    prevention: ["Flea control for cats", "Avoid cat scratches/bites (especially kittens)", "Wound cleaning after cat contact", "Avoid contact with feral cats"],
    incubationPeriod: "Papule: 3-10 days. Lymphadenopathy: 1-3 weeks after inoculation",
    complications: ["Bacillary angiomatosis (HIV/AIDS – vascular proliferative lesions)", "Peliosis hepatis", "Endocarditis (culture-negative)", "Neuroretinitis", "Encephalopathy"],
    cultureConditions: "Blood/chocolate agar, 37°C, 5% CO₂, 2-6 weeks. Very slow growth. Lysis centrifugation of blood cultures. Often detected by PCR/serology instead.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Alphaproteobacteria", order: "Hyphomicrobiales", family: "Bartonellaceae" },
  },

  // ==================== ATYPICAL BACTERIA ====================
  "chlamydia-trachomatis": {
    virulenceFactors: ["Elementary body (EB – infectious, metabolically inactive)", "Reticulate body (RB – replicating, intracellular)", "Type III secretion system (TARP, Inc proteins)", "MOMP (major outer membrane protein)", "Trachoma (serovars A-C): chronic scarring", "LGV (serovars L1-L3): invasive"],
    transmission: "Sexual contact (serovars D-K), vertical during birth (conjunctivitis, pneumonia), eye-to-eye (trachoma, serovars A-C)",
    epidemiology: "Most common reportable bacterial STI in US (~1.8 million cases/year). Leading infectious cause of blindness globally (trachoma). Serovars D-K cause genital disease.",
    prevention: ["Condom use", "Annual screening for sexually active women <25", "Partner treatment", "SAFE strategy for trachoma (Surgery, Antibiotics, Facial cleanliness, Environmental improvement)"],
    incubationPeriod: "7-21 days for genital infection. LGV: 3-30 days",
    complications: ["PID", "Ectopic pregnancy", "Infertility (tubal factor)", "Reactive arthritis (Reiter's syndrome)", "Neonatal conjunctivitis (ophthalmia neonatorum)", "Neonatal pneumonia", "Blindness (trachoma – repeated infections)"],
    cultureConditions: "Obligate intracellular – requires cell culture (McCoy cells). NAAT (PCR) is standard diagnostic method. Cannot grow on routine media.",
    taxonomy: { domain: "Bacteria", phylum: "Chlamydiota", class: "Chlamydiia", order: "Chlamydiales", family: "Chlamydiaceae" },
  },
  "chlamydophila-pneumoniae": {
    virulenceFactors: ["Elementary body/reticulate body lifecycle", "Type III secretion system", "MOMP", "Pmp (polymorphic membrane proteins)", "Persistent infection capability"],
    transmission: "Respiratory droplets. Person-to-person. No animal reservoir",
    epidemiology: "Seroprevalence 50-70% by age 20. Causes 5-10% of community-acquired pneumonia. Possible association with atherosclerosis (controversial).",
    prevention: ["No vaccine available", "Standard respiratory precautions"],
    incubationPeriod: "21 days (longer than most respiratory pathogens)",
    complications: ["Chronic infection", "Exacerbation of asthma", "Possible role in atherosclerosis", "Guillain-Barré syndrome (rare)"],
    cultureConditions: "Obligate intracellular. Cell culture (HEp-2 cells). PCR preferred for diagnosis.",
    taxonomy: { domain: "Bacteria", phylum: "Chlamydiota", class: "Chlamydiia", order: "Chlamydiales", family: "Chlamydiaceae" },
  },
  "rickettsia-rickettsii": {
    virulenceFactors: ["OmpA/OmpB (outer membrane proteins – adhesion/invasion)", "Phospholipase A2 (phagosome escape)", "Actin-based motility", "Endothelial cell tropism (causes vasculitis)"],
    transmission: "Tick bite (Dermacentor variabilis – American dog tick, D. andersoni – Rocky Mountain wood tick, Amblyomma americanum – Lone Star tick)",
    epidemiology: "US: ~5,000 cases/year. Most common in Southeast/South Central states. Peak: April-September. Case fatality 5-10% (higher without treatment).",
    prevention: ["Tick avoidance and repellents", "Tick checks", "Prompt tick removal", "No vaccine available"],
    incubationPeriod: "2-14 days (usually 5-7 days)",
    complications: ["DIC", "ARDS", "Encephalitis", "Gangrene (extremities)", "Renal failure", "Death (20-25% untreated)"],
    cultureConditions: "Obligate intracellular. Cell culture (Vero cells, BSL-3). Diagnosis by serology (IFA) or PCR.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Alphaproteobacteria", order: "Rickettsiales", family: "Rickettsiaceae" },
  },
  "coxiella-burnetii": {
    virulenceFactors: ["Phase variation (Phase I virulent → Phase II avirulent)", "Type IV secretion system (Dot/Icm)", "Spore-like forms (environmental resistance)", "Acid phosphatase", "Superoxide dismutase"],
    transmission: "Inhalation of contaminated aerosols from infected animals (cattle, sheep, goats). Birth products, milk, feces. Very low infectious dose (1-10 organisms). NOT usually tick-borne",
    epidemiology: "Worldwide. Underreported. Occupational risk: farmers, veterinarians, lab workers. Large outbreak in Netherlands (2007-2010, >4,000 cases).",
    prevention: ["Vaccination of livestock", "Q-Vax vaccine (Australia, for high-risk workers)", "Pasteurization of milk", "Proper disposal of birth products"],
    incubationPeriod: "Acute: 2-3 weeks. Chronic: months to years",
    complications: ["Chronic Q fever (endocarditis – prosthetic valves, vascular grafts)", "Hepatitis", "Osteomyelitis", "Chronic fatigue syndrome", "Pregnancy complications"],
    cultureConditions: "Obligate intracellular. Cell culture (Vero cells, BSL-3). Diagnosis by serology (IFA – Phase I and II antigens) or PCR.",
    taxonomy: { domain: "Bacteria", phylum: "Pseudomonadota", class: "Gammaproteobacteria", order: "Legionellales", family: "Coxiellaceae" },
  },
  "mycoplasma-pneumoniae": {
    virulenceFactors: ["P1 adhesin (cytadherence to respiratory epithelium)", "CARDS toxin (Community-Acquired Respiratory Distress Syndrome toxin – ADP-ribosyltransferase)", "Hydrogen peroxide production (ciliary damage)", "Superantigen activity", "Biofilm formation"],
    transmission: "Respiratory droplets, close contact (families, schools, military barracks). Slow transmission",
    epidemiology: "Causes 10-40% of community-acquired pneumonia. Peak: children 5-15 years and young adults. Cyclic epidemics every 3-7 years.",
    prevention: ["No vaccine available", "Droplet precautions for hospitalized patients", "Hand hygiene"],
    incubationPeriod: "1-4 weeks (usually 2-3 weeks)",
    complications: ["Cold agglutinin hemolytic anemia (anti-I)", "Stevens-Johnson syndrome/erythema multiforme", "Encephalitis", "Guillain-Barré syndrome", "Myocarditis", "Bullous myringitis"],
    cultureConditions: "Specialized media (SP4 broth/agar). Extremely slow growth (weeks). 'Fried egg' colonies on agar. PCR is preferred diagnostic method.",
    taxonomy: { domain: "Bacteria", phylum: "Mycoplasmatota", class: "Mollicutes", order: "Mycoplasmatales", family: "Mycoplasmataceae" },
  },
  "ureaplasma-urealyticum": {
    virulenceFactors: ["Urease (produces ammonia, local tissue damage)", "IgA protease", "Multiple-banded antigen (MBA – antigenic variation)", "Phospholipase"],
    transmission: "Sexual contact, vertical transmission during birth",
    epidemiology: "Colonizes genital tract of 40-80% of sexually active women. Role in disease is debated. Associated with preterm birth, neonatal morbidity.",
    prevention: ["Safe sex practices", "Screening in high-risk pregnancies (controversial)"],
    incubationPeriod: "Variable; often colonization without clear onset",
    complications: ["Preterm birth", "Low birth weight", "Neonatal pneumonia/meningitis", "Chronic lung disease in preterm infants", "Male infertility"],
    cultureConditions: "Specialized media with urea (A8 agar). 37°C, 24-48h. Tiny colonies (15-60 µm). Urease positive differentiates from Mycoplasma.",
    taxonomy: { domain: "Bacteria", phylum: "Mycoplasmatota", class: "Mollicutes", order: "Mycoplasmatales", family: "Mycoplasmataceae" },
  },

  // ==================== ACID-FAST BACILLI ====================
  "mycobacterium-tuberculosis": {
    virulenceFactors: ["Cord factor (trehalose dimycolate – granuloma formation, inhibits phagolysosome fusion)", "Mycolic acids (waxy cell wall, immune evasion)", "ESAT-6/CFP-10 (secreted via ESX-1, phagosome escape)", "LAM (lipoarabinomannan – inhibits macrophage activation)", "Catalase-peroxidase (KatG)", "Sulfatides"],
    transmission: "Airborne (respiratory droplets/aerosols). Person-to-person via coughing/sneezing. Requires prolonged close contact",
    epidemiology: "~10 million new cases/year, ~1.3 million deaths globally (leading infectious cause of death). One-quarter of world population has latent TB. MDR-TB: ~500,000 cases/year.",
    prevention: ["BCG vaccine (variable efficacy, used worldwide except US)", "Latent TB treatment (isoniazid 9 months, or rifampin 4 months)", "Contact tracing and investigation", "Respiratory isolation (airborne precautions)", "HEPA filtration, UV germicidal irradiation"],
    incubationPeriod: "Primary infection to positive TST: 2-12 weeks. Active disease: months to decades after infection",
    complications: ["Miliary TB (hematogenous dissemination)", "TB meningitis (high mortality)", "Pleural effusion", "Pericarditis", "Drug-induced hepatotoxicity (treatment complication)", "IRIS (immune reconstitution syndrome in HIV)"],
    cultureConditions: "Lowenstein-Jensen (LJ) medium or Middlebrook 7H10/7H11. 37°C, 3-8 weeks. Buff-colored, rough colonies (cauliflower-like). MGIT liquid culture faster (1-2 weeks).",
    taxonomy: { domain: "Bacteria", phylum: "Actinomycetota", class: "Actinomycetes", order: "Mycobacteriales", family: "Mycobacteriaceae" },
  },
  "mycobacterium-avium-complex": {
    virulenceFactors: ["Glycopeptidolipids (GPL – biofilm, immune modulation)", "Cell wall lipids", "Catalase", "Superoxide dismutase"],
    transmission: "Environmental inhalation or ingestion (soil, water, biofilms in plumbing). NOT person-to-person",
    epidemiology: "Most common NTM causing disease. In AIDS: disseminated MAC when CD4 <50. Non-HIV: chronic pulmonary disease (Lady Windermere syndrome – middle lobe/lingula).",
    prevention: ["Azithromycin or clarithromycin prophylaxis in AIDS when CD4 <50", "ART (immune reconstitution)", "No environmental prevention practical"],
    incubationPeriod: "Weeks to months; insidious onset",
    complications: ["Disseminated disease (fever, weight loss, hepatosplenomegaly, cytopenias)", "Chronic fibrocavitary lung disease", "IRIS on ART"],
    cultureConditions: "LJ medium or MGIT. 37°C, 2-6 weeks. Smooth, non-pigmented colonies. Molecular probes for identification.",
    taxonomy: { domain: "Bacteria", phylum: "Actinomycetota", class: "Actinomycetes", order: "Mycobacteriales", family: "Mycobacteriaceae" },
  },
  "mycobacterium-leprae": {
    virulenceFactors: ["Phenolic glycolipid-1 (PGL-1 – complement resistance, nerve demyelination)", "Cell wall lipids", "Tropism for Schwann cells and cooler body temperatures", "Very slow growth (doubling time 12-14 days)"],
    transmission: "Prolonged close contact (respiratory droplets from nasal secretions). Armadillo contact (Southern US). Low transmissibility",
    epidemiology: "~200,000 new cases/year globally. India, Brazil, Indonesia account for >80% of cases. US: ~150 cases/year. Declining globally due to MDT.",
    prevention: ["Multi-drug therapy for cases (interrupts transmission)", "BCG provides some protection (20-80%)", "Chemoprophylaxis for contacts (single-dose rifampin)"],
    incubationPeriod: "Average 5 years (range 2-20 years) – one of the longest incubation periods",
    complications: ["Peripheral neuropathy (irreversible)", "Erythema nodosum leprosum (ENL, type 2 reaction)", "Reversal reaction (type 1 reaction)", "Blindness", "Limb deformities and contractures"],
    cultureConditions: "Cannot be cultured in vitro. Grows in mouse footpad or nine-banded armadillo. Diagnosis is clinical + skin biopsy.",
    taxonomy: { domain: "Bacteria", phylum: "Actinomycetota", class: "Actinomycetes", order: "Mycobacteriales", family: "Mycobacteriaceae" },
  },

  // ==================== FUNGI ====================
  "candida-albicans": {
    virulenceFactors: ["Phenotypic switching (yeast ↔ hyphae, immune evasion)", "Adhesins (ALS family – agglutinin-like sequence)", "Secreted aspartyl proteases (SAP1-10)", "Phospholipases", "Biofilm formation", "Germ tube/true hyphae formation (tissue invasion)"],
    transmission: "Endogenous (normal flora becomes pathogenic). Nosocomial (contaminated catheters, hands, TPN)",
    epidemiology: "Most common human fungal pathogen. Fourth most common cause of nosocomial bloodstream infections. Mucosal disease very common (75% women have VVC).",
    prevention: ["Fluconazole prophylaxis (high-risk transplant patients)", "Echinocandin prophylaxis (certain ICU populations)", "Central line care bundles", "Antifungal stewardship"],
    incubationPeriod: "Variable; endogenous infection related to immune status or disrupted barriers",
    complications: ["Candidemia (10-40% mortality)", "Endocarditis", "Endophthalmitis", "Hepatosplenic candidiasis (chronic disseminated)", "Catheter-related complications"],
    cultureConditions: "SDA (Sabouraud Dextrose Agar) or blood agar. 37°C, 24-48h. Creamy white colonies. CHROMagar for species identification. Germ tube in serum at 37°C.",
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Saccharomycetes", order: "Saccharomycetales", family: "Saccharomycetaceae" },
  },
  "candida-auris": {
    virulenceFactors: ["Biofilm formation (on skin and surfaces)", "Thermotolerance", "Adhesins", "Phospholipases", "SAP proteases", "Environmental persistence (survives months on surfaces)"],
    transmission: "Healthcare-associated person-to-person and contaminated surfaces. Persists on skin and in environment",
    epidemiology: "First identified in 2009 (Japan). Now global. CDC urgent threat. Outbreaks in ICUs, long-term care facilities. Five major clades. 30-60% mortality.",
    prevention: ["Contact precautions with gown and gloves", "Enhanced environmental cleaning (quaternary ammonium products)", "Active surveillance screening", "Colonized patients require dedicated equipment"],
    incubationPeriod: "Colonization to invasive infection: variable",
    complications: ["Pan-drug resistant infections", "Healthcare-associated outbreaks difficult to control", "Treatment failure", "High mortality"],
    cultureConditions: "SDA 37-40°C. Often misidentified by conventional methods. MALDI-TOF or molecular ID required. Grows at high temperatures.",
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Saccharomycetes", order: "Saccharomycetales", family: "Metschnikowiaceae" },
  },
  "aspergillus-fumigatus": {
    virulenceFactors: ["Galactomannan (cell wall component, biomarker)", "Gliotoxin (immunosuppressive)", "Melanin (conidial pigment, oxidative stress resistance)", "Thermotolerance (up to 55°C)", "Small conidia size (2-3 μm, reach alveoli)", "Hydrophobins (immune evasion)", "Proteases (elastase, collagenase)"],
    transmission: "Inhalation of ubiquitous airborne conidia. NOT person-to-person. Environmental (decaying vegetation, soil, compost)",
    epidemiology: "Most common cause of invasive aspergillosis. Risk: neutropenia, hematopoietic stem cell transplant, solid organ transplant, high-dose steroids. ~200,000 cases of invasive aspergillosis/year globally.",
    prevention: ["HEPA-filtered rooms for neutropenic patients", "Posaconazole/voriconazole prophylaxis (transplant recipients)", "Avoid construction areas (release conidia)", "Galactomannan surveillance"],
    incubationPeriod: "Days to weeks after exposure in susceptible hosts",
    complications: ["Angioinvasion and tissue necrosis", "Pulmonary hemorrhage", "Dissemination to brain, skin, other organs", "Azole-resistant invasive aspergillosis (increasing)", "Allergic bronchopulmonary aspergillosis (ABPA) with asthma/CF"],
    cultureConditions: "SDA 37°C, 24-72h. Rapid growth. Blue-green (smoky gray) colonies. Dichotomous branching at 45° (tissue). Septate hyphae.",
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Eurotiomycetes", order: "Eurotiales", family: "Aspergillaceae" },
  },
  "cryptococcus-neoformans": {
    virulenceFactors: ["Polysaccharide capsule (glucuronoxylomannan – antiphagocytic, immunomodulatory)", "Melanin (laccase enzyme – antioxidant protection)", "Urease (BBB penetration)", "Phospholipase", "Growth at 37°C"],
    transmission: "Inhalation of environmental yeast/basidiospores from pigeon droppings, eucalyptus trees. NOT person-to-person",
    epidemiology: "Major opportunistic infection in AIDS (CD4 <100). ~223,000 cases of cryptococcal meningitis/year, ~181,000 deaths (mostly sub-Saharan Africa). Also in transplant recipients.",
    prevention: ["ART (best prevention in HIV+)", "Fluconazole prophylaxis (resource-limited settings, CD4 <100)", "Screening with CrAg (cryptococcal antigen) in HIV+ with low CD4"],
    incubationPeriod: "Weeks to months; can reactivate years after initial exposure",
    complications: ["Elevated intracranial pressure (requires serial LPs/shunting)", "Cryptococcoma (mass lesion)", "IRIS during ART initiation", "Permanent neurological deficits", "Death (15-30% even with treatment)"],
    cultureConditions: "SDA or blood agar, 37°C, 48-72h. Mucoid, cream-colored colonies. India ink shows capsule. Birdseed (niger seed) agar: brown colonies (melanin production).",
    taxonomy: { domain: "Eukaryota", phylum: "Basidiomycota", class: "Tremellomycetes", order: "Tremellales", family: "Cryptococcaceae" },
  },
  "histoplasma-capsulatum": {
    virulenceFactors: ["Dimorphism (mold at 25°C → yeast at 37°C)", "CBP1 (calcium-binding protein – intracellular survival in macrophages)", "Heat shock protein (Hsp60)", "YPS3 (virulence in disseminated disease)", "Siderophores"],
    transmission: "Inhalation of microconidia from soil contaminated with bird/bat droppings. NOT person-to-person",
    epidemiology: "Endemic in Ohio/Mississippi River valleys, Central America. Exposure: spelunking, chicken coops, demolition of old buildings. Reactivation in immunocompromised.",
    prevention: ["Avoid exposure to bird/bat droppings", "Wetting soil before excavation", "Respiratory protection (N95) in endemic areas during soil disturbance", "Itraconazole prophylaxis (AIDS, CD4 <150 in endemic areas)"],
    incubationPeriod: "3-17 days (usually 7-14 days)",
    complications: ["Progressive disseminated histoplasmosis (AIDS)", "Mediastinal fibrosis (rare, excessive fibrotic response)", "Pericarditis", "Adrenal insufficiency", "Oral ulcers (disseminated)"],
    cultureConditions: "SDA 25°C: mold form (fluffy white/brown, tuberculate macroconidia). BHI 37°C: yeast form. 2-4 weeks. BSL-3 for mold culture.",
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Eurotiomycetes", order: "Onygenales", family: "Ajellomycetaceae" },
  },
  "blastomyces-dermatitidis": {
    virulenceFactors: ["Dimorphism", "BAD1 (Blastomyces adhesin 1 – adhesion, immune evasion)", "Cell wall alpha-1,3-glucan (resistance to phagocytosis)", "Melanin production"],
    transmission: "Inhalation of conidia from soil near waterways (rivers, lakes). NOT person-to-person",
    epidemiology: "Endemic in Great Lakes region, Ohio/Mississippi/St. Lawrence River valleys. Outdoor activities near waterways are risk factors. Often misdiagnosed.",
    prevention: ["No vaccine", "Avoidance of soil exposure in endemic areas (limited practicality)"],
    incubationPeriod: "21-100 days (usually 30-45 days)",
    complications: ["Dissemination to skin (most common extrapulmonary)", "Bone/joint disease", "CNS disease (meningitis, abscess)", "Genitourinary (prostatitis, epididymitis)", "ARDS"],
    cultureConditions: "SDA 25°C: white mold. BHI 37°C: broad-based budding yeast (8-15 μm, very characteristic). 1-4 weeks. BSL-3 for mold culture.",
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Eurotiomycetes", order: "Onygenales", family: "Ajellomycetaceae" },
  },
  "coccidioides-immitis": {
    virulenceFactors: ["Spherule outer wall (SOW) glycoprotein", "Urease (tissue damage)", "Metalloproteinase (Mep1)", "Chitinase", "Dimorphism (mold → spherule with endospores)"],
    transmission: "Inhalation of airborne arthroconidia from disturbed soil. NOT person-to-person. Highly infectious (single arthroconidium can cause infection)",
    epidemiology: "Endemic in US Southwest (Arizona, California), Mexico, Central/South America. ~150,000 infections/year in US. Increasing with climate change (expanding range). Dust storms increase risk.",
    prevention: ["No vaccine (candidates in development)", "Avoid dust exposure in endemic areas", "N95 masks during soil disturbance", "Fluconazole prophylaxis (transplant recipients in endemic areas)"],
    incubationPeriod: "1-3 weeks (usually 7-21 days)",
    complications: ["Disseminated disease (1% of infected; risk: Filipino, African American, immunosuppressed, pregnant)", "Coccidioidal meningitis (requires lifelong azole therapy)", "Bone/joint disease", "Skin lesions"],
    cultureConditions: "SDA 25°C: white cottony mold with barrel-shaped arthroconidia. EXTREMELY DANGEROUS – BSL-3 mandatory. Spherules in tissue at 37°C.",
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Eurotiomycetes", order: "Onygenales", family: "Onygenaceae" },
  },
  "pneumocystis-jirovecii": {
    virulenceFactors: ["Major surface glycoprotein (MSG/gpA – adhesion to alveolar epithelium, antigenic variation)", "Beta-1,3-glucan (cell wall component, triggers inflammatory response)", "Cannot be cultured in vitro"],
    transmission: "Airborne, person-to-person (or environmental). Primary infection in childhood, reactivation in immunocompromised",
    epidemiology: "AIDS-defining illness (CD4 <200). Declining with ART and prophylaxis. Also in transplant recipients, chronic steroids, anti-CD20 therapy (rituximab).",
    prevention: ["TMP-SMX prophylaxis (CD4 <200 in HIV, or immunosuppressed patients)", "Dapsone or atovaquone alternatives", "ART for HIV+ patients"],
    incubationPeriod: "Acute: days to weeks in immunocompromised. Gradual onset over weeks typical in AIDS",
    complications: ["Respiratory failure", "Pneumothorax (spontaneous)", "Death (10-20% with treatment in AIDS, higher in non-HIV immunosuppression)"],
    cultureConditions: "Cannot be cultured in vitro (unique among fungi). Diagnosis by microscopy (GMS, DFA) or PCR from induced sputum or BAL.",
    taxonomy: { domain: "Eukaryota", phylum: "Ascomycota", class: "Pneumocystidomycetes", order: "Pneumocystidales", family: "Pneumocystidaceae" },
  },
  "mucor-rhizopus": {
    virulenceFactors: ["High-affinity iron uptake systems (especially in ketoacidosis/deferoxamine)", "Rapid growth and angioinvasion", "Spore germination in hyperglycemic/acidotic conditions", "CotH (spore coat protein – endothelial invasion)", "Rhizopus lipase"],
    transmission: "Inhalation of ubiquitous sporangiospores. Wound contamination. Ingestion (rare). NOT person-to-person",
    epidemiology: "Risk factors: diabetic ketoacidosis (most common), deferoxamine therapy, neutropenia, trauma/burns, COVID-19 (India). Mortality 40-80%.",
    prevention: ["Glycemic control", "Avoid deferoxamine in susceptible patients", "HEPA-filtered rooms for neutropenic patients"],
    incubationPeriod: "Rapid: 1-7 days in susceptible hosts",
    complications: ["Rhinocerebral extension (black necrotic eschar)", "Cavernous sinus thrombosis", "Brain abscess", "Pulmonary hemorrhage", "Disseminated disease", "Death (high even with treatment)"],
    cultureConditions: "SDA 37°C, 24-48h. Very rapid growth ('lid lifters'). Cotton candy-like colonies. Broad, pauciseptate/aseptate hyphae at 90° branching in tissue.",
    taxonomy: { domain: "Eukaryota", phylum: "Mucoromycota", class: "Mucoromycetes", order: "Mucorales", family: "Mucoraceae/Rhizopodaceae" },
  },

  // ==================== PARASITES ====================
  "plasmodium-falciparum": {
    virulenceFactors: ["PfEMP1 (erythrocyte membrane protein 1 – cytoadherence, rosetting, immune evasion, antigenic variation via var genes)", "RIFIN/STEVOR proteins", "Knob formation on infected RBCs", "Sequestration in microvasculature", "Rosetting", "Hemozoin (malaria pigment)"],
    transmission: "Female Anopheles mosquito bite. Also blood transfusion, congenital, needle sharing",
    epidemiology: "~247 million cases/year, ~619,000 deaths (2021). Sub-Saharan Africa bears 95% of burden. Children <5 most affected. Resistance to antimalarials spreading from Southeast Asia.",
    prevention: ["Insecticide-treated bed nets (ITNs)", "Indoor residual spraying (IRS)", "Chemoprophylaxis for travelers", "RTS,S/AS01 (Mosquirix) vaccine (WHO recommended for children in endemic areas)", "R21/Matrix-M vaccine (2023 approved)"],
    incubationPeriod: "7-30 days (usually 9-14 days). Can be longer with chemoprophylaxis",
    complications: ["Cerebral malaria (seizures, coma)", "Severe malarial anemia", "ARDS", "Acute renal failure", "Hypoglycemia", "Metabolic acidosis", "Blackwater fever (massive hemolysis)", "Death (1-3% of severe malaria)"],
    cultureConditions: "Cannot be routinely cultured. Diagnosis by thick/thin blood smears (Giemsa stain), rapid diagnostic tests (RDTs), PCR.",
    taxonomy: { domain: "Eukaryota", phylum: "Apicomplexa", class: "Aconoidasida", order: "Haemosporida", family: "Plasmodiidae" },
  },
  "toxoplasma-gondii": {
    virulenceFactors: ["Rhoptry proteins (ROP16, ROP18 – manipulate host immune signaling)", "Dense granule proteins (GRA – modify parasitophorous vacuole)", "Microneme proteins (MIC – adhesion, invasion)", "SAG1 (surface antigen 1)", "Gliding motility complex"],
    transmission: "Ingestion of oocysts from cat feces (contaminated soil, water), undercooked meat with tissue cysts (pork, lamb), vertical (transplacental), organ transplant/blood transfusion (rare)",
    epidemiology: "Seroprevalence 10-80% worldwide (varies by country). France, Brazil: >50%. US: ~11%. Most primary infections are asymptomatic in immunocompetent.",
    prevention: ["Cook meat to safe temperatures", "Wash fruits/vegetables", "Avoid cat litter during pregnancy (or use gloves)", "Wash hands after gardening", "TMP-SMX prophylaxis (AIDS, CD4 <100)"],
    incubationPeriod: "5-23 days after ingestion of oocysts. Congenital: transmission at any trimester (worst outcomes in first trimester)",
    complications: ["Encephalitis (AIDS – ring-enhancing brain lesions)", "Congenital toxoplasmosis (intracranial calcifications, hydrocephalus, chorioretinitis)", "Chorioretinitis (can reactivate)", "Myocarditis"],
    cultureConditions: "Obligate intracellular parasite. Cell culture (human fibroblasts). Mouse inoculation (research). PCR preferred for diagnosis.",
    taxonomy: { domain: "Eukaryota", phylum: "Apicomplexa", class: "Conoidasida", order: "Eucoccidiorida", family: "Sarcocystidae" },
  },
  "giardia-lamblia": {
    virulenceFactors: ["Variant surface proteins (VSPs – antigenic variation, immune evasion)", "Ventral disc (attachment to intestinal epithelium)", "Cysteine proteases", "Cyst wall proteins (environmental resistance)"],
    transmission: "Fecal-oral via contaminated water (cysts resist chlorination), person-to-person (daycare, MSM), foodborne, zoonotic (beavers, dogs)",
    epidemiology: "Most common intestinal protozoan worldwide. ~280 million symptomatic infections/year. Common in travelers, daycare attendees, hikers/campers, immunodeficient (IgA deficiency).",
    prevention: ["Water treatment (filtration, boiling)", "Hand hygiene", "Avoid untreated water", "Proper food handling"],
    incubationPeriod: "1-3 weeks (usually 7-14 days)",
    complications: ["Chronic diarrhea", "Malabsorption (fat, vitamins A, B12, folate)", "Failure to thrive (children)", "Lactose intolerance (post-infectious)", "Reactive arthritis (rare)"],
    cultureConditions: "Not routinely cultured. Diagnosis: stool O&P (cysts), stool antigen (EIA/DFA), PCR. Duodenal aspirate for trophozoites.",
    taxonomy: { domain: "Eukaryota", phylum: "Metamonada", class: "Trepomonadea", order: "Diplomonadida", family: "Hexamitidae" },
  },
  "entamoeba-histolytica": {
    virulenceFactors: ["Gal/GalNAc lectin (adhesion, cytotoxicity)", "Cysteine proteases (tissue invasion, degrade IgA, complement, ECM)", "Amoebapores (pore-forming peptides)", "Phagocytosis of host cells (erythrophagocytosis)"],
    transmission: "Fecal-oral via cyst ingestion (contaminated water/food). Person-to-person (MSM). Not from trophozoites (destroyed by gastric acid)",
    epidemiology: "~50 million infections/year, ~100,000 deaths. Endemic in developing countries (Mexico, India, Africa). Only 10-20% of infected develop disease.",
    prevention: ["Safe water supply", "Proper sanitation", "Hand hygiene", "Food safety"],
    incubationPeriod: "2-4 weeks (range days to years; cysts may persist)",
    complications: ["Fulminant colitis", "Colonic perforation", "Ameboma (mass lesion)", "Liver abscess (right lobe, can rupture)", "Pericarditis (extension from liver)", "Brain abscess (rare)"],
    cultureConditions: "Diamond's TYI-S-33 medium (research). Diagnosis: stool O&P, stool antigen, serology (liver abscess), PCR (distinguishes from E. dispar).",
    taxonomy: { domain: "Eukaryota", phylum: "Amoebozoa", class: "Archamoebae", order: "Mastigamoebida", family: "Entamoebidae" },
  },
  "cryptosporidium-parvum": {
    virulenceFactors: ["Oocyst wall proteins (COWP – environmental resistance, resist chlorination)", "GP60 (adhesion to intestinal epithelium)", "Intracellular but extracytoplasmic location (unique)", "Thin-walled autoinfective oocysts"],
    transmission: "Fecal-oral via contaminated water (oocysts resist chlorination), person-to-person, animal contact, recreational water",
    epidemiology: "Leading cause of waterborne disease outbreaks (Milwaukee 1993: 403,000 cases). Common in children, travelers, HIV/AIDS. Chlorine-resistant oocysts are major challenge.",
    prevention: ["Water filtration (oocysts are 4-6 μm)", "Boiling water", "UV disinfection", "ART for HIV+ patients", "Hygiene in daycare centers"],
    incubationPeriod: "2-10 days (usually 7 days)",
    complications: ["Chronic diarrhea in AIDS (severe wasting)", "Biliary disease (cholangitis, cholecystitis in AIDS)", "Pancreatitis", "Respiratory cryptosporidiosis (rare)"],
    cultureConditions: "Cannot be routinely cultured. Diagnosis: modified acid-fast stain (small pink oocysts 4-6 μm), DFA, stool antigen EIA, PCR.",
    taxonomy: { domain: "Eukaryota", phylum: "Apicomplexa", class: "Conoidasida", order: "Eucoccidiorida", family: "Cryptosporidiidae" },
  },
  "trichomonas-vaginalis": {
    virulenceFactors: ["Adhesins (AP65, AP51, AP33, AP23)", "Cysteine proteases (tissue damage, immune evasion)", "Cell-detaching factor", "Lipophosphoglycan", "Hydrogenosomes (unique organelle, metronidazole activation)"],
    transmission: "Sexual contact exclusively. No cyst stage – fragile, dies quickly outside host. Direct mucous membrane to mucous membrane contact required",
    epidemiology: "Most common non-viral STI worldwide (~156 million new cases/year). Higher prevalence in women than men. Often asymptomatic (70-85% of infections).",
    prevention: ["Condom use", "Partner treatment (concurrent)", "Screening in high-risk populations", "Rescreen at 3 months after treatment"],
    incubationPeriod: "5-28 days (average 7 days)",
    complications: ["Increased HIV acquisition and transmission (2-3 fold)", "Preterm birth", "Low birth weight", "Facilitation of other STI transmission", "Prostatitis (men)"],
    cultureConditions: "InPouch TV or Diamond's medium. 37°C, 2-7 days. Motile trophozoites. NAAT most sensitive diagnostic method.",
    taxonomy: { domain: "Eukaryota", phylum: "Metamonada", class: "Parabasalia", order: "Trichomonadida", family: "Trichomonadidae" },
  },
  "trypanosoma-cruzi": {
    virulenceFactors: ["Trans-sialidase (acquires sialic acid from host cells – immune evasion)", "Mucin coat (GPI-anchored)", "GP82/GP85 (invasion of non-phagocytic cells)", "Cruzipain (cysteine protease)", "Complement regulatory protein"],
    transmission: "Triatomine bug ('kissing bug') feces rubbed into bite wound or mucous membranes. Also blood transfusion, organ transplant, congenital, oral (contaminated food/juice)",
    epidemiology: "Endemic in Latin America (21 countries). ~6-7 million infected. US: ~300,000 (immigrants from endemic areas). WHO neglected tropical disease.",
    prevention: ["Housing improvement (reduce bug habitat)", "Insecticide spraying", "Blood/organ donor screening", "Congenital screening programs"],
    incubationPeriod: "Acute phase: 1-2 weeks after vector bite. Chronic phase: decades after initial infection",
    complications: ["Chagas cardiomyopathy (dilated, conduction defects – most common cause of death)", "Megacolon (Hirschsprung-like)", "Megaesophagus (achalasia-like)", "Meningoencephalitis (acute, children/immunosuppressed)", "Reactivation in immunosuppression (HIV, transplant)"],
    cultureConditions: "Cell culture (Vero cells) or NNN medium. Blood smear (Giemsa stain) for trypomastigotes. PCR, serology for chronic disease.",
    taxonomy: { domain: "Eukaryota", phylum: "Euglenozoa", class: "Kinetoplastea", order: "Trypanosomatida", family: "Trypanosomatidae" },
  },
  "leishmania-species": {
    virulenceFactors: ["LPG (lipophosphoglycan – complement resistance, macrophage modulation)", "GP63 (metalloprotease – complement C3b cleavage)", "A2 protein (heat tolerance, viscerotropism)", "Promastigote → amastigote transition (pH/temperature triggered)", "Phagolysosome survival"],
    transmission: "Bite of female phlebotomine sandfly (Lutzomyia in Americas, Phlebotomus in Old World). Also blood transfusion, congenital (rare), needle sharing",
    epidemiology: "700,000-1 million new cases/year, ~20,000-30,000 deaths. Visceral (VL): India, East Africa, Brazil. Cutaneous (CL): Afghanistan, Middle East, Americas. WHO neglected tropical disease.",
    prevention: ["Sandfly avoidance (insecticide-treated nets, repellents)", "Indoor residual spraying", "Reservoir control (dogs for VL in Americas)", "No vaccine for humans (dogs vaccine available)"],
    incubationPeriod: "CL: 2 weeks to months. VL: 2-6 months (range weeks to years). PKDL: months to years after VL treatment",
    complications: ["VL: fatal without treatment (95% mortality)", "Pancytopenia", "Secondary infections", "PKDL (post-kala-azar dermal leishmaniasis)", "Mucocutaneous: destructive facial lesions (L. braziliensis)"],
    cultureConditions: "NNN (Novy-MacNeal-Nicolle) medium or Schneider's insect medium. 22-26°C, 1-4 weeks. Promastigotes in culture, amastigotes in tissue.",
    taxonomy: { domain: "Eukaryota", phylum: "Euglenozoa", class: "Kinetoplastea", order: "Trypanosomatida", family: "Trypanosomatidae" },
  },
};
