// Comprehensive virus dataset
// Sources: NCBI Taxonomy, ICTV (International Committee on Taxonomy of Viruses), CDC, WHO, PubMed, ViralZone
import type { Organism } from "./organismData";

export const virusOrganisms: Organism[] = [
  // ==================== DNA VIRUSES ====================
  {
    id: "hiv-1",
    name: "Human Immunodeficiency Virus (HIV-1)",
    genus: "Lentivirus",
    species: "HIV-1",
    gramStain: "Not Applicable",
    shape: "Viral",
    arrangement: "Enveloped, icosahedral capsid, diploid +ssRNA retrovirus",
    oxygen: "Obligate Intracellular",
    pathogenic: true,
    habitat: "Human CD4+ T cells, macrophages, dendritic cells",
    diseases: ["HIV/AIDS", "Opportunistic infections", "AIDS-defining malignancies", "HIV-associated neurocognitive disorder"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "9.7 kb (diploid +ssRNA)", gcContent: "42%", genes: "9 genes (gag, pol, env, tat, rev, nef, vif, vpr, vpu)", notableGenes: ["gag (structural)", "pol (RT, integrase, protease)", "env (gp120/gp41)", "tat/rev (regulatory)"] },
    resistance: { intrinsic: [], acquired: ["NRTIs", "NNRTIs", "Protease inhibitors", "Integrase inhibitors"], mechanism: "High mutation rate (error-prone RT), recombination, archived resistance" },
    treatment: ["ART: 2 NRTIs + INSTI (preferred)", "Bictegravir/emtricitabine/TAF", "Dolutegravir-based regimens", "Long-acting cabotegravir + rilpivirine"],
    clinicalSignificance: "~38 million living with HIV worldwide. Targets CD4+ T cells. Untreated: progression to AIDS (CD4 <200). ART achieves viral suppression. U=U (undetectable = untransmittable).",
    labIdentification: ["4th gen Ag/Ab combo test (p24 + anti-HIV-1/2)", "HIV-1/2 differentiation immunoassay", "HIV-1 RNA viral load (RT-PCR)", "CD4 count monitoring", "Western blot (historical)"],
    virulenceFactors: ["gp120 (CD4/CCR5/CXCR4 binding)", "Reverse transcriptase (error-prone)", "Integrase (proviral integration)", "Nef (MHC-I downregulation)", "Vif (APOBEC3G degradation)"],
    transmission: "Sexual contact, blood/blood products, vertical (mother-to-child), needlestick",
    epidemiology: "~38 million people living with HIV globally. Sub-Saharan Africa most affected. ~1.3 million new infections/year (2022). ART has dramatically reduced mortality.",
    prevention: ["PrEP (emtricitabine/TAF or TDF)", "Condom use", "PMTCT (prevention of mother-to-child)", "Post-exposure prophylaxis (PEP)", "Treatment as prevention"],
    incubationPeriod: "Acute retroviral syndrome: 2-4 weeks. AIDS: 8-10 years without treatment",
    taxonomy: { domain: "Viruses", phylum: "Artverviricota", class: "Revtraviricetes", order: "Ortervirales", family: "Retroviridae" },
  },
  {
    id: "sars-cov-2",
    name: "SARS-CoV-2",
    genus: "Betacoronavirus",
    species: "Severe acute respiratory syndrome coronavirus 2",
    gramStain: "Not Applicable",
    shape: "Viral",
    arrangement: "Enveloped, +ssRNA, crown-like spike proteins",
    oxygen: "Obligate Intracellular",
    pathogenic: true,
    habitat: "Human respiratory epithelium (ACE2 receptor)",
    diseases: ["COVID-19", "ARDS", "Multisystem inflammatory syndrome", "Long COVID"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "29.9 kb (+ssRNA, largest RNA virus genome)", gcContent: "38%", genes: "~29 proteins", notableGenes: ["S (spike)", "N (nucleocapsid)", "E (envelope)", "RdRp (nsp12)", "3CLpro (nsp5)"] },
    resistance: { intrinsic: [], acquired: ["Remdesivir (some variants)", "Monoclonal antibodies (variant-dependent)"], mechanism: "Spike mutations (immune escape), RdRp mutations" },
    treatment: ["Nirmatrelvir/ritonavir (Paxlovid)", "Remdesivir", "Dexamethasone (hospitalized, hypoxic)", "Molnupiravir"],
    clinicalSignificance: "Pandemic pathogen (2019-present). >7 million confirmed deaths. Variants of concern: Alpha, Beta, Delta, Omicron. mRNA vaccines revolutionized vaccinology.",
    labIdentification: ["RT-PCR (nasopharyngeal swab, gold standard)", "Rapid antigen test", "Whole genome sequencing (variant surveillance)", "Serology (anti-N, anti-S antibodies)"],
    virulenceFactors: ["Spike protein (ACE2 binding, furin cleavage site)", "NSP1 (host shutoff)", "ORF8 (MHC-I downregulation)", "N protein (immune evasion)"],
    transmission: "Airborne/aerosol, respiratory droplets, fomites (minor). Super-spreading events",
    epidemiology: "Pandemic since Dec 2019. >770 million confirmed cases. Omicron subvariants dominant. Endemic transition ongoing.",
    prevention: ["mRNA vaccines (Pfizer, Moderna)", "Updated boosters", "Masks, ventilation", "Hand hygiene"],
    incubationPeriod: "2-14 days (median 5 days, Omicron: 3 days)",
    taxonomy: { domain: "Viruses", phylum: "Pisuviricota", class: "Pisoniviricetes", order: "Nidovirales", family: "Coronaviridae" },
  },
  {
    id: "influenza-a",
    name: "Influenza A virus",
    genus: "Alphainfluenzavirus",
    species: "Influenza A virus",
    gramStain: "Not Applicable",
    shape: "Viral",
    arrangement: "Enveloped, segmented -ssRNA (8 segments), pleomorphic",
    oxygen: "Obligate Intracellular",
    pathogenic: true,
    habitat: "Human respiratory epithelium, birds (reservoir), swine",
    diseases: ["Seasonal influenza", "Pandemic influenza", "Viral pneumonia", "Myocarditis", "Encephalitis"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "13.6 kb (8 segments, -ssRNA)", gcContent: "43%", genes: "11-14 proteins", notableGenes: ["HA (hemagglutinin, 18 subtypes)", "NA (neuraminidase, 11 subtypes)", "M2 (ion channel)", "PB2/PB1/PA (polymerase)"] },
    resistance: { intrinsic: [], acquired: ["Oseltamivir (H275Y in NA)", "Amantadine (M2 mutations - widespread)"], mechanism: "NA mutations (H275Y), M2 S31N mutation" },
    treatment: ["Oseltamivir (within 48h)", "Baloxavir marboxil", "Zanamivir", "Peramivir (IV)"],
    clinicalSignificance: "Annual epidemics, periodic pandemics (1918, 2009). Antigenic drift (point mutations) → seasonal epidemics. Antigenic shift (reassortment) → pandemics. H5N1 avian flu pandemic potential.",
    labIdentification: ["Rapid influenza diagnostic test (RIDT)", "RT-PCR (gold standard)", "Viral culture (MDCK cells)", "Direct fluorescent antibody (DFA)", "Hemagglutination inhibition (subtyping)"],
    transmission: "Respiratory droplets, aerosols, fomites. R0: 1.5-2.0",
    epidemiology: "3-5 million severe cases/year, 290,000-650,000 deaths/year globally. H1N1 and H3N2 circulate seasonally.",
    prevention: ["Annual influenza vaccine (quadrivalent)", "Antiviral chemoprophylaxis", "Hand hygiene", "Respiratory etiquette"],
    incubationPeriod: "1-4 days (median 2 days)",
    taxonomy: { domain: "Viruses", phylum: "Negarnaviricota", class: "Insthoviricetes", order: "Articulavirales", family: "Orthomyxoviridae" },
  },
  {
    id: "hepatitis-b",
    name: "Hepatitis B virus (HBV)",
    genus: "Orthohepadnavirus",
    species: "Hepatitis B virus",
    gramStain: "Not Applicable",
    shape: "Viral",
    arrangement: "Enveloped, partially dsDNA (relaxed circular), icosahedral",
    oxygen: "Obligate Intracellular",
    pathogenic: true,
    habitat: "Human hepatocytes",
    diseases: ["Acute hepatitis B", "Chronic hepatitis B", "Cirrhosis", "Hepatocellular carcinoma"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "3.2 kb (partially dsDNA, rcDNA)", gcContent: "48%", genes: "4 overlapping ORFs (S, C, P, X)", notableGenes: ["HBsAg (surface)", "HBcAg (core)", "HBeAg (secretory)", "Pol (reverse transcriptase)", "HBx (transactivator)"] },
    resistance: { intrinsic: [], acquired: ["Lamivudine (rtM204V/I)", "Adefovir (rtN236T)"], mechanism: "RT domain mutations" },
    treatment: ["Tenofovir (TDF or TAF)", "Entecavir", "Pegylated interferon-alpha (finite therapy)", "Functional cure goal: HBsAg loss"],
    clinicalSignificance: "~296 million chronically infected. Leading cause of HCC worldwide. cccDNA persists in hepatocytes (cure difficult). Vertical transmission risk high. Serology interpretation is critical.",
    labIdentification: ["HBsAg (acute/chronic infection)", "Anti-HBs (immunity)", "Anti-HBc IgM (acute) / IgG (past/chronic)", "HBeAg/anti-HBe (replication status)", "HBV DNA viral load (PCR)"],
    transmission: "Blood, sexual contact, vertical (perinatal). 100x more infectious than HIV",
    epidemiology: "~296 million chronic carriers. Highest prevalence: sub-Saharan Africa, East Asia. ~820,000 deaths/year from complications.",
    prevention: ["HBV vaccine (recombinant HBsAg, 3-dose series)", "HBIG + vaccine for neonates of HBsAg+ mothers", "Universal screening in pregnancy", "Blood donor screening"],
    incubationPeriod: "45-160 days (average 120 days)",
    taxonomy: { domain: "Viruses", phylum: "Artverviricota", class: "Revtraviricetes", order: "Blubervirales", family: "Hepadnaviridae" },
  },
  {
    id: "hepatitis-c",
    name: "Hepatitis C virus (HCV)",
    genus: "Hepacivirus",
    species: "Hepacivirus C",
    gramStain: "Not Applicable",
    shape: "Viral",
    arrangement: "Enveloped, +ssRNA, icosahedral",
    oxygen: "Obligate Intracellular",
    pathogenic: true,
    habitat: "Human hepatocytes",
    diseases: ["Acute hepatitis C", "Chronic hepatitis C", "Cirrhosis", "Hepatocellular carcinoma", "Cryoglobulinemia"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "9.6 kb (+ssRNA)", gcContent: "Variable", genes: "~10 proteins (single polyprotein)", notableGenes: ["NS3/4A (protease)", "NS5A (replication complex)", "NS5B (RdRp)", "E1/E2 (envelope glycoproteins)"] },
    resistance: { intrinsic: [], acquired: ["NS5A inhibitor resistance (RAS)"], mechanism: "NS5A resistance-associated substitutions, NS3 mutations" },
    treatment: ["DAAs: Sofosbuvir/velpatasvir (pangenotypic)", "Glecaprevir/pibrentasvir", "Cure rate >95% in 8-12 weeks", "No vaccine available"],
    clinicalSignificance: "~58 million chronically infected. 'Silent epidemic' - often asymptomatic for decades. Now curable with DAAs. 6 genotypes. Leading indication for liver transplant (declining).",
    labIdentification: ["Anti-HCV antibody (screening)", "HCV RNA (confirmatory, PCR)", "HCV genotype (treatment guidance)", "HCV core antigen (alternative to RNA)"],
    transmission: "Blood (IVDU primary risk), sexual (less efficient than HBV), vertical (5%)",
    epidemiology: "~58 million chronic infections. Highest: Eastern Mediterranean, European regions. WHO elimination target: 2030.",
    prevention: ["No vaccine", "Harm reduction (needle exchange)", "Blood product screening", "Universal birth cohort screening"],
    incubationPeriod: "2-26 weeks (average 6-7 weeks)",
    taxonomy: { domain: "Viruses", phylum: "Kitrinoviricota", class: "Flasuviricetes", order: "Amarillovirales", family: "Flaviviridae" },
  },
  {
    id: "ebola-virus",
    name: "Ebola virus (Zaire ebolavirus)",
    genus: "Ebolavirus",
    species: "Zaire ebolavirus",
    gramStain: "Not Applicable",
    shape: "Viral",
    arrangement: "Enveloped, -ssRNA, filamentous (shepherd's crook shape)",
    oxygen: "Obligate Intracellular",
    pathogenic: true,
    habitat: "Fruit bats (reservoir), primates",
    diseases: ["Ebola virus disease (EVD)", "Hemorrhagic fever", "Multi-organ failure"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "18.9 kb (-ssRNA)", gcContent: "42%", genes: "7 genes (NP, VP35, VP40, GP, VP30, VP24, L)", notableGenes: ["GP (glycoprotein, host attachment/fusion)", "VP40 (matrix, budding)", "VP35 (interferon antagonist)", "L (RNA polymerase)"] },
    resistance: { intrinsic: [], acquired: [], mechanism: "N/A" },
    treatment: ["Inmazeb (atoltivimab + maftivimab + odesivimab)", "Ebanga (ansuvimab)", "Supportive care (fluid resuscitation)", "Remdesivir (investigational)"],
    clinicalSignificance: "Case fatality rate 25-90% (Zaire species ~50-90%). 2014 West Africa outbreak: 28,616 cases, 11,310 deaths. BSL-4 pathogen. WHO Public Health Emergency.",
    labIdentification: ["RT-PCR (blood, BSL-4/point-of-care)", "ELISA (antigen detection)", "IgM/IgG serology", "Electron microscopy (filamentous virion)", "Rapid diagnostic tests (field)"],
    virulenceFactors: ["GP (cytotoxicity, vascular permeability)", "VP35 (blocks IFN-α/β)", "VP24 (blocks IFN signaling, STAT1)", "VP40 (budding efficiency)", "sGP (antibody decoy)"],
    transmission: "Direct contact with blood/body fluids, bushmeat. Not airborne. Virus persists in semen up to 18 months",
    epidemiology: "Endemic in Central/West Africa. Major outbreaks: 2014-16 (West Africa), 2018-20 (DRC). Reservoir: fruit bats (Pteropodidae).",
    prevention: ["rVSV-ZEBOV vaccine (Ervebo)", "Contact tracing and isolation", "Safe burial practices", "PPE for healthcare workers"],
    incubationPeriod: "2-21 days (average 8-10 days)",
    taxonomy: { domain: "Viruses", phylum: "Negarnaviricota", class: "Monjiviricetes", order: "Mononegavirales", family: "Filoviridae" },
  },
  {
    id: "dengue-virus",
    name: "Dengue virus",
    genus: "Flavivirus",
    species: "Dengue virus (DENV 1-4)",
    gramStain: "Not Applicable",
    shape: "Viral",
    arrangement: "Enveloped, +ssRNA, icosahedral",
    oxygen: "Obligate Intracellular",
    pathogenic: true,
    habitat: "Aedes mosquitoes (A. aegypti, A. albopictus)",
    diseases: ["Dengue fever", "Dengue hemorrhagic fever", "Dengue shock syndrome"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "10.7 kb (+ssRNA)", gcContent: "46%", genes: "Single polyprotein (3 structural + 7 non-structural)", notableGenes: ["NS1 (diagnostic target, immune evasion)", "NS3 (protease/helicase)", "NS5 (RdRp/methyltransferase)", "E (envelope)"] },
    resistance: { intrinsic: [], acquired: [], mechanism: "N/A" },
    treatment: ["Supportive care (fluid management)", "No specific antivirals", "Avoid aspirin/NSAIDs (bleeding risk)", "Monitor for warning signs of severe dengue"],
    clinicalSignificance: "Most common arboviral disease (390 million infections/year). 4 serotypes → secondary heterotypic infection risk for severe dengue (antibody-dependent enhancement). Tourniquet test.",
    labIdentification: ["NS1 antigen (first 5 days)", "IgM (day 5+)", "IgG (secondary infection: early rise)", "RT-PCR (viremia period)", "CBC: thrombocytopenia, leukopenia, hemoconcentration"],
    transmission: "Aedes mosquito bite. No person-to-person",
    epidemiology: "~390 million infections/year, 96 million symptomatic. Expanding range due to climate change. Endemic in >100 countries. SE Asia, Americas most affected.",
    prevention: ["Dengvaxia vaccine (seropositive individuals only)", "Mosquito control (Aedes elimination)", "Personal protective measures", "Wolbachia-infected mosquito release"],
    incubationPeriod: "4-10 days (average 5-7 days)",
    taxonomy: { domain: "Viruses", phylum: "Kitrinoviricota", class: "Flasuviricetes", order: "Amarillovirales", family: "Flaviviridae" },
  },
  {
    id: "rabies-virus",
    name: "Rabies virus",
    genus: "Lyssavirus",
    species: "Rabies lyssavirus",
    gramStain: "Not Applicable",
    shape: "Viral",
    arrangement: "Enveloped, -ssRNA, bullet-shaped (pathognomonic)",
    oxygen: "Obligate Intracellular",
    pathogenic: true,
    habitat: "Mammals (bats, raccoons, skunks, foxes, dogs)",
    diseases: ["Rabies encephalitis (nearly 100% fatal)", "Furious rabies", "Paralytic rabies"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "11.9 kb (-ssRNA)", gcContent: "45%", genes: "5 genes (N, P, M, G, L)", notableGenes: ["G (glycoprotein, attachment, vaccine target)", "N (nucleoprotein, diagnostic target)", "L (RNA polymerase)"] },
    resistance: { intrinsic: [], acquired: [], mechanism: "N/A" },
    treatment: ["Post-exposure prophylaxis (PEP): wound wash + rabies vaccine + HRIG", "No treatment once symptomatic (nearly 100% fatal)", "Milwaukee protocol (experimental, very rare survival)"],
    clinicalSignificance: "Nearly 100% fatal once symptomatic (~59,000 deaths/year). Travels via peripheral nerves to CNS. Negri bodies (eosinophilic cytoplasmic inclusions in neurons). Hydrophobia pathognomonic.",
    labIdentification: ["DFA of brain tissue (gold standard, postmortem)", "DFA of nuchal skin biopsy (antemortem)", "RT-PCR of saliva", "Negri bodies on histology", "Virus isolation (mouse/cell culture)"],
    transmission: "Animal bite (saliva). Rarely: aerosol (bat caves), transplant",
    epidemiology: "~59,000 deaths/year globally (99% from dog bites). Eliminated in many developed countries. Endemic in Africa, Asia. US: bats most common source.",
    prevention: ["Pre-exposure vaccination (travelers, veterinarians)", "Post-exposure prophylaxis", "Dog vaccination programs", "Wound washing with soap (reduces risk 90%)"],
    incubationPeriod: "Usually 1-3 months (range: 1 week to >1 year, depends on wound location)",
    taxonomy: { domain: "Viruses", phylum: "Negarnaviricota", class: "Monjiviricetes", order: "Mononegavirales", family: "Rhabdoviridae" },
  },
  {
    id: "hpv",
    name: "Human Papillomavirus (HPV)",
    genus: "Alphapapillomavirus",
    species: "Various (HPV-16, HPV-18 most oncogenic)",
    gramStain: "Not Applicable",
    shape: "Viral",
    arrangement: "Non-enveloped, dsDNA, icosahedral",
    oxygen: "Obligate Intracellular",
    pathogenic: true,
    habitat: "Human epithelial cells (skin, mucosa)",
    diseases: ["Cervical cancer", "Genital warts (condylomata acuminata)", "Oropharyngeal cancer", "Anal cancer", "Common warts"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "8 kb (circular dsDNA)", gcContent: "42%", genes: "8 genes (E1, E2, E4, E5, E6, E7, L1, L2)", notableGenes: ["E6 (degrades p53)", "E7 (inactivates Rb)", "L1 (major capsid, vaccine target)", "E2 (transcription regulator)"] },
    resistance: { intrinsic: [], acquired: [], mechanism: "N/A" },
    treatment: ["No antivirals", "Cryotherapy/electrocautery (warts)", "LEEP/conization (CIN)", "Imiquimod (topical immune modifier)", "Podophyllotoxin"],
    clinicalSignificance: "Most common STI. >200 types. High-risk types (16, 18) cause ~70% cervical cancers. E6 degrades p53, E7 inactivates Rb → uncontrolled cell proliferation. Koilocytes on Pap smear.",
    labIdentification: ["Pap smear (koilocytes, ASCUS, LSIL, HSIL)", "HPV DNA testing (HC2, PCR)", "p16 immunohistochemistry (surrogate for HPV)", "Genotyping (type 16/18 reflex)"],
    virulenceFactors: ["E6 (p53 degradation via ubiquitin)", "E7 (Rb inactivation)", "E5 (growth factor receptor modulation)", "L1 (immune evasion via late expression)"],
    transmission: "Direct skin/mucosal contact, sexual contact. Vertical transmission rare",
    epidemiology: "~80% of sexually active people infected at some point. ~570,000 cervical cancer cases/year. HPV vaccine dramatically reducing incidence.",
    prevention: ["HPV vaccine (Gardasil 9: types 6,11,16,18,31,33,45,52,58)", "Cervical cancer screening (Pap + HPV co-testing)", "Condoms (partial protection)"],
    taxonomy: { domain: "Viruses", phylum: "Preplasmiviricota", class: "Papovaviricetes", order: "Zurhausenvirales", family: "Papillomaviridae" },
  },
  {
    id: "herpes-simplex-1",
    name: "Herpes Simplex Virus 1 (HSV-1)",
    genus: "Simplexvirus",
    species: "Human alphaherpesvirus 1",
    gramStain: "Not Applicable",
    shape: "Viral",
    arrangement: "Enveloped, linear dsDNA, icosahedral",
    oxygen: "Obligate Intracellular",
    pathogenic: true,
    habitat: "Human sensory ganglia (trigeminal ganglion), mucocutaneous surfaces",
    diseases: ["Oral herpes (cold sores)", "Herpes encephalitis", "Herpes keratitis", "Genital herpes", "Herpetic whitlow"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "152 kb (linear dsDNA)", gcContent: "68%", genes: "~77 genes", notableGenes: ["UL30 (DNA polymerase, acyclovir target)", "gB/gD (attachment/fusion)", "ICP0 (immune evasion)", "LAT (latency-associated transcript)"] },
    resistance: { intrinsic: [], acquired: ["Acyclovir (TK mutations, immunocompromised)"], mechanism: "Thymidine kinase mutations (TK-negative or TK-altered)" },
    treatment: ["Acyclovir/valacyclovir (first-line)", "Famciclovir", "Foscarnet (acyclovir-resistant)", "IV acyclovir (encephalitis, neonatal)"],
    clinicalSignificance: "Latency in trigeminal ganglia with periodic reactivation. Temporal lobe encephalitis (most common fatal sporadic encephalitis). Tzanck smear shows multinucleated giant cells.",
    labIdentification: ["PCR (CSF for encephalitis, gold standard)", "Culture (CPE in 1-3 days)", "DFA", "Tzanck smear (multinucleated giant cells, nonspecific)", "Type-specific serology (gG-1)"],
    transmission: "Direct contact with lesions or asymptomatic shedding, saliva",
    epidemiology: "~67% of global population <50 has HSV-1. Seroprevalence increasing for genital HSV-1.",
    prevention: ["Avoid contact during active lesions", "Suppressive therapy for frequent recurrences", "Condoms (partial protection)"],
    incubationPeriod: "2-12 days (average 4 days)",
    taxonomy: { domain: "Viruses", phylum: "Peploviricota", class: "Herviviricetes", order: "Herpesvirales", family: "Orthoherpesviridae" },
  },
  {
    id: "varicella-zoster",
    name: "Varicella-Zoster Virus (VZV)",
    genus: "Varicellovirus",
    species: "Human alphaherpesvirus 3",
    gramStain: "Not Applicable",
    shape: "Viral",
    arrangement: "Enveloped, linear dsDNA, icosahedral",
    oxygen: "Obligate Intracellular",
    pathogenic: true,
    habitat: "Human dorsal root ganglia, skin",
    diseases: ["Chickenpox (varicella)", "Shingles (herpes zoster)", "Post-herpetic neuralgia", "Ramsay Hunt syndrome"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "125 kb (linear dsDNA)", gcContent: "46%", genes: "~71 genes", notableGenes: ["ORF62/63 (IE transactivator)", "gE (glycoprotein E, Shingrix target)", "TK (thymidine kinase)"] },
    resistance: { intrinsic: [], acquired: ["Acyclovir (rare, immunocompromised)"], mechanism: "TK mutations" },
    treatment: ["Acyclovir/valacyclovir (varicella in adults, zoster)", "Calamine lotion (symptomatic)", "Gabapentin/pregabalin (post-herpetic neuralgia)"],
    clinicalSignificance: "Primary infection: chickenpox (diffuse vesicular rash in crops, all stages simultaneously). Latency in dorsal root ganglia. Reactivation: shingles (dermatomal distribution). Congenital varicella syndrome.",
    labIdentification: ["Clinical diagnosis usually sufficient", "DFA of vesicle scraping", "PCR (gold standard for zoster)", "Tzanck smear (nonspecific)", "Culture (slow, 7-10 days)"],
    transmission: "Airborne (varicella is highly contagious, R0 ~10-12), direct contact with vesicle fluid",
    epidemiology: "Before vaccine: ~4 million cases/year in US. Zoster: ~1 million cases/year in US. Risk increases with age and immunosuppression.",
    prevention: ["Varicella vaccine (live attenuated)", "Shingrix (recombinant gE, 2 doses for adults ≥50)", "VZIG for exposed immunocompromised"],
    incubationPeriod: "Varicella: 10-21 days (average 14-16 days). Zoster: reactivation from latency",
    taxonomy: { domain: "Viruses", phylum: "Peploviricota", class: "Herviviricetes", order: "Herpesvirales", family: "Orthoherpesviridae" },
  },
  {
    id: "epstein-barr",
    name: "Epstein-Barr Virus (EBV)",
    genus: "Lymphocryptovirus",
    species: "Human gammaherpesvirus 4",
    gramStain: "Not Applicable",
    shape: "Viral",
    arrangement: "Enveloped, linear dsDNA, icosahedral",
    oxygen: "Obligate Intracellular",
    pathogenic: true,
    habitat: "Human B lymphocytes, oropharyngeal epithelium",
    diseases: ["Infectious mononucleosis", "Burkitt lymphoma", "Nasopharyngeal carcinoma", "PTLD (post-transplant lymphoproliferative disease)", "Hodgkin lymphoma"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "172 kb (linear dsDNA)", gcContent: "60%", genes: "~85 genes", notableGenes: ["LMP1 (oncogene, mimics CD40)", "EBNA1/2/3 (nuclear antigens)", "BZLF1 (lytic switch)", "EBERs (non-coding RNAs)"] },
    resistance: { intrinsic: [], acquired: [], mechanism: "N/A" },
    treatment: ["Supportive care (mono)", "Rituximab (PTLD)", "Reduce immunosuppression (PTLD)", "Chemotherapy (EBV-associated malignancies)"],
    clinicalSignificance: "~95% of adults seropositive. 'Kissing disease' (mono). Atypical lymphocytes (Downey cells). Associated with multiple cancers. Heterophile antibodies (Monospot).",
    labIdentification: ["Monospot (heterophile antibodies)", "EBV VCA IgM/IgG, EBNA IgG (serology)", "Atypical lymphocytes on CBC/smear", "EBV PCR (viral load, transplant monitoring)", "EBER ISH (tissue, gold standard for EBV in tumors)"],
    transmission: "Saliva ('kissing disease'), blood, transplant",
    epidemiology: "Ubiquitous. >95% adult seroprevalence. Primary infection in children often subclinical. Adolescent/young adult primary → mono. Burkitt lymphoma: African jaw variant.",
    prevention: ["No vaccine", "Avoid sharing utensils during acute illness", "EBV viral load monitoring in transplant"],
    incubationPeriod: "30-50 days (adolescents/adults)",
    taxonomy: { domain: "Viruses", phylum: "Peploviricota", class: "Herviviricetes", order: "Herpesvirales", family: "Orthoherpesviridae" },
  },
  {
    id: "cytomegalovirus",
    name: "Cytomegalovirus (CMV)",
    genus: "Cytomegalovirus",
    species: "Human betaherpesvirus 5",
    gramStain: "Not Applicable",
    shape: "Viral",
    arrangement: "Enveloped, linear dsDNA, largest human herpesvirus",
    oxygen: "Obligate Intracellular",
    pathogenic: true,
    habitat: "Human monocytes, endothelial cells, epithelial cells",
    diseases: ["Congenital CMV (leading infectious cause of birth defects)", "CMV retinitis", "CMV colitis", "CMV pneumonitis", "Mononucleosis-like syndrome"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "236 kb (linear dsDNA, largest human herpesvirus)", gcContent: "57%", genes: "~165 genes", notableGenes: ["UL97 (kinase, ganciclovir activation)", "UL54 (DNA polymerase)", "pp65 (tegument, antigenemia target)", "gB (vaccine candidate)"] },
    resistance: { intrinsic: [], acquired: ["Ganciclovir (UL97 mutations)", "Foscarnet (UL54 mutations)"], mechanism: "UL97 kinase mutations, UL54 polymerase mutations" },
    treatment: ["Ganciclovir/valganciclovir (first-line)", "Foscarnet (resistant CMV)", "Cidofovir", "Letermovir (prophylaxis in transplant)", "Maribavir (refractory)"],
    clinicalSignificance: "Most common congenital infection (SNHL leading cause). 'Owl's eye' intranuclear inclusions pathognomonic. Opportunistic in transplant and AIDS (CD4 <50).",
    labIdentification: ["CMV PCR/viral load (quantitative)", "pp65 antigenemia", "Shell vial culture (24-48h)", "'Owl's eye' inclusions on biopsy", "CMV IgM/IgG (screening)"],
    transmission: "Saliva, urine, sexual contact, blood, transplant, vertical",
    epidemiology: "50-90% adult seroprevalence. Congenital: ~1/200 newborns infected, 1/750 symptomatic. Leading infectious cause of SNHL.",
    prevention: ["Hand hygiene (pregnant women)", "CMV serology matching (transplant)", "Letermovir prophylaxis (HSCT)", "Valganciclovir prophylaxis (SOT)"],
    incubationPeriod: "4-8 weeks (acquired). Congenital: in utero",
    taxonomy: { domain: "Viruses", phylum: "Peploviricota", class: "Herviviricetes", order: "Herpesvirales", family: "Orthoherpesviridae" },
  },
  {
    id: "norovirus",
    name: "Norovirus",
    genus: "Norovirus",
    species: "Norwalk virus",
    gramStain: "Not Applicable",
    shape: "Viral",
    arrangement: "Non-enveloped, +ssRNA, icosahedral",
    oxygen: "Obligate Intracellular",
    pathogenic: true,
    habitat: "Human GI tract, contaminated food/water/surfaces",
    diseases: ["Acute gastroenteritis ('stomach flu')", "Projectile vomiting", "Watery diarrhea"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "7.6 kb (+ssRNA)", gcContent: "48%", genes: "3 ORFs", notableGenes: ["VP1 (major capsid)", "VP2 (minor capsid)", "RdRp"] },
    resistance: { intrinsic: [], acquired: [], mechanism: "N/A" },
    treatment: ["Supportive care (oral/IV rehydration)", "No antivirals", "Self-limited (24-72 hours)"],
    clinicalSignificance: "Most common cause of acute gastroenteritis worldwide. Extremely contagious (<18 viral particles). Outbreaks in cruise ships, restaurants, hospitals. Resistant to alcohol-based sanitizers.",
    labIdentification: ["RT-PCR (stool, gold standard)", "ELISA (less sensitive)", "Electron microscopy (historical)", "Cannot be cultured routinely"],
    transmission: "Fecal-oral, contaminated food/water, fomites, aerosolized vomitus. Extremely low infectious dose",
    epidemiology: "~685 million cases/year globally, ~200,000 deaths (mostly children <5 in developing countries). Winter predominance ('winter vomiting disease').",
    prevention: ["Hand washing with soap and water (alcohol ineffective)", "Bleach-based disinfection", "Food handler hygiene", "Exclude symptomatic workers 48h"],
    incubationPeriod: "12-48 hours",
    taxonomy: { domain: "Viruses", phylum: "Pisuviricota", class: "Pisoniviricetes", order: "Picornavirales", family: "Caliciviridae" },
  },
  {
    id: "rotavirus",
    name: "Rotavirus",
    genus: "Rotavirus",
    species: "Rotavirus A",
    gramStain: "Not Applicable",
    shape: "Viral",
    arrangement: "Non-enveloped, dsRNA (11 segments), triple-layered icosahedral ('wheel-like')",
    oxygen: "Obligate Intracellular",
    pathogenic: true,
    habitat: "Human intestinal epithelium",
    diseases: ["Severe watery diarrhea (children <5)", "Dehydration", "Febrile gastroenteritis"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "18.5 kb (11 segments, dsRNA)", gcContent: "34%", genes: "11 segments encoding 6 structural + 6 non-structural proteins", notableGenes: ["VP4 (P-type, attachment)", "VP7 (G-type, neutralization)", "NSP4 (viral enterotoxin)", "NSP1 (interferon antagonist)"] },
    resistance: { intrinsic: [], acquired: [], mechanism: "N/A" },
    treatment: ["Oral rehydration therapy (ORT)", "IV fluids (severe dehydration)", "Zinc supplementation", "No antivirals"],
    clinicalSignificance: "Leading cause of severe diarrhea in children <5. Before vaccine: ~500,000 deaths/year. NSP4 is first described viral enterotoxin. Segmented genome allows reassortment.",
    labIdentification: ["ELISA (stool antigen, most common)", "RT-PCR (genotyping)", "Latex agglutination", "EM ('wheel-like' particles)"],
    transmission: "Fecal-oral. Very stable in environment",
    epidemiology: "Before vaccine: virtually all children infected by age 5. Post-vaccine: >90% reduction in hospitalizations in developed countries. Still ~128,500 deaths/year (developing countries).",
    prevention: ["Rotavirus vaccine (RotaTeq 3-dose / Rotarix 2-dose, oral, live)", "Oral rehydration preparedness", "Hand hygiene"],
    incubationPeriod: "1-3 days",
    taxonomy: { domain: "Viruses", phylum: "Duplornaviricota", class: "Resentoviricetes", order: "Reovirales", family: "Sedoreoviridae" },
  },
  {
    id: "measles-virus",
    name: "Measles virus",
    genus: "Morbillivirus",
    species: "Measles morbillivirus",
    gramStain: "Not Applicable",
    shape: "Viral",
    arrangement: "Enveloped, -ssRNA, pleomorphic (helical nucleocapsid)",
    oxygen: "Obligate Intracellular",
    pathogenic: true,
    habitat: "Human respiratory epithelium, lymphocytes",
    diseases: ["Measles (rubeola)", "Pneumonia", "Encephalitis", "Subacute sclerosing panencephalitis (SSPE)"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "15.9 kb (-ssRNA)", gcContent: "48%", genes: "6 genes (N, P, M, F, H, L)", notableGenes: ["H (hemagglutinin, receptor binding)", "F (fusion protein)", "N (nucleocapsid)", "V protein (innate immune evasion)"] },
    resistance: { intrinsic: [], acquired: [], mechanism: "N/A" },
    treatment: ["Supportive care", "Vitamin A (WHO recommendation)", "Ribavirin (SSPE, limited efficacy)", "No specific antivirals"],
    clinicalSignificance: "Most contagious human pathogen (R0: 12-18). Koplik spots (pathognomonic). Maculopapular rash starts at hairline, spreads cephalocaudally. 'Immune amnesia' (deletes immune memory). SSPE years later.",
    labIdentification: ["IgM serology (diagnostic)", "RT-PCR (throat swab, urine)", "Warthin-Finkeldey giant cells (tissue)", "Viral culture (research)"],
    transmission: "Airborne (can linger 2 hours in a room). Highly contagious",
    epidemiology: "Before vaccine: 2.6 million deaths/year. Now ~128,000 deaths/year (2021). Resurgence due to vaccine hesitancy. Requires 95% vaccination for herd immunity.",
    prevention: ["MMR vaccine (live attenuated, 2 doses)", "Post-exposure prophylaxis (vaccine within 72h or IG within 6 days)", "Isolation of cases"],
    incubationPeriod: "10-14 days (rash appears ~14 days after exposure)",
    taxonomy: { domain: "Viruses", phylum: "Negarnaviricota", class: "Monjiviricetes", order: "Mononegavirales", family: "Paramyxoviridae" },
  },
  {
    id: "zika-virus",
    name: "Zika virus",
    genus: "Flavivirus",
    species: "Zika virus",
    gramStain: "Not Applicable",
    shape: "Viral",
    arrangement: "Enveloped, +ssRNA, icosahedral",
    oxygen: "Obligate Intracellular",
    pathogenic: true,
    habitat: "Aedes mosquitoes, human neural progenitor cells",
    diseases: ["Zika fever", "Congenital Zika syndrome (microcephaly)", "Guillain-Barré syndrome"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "10.8 kb (+ssRNA)", gcContent: "51%", genes: "Single polyprotein", notableGenes: ["NS5 (RdRp)", "prM-E (structural)", "NS1", "NS3 (protease/helicase)"] },
    resistance: { intrinsic: [], acquired: [], mechanism: "N/A" },
    treatment: ["Supportive care", "No specific antivirals", "Acetaminophen (avoid aspirin)"],
    clinicalSignificance: "Tropism for neural progenitor cells → microcephaly. 2015-16 epidemic in Americas. 80% asymptomatic. Unique among flaviviruses for sexual and vertical transmission.",
    labIdentification: ["RT-PCR (blood, urine within 2 weeks)", "IgM serology (cross-reacts with dengue)", "PRNT (confirmatory)", "Urine PCR more sensitive than blood"],
    transmission: "Aedes mosquito bite, sexual contact, vertical (congenital), blood transfusion",
    epidemiology: "2015-16 epidemic: >500,000 suspected cases in Americas. Now sporadic. Cross-immunity may limit future epidemics.",
    prevention: ["Mosquito avoidance", "No vaccine approved", "Sexual abstinence/condoms for travelers", "Avoid travel to endemic areas during pregnancy"],
    incubationPeriod: "3-14 days",
    taxonomy: { domain: "Viruses", phylum: "Kitrinoviricota", class: "Flasuviricetes", order: "Amarillovirales", family: "Flaviviridae" },
  },
  {
    id: "mpox-virus",
    name: "Monkeypox virus (Mpox)",
    genus: "Orthopoxvirus",
    species: "Monkeypox virus",
    gramStain: "Not Applicable",
    shape: "Viral",
    arrangement: "Enveloped, linear dsDNA, brick-shaped (largest human virus)",
    oxygen: "Obligate Intracellular",
    pathogenic: true,
    habitat: "Rodents (reservoir), primates",
    diseases: ["Mpox (monkeypox)", "Vesiculopustular rash", "Lymphadenopathy"],
    characteristics: { catalase: "Not applicable", oxidase: "Not applicable", motility: "Non-motile" },
    molecular: { genome: "197 kb (linear dsDNA)", gcContent: "33%", genes: "~190 genes", notableGenes: ["A30L (DNA packaging)", "B6R (complement control)", "CKBP (chemokine binding proteins)"] },
    resistance: { intrinsic: [], acquired: [], mechanism: "N/A" },
    treatment: ["Tecovirimat (TPOXX, first-line)", "Cidofovir/brincidofovir", "Vaccinia immune globulin", "Supportive care"],
    clinicalSignificance: "2022 global outbreak (clade IIb) primarily in MSM. Lesions in same stage (vs varicella different stages). Lymphadenopathy distinguishes from smallpox. Two clades: I (more severe) and II.",
    labIdentification: ["PCR of lesion swab (gold standard)", "EM (brick-shaped virion)", "Cell culture", "Serology (cross-reactive with other orthopoxviruses)"],
    transmission: "Close/intimate contact with lesions, respiratory droplets (prolonged), fomites",
    epidemiology: "2022: >90,000 cases in 116 countries. Endemic in West/Central Africa. Clade I outbreak in DRC (2023-24, more severe). WHO PHEIC declared.",
    prevention: ["JYNNEOS/Imvamune vaccine (modified vaccinia Ankara)", "Smallpox vaccine (ACAM2000, limited use)", "Contact tracing", "Isolation during infectious period"],
    incubationPeriod: "5-21 days (usually 6-13 days)",
    taxonomy: { domain: "Viruses", phylum: "Nucleocytoviricota", class: "Pokkesviricetes", order: "Chitovirales", family: "Poxviridae" },
  },
];
