import { LabCase } from "./types";

export const bloodBankCases: LabCase[] = [
  {
    id: "bb-001",
    title: "ABO/Rh Typing Discrepancy",
    department: "Blood Bank / Immunohematology",
    difficulty: "Intermediate",
    patientAge: 72,
    patientGender: "Male",
    clinicalPresentation: "Elective hip replacement surgery. Pre-operative type and screen ordered.",
    history: "Multiple myeloma diagnosed 1 year ago. No prior transfusions.",
    sampleType: "Blood (EDTA)",
    laboratoryFindings: [
      "Forward typing: Anti-A: 4+, Anti-B: 0, Anti-D: 4+ → Suggests A-positive",
      "Reverse typing: A1 cells: 0, B cells: 0 → No expected anti-B detected",
      "Discrepancy: Forward says type A, reverse should show anti-B but shows no reaction",
      "Serum protein electrophoresis: IgG M-spike (monoclonal gammopathy)",
      "Direct antiglobulin test (DAT): Negative",
    ],
    questions: [{
      question: "What is causing this ABO typing discrepancy?",
      options: [
        "Cold autoantibody interference",
        "Weakened or absent isoagglutinins (anti-B) due to hypogammaglobulinemia or monoclonal protein",
        "Mixed-field agglutination from recent transfusion",
        "Subgroup of A (A₂) with anti-A1",
      ],
      correctAnswer: 1,
      hint: "Multiple myeloma produces monoclonal immunoglobulin but suppresses normal antibody production.",
    }],
    explanation: "In multiple myeloma, immunoparesis (suppression of normal immunoglobulins) leads to weakened or absent ABO isoagglutinins. Forward typing is based on RBC antigens (unaffected). Reverse typing detects serum antibodies (weakened). Resolution: enhance reverse typing at room temperature, use additional A1/B cells, consider patient history. Report forward typing result with comment.",
    reference: "AABB Technical Manual, 20th Ed.",
  },
  {
    id: "bb-002",
    title: "Acute Hemolytic Transfusion Reaction",
    department: "Blood Bank / Immunohematology",
    difficulty: "Beginner",
    patientAge: 55,
    patientGender: "Female",
    clinicalPresentation: "Fever, chills, flank pain, dark urine (hemoglobinuria), and hypotension occurring 15 minutes into transfusion of packed RBCs.",
    history: "Type A-positive patient. Unit label checked reveals type B-positive RBCs were given (clerical error).",
    sampleType: "Post-transfusion blood + urine",
    laboratoryFindings: [
      "Post-transfusion DAT: Positive (mixed-field — donor and patient RBCs)",
      "Plasma: Pink (free hemoglobin — intravascular hemolysis)",
      "LDH: Markedly elevated",
      "Haptoglobin: Undetectable",
      "Urine: Hemoglobinuria (dark red-brown)",
      "Repeat ABO on pre-transfusion sample: Type A-positive (confirmed)",
      "Repeat ABO on unit segment: Type B-positive (confirmed — WRONG unit given)",
    ],
    questions: [{
      question: "What type of antibodies cause the most severe acute hemolytic transfusion reactions?",
      options: ["IgG anti-D", "IgM anti-A / anti-B (ABO antibodies)", "IgG anti-Kell", "IgG anti-Duffy"],
      correctAnswer: 1,
      hint: "These are naturally occurring IgM antibodies that activate complement fully, causing intravascular hemolysis.",
    }],
    explanation: "ABO-incompatible transfusion is the most dangerous hemolytic reaction. Anti-A and anti-B are IgM antibodies that fully activate complement → C5b-9 membrane attack complex → intravascular hemolysis → hemoglobinemia, hemoglobinuria, DIC, renal failure, shock, death. #1 cause is clerical error (wrong patient/wrong unit). Prevention: two-person verification at bedside.",
    reference: "AABB Technical Manual, 20th Ed.",
  },
  {
    id: "bb-003",
    title: "Antibody Identification (Anti-Kell)",
    department: "Blood Bank / Immunohematology",
    difficulty: "Intermediate",
    patientAge: 35,
    patientGender: "Female",
    clinicalPresentation: "Pre-transfusion testing shows positive antibody screen. History of 2 pregnancies.",
    history: "Type O-positive. No prior transfusions. Two previous pregnancies (G2P2).",
    sampleType: "Blood (serum)",
    laboratoryFindings: [
      "Antibody screen: Positive (2+ reactions at AHG phase with 2 of 3 screening cells)",
      "Panel (11-cell): Reactive with cells 2, 5, and 9 at AHG phase (37°C + anti-IgG)",
      "Rule-out analysis: All reactive cells are K-positive; all non-reactive cells are K-negative",
      "Pattern: Matches anti-K (Kell) perfectly",
      "Autocontrol: Negative (rules out autoantibody)",
      "DAT: Negative",
    ],
    questions: [{
      question: "What is the clinical significance of anti-K (Kell)?",
      options: [
        "Clinically insignificant — can be ignored",
        "Highly clinically significant — causes severe HTR and severe HDFN",
        "Only significant at cold temperatures",
        "Only causes mild HDFN",
      ],
      correctAnswer: 1,
      hint: "Kell antibodies suppress erythropoiesis in fetal bone marrow, causing severe fetal anemia.",
    }],
    explanation: "Anti-K is a clinically significant IgG antibody (reacts at 37°C/AHG). It causes: (1) Severe hemolytic transfusion reactions and (2) Severe HDFN (uniquely, anti-K suppresses fetal erythropoiesis in addition to hemolysis). Must provide K-negative, crossmatch-compatible RBCs. ~91% of population is K-negative, so finding compatible units is usually feasible.",
    reference: "AABB Technical Manual, 20th Ed.",
  },
  {
    id: "bb-004",
    title: "Hemolytic Disease of the Fetus and Newborn (Anti-D)",
    department: "Blood Bank / Immunohematology",
    difficulty: "Intermediate",
    patientAge: 30,
    patientGender: "Female",
    clinicalPresentation: "Second pregnancy, Rh-negative mother. Prenatal antibody screen positive. Fetal ultrasound shows hydrops fetalis.",
    history: "First pregnancy (Rh-positive baby) — did NOT receive RhIg postpartum.",
    sampleType: "Maternal blood + cord blood",
    laboratoryFindings: [
      "Maternal type: O Rh-negative",
      "Maternal antibody screen: Positive",
      "Antibody identification: Anti-D, titer 1:256 (critical titer usually ≥16)",
      "Father's type: A Rh-positive (heterozygous D)",
      "Cord blood type: A Rh-positive",
      "Cord blood DAT: Strongly positive (4+)",
      "Cord blood Hb: 6.0 g/dL (severely anemic)",
      "Cord blood bilirubin: 8 mg/dL (elevated at birth)",
    ],
    questions: [{
      question: "When should RhIg (RhoGAM) have been given to prevent this?",
      options: [
        "Only at delivery",
        "At 28 weeks gestation AND within 72 hours of delivery of Rh-positive baby",
        "Only during second pregnancy",
        "Only if amniocentesis is performed",
      ],
      correctAnswer: 1,
      hint: "Prophylactic passive anti-D prevents active maternal immunization against fetal D antigen.",
    }],
    explanation: "RhIg prevention: (1) 28 weeks antepartum (300 µg), (2) Within 72 hours postpartum if baby is Rh-positive. Also given after: amniocentesis, miscarriage, ectopic pregnancy, abdominal trauma. RhIg destroys fetal Rh+ cells before they sensitize the mother. Rosette test screens for large fetomaternal hemorrhage (FMH); KB (Kleihauer-Betke) test quantifies FMH for additional RhIg doses.",
    reference: "AABB Technical Manual, 20th Ed.",
  },
  {
    id: "bb-005",
    title: "Delayed Hemolytic Transfusion Reaction",
    department: "Blood Bank / Immunohematology",
    difficulty: "Advanced",
    patientAge: 40,
    patientGender: "Female",
    clinicalPresentation: "Unexplained drop in hemoglobin 7 days post-transfusion, mild jaundice, and low-grade fever. Recent surgery required 2 units RBCs.",
    history: "History of multiple transfusions and pregnancies (G3P3). Pre-transfusion antibody screen was NEGATIVE.",
    sampleType: "Blood (post-reaction)",
    laboratoryFindings: [
      "Post-transfusion DAT: Positive (IgG + C3d)",
      "New antibody identified: Anti-Jka (Kidd)",
      "Pre-transfusion sample (retested): Negative for anti-Jka (below detection threshold)",
      "LDH: Mildly elevated",
      "Haptoglobin: Low",
      "Indirect bilirubin: Mildly elevated",
      "Hb dropped from 10.5 to 8.0 g/dL without bleeding",
    ],
    questions: [{
      question: "Why was anti-Jka not detected on the pre-transfusion antibody screen?",
      options: [
        "Lab error in screening",
        "Kidd antibodies are notorious for dropping below detectable levels (evanescent) and reappearing upon re-exposure (anamnestic response)",
        "Jka antigen is not on screening cells",
        "Anti-Jka only reacts at cold temperatures",
      ],
      correctAnswer: 1,
      hint: "Kidd system antibodies are called 'tricky' because they disappear and cause delayed reactions.",
    }],
    explanation: "Kidd antibodies (anti-Jka, anti-Jkb) are notorious for: (1) Evanescence — titer drops below detection, (2) Anamnestic response — re-exposure boosts antibody rapidly (3–7 days), (3) Complement activation → delayed hemolytic transfusion reaction. They show dosage effect (stronger with homozygous cells). Always suspect Kidd in unexplained post-transfusion Hb drop.",
    reference: "AABB Technical Manual, 20th Ed.",
  },
  {
    id: "bb-006",
    title: "Massive Transfusion Protocol",
    department: "Blood Bank / Immunohematology",
    difficulty: "Intermediate",
    patientAge: 28,
    patientGender: "Male",
    clinicalPresentation: "Trauma patient with hemorrhagic shock (BP 60/40, HR 140) after motor vehicle accident. Estimated blood loss >3 liters.",
    history: "No medical history. Unknown blood type at presentation.",
    sampleType: "Emergency release blood",
    laboratoryFindings: [
      "Type & screen: Pending (no time to wait)",
      "Emergency release: O Rh-negative uncrossmatched RBCs issued",
      "After 6 units RBCs: Labs show PT 25 sec, aPTT 60 sec, fibrinogen 80 mg/dL, platelets 45,000",
      "Massive transfusion protocol activated: 1:1:1 ratio (RBC:FFP:platelets)",
      "Thromboelastography (TEG): Shows fibrinolysis and factor depletion",
    ],
    questions: [{
      question: "What blood type is given as emergency release when patient type is unknown?",
      options: ["Type A Rh-positive", "Type O Rh-negative", "Type AB Rh-positive", "Type B Rh-negative"],
      correctAnswer: 1,
      hint: "Universal donor for RBCs: no A, B, or D antigens to react with recipient antibodies.",
    }],
    explanation: "Emergency release: O Rh-negative RBCs (universal donor — no ABO/D antigens). For women of childbearing age, must be Rh-negative to prevent anti-D sensitization. Males >50 can receive O Rh-positive if Rh-neg units are scarce. Massive transfusion (>10 units/24h): dilutional coagulopathy → 1:1:1 balanced resuscitation (RBC:FFP:platelets). Monitor with viscoelastic testing (TEG/ROTEM).",
    reference: "AABB Technical Manual, 20th Ed.",
  },
  {
    id: "bb-007",
    title: "Transfusion-Related Acute Lung Injury (TRALI)",
    department: "Blood Bank / Immunohematology",
    difficulty: "Advanced",
    patientAge: 60,
    patientGender: "Male",
    clinicalPresentation: "Acute respiratory distress, hypoxemia (SpO₂ 82%), bilateral pulmonary infiltrates on CXR, and fever within 2 hours of FFP transfusion.",
    history: "Received 2 units FFP for coagulopathy before liver biopsy. No prior cardiac history.",
    sampleType: "Donor and recipient blood",
    laboratoryFindings: [
      "CXR: Bilateral white-out (non-cardiogenic pulmonary edema)",
      "BNP: Normal (excludes cardiogenic pulmonary edema/TACO)",
      "CVP/PCWP: Normal (non-volume overload)",
      "Donor investigation: Multiparous female donor with anti-HLA Class I antibodies",
      "Recipient HLA typing: Positive for corresponding HLA antigens",
      "Neutrophil priming assay: Positive",
    ],
    questions: [{
      question: "What differentiates TRALI from TACO (transfusion-associated circulatory overload)?",
      options: [
        "TRALI has elevated BNP; TACO has normal BNP",
        "TRALI has normal BNP/CVP (non-cardiogenic); TACO has elevated BNP/CVP (volume overload)",
        "TRALI occurs after 24 hours; TACO within 1 hour",
        "TACO causes fever; TRALI does not",
      ],
      correctAnswer: 1,
      hint: "TRALI is immune-mediated lung injury; TACO is volume overload.",
    }],
    explanation: "TRALI: donor anti-HLA or anti-HNA antibodies activate recipient neutrophils → pulmonary capillary leak → non-cardiogenic pulmonary edema within 6 hours of transfusion. BNP/CVP normal (vs. TACO: elevated BNP, jugular distension, response to diuretics). Prevention: use male-only plasma donors (multiparous females carry anti-HLA from pregnancies). Treatment: supportive (O₂, ventilation). No diuretics (not volume overload).",
    reference: "AABB Technical Manual, 20th Ed.",
  },
  {
    id: "bb-008",
    title: "Cold Agglutinin Disease",
    department: "Blood Bank / Immunohematology",
    difficulty: "Advanced",
    patientAge: 68,
    patientGender: "Female",
    clinicalPresentation: "Acrocyanosis (blue fingers/toes in cold), Raynaud's phenomenon, mild jaundice, and fatigue.",
    history: "Symptoms worsen in winter. Labs show unexplained macrocytosis and autoagglutination.",
    sampleType: "Blood (EDTA, kept warm at 37°C)",
    laboratoryFindings: [
      "CBC (room temp): Hb 9.5 g/dL, MCV falsely elevated >120 fL (RBC clumping artifact)",
      "CBC (37°C prewarmed): Hb 9.5, MCV 92 fL (true value)",
      "ABO typing: Discrepancy — forward and reverse don't match at room temperature",
      "Resolved by prewarming: ABO typing resolves to Group A, Rh-positive",
      "DAT: Positive — C3d only (no IgG)",
      "Cold agglutinin titer: 1:2048 (pathological, normally <1:64)",
      "Thermal amplitude: Reacts up to 30°C",
    ],
    questions: [{
      question: "What class of antibody causes cold agglutinin disease?",
      options: ["IgG", "IgM", "IgA", "IgE"],
      correctAnswer: 1,
      hint: "This pentameric antibody is the most efficient complement activator and agglutinates RBCs in the cold.",
    }],
    explanation: "Cold agglutinin disease: IgM autoantibody (usually anti-I specificity) binds RBCs at <37°C → activates complement (C3b deposition). DAT positive for C3d only (IgM dissociates at 37°C during wash). Causes ABO discrepancies and false MCV elevation at room temperature. Prewarm all testing. If transfusion needed: use blood warmer. Associated with Mycoplasma pneumoniae or lymphoma.",
    reference: "AABB Technical Manual, 20th Ed.",
  },
  {
    id: "bb-009",
    title: "Neonatal Alloimmune Thrombocytopenia (NAIT)",
    department: "Blood Bank / Immunohematology",
    difficulty: "Advanced",
    patientAge: 0,
    patientGender: "Neonate",
    clinicalPresentation: "Full-term neonate born with severe thrombocytopenia (platelets 8,000/µL), petechiae, and intracranial hemorrhage on head ultrasound.",
    history: "First pregnancy. Mother's platelet count is normal. No gestational complications.",
    sampleType: "Maternal and neonatal blood",
    laboratoryFindings: [
      "Neonatal platelet count: 8,000/µL (critical)",
      "Maternal platelet count: 250,000/µL (normal)",
      "Neonatal HPA genotyping: HPA-1a positive",
      "Maternal HPA genotyping: HPA-1a negative (HPA-1b/1b homozygous)",
      "Maternal serum: Anti-HPA-1a antibodies detected (MAIPA assay)",
      "Paternal genotyping: HPA-1a/1b heterozygous",
    ],
    questions: [{
      question: "NAIT is analogous to which condition involving red blood cells?",
      options: [
        "Autoimmune hemolytic anemia",
        "Hemolytic disease of the fetus and newborn (HDFN)",
        "ITP",
        "TTP",
      ],
      correctAnswer: 1,
      hint: "Mother forms IgG antibodies against fetal platelet antigens — the platelet equivalent of Rh disease.",
    }],
    explanation: "NAIT: maternal IgG anti-HPA antibodies (most commonly anti-HPA-1a) cross placenta and destroy fetal platelets. Platelet equivalent of HDFN. Unlike HDFN, can occur in FIRST pregnancy (~50% of cases). HPA-1a is the most common antigen (~2% of Caucasians are HPA-1a negative). Treatment: IVIG + HPA-1a negative (washed maternal) platelets. Risk of intracranial hemorrhage.",
    reference: "AABB Technical Manual, 20th Ed.",
  },
  {
    id: "bb-010",
    title: "Febrile Non-Hemolytic Transfusion Reaction (FNHTR)",
    department: "Blood Bank / Immunohematology",
    difficulty: "Beginner",
    patientAge: 50,
    patientGender: "Male",
    clinicalPresentation: "Temperature rise from 37°C to 38.8°C (≥1°C increase) and chills 30 minutes into RBC transfusion. No hypotension, hemoglobinuria, or respiratory distress.",
    history: "Multiple prior transfusions for myelodysplastic syndrome. No hemolytic history.",
    sampleType: "Blood (post-reaction workup)",
    laboratoryFindings: [
      "Post-transfusion DAT: Negative",
      "Visual check of plasma/serum: Clear (no hemolysis)",
      "Post-transfusion Hb: Appropriate rise (transfusion effective)",
      "Clerical check: Confirmed — correct unit given to correct patient",
      "Gram stain of unit: Negative (rules out bacterial contamination)",
    ],
    questions: [{
      question: "What is the most common cause of FNHTR?",
      options: [
        "ABO incompatibility",
        "Cytokines released from donor WBCs during storage, or recipient antibodies against donor WBC HLA antigens",
        "Bacterial contamination",
        "IgA deficiency with anti-IgA",
      ],
      correctAnswer: 1,
      hint: "This reaction involves white blood cells and cytokines, not red cell antigens.",
    }],
    explanation: "FNHTR is the most common transfusion reaction. Caused by: (1) Recipient anti-HLA antibodies reacting with donor WBCs, (2) Cytokines (IL-1, IL-6, TNF-α) accumulated in stored blood products from donor WBCs. Prevention: prestorage leukoreduction (removes >99.9% of WBCs). Management: stop transfusion, rule out hemolytic reaction and sepsis, give antipyretics.",
    reference: "AABB Technical Manual, 20th Ed.",
  },
];
