import { LabCase } from "./types";

export const chemistryCases: LabCase[] = [
  {
    id: "chem-001",
    title: "Diabetic Ketoacidosis (DKA)",
    department: "Clinical Chemistry",
    difficulty: "Beginner",
    patientAge: 22,
    patientGender: "Male",
    clinicalPresentation: "Polyuria, polydipsia, weight loss, nausea/vomiting, abdominal pain, and fruity breath odor. Kussmaul respiration.",
    history: "Type 1 diabetes, stopped insulin 3 days ago due to illness.",
    sampleType: "Blood (serum + arterial)",
    laboratoryFindings: [
      "Blood glucose: 450 mg/dL (critically high)",
      "ABG: pH 7.15 (acidosis), pCO₂ 18 mmHg (compensatory), HCO₃⁻ 8 mEq/L (low)",
      "Serum ketones (β-hydroxybutyrate): 6.5 mmol/L (elevated)",
      "Anion gap: 28 mEq/L (elevated, normal: 8–12)",
      "Serum Na⁺: 130 mEq/L (pseudohyponatremia), K⁺: 5.8 mEq/L (may be high despite total body depletion)",
      "BUN: 35 mg/dL, Creatinine: 1.8 mg/dL (prerenal)",
      "Serum osmolality: 320 mOsm/kg (elevated)",
    ],
    questions: [{
      question: "What is the primary acid-base disturbance in DKA?",
      options: ["Metabolic alkalosis", "High anion gap metabolic acidosis", "Respiratory acidosis", "Normal anion gap metabolic acidosis"],
      correctAnswer: 1,
      hint: "Ketoacids (β-hydroxybutyrate, acetoacetate) are unmeasured anions that increase the anion gap.",
    }],
    explanation: "DKA = insulin deficiency → lipolysis → hepatic ketogenesis → accumulation of β-hydroxybutyrate and acetoacetate → high anion gap metabolic acidosis. Anion gap = Na − (Cl + HCO₃). Kussmaul respiration is respiratory compensation (↓pCO₂). K⁺ may be elevated from acidosis-driven shift despite total body potassium depletion.",
    reference: "Tietz Textbook of Clinical Chemistry and Molecular Diagnostics, 7th Ed.",
  },
  {
    id: "chem-002",
    title: "Acute Myocardial Infarction",
    department: "Clinical Chemistry",
    difficulty: "Beginner",
    patientAge: 58,
    patientGender: "Male",
    clinicalPresentation: "Crushing substernal chest pain radiating to left arm, diaphoresis, nausea, and shortness of breath for 2 hours.",
    history: "Hypertension, dyslipidemia, smoker (20 pack-years). Family history of premature CAD.",
    sampleType: "Blood (serum)",
    laboratoryFindings: [
      "Troponin I (0h): 0.8 ng/mL (elevated, normal: <0.04)",
      "Troponin I (3h): 15.2 ng/mL (markedly elevated, rising pattern)",
      "CK-MB: 45 U/L (elevated, normal: <25)",
      "CK-MB index: 8% (>5% suggests cardiac source)",
      "Myoglobin: Elevated (early, non-specific)",
      "ECG: ST-elevation in leads II, III, aVF (inferior STEMI)",
      "BNP: 350 pg/mL (elevated — cardiac stress)",
    ],
    questions: [{
      question: "Which biomarker is the gold standard for diagnosing acute MI?",
      options: ["CK-MB", "Cardiac troponin (I or T)", "Myoglobin", "LDH"],
      correctAnswer: 1,
      hint: "This biomarker is highly sensitive and specific for myocardial injury and remains elevated for 7–14 days.",
    }],
    explanation: "Cardiac troponin (cTnI or cTnT) is the gold standard for MI diagnosis: highly sensitive and specific for myocardial necrosis. Rises 3–6 hours after onset, peaks at 12–24 hours, remains elevated 7–14 days. Serial testing (0h and 3h) showing rise/fall pattern confirms acute MI. CK-MB is useful for reinfarction detection (shorter window). Myoglobin is earliest but non-specific.",
    reference: "Tietz Textbook of Clinical Chemistry and Molecular Diagnostics, 7th Ed.",
  },
  {
    id: "chem-003",
    title: "Acute Pancreatitis",
    department: "Clinical Chemistry",
    difficulty: "Beginner",
    patientAge: 48,
    patientGender: "Female",
    clinicalPresentation: "Severe epigastric pain radiating to back, nausea, vomiting, and tenderness. Pain worse after eating.",
    history: "History of gallstones. Moderate alcohol use.",
    sampleType: "Blood (serum)",
    laboratoryFindings: [
      "Serum amylase: 1200 U/L (>3× ULN, normal: 30–110)",
      "Serum lipase: 2500 U/L (>3× ULN, normal: 0–160)",
      "ALT: 180 U/L (elevated — suggests biliary etiology)",
      "Total bilirubin: 3.5 mg/dL (elevated)",
      "Calcium: 7.2 mg/dL (low — poor prognostic sign, Ranson criteria)",
      "Triglycerides: Normal (excluding hypertriglyceridemia as cause)",
    ],
    questions: [{
      question: "Which enzyme is more specific for pancreatitis than amylase?",
      options: ["ALT", "Lipase", "GGT", "Alkaline phosphatase"],
      correctAnswer: 1,
      hint: "This enzyme is produced almost exclusively by the pancreas and stays elevated longer.",
    }],
    explanation: "Lipase is more specific for pancreatitis than amylase because: (1) it's primarily of pancreatic origin (amylase has salivary sources), (2) it stays elevated longer (8–14 days vs. 3–5 days for amylase), (3) it doesn't rise in non-pancreatic conditions that elevate amylase (parotitis, macroamylasemia). Diagnosis: ≥2 of 3 criteria (characteristic pain, lipase/amylase ≥3× ULN, imaging findings).",
    reference: "Tietz Textbook of Clinical Chemistry and Molecular Diagnostics, 7th Ed.",
  },
  {
    id: "chem-004",
    title: "Hepatitis and Liver Function",
    department: "Clinical Chemistry",
    difficulty: "Intermediate",
    patientAge: 35,
    patientGender: "Male",
    clinicalPresentation: "Jaundice, dark urine, clay-colored stools, fatigue, and right upper quadrant tenderness for 5 days.",
    history: "IV drug use history. No known hepatitis vaccination.",
    sampleType: "Blood (serum)",
    laboratoryFindings: [
      "Total bilirubin: 8.5 mg/dL (elevated)",
      "Direct (conjugated) bilirubin: 6.2 mg/dL (elevated)",
      "ALT: 1850 U/L (markedly elevated)",
      "AST: 1200 U/L (markedly elevated)",
      "ALP: 180 U/L (mildly elevated)",
      "Albumin: 3.0 g/dL (low)",
      "PT/INR: 1.8 (prolonged — synthetic dysfunction)",
      "Hepatitis B surface antigen (HBsAg): Positive",
      "Anti-HBc IgM: Positive",
      "HBeAg: Positive",
    ],
    questions: [{
      question: "What hepatitis B serological pattern indicates acute infection?",
      options: [
        "HBsAg+, Anti-HBc IgG+, Anti-HBs−",
        "HBsAg+, Anti-HBc IgM+, HBeAg+",
        "HBsAg−, Anti-HBc IgG+, Anti-HBs+",
        "HBsAg−, Anti-HBs+, Anti-HBc−",
      ],
      correctAnswer: 1,
      hint: "IgM anti-HBc is the hallmark of acute HBV infection.",
    }],
    explanation: "Acute HBV: HBsAg+ (active virus), Anti-HBc IgM+ (acute phase marker), HBeAg+ (high replication/infectivity). ALT/AST markedly elevated (hepatocellular pattern: ALT>AST). Chronic HBV: HBsAg+, Anti-HBc IgG+ (IgM negative). Resolved: HBsAg−, Anti-HBs+, Anti-HBc IgG+. Vaccine immunity: only Anti-HBs+.",
    reference: "Tietz Textbook of Clinical Chemistry and Molecular Diagnostics, 7th Ed.",
  },
  {
    id: "chem-005",
    title: "Hypothyroidism",
    department: "Clinical Chemistry",
    difficulty: "Beginner",
    patientAge: 42,
    patientGender: "Female",
    clinicalPresentation: "Weight gain, fatigue, cold intolerance, constipation, dry skin, hair loss, and bradycardia.",
    history: "Family history of autoimmune disease. Gradual onset over 6 months.",
    sampleType: "Blood (serum)",
    laboratoryFindings: [
      "TSH: 45 mIU/L (markedly elevated, normal: 0.4–4.0)",
      "Free T4: 0.3 ng/dL (low, normal: 0.8–1.8)",
      "Free T3: Low",
      "Anti-TPO antibodies: Positive (>600 IU/mL)",
      "Anti-thyroglobulin antibodies: Positive",
      "Total cholesterol: 280 mg/dL (elevated — thyroid affects lipid metabolism)",
    ],
    questions: [{
      question: "What pattern indicates primary hypothyroidism?",
      options: ["Low TSH, low FT4", "High TSH, low FT4", "High TSH, high FT4", "Low TSH, high FT4"],
      correctAnswer: 1,
      hint: "When the thyroid gland fails, the pituitary increases TSH output as negative feedback is lost.",
    }],
    explanation: "Primary hypothyroidism: thyroid gland failure → ↓T4/T3 → loss of negative feedback → ↑TSH. Most common cause: Hashimoto's thyroiditis (anti-TPO antibodies). Secondary hypothyroidism (pituitary failure): ↓TSH, ↓FT4. TSH is the best single screening test for thyroid dysfunction. Hypothyroidism also causes hyperlipidemia.",
    reference: "Tietz Textbook of Clinical Chemistry and Molecular Diagnostics, 7th Ed.",
  },
  {
    id: "chem-006",
    title: "Chronic Kidney Disease (CKD)",
    department: "Clinical Chemistry",
    difficulty: "Intermediate",
    patientAge: 62,
    patientGender: "Male",
    clinicalPresentation: "Fatigue, nocturia, peripheral edema, and pruritus. Found to have hypertension and proteinuria.",
    history: "Type 2 diabetes for 15 years, poorly controlled (HbA1c 9.5%). Hypertension.",
    sampleType: "Blood + urine",
    laboratoryFindings: [
      "Serum creatinine: 4.2 mg/dL (elevated)",
      "BUN: 65 mg/dL (elevated)",
      "eGFR: 15 mL/min/1.73m² (CKD Stage 5)",
      "Urine albumin/creatinine ratio (ACR): 450 mg/g (severely elevated)",
      "Calcium: 7.8 mg/dL (low)",
      "Phosphorus: 7.5 mg/dL (high)",
      "PTH: 350 pg/mL (elevated — secondary hyperparathyroidism)",
      "Hb: 9.0 g/dL (anemia of CKD — ↓erythropoietin)",
      "Potassium: 5.8 mEq/L (elevated)",
    ],
    questions: [{
      question: "What causes the calcium/phosphorus abnormality in CKD?",
      options: [
        "Excess vitamin D production",
        "Decreased renal phosphorus excretion → hyperphosphatemia → drives calcium down → secondary hyperparathyroidism",
        "Primary hyperparathyroidism",
        "Excess calcium absorption from gut",
      ],
      correctAnswer: 1,
      hint: "Failing kidneys cannot excrete phosphorus or convert vitamin D to its active form.",
    }],
    explanation: "CKD → ↓phosphorus excretion → hyperphosphatemia → binds calcium → hypocalcemia. Also, ↓1,25(OH)₂D₃ production (kidneys can't hydroxylate 25-OH vitamin D) → ↓Ca absorption. Both stimulate PTH → secondary hyperparathyroidism → renal osteodystrophy. eGFR <15 = Stage 5 (dialysis indicated). Anemia from ↓EPO production.",
    reference: "Tietz Textbook of Clinical Chemistry and Molecular Diagnostics, 7th Ed.",
  },
  {
    id: "chem-007",
    title: "Westgard QC Rule Violation",
    department: "Clinical Chemistry",
    difficulty: "Intermediate",
    patientAge: 0,
    patientGender: "Male",
    clinicalPresentation: "Morning QC results for glucose analyzer show both Level 1 and Level 2 controls on the same side of the mean, with one exceeding 2 SD.",
    history: "Daily Levey-Jennings QC monitoring. No recent calibration or reagent lot change.",
    sampleType: "QC material (Level 1 and Level 2)",
    laboratoryFindings: [
      "Level 1 QC (normal): Mean = 100 mg/dL, SD = 3. Today's value: 108 mg/dL (+2.67 SD)",
      "Level 2 QC (abnormal): Mean = 250 mg/dL, SD = 6. Today's value: 263 mg/dL (+2.17 SD)",
      "Both values exceed +2 SD on the same side of the mean",
      "Previous 5 days: All QC values within ±1 SD",
    ],
    questions: [{
      question: "Which Westgard rule is violated when both QC levels exceed ±2 SD on the same side?",
      options: ["1₂s (warning)", "2₂s (systematic error)", "R₄s (random error)", "1₃s (rejection)"],
      correctAnswer: 1,
      hint: "Two consecutive QC values exceeding 2 SD in the same direction indicates a systematic problem.",
    }],
    explanation: "The 2₂s rule: two consecutive QC measurements exceed ±2 SD on the same side of the mean → systematic error (bias/shift). This triggers rejection of patient results and investigation (calibration drift, reagent deterioration, temperature change). The 1₂s rule is a warning only. R₄s (range of 4 SD between two QC levels) indicates random error.",
    reference: "Tietz Textbook of Clinical Chemistry, 7th Ed.; Westgard JO, Basic QC Practices.",
  },
  {
    id: "chem-008",
    title: "Primary Hyperparathyroidism",
    department: "Clinical Chemistry",
    difficulty: "Intermediate",
    patientAge: 55,
    patientGender: "Female",
    clinicalPresentation: "Recurrent kidney stones, bone pain, abdominal pain, fatigue, and depression. 'Stones, bones, groans, and moans.'",
    history: "Incidental hypercalcemia found on routine labs. Postmenopausal.",
    sampleType: "Blood (serum) + 24-hour urine",
    laboratoryFindings: [
      "Total calcium: 12.2 mg/dL (elevated, normal: 8.5–10.5)",
      "Ionized calcium: 1.55 mmol/L (elevated)",
      "Phosphorus: 2.0 mg/dL (low)",
      "PTH (intact): 180 pg/mL (elevated, normal: 15–65)",
      "ALP: Elevated (bone turnover)",
      "24-hour urine calcium: Elevated (>250 mg/day)",
      "Vitamin D, 25-OH: Normal",
    ],
    questions: [{
      question: "What calcium and PTH pattern indicates primary hyperparathyroidism?",
      options: [
        "↑Calcium, ↓PTH",
        "↑Calcium, ↑PTH",
        "↓Calcium, ↑PTH",
        "Normal calcium, ↑PTH",
      ],
      correctAnswer: 1,
      hint: "Normally, high calcium suppresses PTH. If PTH remains high despite high calcium, it's autonomous.",
    }],
    explanation: "Primary hyperparathyroidism: autonomous PTH secretion (usually parathyroid adenoma ~85%) → ↑calcium, ↓phosphorus, ↑ALP. PTH is inappropriately elevated despite hypercalcemia. In secondary hyperparathyroidism (e.g., CKD), calcium is low/normal with high PTH. Malignancy-related hypercalcemia: ↑calcium, ↓PTH (PTHrP mediated).",
    reference: "Tietz Textbook of Clinical Chemistry and Molecular Diagnostics, 7th Ed.",
  },
  {
    id: "chem-009",
    title: "Adrenal Insufficiency (Addison's Disease)",
    department: "Clinical Chemistry",
    difficulty: "Advanced",
    patientAge: 38,
    patientGender: "Female",
    clinicalPresentation: "Fatigue, weight loss, hyperpigmentation (skin folds, buccal mucosa), hypotension, and salt craving.",
    history: "Autoimmune thyroid disease (Hashimoto's). Symptoms worsened during recent flu.",
    sampleType: "Blood (serum)",
    laboratoryFindings: [
      "Morning cortisol: 2.5 µg/dL (low, normal: 6–23)",
      "ACTH: 250 pg/mL (markedly elevated, normal: 10–60)",
      "ACTH stimulation test: Cortisol fails to rise (peak <18 µg/dL)",
      "Sodium: 128 mEq/L (hyponatremia — ↓aldosterone)",
      "Potassium: 5.9 mEq/L (hyperkalemia — ↓aldosterone)",
      "Glucose: 55 mg/dL (hypoglycemia — ↓cortisol)",
      "Anti-21-hydroxylase antibodies: Positive",
    ],
    questions: [{
      question: "What distinguishes primary from secondary adrenal insufficiency?",
      options: [
        "Low cortisol in both; ACTH is HIGH in primary and LOW in secondary",
        "Low cortisol in both; ACTH is LOW in primary and HIGH in secondary",
        "High cortisol with low ACTH",
        "Normal cortisol with elevated ACTH",
      ],
      correctAnswer: 0,
      hint: "When adrenal glands fail (primary), the pituitary overproduces ACTH trying to stimulate them.",
    }],
    explanation: "Primary adrenal insufficiency (Addison's): adrenal destruction → ↓cortisol + ↓aldosterone → ↑ACTH (feedback). ACTH excess → hyperpigmentation (ACTH shares POMC precursor with MSH). Electrolyte pattern: hyponatremia + hyperkalemia (from ↓aldosterone). Secondary (pituitary failure): ↓ACTH → ↓cortisol, but aldosterone is preserved (RAAS-regulated), so no hyperkalemia.",
    reference: "Tietz Textbook of Clinical Chemistry and Molecular Diagnostics, 7th Ed.",
  },
  {
    id: "chem-010",
    title: "Tumor Lysis Syndrome",
    department: "Clinical Chemistry",
    difficulty: "Advanced",
    patientAge: 15,
    patientGender: "Male",
    clinicalPresentation: "Nausea, vomiting, muscle cramps, cardiac arrhythmia, and oliguria 48 hours after starting chemotherapy.",
    history: "Burkitt lymphoma with high tumor burden. Started aggressive chemotherapy.",
    sampleType: "Blood (serum)",
    laboratoryFindings: [
      "Potassium: 7.2 mEq/L (critically high → arrhythmia risk)",
      "Phosphorus: 9.5 mg/dL (critically high)",
      "Calcium: 6.5 mg/dL (critically low — bound by phosphorus)",
      "Uric acid: 15 mg/dL (markedly elevated)",
      "LDH: 2500 U/L (massive cell lysis)",
      "Creatinine: 3.5 mg/dL (acute kidney injury — uric acid crystal deposition)",
      "ECG: Peaked T waves, widened QRS (hyperkalemia)",
    ],
    questions: [{
      question: "What electrolyte pattern is pathognomonic for tumor lysis syndrome?",
      options: [
        "↑K⁺, ↑PO₄, ↓Ca²⁺, ↑uric acid",
        "↓K⁺, ↓PO₄, ↑Ca²⁺, ↓uric acid",
        "↑K⁺, ↓PO₄, ↑Ca²⁺, ↑uric acid",
        "↓K⁺, ↑PO₄, ↓Ca²⁺, ↓uric acid",
      ],
      correctAnswer: 0,
      hint: "Massive cell death releases intracellular contents: K⁺, PO₄, and nucleic acids (→ uric acid).",
    }],
    explanation: "TLS: rapid cell lysis releases intracellular contents: ↑K⁺ (most dangerous — arrhythmia), ↑PO₄ (binds calcium → ↓Ca²⁺ → seizures/tetany), ↑uric acid (nucleic acid degradation → crystal nephropathy → AKI). Prevention: hydration + rasburicase (converts uric acid to allantoin) or allopurinol. ECG monitoring mandatory.",
    reference: "Tietz Textbook of Clinical Chemistry and Molecular Diagnostics, 7th Ed.",
  },
  {
    id: "chem-011",
    title: "Metabolic Syndrome and Lipid Panel",
    department: "Clinical Chemistry",
    difficulty: "Beginner",
    patientAge: 50,
    patientGender: "Male",
    clinicalPresentation: "Obesity (BMI 34), waist circumference 110 cm, hypertension (145/92 mmHg), and acanthosis nigricans.",
    history: "Sedentary lifestyle. Family history of diabetes and cardiovascular disease.",
    sampleType: "Fasting blood (serum)",
    laboratoryFindings: [
      "Fasting glucose: 128 mg/dL (impaired, normal: <100)",
      "HbA1c: 6.8% (diabetes threshold ≥6.5%)",
      "Total cholesterol: 260 mg/dL (high)",
      "LDL-C: 165 mg/dL (high)",
      "HDL-C: 32 mg/dL (low, normal: >40 for males)",
      "Triglycerides: 320 mg/dL (high, normal: <150)",
      "Fasting insulin: 35 µIU/mL (elevated — insulin resistance)",
    ],
    questions: [{
      question: "Which lipid abnormality pattern is most characteristic of metabolic syndrome?",
      options: [
        "Isolated high LDL",
        "High triglycerides + low HDL",
        "Isolated low HDL",
        "High total cholesterol only",
      ],
      correctAnswer: 1,
      hint: "Insulin resistance drives hepatic VLDL overproduction (↑TG) and accelerates HDL catabolism (↓HDL).",
    }],
    explanation: "Metabolic syndrome dyslipidemia: ↑triglycerides + ↓HDL-C (atherogenic dyslipidemia). Insulin resistance → ↑hepatic VLDL production → ↑TG → small dense LDL (more atherogenic) + ↓HDL. The Friedewald equation (LDL = TC − HDL − TG/5) is unreliable when TG >400 mg/dL. Metabolic syndrome requires ≥3 of 5 criteria (waist, TG, HDL, BP, fasting glucose).",
    reference: "Tietz Textbook of Clinical Chemistry and Molecular Diagnostics, 7th Ed.",
  },
  {
    id: "chem-012",
    title: "Hemolysis Interference in Lab Results",
    department: "Clinical Chemistry",
    difficulty: "Intermediate",
    patientAge: 55,
    patientGender: "Female",
    clinicalPresentation: "Routine blood work results flagged as hemolyzed. Potassium reported as 6.8 mEq/L but patient is asymptomatic with normal ECG.",
    history: "Difficult venipuncture with small-gauge needle. Multiple attempts.",
    sampleType: "Hemolyzed serum specimen",
    laboratoryFindings: [
      "Hemolysis index: 3+ (grossly hemolyzed, pink-red serum)",
      "Potassium: 6.8 mEq/L (falsely elevated)",
      "LDH: 850 U/L (falsely elevated — released from RBCs)",
      "AST: 120 U/L (falsely elevated — released from RBCs)",
      "Total bilirubin: May be affected",
      "Repeat draw (non-hemolyzed): K⁺ 4.2, LDH 180, AST 25 — all normal",
    ],
    questions: [{
      question: "Which analyte is most significantly affected by in vitro hemolysis?",
      options: ["Sodium", "Potassium", "Chloride", "BUN"],
      correctAnswer: 1,
      hint: "RBCs contain 23× more of this electrolyte than plasma.",
    }],
    explanation: "In vitro hemolysis falsely elevates K⁺ (intracellular [K⁺] ≈150 mEq/L vs. plasma 4 mEq/L), LDH, AST, magnesium, phosphorus, and iron. It falsely decreases haptoglobin. Causes: traumatic venipuncture, small-gauge needles, vigorous mixing, pneumatic tube transport. Always check hemolysis index before reporting critical values. Recollect when hemolyzed.",
    reference: "Tietz Textbook of Clinical Chemistry and Molecular Diagnostics, 7th Ed.",
  },
  {
    id: "chem-013",
    title: "Obstructive Jaundice (Cholestatic Pattern)",
    department: "Clinical Chemistry",
    difficulty: "Intermediate",
    patientAge: 65,
    patientGender: "Female",
    clinicalPresentation: "Progressive painless jaundice, pruritus, dark urine, clay-colored stools, and weight loss.",
    history: "No alcohol use. CT shows pancreatic head mass.",
    sampleType: "Blood (serum)",
    laboratoryFindings: [
      "Total bilirubin: 15 mg/dL (markedly elevated)",
      "Direct (conjugated) bilirubin: 12.5 mg/dL (predominantly direct)",
      "ALP: 650 U/L (markedly elevated — cholestatic pattern)",
      "GGT: 450 U/L (elevated — confirms hepatobiliary source of ALP)",
      "ALT: 85 U/L (mildly elevated)",
      "AST: 70 U/L (mildly elevated)",
      "Urine bilirubin: Positive (conjugated bilirubin is water-soluble)",
      "Urine urobilinogen: Absent (no bilirubin reaching gut)",
    ],
    questions: [{
      question: "What liver enzyme pattern indicates obstructive (cholestatic) jaundice?",
      options: [
        "ALT/AST markedly elevated, ALP mildly elevated",
        "ALP/GGT markedly elevated, ALT/AST mildly elevated",
        "All enzymes normal with elevated bilirubin",
        "ALT markedly elevated with normal ALP",
      ],
      correctAnswer: 1,
      hint: "ALP and GGT are markers of biliary obstruction, while ALT/AST reflect hepatocellular damage.",
    }],
    explanation: "Cholestatic pattern: ↑↑ALP + ↑GGT + predominantly ↑direct bilirubin + mild ↑ALT/AST. GGT confirms hepatobiliary source of ALP (vs. bone). Urine bilirubin positive (conjugated bilirubin is water-soluble), urine urobilinogen absent (bile can't reach intestine). Hepatocellular pattern: ↑↑ALT/AST + mild ↑ALP + ↑indirect bilirubin.",
    reference: "Tietz Textbook of Clinical Chemistry and Molecular Diagnostics, 7th Ed.",
  },
  {
    id: "chem-014",
    title: "Cushing Syndrome",
    department: "Clinical Chemistry",
    difficulty: "Advanced",
    patientAge: 40,
    patientGender: "Female",
    clinicalPresentation: "Moon face, buffalo hump, central obesity, purple striae, easy bruising, proximal muscle weakness, and hypertension.",
    history: "Irregular menstrual periods, depression, osteoporosis at young age.",
    sampleType: "Blood + 24-hour urine + saliva",
    laboratoryFindings: [
      "24-hour urine free cortisol: 380 µg/day (>4× ULN, normal: <50)",
      "Late-night salivary cortisol: Elevated (loss of diurnal rhythm)",
      "Low-dose dexamethasone suppression test (1 mg overnight): Cortisol 12 µg/dL (no suppression, normal: <1.8)",
      "ACTH: 85 pg/mL (elevated — ACTH-dependent)",
      "High-dose dexamethasone suppression test: >50% suppression",
      "Pituitary MRI: 8 mm microadenoma",
      "Fasting glucose: 185 mg/dL (secondary diabetes)",
    ],
    questions: [{
      question: "What does ACTH level tell you about the source of Cushing syndrome?",
      options: [
        "High ACTH = adrenal tumor",
        "High ACTH = ACTH-dependent (pituitary or ectopic source)",
        "Low ACTH = pituitary adenoma",
        "ACTH level is not useful in evaluation",
      ],
      correctAnswer: 1,
      hint: "ACTH-dependent sources produce cortisol excess through ACTH stimulation of normal adrenals.",
    }],
    explanation: "Cushing syndrome evaluation: (1) Confirm hypercortisolism (24h UFC, late-night salivary cortisol, overnight DST). (2) Determine ACTH dependence: High ACTH = pituitary (Cushing's disease, 70%) or ectopic ACTH. Low/undetectable ACTH = adrenal tumor (autonomous cortisol). (3) High-dose DST: pituitary adenomas typically suppress >50%, ectopic does not. CRH stimulation test also differentiates.",
    reference: "Tietz Textbook of Clinical Chemistry and Molecular Diagnostics, 7th Ed.",
  },
  {
    id: "chem-015",
    title: "Arterial Blood Gas Interpretation",
    department: "Clinical Chemistry",
    difficulty: "Beginner",
    patientAge: 70,
    patientGender: "Male",
    clinicalPresentation: "Severe COPD exacerbation with dyspnea, cyanosis, use of accessory muscles, and drowsiness.",
    history: "Advanced COPD. Chronic CO₂ retainer. Presented with acute worsening.",
    sampleType: "Arterial blood",
    laboratoryFindings: [
      "pH: 7.28 (acidosis)",
      "pCO₂: 68 mmHg (elevated — respiratory cause)",
      "pO₂: 52 mmHg (hypoxemia)",
      "HCO₃⁻: 32 mEq/L (elevated — chronic compensation)",
      "Base excess: +6 (positive — metabolic compensation present)",
      "Expected HCO₃⁻ for acute respiratory acidosis: 24 + (68-40)/10 = 26.8",
      "Actual HCO₃⁻ (32) > expected acute (26.8) → chronic component with acute exacerbation",
    ],
    questions: [{
      question: "What is the primary acid-base disorder?",
      options: ["Metabolic acidosis", "Respiratory acidosis with chronic compensation", "Metabolic alkalosis", "Respiratory alkalosis"],
      correctAnswer: 1,
      hint: "Elevated pCO₂ causes the acidosis; elevated HCO₃⁻ beyond acute expected compensation indicates chronicity.",
    }],
    explanation: "Respiratory acidosis: ↑pCO₂ → ↓pH. Compensation: kidneys retain HCO₃⁻. Acute: HCO₃⁻ rises 1 mEq/L per 10 mmHg ↑pCO₂. Chronic: HCO₃⁻ rises 3.5 mEq/L per 10 mmHg. This patient's HCO₃⁻ of 32 exceeds acute expected (26.8) but fits chronic pattern — consistent with COPD with acute exacerbation (acute-on-chronic respiratory acidosis).",
    reference: "Tietz Textbook of Clinical Chemistry and Molecular Diagnostics, 7th Ed.",
  },
];
