import { LabCase } from "./types";

export const hematologyCases: LabCase[] = [
  {
    id: "heme-001",
    title: "Iron Deficiency Anemia",
    department: "Hematology",
    difficulty: "Beginner",
    patientAge: 32,
    patientGender: "Female",
    clinicalPresentation: "Fatigue, pallor, pica (ice craving), koilonychia (spoon nails), and exertional dyspnea for 3 months.",
    history: "Heavy menstrual periods (menorrhagia). Vegetarian diet.",
    sampleType: "Blood (EDTA)",
    laboratoryFindings: [
      "Hb: 8.5 g/dL (low)",
      "MCV: 68 fL (microcytic)",
      "MCH: 22 pg (hypochromic)",
      "RDW: 18% (elevated — anisocytosis)",
      "Peripheral smear: Microcytic hypochromic RBCs, target cells, pencil cells",
      "Serum iron: 25 µg/dL (low)",
      "TIBC: 450 µg/dL (high)",
      "Ferritin: 8 ng/mL (low)",
      "Transferrin saturation: 6% (low)",
    ],
    questions: [{
      question: "What type of anemia does this iron study pattern indicate?",
      options: ["Anemia of chronic disease", "Iron deficiency anemia", "Thalassemia trait", "Sideroblastic anemia"],
      correctAnswer: 1,
      hint: "Low ferritin + low serum iron + high TIBC = body iron stores depleted.",
    }],
    explanation: "Iron deficiency anemia shows: ↓ferritin (most specific marker), ↓serum iron, ↑TIBC, ↓transferrin saturation. Smear: microcytic hypochromic cells, target cells, pencil (elliptocytes) cells. Distinguished from thalassemia trait by elevated RDW and low ferritin. RDW is normal in thalassemia trait.",
    reference: "Rodak's Hematology: Clinical Principles and Applications, 6th Ed.",
  },
  {
    id: "heme-002",
    title: "Sickle Cell Disease (Vasoocclusive Crisis)",
    department: "Hematology",
    difficulty: "Intermediate",
    patientAge: 18,
    patientGender: "Male",
    clinicalPresentation: "Severe pain in long bones and chest, fever, and jaundice. History of recurrent pain crises.",
    history: "Known sickle cell disease (HbSS). Splenectomy at age 10 (autosplenectomy).",
    sampleType: "Blood (EDTA)",
    laboratoryFindings: [
      "Hb: 7.2 g/dL",
      "MCV: 90 fL (normocytic)",
      "Reticulocyte count: 12% (elevated — hemolytic anemia)",
      "Peripheral smear: Sickle cells (drepanocytes), target cells, Howell-Jolly bodies",
      "Hb electrophoresis: HbS 85%, HbF 10%, HbA2 3.5%, HbA 0%",
      "Solubility test (Sickledex): Positive (turbid)",
      "LDH: Elevated, Haptoglobin: Low, Indirect bilirubin: Elevated",
    ],
    questions: [{
      question: "What hemoglobin pattern confirms sickle cell disease (HbSS)?",
      options: ["HbA 60%, HbS 40%", "HbS 85%, HbF 10%, HbA 0%", "HbA 95%, HbA2 5%", "HbC 50%, HbS 50%"],
      correctAnswer: 1,
      hint: "Homozygous HbSS has no HbA (both β-globin genes produce HbS).",
    }],
    explanation: "Sickle cell disease (HbSS): predominant HbS, elevated HbF, no HbA. Howell-Jolly bodies indicate functional asplenia. Hemolysis markers: ↑reticulocytes, ↑LDH, ↓haptoglobin, ↑indirect bilirubin. Sickle trait (HbAS) has ~60% HbA and ~40% HbS and is usually asymptomatic.",
    reference: "Rodak's Hematology: Clinical Principles and Applications, 6th Ed.",
  },
  {
    id: "heme-003",
    title: "Acute Promyelocytic Leukemia (APL)",
    department: "Hematology",
    difficulty: "Advanced",
    patientAge: 35,
    patientGender: "Female",
    clinicalPresentation: "Gum bleeding, epistaxis, petechiae, and fatigue for 1 week. Ecchymoses on extremities.",
    history: "Previously healthy. Coagulation: PT prolonged, fibrinogen low, D-dimer elevated (DIC).",
    sampleType: "Blood and bone marrow aspirate",
    laboratoryFindings: [
      "WBC: 2,500/µL (leukopenia — some cases present with leukocytosis)",
      "Peripheral smear: Abnormal promyelocytes with abundant Auer rods (faggot cells)",
      "Bone marrow: Hypercellular with >20% abnormal promyelocytes",
      "Cytochemistry: MPO strongly positive, Sudan Black B positive",
      "Flow cytometry: CD13+, CD33+, HLA-DR negative",
      "Cytogenetics: t(15;17)(q24;q21) — PML-RARA fusion",
      "FISH: PML-RARA fusion confirmed",
    ],
    questions: [{
      question: "What is the diagnosis based on faggot cells and t(15;17)?",
      options: ["AML-M3 (APL)", "AML-M2", "CML blast crisis", "ALL"],
      correctAnswer: 0,
      hint: "Faggot cells (bundles of Auer rods) + t(15;17) + DIC = medical emergency.",
    }],
    explanation: "APL (AML-M3/FAB) is characterized by abnormal promyelocytes with multiple Auer rods (faggot cells), t(15;17) creating PML-RARA fusion, and DIC. HLA-DR negative distinguishes from other AMLs. Medical emergency: start all-trans retinoic acid (ATRA) immediately to prevent fatal DIC. Cure rate >90% with ATRA + arsenic trioxide.",
    reference: "Rodak's Hematology: Clinical Principles and Applications, 6th Ed.",
  },
  {
    id: "heme-004",
    title: "Chronic Myeloid Leukemia",
    department: "Hematology",
    difficulty: "Intermediate",
    patientAge: 48,
    patientGender: "Male",
    clinicalPresentation: "Fatigue, early satiety, left upper quadrant fullness. Massive splenomegaly on exam.",
    history: "Weight loss of 5 kg over 2 months. Night sweats.",
    sampleType: "Blood + bone marrow",
    laboratoryFindings: [
      "WBC: 180,000/µL (marked leukocytosis)",
      "Differential: Entire myeloid series present — myeloblasts 2%, promyelocytes, myelocytes, metamyelocytes, bands, neutrophils",
      "Basophilia and eosinophilia",
      "Peripheral smear: Leukoerythroblastic picture, dwarf megakaryocytes",
      "LAP (leukocyte alkaline phosphatase) score: Low",
      "Bone marrow: Hypercellular with myeloid hyperplasia",
      "Cytogenetics: t(9;22)(q34;q11) — Philadelphia chromosome",
      "BCR-ABL1 fusion by RT-PCR: Positive",
    ],
    questions: [{
      question: "Which translocation and fusion gene define this leukemia?",
      options: ["t(15;17) PML-RARA", "t(9;22) BCR-ABL1", "t(8;14) MYC-IGH", "t(14;18) BCL2-IGH"],
      correctAnswer: 1,
      hint: "Philadelphia chromosome (Ph+) with markedly elevated WBC showing the entire myeloid series.",
    }],
    explanation: "CML is defined by the Philadelphia chromosome t(9;22) creating BCR-ABL1 tyrosine kinase. Chronic phase shows leukocytosis with full myeloid maturation, basophilia, low LAP score. Treatment: tyrosine kinase inhibitors (imatinib). Monitor response by BCR-ABL1 RT-PCR (molecular response).",
    reference: "Rodak's Hematology: Clinical Principles and Applications, 6th Ed.",
  },
  {
    id: "heme-005",
    title: "Immune Thrombocytopenic Purpura (ITP)",
    department: "Hematology",
    difficulty: "Beginner",
    patientAge: 6,
    patientGender: "Child",
    clinicalPresentation: "Sudden onset petechiae and purpura over trunk and extremities, epistaxis. Otherwise well-appearing.",
    history: "Recent viral upper respiratory infection 2 weeks ago. No medications.",
    sampleType: "Blood (EDTA)",
    laboratoryFindings: [
      "Platelet count: 12,000/µL (severely low)",
      "Hb: 13.5 g/dL (normal)",
      "WBC: 8,000/µL (normal)",
      "Peripheral smear: Decreased platelets, some large (megathrombocytes/giant platelets)",
      "PT: Normal, aPTT: Normal",
      "Bone marrow (if done): Increased/normal megakaryocytes",
    ],
    questions: [{
      question: "What is the most likely diagnosis?",
      options: ["Aplastic anemia", "ITP (immune thrombocytopenic purpura)", "TTP", "DIC"],
      correctAnswer: 1,
      hint: "Isolated thrombocytopenia in an otherwise healthy child after viral illness, with normal PT/aPTT.",
    }],
    explanation: "ITP is an autoimmune condition with anti-platelet antibodies (usually anti-GPIIb/IIIa) causing peripheral platelet destruction. In children, often follows viral infection and is self-limiting. Key: isolated thrombocytopenia with normal Hb, WBC, PT, aPTT. Large platelets indicate peripheral destruction with compensatory megakaryopoiesis.",
    reference: "Rodak's Hematology: Clinical Principles and Applications, 6th Ed.",
  },
  {
    id: "heme-006",
    title: "Megaloblastic Anemia (B12 Deficiency)",
    department: "Hematology",
    difficulty: "Intermediate",
    patientAge: 62,
    patientGender: "Female",
    clinicalPresentation: "Fatigue, glossitis (smooth, red tongue), paresthesias in hands and feet (peripheral neuropathy), and unsteady gait.",
    history: "Gastric bypass surgery 5 years ago. Strict vegan diet.",
    sampleType: "Blood (EDTA)",
    laboratoryFindings: [
      "Hb: 7.8 g/dL",
      "MCV: 118 fL (macrocytic)",
      "Peripheral smear: Macro-ovalocytes, hypersegmented neutrophils (≥5 lobes)",
      "Reticulocyte count: 0.5% (low — inadequate response)",
      "Serum vitamin B12: 85 pg/mL (low, normal: 200–900)",
      "Methylmalonic acid: Elevated",
      "Homocysteine: Elevated",
      "LDH: Markedly elevated (ineffective erythropoiesis)",
      "Anti-intrinsic factor antibodies: Positive",
    ],
    questions: [{
      question: "What distinguishes B12 deficiency from folate deficiency?",
      options: ["Macro-ovalocytes", "Elevated methylmalonic acid", "Hypersegmented neutrophils", "Elevated homocysteine"],
      correctAnswer: 1,
      hint: "Methylmalonic acid is elevated only in B12 deficiency, not folate deficiency.",
    }],
    explanation: "Both B12 and folate deficiency cause megaloblastic anemia with macro-ovalocytes and hypersegmented neutrophils. Only B12 deficiency elevates methylmalonic acid (MMA) — this is the key distinguishing marker. Both elevate homocysteine. B12 deficiency also causes neurological symptoms (subacute combined degeneration). Anti-IF antibodies = pernicious anemia.",
    reference: "Rodak's Hematology: Clinical Principles and Applications, 6th Ed.",
  },
  {
    id: "heme-007",
    title: "β-Thalassemia Major",
    department: "Hematology",
    difficulty: "Intermediate",
    patientAge: 2,
    patientGender: "Child",
    clinicalPresentation: "Severe pallor, failure to thrive, hepatosplenomegaly, and frontal bossing (chipmunk facies) starting at 6 months.",
    history: "Both parents are carriers (thalassemia trait). Mediterranean descent.",
    sampleType: "Blood (EDTA)",
    laboratoryFindings: [
      "Hb: 4.5 g/dL (severely low)",
      "MCV: 62 fL (microcytic)",
      "Peripheral smear: Severe microcytic hypochromic anemia, target cells, tear drops, nucleated RBCs",
      "Hb electrophoresis: HbF 90%, HbA2 5%, HbA <5%",
      "Reticulocyte count: Variable (ineffective erythropoiesis)",
      "Serum ferritin: Elevated (iron overload from transfusions)",
      "X-ray skull: 'Hair-on-end' appearance (extramedullary hematopoiesis)",
    ],
    questions: [{
      question: "What Hb electrophoresis pattern indicates β-thalassemia major?",
      options: ["HbA 95%, HbA2 5%", "HbS 85%, HbF 10%", "HbF 90%, HbA <5%", "HbH inclusions on supravital stain"],
      correctAnswer: 2,
      hint: "Absence of HbA with predominant HbF indicates both β-globin genes are non-functional.",
    }],
    explanation: "β-thalassemia major (Cooley's anemia): homozygous β⁰/β⁰ with absent/minimal HbA production. Compensatory ↑HbF (γ-chains). Severe ineffective erythropoiesis → skeletal changes (hair-on-end), hepatosplenomegaly. Treatment: chronic transfusions + iron chelation (deferoxamine). Cure: bone marrow transplant.",
    reference: "Rodak's Hematology: Clinical Principles and Applications, 6th Ed.",
  },
  {
    id: "heme-008",
    title: "Disseminated Intravascular Coagulation (DIC)",
    department: "Hematology",
    difficulty: "Advanced",
    patientAge: 45,
    patientGender: "Female",
    clinicalPresentation: "Septic shock with bleeding from IV sites, petechiae, mucosal bleeding, and acral cyanosis (purpura fulminans).",
    history: "E. coli urosepsis progressed to septic shock.",
    sampleType: "Blood (citrate + EDTA)",
    laboratoryFindings: [
      "Platelet count: 35,000/µL (low)",
      "PT: 22 sec (prolonged)",
      "aPTT: 55 sec (prolonged)",
      "Fibrinogen: 80 mg/dL (low, consumed)",
      "D-dimer: >20 µg/mL (markedly elevated)",
      "Peripheral smear: Schistocytes (fragmented RBCs), decreased platelets",
      "Thrombin time: Prolonged",
    ],
    questions: [{
      question: "Which combination of lab findings is most characteristic of acute DIC?",
      options: [
        "↓Platelets, prolonged PT/aPTT, ↑fibrinogen, ↓D-dimer",
        "↓Platelets, prolonged PT/aPTT, ↓fibrinogen, ↑D-dimer",
        "Normal platelets, normal PT/aPTT, ↓fibrinogen, ↑D-dimer",
        "↓Platelets, normal PT, prolonged aPTT, ↑D-dimer",
      ],
      correctAnswer: 1,
      hint: "DIC consumes both platelets AND clotting factors, with massive fibrin degradation.",
    }],
    explanation: "Acute DIC: simultaneous widespread thrombin generation and fibrinolysis. Labs show: ↓platelets (consumed), prolonged PT/aPTT (factor consumption), ↓fibrinogen (consumed), ↑D-dimer/FDPs (fibrinolysis), schistocytes (microangiopathic hemolysis from fibrin strands). Treatment: treat underlying cause + supportive (platelets, FFP, cryoprecipitate).",
    reference: "Rodak's Hematology: Clinical Principles and Applications, 6th Ed.",
  },
  {
    id: "heme-009",
    title: "Hereditary Spherocytosis",
    department: "Hematology",
    difficulty: "Beginner",
    patientAge: 14,
    patientGender: "Female",
    clinicalPresentation: "Intermittent jaundice, splenomegaly, and gallstones (pigmented bilirubin stones) at young age.",
    history: "Family history of anemia and cholecystectomy in mother and uncle. Northern European descent.",
    sampleType: "Blood (EDTA)",
    laboratoryFindings: [
      "Hb: 10.5 g/dL (mild anemia)",
      "MCV: 85 fL (normocytic)",
      "MCHC: 37 g/dL (elevated — spherocytes are hyperchromic)",
      "Peripheral smear: Spherocytes (round, no central pallor)",
      "Reticulocyte count: 8% (elevated — hemolytic)",
      "Direct Coombs (DAT): Negative",
      "Osmotic fragility test: Increased (spherocytes lyse earlier in hypotonic saline)",
      "Indirect bilirubin: Elevated, LDH: Elevated, Haptoglobin: Low",
    ],
    questions: [{
      question: "What test distinguishes hereditary spherocytosis from autoimmune hemolytic anemia?",
      options: ["Osmotic fragility test", "Direct antiglobulin test (DAT/Coombs)", "Peripheral smear", "Reticulocyte count"],
      correctAnswer: 1,
      hint: "Both show spherocytes, but the mechanism differs: inherited membrane defect vs. autoantibodies.",
    }],
    explanation: "Both hereditary spherocytosis (HS) and warm AIHA show spherocytes. DAT (direct Coombs) distinguishes them: Negative in HS (membrane protein defect — spectrin/ankyrin), Positive in AIHA (anti-RBC IgG antibodies). HS has elevated MCHC and increased osmotic fragility. Treatment: splenectomy for severe cases.",
    reference: "Rodak's Hematology: Clinical Principles and Applications, 6th Ed.",
  },
  {
    id: "heme-010",
    title: "Chronic Lymphocytic Leukemia (CLL)",
    department: "Hematology",
    difficulty: "Intermediate",
    patientAge: 68,
    patientGender: "Male",
    clinicalPresentation: "Incidental finding of lymphocytosis on routine blood work. Painless cervical and axillary lymphadenopathy.",
    history: "Otherwise asymptomatic. No B-symptoms (fever, weight loss, night sweats).",
    sampleType: "Blood (EDTA)",
    laboratoryFindings: [
      "WBC: 55,000/µL (lymphocytosis)",
      "Differential: 85% mature-appearing small lymphocytes",
      "Peripheral smear: Mature small lymphocytes with smudge cells (basket cells)",
      "Flow cytometry: CD5+, CD19+, CD20 dim, CD23+, FMC7 negative",
      "Cytogenetics: del(13q14) (most common, good prognosis)",
    ],
    questions: [{
      question: "What immunophenotype is characteristic of CLL?",
      options: ["CD5+, CD19+, CD23+", "CD10+, CD19+, CD20+", "CD3+, CD4+, CD25+", "CD20+, CD5−, CD10+"],
      correctAnswer: 0,
      hint: "CLL is a B-cell neoplasm aberrantly expressing the T-cell marker CD5.",
    }],
    explanation: "CLL is the most common leukemia in adults. Key: mature small lymphocytes with smudge cells on smear. Immunophenotype: CD5+ (T-cell marker co-expressed), CD19+, CD20 dim, CD23+, surface Ig dim. Smudge cells are fragile CLL lymphocytes that break during smear preparation. Rai/Binet staging guides treatment.",
    reference: "Rodak's Hematology: Clinical Principles and Applications, 6th Ed.",
  },
  {
    id: "heme-011",
    title: "G6PD Deficiency (Hemolytic Crisis)",
    department: "Hematology",
    difficulty: "Intermediate",
    patientAge: 25,
    patientGender: "Male",
    clinicalPresentation: "Sudden onset dark urine (hemoglobinuria), jaundice, pallor, and back pain 2 days after starting a new medication.",
    history: "Prescribed primaquine for malaria prophylaxis. African descent.",
    sampleType: "Blood (EDTA)",
    laboratoryFindings: [
      "Hb: 7.0 g/dL (dropped from 14 g/dL baseline)",
      "Reticulocyte count: 15% (elevated)",
      "Peripheral smear: Bite cells, Heinz bodies (supravital stain), blister cells",
      "Direct Coombs: Negative",
      "G6PD enzyme level: Low (test between crises for accuracy)",
      "LDH: Elevated, Haptoglobin: Undetectable",
      "Urine: Hemoglobinuria",
    ],
    questions: [{
      question: "What is the characteristic peripheral smear finding in G6PD deficiency crisis?",
      options: ["Spherocytes", "Schistocytes", "Bite cells and Heinz bodies", "Target cells"],
      correctAnswer: 2,
      hint: "Denatured hemoglobin (Heinz bodies) is removed by spleen, creating bite cells.",
    }],
    explanation: "G6PD deficiency: X-linked disorder → ↓NADPH → inability to reduce glutathione → oxidized hemoglobin denatures into Heinz bodies. Splenic macrophages 'bite out' Heinz bodies → bite cells. Triggered by oxidant drugs (primaquine, dapsone, sulfonamides), fava beans, infections. G6PD levels may be falsely normal during crisis (reticulocytes have higher G6PD).",
    reference: "Rodak's Hematology: Clinical Principles and Applications, 6th Ed.",
  },
  {
    id: "heme-012",
    title: "Thrombotic Thrombocytopenic Purpura (TTP)",
    department: "Hematology",
    difficulty: "Advanced",
    patientAge: 33,
    patientGender: "Female",
    clinicalPresentation: "Fever, petechiae, confusion (fluctuating neurological symptoms), and dark urine.",
    history: "Previously healthy. No medications or recent infections.",
    sampleType: "Blood (EDTA + citrate)",
    laboratoryFindings: [
      "Platelet count: 18,000/µL (severely low)",
      "Hb: 7.5 g/dL",
      "Peripheral smear: Numerous schistocytes (>1% = significant)",
      "LDH: Markedly elevated (>1000 U/L)",
      "Haptoglobin: Undetectable",
      "Direct Coombs: Negative",
      "PT/aPTT: Normal (key distinguishing feature from DIC)",
      "ADAMTS13 activity: <10% (severely deficient)",
      "Creatinine: 1.5 mg/dL (mild renal impairment)",
    ],
    questions: [{
      question: "What lab finding distinguishes TTP from DIC?",
      options: ["Schistocytes on smear", "Normal PT and aPTT", "Low platelet count", "Elevated LDH"],
      correctAnswer: 1,
      hint: "In TTP, clotting factors are NOT consumed — only platelets are consumed in microthrombi.",
    }],
    explanation: "TTP pentad: thrombocytopenia, microangiopathic hemolytic anemia (MAHA/schistocytes), neurological symptoms, renal dysfunction, fever. Critical distinction from DIC: PT/aPTT are NORMAL in TTP (no coagulation factor consumption). ADAMTS13 <10% confirms TTP. Treatment: emergent plasma exchange (PLEX). Do NOT transfuse platelets.",
    reference: "Rodak's Hematology: Clinical Principles and Applications, 6th Ed.",
  },
  {
    id: "heme-013",
    title: "Multiple Myeloma",
    department: "Hematology",
    difficulty: "Advanced",
    patientAge: 65,
    patientGender: "Male",
    clinicalPresentation: "Back pain, fatigue, recurrent infections (pneumonia twice this year), and unexplained renal insufficiency.",
    history: "Hypercalcemia (Ca 12.5 mg/dL), normocytic anemia.",
    sampleType: "Blood + bone marrow + urine",
    laboratoryFindings: [
      "Hb: 9.2 g/dL, MCV: 88 fL",
      "ESR: 110 mm/hr (markedly elevated)",
      "Peripheral smear: Rouleaux formation",
      "Serum protein electrophoresis (SPEP): M-spike in gamma region (IgG κ)",
      "Bone marrow: 45% plasma cells (clonal)",
      "24-hour urine: Bence Jones proteinuria (free light chains)",
      "Skeletal survey: Multiple lytic ('punched-out') lesions in skull",
      "β2-microglobulin: Elevated",
    ],
    questions: [{
      question: "What peripheral smear finding is classic for multiple myeloma?",
      options: ["Schistocytes", "Rouleaux formation", "Smudge cells", "Teardrop cells"],
      correctAnswer: 1,
      hint: "Excess immunoglobulin causes RBCs to stack like coins.",
    }],
    explanation: "Multiple myeloma: clonal plasma cell neoplasm producing monoclonal immunoglobulin (M-protein). CRAB criteria: hyperCalcemia, Renal insufficiency, Anemia, Bone lesions. Rouleaux on smear is due to high immunoglobulin. Bence Jones = urinary free light chains. Bone lesions are lytic (NOT blastic) — bone scan may be negative (use skeletal survey or PET-CT).",
    reference: "Rodak's Hematology: Clinical Principles and Applications, 6th Ed.",
  },
  {
    id: "heme-014",
    title: "Polycythemia Vera",
    department: "Hematology",
    difficulty: "Intermediate",
    patientAge: 58,
    patientGender: "Male",
    clinicalPresentation: "Headache, dizziness, plethora (ruddy complexion), pruritus after hot shower, and splenomegaly.",
    history: "History of DVT. Erythrocytosis found on routine labs.",
    sampleType: "Blood (EDTA)",
    laboratoryFindings: [
      "Hb: 20 g/dL, Hct: 62% (markedly elevated)",
      "WBC: 15,000/µL (mild leukocytosis)",
      "Platelet count: 550,000/µL (thrombocytosis)",
      "EPO level: Low/undetectable",
      "JAK2 V617F mutation: Positive",
      "Bone marrow: Hypercellular with trilineage hyperplasia (panmyelosis)",
      "Peripheral smear: Increased RBC mass, basophilia",
    ],
    questions: [{
      question: "Which mutation is found in >95% of polycythemia vera cases?",
      options: ["BCR-ABL1", "JAK2 V617F", "CALR", "MPL W515L"],
      correctAnswer: 1,
      hint: "This mutation causes constitutive activation of JAK-STAT signaling.",
    }],
    explanation: "Polycythemia vera (PV) is a JAK2-driven myeloproliferative neoplasm (>95% JAK2 V617F+). Key: ↑Hb/Hct, ↓EPO (vs. secondary polycythemia where EPO is elevated), panmyelosis. Risk of thrombosis, progression to myelofibrosis or AML. Treatment: phlebotomy to Hct <45% + aspirin ± hydroxyurea for high-risk.",
    reference: "Rodak's Hematology: Clinical Principles and Applications, 6th Ed.",
  },
  {
    id: "heme-015",
    title: "Von Willebrand Disease Type 1",
    department: "Hematology",
    difficulty: "Beginner",
    patientAge: 22,
    patientGender: "Female",
    clinicalPresentation: "Lifelong history of easy bruising, heavy menstrual bleeding (menorrhagia), and prolonged bleeding after dental extraction.",
    history: "Mother has similar bleeding history. No joint bleeds.",
    sampleType: "Blood (citrate)",
    laboratoryFindings: [
      "Platelet count: 210,000/µL (normal)",
      "PT: Normal",
      "aPTT: 38 sec (mildly prolonged)",
      "Bleeding time: Prolonged (if performed)",
      "PFA-100 closure time: Prolonged (both collagen/EPI and collagen/ADP)",
      "vWF antigen: 25% (low, normal: 50–150%)",
      "vWF activity (ristocetin cofactor): 22% (low)",
      "Factor VIII: 35% (mildly low — vWF carries/stabilizes FVIII)",
    ],
    questions: [{
      question: "Why is aPTT prolonged in von Willebrand disease?",
      options: [
        "vWF is needed for platelet aggregation",
        "vWF stabilizes Factor VIII, so low vWF → low FVIII → prolonged aPTT",
        "vWF activates Factor XII",
        "vWF inhibits tissue factor pathway inhibitor",
      ],
      correctAnswer: 1,
      hint: "vWF acts as a carrier protein that protects Factor VIII from premature degradation.",
    }],
    explanation: "vWD Type 1 (most common, ~80%): partial quantitative deficiency of vWF. vWF has dual roles: platelet adhesion to injured endothelium AND carrying/stabilizing FVIII. Low vWF → ↓FVIII → mildly prolonged aPTT. Mucocutaneous bleeding pattern (vs. hemophilia = deep tissue/joint bleeding). Treatment: DDAVP (desmopressin) releases stored vWF.",
    reference: "Rodak's Hematology: Clinical Principles and Applications, 6th Ed.",
  },
];
