import { LabCase } from "./types";

export const histopathologyCases: LabCase[] = [
  {
    id: "histo-001",
    title: "Cervical Intraepithelial Neoplasia (CIN)",
    department: "Histopathology / Cytology",
    difficulty: "Beginner",
    patientAge: 32,
    patientGender: "Female",
    clinicalPresentation: "Abnormal Pap smear reported as HSIL (high-grade squamous intraepithelial lesion). Referred for colposcopy.",
    history: "HPV-positive (high-risk type 16). Smoker. Multiple sexual partners.",
    sampleType: "Cervical biopsy",
    laboratoryFindings: [
      "Pap smear: HSIL — cells with high N/C ratio, hyperchromatic nuclei, coarsely granular chromatin",
      "Colposcopy: Acetowhite lesion with punctation and mosaicism at transformation zone",
      "Biopsy H&E: Dysplastic squamous cells involving full thickness of epithelium",
      "p16 immunostain: Diffuse, strong block-positive (confirms high-risk HPV-driven dysplasia)",
      "Ki-67: Positive throughout full thickness of epithelium",
    ],
    questions: [{
      question: "What grade of CIN corresponds to HSIL involving full-thickness dysplasia?",
      options: ["CIN 1 (mild)", "CIN 2 (moderate)", "CIN 3 (severe / carcinoma in situ)", "Invasive squamous cell carcinoma"],
      correctAnswer: 2,
      hint: "Full-thickness dysplasia without invasion through the basement membrane = CIN 3.",
    }],
    explanation: "CIN 3 (carcinoma in situ): dysplastic cells replace the full thickness of squamous epithelium but DO NOT invade through the basement membrane. p16 block-positive staining is a surrogate marker for high-risk HPV E7 protein (inactivates Rb → p16 overexpression). Ki-67 throughout epithelium confirms high proliferation. Treatment: LEEP/cone biopsy excision.",
    reference: "Bancroft's Theory and Practice of Histological Techniques, 8th Ed.; Robbins Pathology.",
  },
  {
    id: "histo-002",
    title: "Breast Carcinoma (HER2 Positive)",
    department: "Histopathology / Cytology",
    difficulty: "Intermediate",
    patientAge: 52,
    patientGender: "Female",
    clinicalPresentation: "Palpable 3 cm breast mass in upper outer quadrant. Mammography: BIRADS 5 (highly suspicious).",
    history: "No family history of breast cancer. Postmenopausal.",
    sampleType: "Core needle biopsy of breast mass",
    laboratoryFindings: [
      "H&E: Invasive ductal carcinoma, Grade 3 (poorly differentiated)",
      "Tubule formation: <10% (score 3)",
      "Mitotic count: >20/10 HPF (score 3)",
      "Nuclear pleomorphism: Marked (score 3)",
      "ER (estrogen receptor) IHC: Negative (<1%)",
      "PR (progesterone receptor) IHC: Negative (<1%)",
      "HER2 IHC: 3+ (strong, complete membrane staining in >10% of tumor cells)",
      "Ki-67: 65% (high proliferation)",
    ],
    questions: [{
      question: "What targeted therapy is indicated for HER2-positive breast cancer?",
      options: ["Tamoxifen", "Trastuzumab (Herceptin)", "CDK4/6 inhibitor", "PARP inhibitor"],
      correctAnswer: 1,
      hint: "This monoclonal antibody targets the HER2/neu receptor (ErbB2).",
    }],
    explanation: "HER2 (ErbB2) amplification/overexpression occurs in ~15–20% of breast cancers. IHC scoring: 0/1+ = negative, 2+ = equivocal (needs FISH), 3+ = positive. HER2+ tumors are aggressive but responsive to trastuzumab (anti-HER2 monoclonal antibody), which dramatically improves survival. ER/PR-negative + HER2-positive = HER2-enriched subtype. Nottingham grade = tubules + mitoses + pleomorphism (3–9 → Grade 1–3).",
    reference: "Bancroft's Theory and Practice of Histological Techniques, 8th Ed.; ASCO/CAP HER2 Testing Guidelines.",
  },
  {
    id: "histo-003",
    title: "Helicobacter pylori Gastritis",
    department: "Histopathology / Cytology",
    difficulty: "Beginner",
    patientAge: 50,
    patientGender: "Male",
    clinicalPresentation: "Chronic dyspepsia and epigastric pain. Endoscopy shows erythematous antral mucosa.",
    history: "Long-standing dyspepsia. No NSAIDs. No alarm features.",
    sampleType: "Gastric antral biopsy",
    laboratoryFindings: [
      "H&E: Active chronic gastritis — neutrophilic infiltration of gastric glands (activity) + lymphoplasmacytic inflammation",
      "Organisms: Small curved bacilli on mucosal surface (difficult to see on H&E)",
      "Giemsa stain: Curved bacilli highlighted in blue on gastric surface epithelium",
      "Warthin-Starry (silver stain): Black-staining spiral organisms",
      "Immunohistochemistry: Anti-H. pylori antibody positive",
    ],
    questions: [{
      question: "Which special stain is commonly used to detect H. pylori in gastric biopsies?",
      options: ["PAS (Periodic Acid-Schiff)", "Giemsa stain", "Masson's trichrome", "Congo red"],
      correctAnswer: 1,
      hint: "This Romanowsky-based stain highlights bacteria in blue against the pink background of gastric mucosa.",
    }],
    explanation: "H. pylori detection in biopsies: Giemsa stain (most commonly used — blue organisms on pink background), Warthin-Starry (silver stain — black organisms), or IHC (most sensitive and specific). Active gastritis = neutrophils in gland epithelium. Chronic = lymphocytes/plasma cells. H. pylori associated with peptic ulcers, gastric MALT lymphoma, and gastric adenocarcinoma.",
    reference: "Bancroft's Theory and Practice of Histological Techniques, 8th Ed.",
  },
  {
    id: "histo-004",
    title: "Renal Amyloidosis",
    department: "Histopathology / Cytology",
    difficulty: "Advanced",
    patientAge: 65,
    patientGender: "Male",
    clinicalPresentation: "Nephrotic syndrome (massive proteinuria >3.5 g/day, hypoalbuminemia, edema, hyperlipidemia), hepatomegaly.",
    history: "Chronic rheumatoid arthritis for 20 years (possible AA amyloidosis) or multiple myeloma workup (AL amyloidosis).",
    sampleType: "Kidney biopsy",
    laboratoryFindings: [
      "H&E: Amorphous, eoite pink (hyaline) material deposited in glomerular mesangium and vessel walls",
      "Congo red stain: Orange-red deposits under light microscopy",
      "Polarized microscopy (Congo red): Apple-green birefringence (PATHOGNOMONIC)",
      "Electron microscopy: Randomly arranged, non-branching fibrils (8–12 nm diameter)",
      "Immunofluorescence: Lambda light chain restriction (→ AL amyloidosis)",
      "Serum free light chains: Lambda markedly elevated",
    ],
    questions: [{
      question: "What is the pathognomonic finding for amyloidosis on histology?",
      options: [
        "PAS-positive material",
        "Apple-green birefringence under polarized light with Congo red stain",
        "Silver-positive fibrils",
        "Metachromatic staining with crystal violet",
      ],
      correctAnswer: 1,
      hint: "Congo red dye binds amyloid fibrils and shows a distinctive color under polarized light.",
    }],
    explanation: "Amyloidosis diagnosis: (1) Congo red stain → orange-red under light microscopy → APPLE-GREEN BIREFRINGENCE under polarized light (pathognomonic). (2) EM: 8–12 nm non-branching fibrils. (3) Typing: AL (light chain — from plasma cell dyscrasias), AA (serum amyloid A — chronic inflammation), ATTR (transthyretin). Typing determines treatment — mass spectrometry (LMD-MS) is gold standard for typing.",
    reference: "Bancroft's Theory and Practice of Histological Techniques, 8th Ed.; Robbins Pathology.",
  },
  {
    id: "histo-005",
    title: "Liver Cirrhosis and Iron Overload",
    department: "Histopathology / Cytology",
    difficulty: "Intermediate",
    patientAge: 55,
    patientGender: "Male",
    clinicalPresentation: "Hepatomegaly, bronze skin discoloration, diabetes mellitus, and signs of liver cirrhosis (ascites, jaundice).",
    history: "Family history of liver disease. Northern European descent. No significant alcohol use.",
    sampleType: "Liver biopsy",
    laboratoryFindings: [
      "H&E: Hepatocytes with golden-brown granular pigment, established cirrhosis (nodular architecture with fibrous septa)",
      "Perl's Prussian blue stain: Intense blue (4+) granular staining within hepatocytes and Kupffer cells",
      "Masson's trichrome: Blue/green fibrosis surrounding regenerative nodules (cirrhosis)",
      "Hepatic iron index: >1.9 (diagnostic for hereditary hemochromatosis)",
      "Serum ferritin: 2500 ng/mL (markedly elevated)",
      "Transferrin saturation: 92% (normal: 20–50%)",
      "HFE gene: C282Y homozygous",
    ],
    questions: [{
      question: "Which special stain specifically demonstrates iron deposition in tissue?",
      options: ["Congo red", "Perl's Prussian blue", "Reticulin (silver)", "Oil Red O"],
      correctAnswer: 1,
      hint: "This histochemical reaction converts ferric iron (Fe³⁺) to a bright blue precipitate.",
    }],
    explanation: "Perl's Prussian blue: potassium ferrocyanide reacts with ferric iron (Fe³⁺) → bright blue precipitate (ferric ferrocyanide). Hereditary hemochromatosis: HFE C282Y mutation → excess iron absorption → deposits in liver (cirrhosis), pancreas (diabetes), heart (cardiomyopathy), skin (bronze), joints. Classic triad: cirrhosis + diabetes + bronze skin = 'bronze diabetes.' Treatment: therapeutic phlebotomy.",
    reference: "Bancroft's Theory and Practice of Histological Techniques, 8th Ed.",
  },
  {
    id: "histo-006",
    title: "Tuberculosis Granuloma",
    department: "Histopathology / Cytology",
    difficulty: "Beginner",
    patientAge: 40,
    patientGender: "Male",
    clinicalPresentation: "Chronic cough, hemoptysis, night sweats, and weight loss. CXR: upper lobe cavitary lesion.",
    history: "Immigration from TB-endemic region. HIV-negative.",
    sampleType: "Lung biopsy (transbronchial)",
    laboratoryFindings: [
      "H&E: Caseating granulomas — central caseous (cheese-like) necrosis surrounded by epithelioid histiocytes, Langhans giant cells (horseshoe-shaped nuclei), lymphocytes",
      "Ziehl-Neelsen (ZN) stain: Acid-fast bacilli (red rods against blue background)",
      "Auramine-rhodamine fluorescent stain: Bright yellow-green fluorescent bacilli",
      "GMS (Grocott methenamine silver): Negative for fungi",
      "PAS: Negative for fungi",
    ],
    questions: [{
      question: "What is the hallmark histological feature of tuberculosis?",
      options: ["Non-caseating granulomas", "Caseating granulomas with Langhans giant cells", "Fibrinoid necrosis", "Eosinophilic infiltration"],
      correctAnswer: 1,
      hint: "Caseous necrosis (cheese-like center) surrounded by epithelioid cells and multinucleated giant cells.",
    }],
    explanation: "TB granuloma: central caseating necrosis (distinguishing from sarcoidosis which is non-caseating) + epithelioid histiocytes (activated macrophages) + Langhans giant cells (fused macrophages with horseshoe nuclei) + lymphocytic cuff. ZN stain: mycolic acid in cell wall resists decolorization by acid-alcohol → acid-fast bacilli (AFB) appear red. Auramine-rhodamine is more sensitive screening stain.",
    reference: "Bancroft's Theory and Practice of Histological Techniques, 8th Ed.",
  },
  {
    id: "histo-007",
    title: "Tissue Processing Artifact",
    department: "Histopathology / Cytology",
    difficulty: "Intermediate",
    patientAge: 60,
    patientGender: "Male",
    clinicalPresentation: "Colon biopsy for suspected malignancy shows poor-quality sections making interpretation difficult.",
    history: "Colonoscopy biopsy submitted in formalin. Histology lab reports processing problems.",
    sampleType: "Colon biopsy",
    laboratoryFindings: [
      "Gross: Tissue appears hardened and dark (possible over-fixation or wrong fixative)",
      "H&E sections: Tissue shrinkage, nuclear pyknosis, poor cellular detail",
      "Retraction artifacts: Clear spaces around cells (processing artifact, not true spaces)",
      "Immunohistochemistry: Failed — no antigen retrieval possible (over-fixation)",
      "Review: Tissue was in 10% formalin for 5 days before processing (recommended: 6–72 hours)",
    ],
    questions: [{
      question: "What is the recommended fixation time for 10% neutral buffered formalin?",
      options: ["1–2 hours", "6–72 hours", "5–7 days", "Fixation time doesn't matter"],
      correctAnswer: 1,
      hint: "Under-fixation causes autolysis; over-fixation causes excessive cross-linking that masks antigens.",
    }],
    explanation: "10% neutral buffered formalin (NBF): optimal fixation 6–72 hours. Under-fixation (<6h): autolysis, poor morphology, unreliable IHC. Over-fixation (>72h): excessive protein cross-linking → antigen masking → IHC failure, tissue brittleness. For HER2 and ER/PR testing (breast), ASCO/CAP requires 6–72 hours cold ischemia time + fixation. Formalin penetrates ~1 mm/hour, so tissue thickness matters.",
    reference: "Bancroft's Theory and Practice of Histological Techniques, 8th Ed.",
  },
  {
    id: "histo-008",
    title: "Fungal Infection in Immunocompromised Host",
    department: "Histopathology / Cytology",
    difficulty: "Intermediate",
    patientAge: 45,
    patientGender: "Male",
    clinicalPresentation: "Rapidly progressive sino-orbital infection with black eschar on nasal turbinate, periorbital edema, and cranial nerve palsy.",
    history: "Uncontrolled diabetes with DKA. Immunosuppressed.",
    sampleType: "Nasal biopsy",
    laboratoryFindings: [
      "H&E: Wide (6–25 µm), ribbon-like, pauci-septate (few septa) hyphae with irregular 90° branching",
      "Angioinvasion: Hyphae invading blood vessel walls → thrombosis and tissue necrosis",
      "GMS (Grocott methenamine silver): Black-staining hyphae against green background",
      "PAS (Periodic Acid-Schiff): Magenta-staining hyphae",
      "No culture growth initially (Mucor is easily killed by tissue processing)",
    ],
    questions: [{
      question: "What morphological feature distinguishes Mucor/Rhizopus from Aspergillus on histology?",
      options: [
        "Septate hyphae with 45° branching (Aspergillus) vs. pauci-septate/ribbon-like hyphae with 90° branching (Mucor)",
        "Mucor produces yeast forms; Aspergillus does not",
        "Both are identical on histology",
        "Mucor has narrow hyphae; Aspergillus has wide hyphae",
      ],
      correctAnswer: 0,
      hint: "The branching angle and septation pattern are key: acute-angle vs. right-angle.",
    }],
    explanation: "Mucormycosis (Mucor/Rhizopus): wide (6–25 µm), ribbon-like, pauci-septate hyphae with irregular 90° (right-angle) branching + angioinvasion → thrombosis → infarction (black eschar). Aspergillus: narrower (3–6 µm), septate hyphae with regular 45° (acute/dichotomous) branching. GMS and PAS are the key special stains for highlighting fungi. Mucor poorly preserved on culture/processing.",
    reference: "Bancroft's Theory and Practice of Histological Techniques, 8th Ed.",
  },
  {
    id: "histo-009",
    title: "Colorectal Adenocarcinoma Staging",
    department: "Histopathology / Cytology",
    difficulty: "Advanced",
    patientAge: 62,
    patientGender: "Male",
    clinicalPresentation: "Change in bowel habits, rectal bleeding, and weight loss. Colonoscopy shows a polypoid mass in sigmoid colon.",
    history: "No family history of colon cancer. No prior colonoscopy.",
    sampleType: "Sigmoid colectomy specimen",
    laboratoryFindings: [
      "Gross: 4 cm ulcerated, fungating mass in sigmoid colon",
      "H&E: Moderately differentiated adenocarcinoma with glandular formation (~50%)",
      "Depth of invasion: Through muscularis propria into pericolonic fat (pT3)",
      "Lymph nodes: 3 of 18 positive for metastatic carcinoma (pN1b)",
      "Resection margins: Negative (R0 resection)",
      "MMR IHC (MLH1, MSH2, MSH6, PMS2): All intact (microsatellite stable)",
      "KRAS mutation testing: KRAS G12D mutant",
    ],
    questions: [{
      question: "Why is KRAS mutation status important in colorectal cancer treatment?",
      options: [
        "KRAS-mutant tumors respond to anti-EGFR therapy",
        "KRAS-mutant tumors are RESISTANT to anti-EGFR therapy (cetuximab/panitumumab)",
        "KRAS testing is only needed for staging",
        "KRAS mutation determines chemotherapy dose",
      ],
      correctAnswer: 1,
      hint: "KRAS is downstream of EGFR; if KRAS is constitutively active, blocking EGFR upstream is ineffective.",
    }],
    explanation: "KRAS mutation (codons 12, 13, 61, 146): constitutive RAS activation → downstream signaling regardless of EGFR blockade → anti-EGFR mAbs (cetuximab, panitumumab) are INEFFECTIVE in KRAS-mutant tumors. Only KRAS/NRAS/BRAF wild-type patients benefit from anti-EGFR therapy. MMR/MSI testing: dMMR/MSI-H tumors respond to immunotherapy (pembrolizumab). pT3N1b = Stage IIIB → adjuvant chemotherapy (FOLFOX).",
    reference: "Bancroft's Theory and Practice of Histological Techniques, 8th Ed.; NCCN Colon Cancer Guidelines.",
  },
  {
    id: "histo-010",
    title: "Papanicolaou Stain Interpretation",
    department: "Histopathology / Cytology",
    difficulty: "Beginner",
    patientAge: 28,
    patientGender: "Female",
    clinicalPresentation: "Routine cervical cancer screening (Pap smear) in an asymptomatic woman.",
    history: "HPV-negative on last test. No abnormal Pap history.",
    sampleType: "Cervical cytology (liquid-based Pap)",
    laboratoryFindings: [
      "Adequacy: Satisfactory for evaluation (adequate cellularity, transformation zone component present)",
      "Superficial squamous cells: Small pyknotic nuclei, abundant pink/orange cytoplasm (eosinophilic)",
      "Intermediate cells: Vesicular nuclei, blue-green (cyanophilic) cytoplasm",
      "Endocervical columnar cells: Honeycomb sheets and strips",
      "No dysplastic cells, no organisms",
      "Interpretation: NILM (Negative for Intraepithelial Lesion or Malignancy)",
    ],
    questions: [{
      question: "In the Pap stain, what determines the color of squamous cell cytoplasm?",
      options: [
        "Cell size",
        "Degree of keratinization/maturation — mature (keratinized) cells stain pink/orange; immature cells stain blue-green",
        "Nuclear-to-cytoplasmic ratio",
        "Fixation time",
      ],
      correctAnswer: 1,
      hint: "Orange G stains keratin (mature cells pink), Light Green/EA stains non-keratinized cytoplasm (blue-green).",
    }],
    explanation: "Papanicolaou stain: polychromatic stain for cytology. Components: (1) Harris hematoxylin (nuclear stain — blue), (2) Orange G (keratin → orange/pink in mature/superficial cells), (3) EA (eosin + Light Green/Bismarck brown → blue-green in immature/intermediate cells). Cell maturity determines cytoplasmic color. Adequacy requires ≥5,000 squamous cells (conventional) or transformation zone component present.",
    reference: "Bancroft's Theory and Practice of Histological Techniques, 8th Ed.",
  },
];
