import { LabCase } from "./types";

export const immunologyCases: LabCase[] = [
  {
    id: "imm-001",
    title: "Systemic Lupus Erythematosus (SLE)",
    department: "Immunology / Serology",
    difficulty: "Intermediate",
    patientAge: 28,
    patientGender: "Female",
    clinicalPresentation: "Malar (butterfly) rash, photosensitivity, joint pain, oral ulcers, fatigue, and proteinuria.",
    history: "Young woman with multisystem involvement. Raynaud's phenomenon. Family history of autoimmune disease.",
    sampleType: "Blood (serum)",
    laboratoryFindings: [
      "ANA (antinuclear antibody): Positive, titer 1:640, homogeneous pattern",
      "Anti-dsDNA: Positive (highly specific for SLE)",
      "Anti-Smith (Sm): Positive (most specific for SLE)",
      "C3: Low, C4: Low (complement consumption)",
      "ESR: 55 mm/hr (elevated)",
      "CRP: Normal or mildly elevated (characteristically normal in SLE flares)",
      "Urinalysis: Proteinuria, RBC casts (lupus nephritis)",
    ],
    questions: [{
      question: "Which autoantibody is MOST SPECIFIC for SLE?",
      options: ["ANA", "Anti-dsDNA", "Anti-Smith (Sm)", "Anti-histone"],
      correctAnswer: 2,
      hint: "While anti-dsDNA correlates with disease activity, this antibody is found almost exclusively in SLE.",
    }],
    explanation: "Anti-Smith (Sm) is the most specific antibody for SLE (~99% specific) but has low sensitivity (~30%). Anti-dsDNA is highly specific (~95%) and correlates with disease activity/nephritis. ANA is sensitive (~98%) but not specific. Low complement (C3/C4) indicates consumption from immune complex deposition. ESR elevated but CRP often normal in SLE flares (distinguishing feature).",
    reference: "Janeway's Immunobiology, 10th Ed.; Harrison's Principles of Internal Medicine.",
  },
  {
    id: "imm-002",
    title: "Rheumatoid Arthritis",
    department: "Immunology / Serology",
    difficulty: "Beginner",
    patientAge: 45,
    patientGender: "Female",
    clinicalPresentation: "Bilateral symmetric joint pain and swelling (MCPs, PIPs, wrists), morning stiffness >1 hour, and fatigue.",
    history: "Symptoms progressing over 6 months. No trauma.",
    sampleType: "Blood (serum)",
    laboratoryFindings: [
      "RF (rheumatoid factor): Positive, titer 1:160",
      "Anti-CCP (anti-cyclic citrullinated peptide): Positive (highly specific)",
      "ESR: 48 mm/hr (elevated)",
      "CRP: 3.5 mg/dL (elevated)",
      "CBC: Mild normocytic anemia (anemia of chronic disease)",
      "X-ray hands: Periarticular osteopenia, joint space narrowing",
    ],
    questions: [{
      question: "Which antibody is most specific for rheumatoid arthritis?",
      options: ["RF (rheumatoid factor)", "Anti-CCP", "ANA", "Anti-dsDNA"],
      correctAnswer: 1,
      hint: "RF is sensitive but found in many conditions; this antibody is ~97% specific for RA.",
    }],
    explanation: "Anti-CCP is ~97% specific for RA (vs. RF ~80% specific). RF (IgM against IgG Fc region) is present in 70–80% of RA but also in other autoimmune diseases, infections, and even healthy elderly. Anti-CCP can appear years before clinical RA and predicts erosive disease. Both positive = high probability of RA.",
    reference: "Janeway's Immunobiology, 10th Ed.",
  },
  {
    id: "imm-003",
    title: "HIV Diagnosis",
    department: "Immunology / Serology",
    difficulty: "Beginner",
    patientAge: 30,
    patientGender: "Male",
    clinicalPresentation: "Weight loss, chronic diarrhea, oral candidiasis, and recurrent herpes zoster.",
    history: "Unprotected sexual contacts. Night sweats and lymphadenopathy for 3 months.",
    sampleType: "Blood (serum)",
    laboratoryFindings: [
      "4th generation HIV Ag/Ab combo test: Reactive",
      "HIV-1/HIV-2 differentiation assay: HIV-1 positive",
      "HIV-1 RNA viral load: 85,000 copies/mL",
      "CD4 count: 180 cells/µL (severely low, normal: 500–1500)",
      "CD4/CD8 ratio: 0.3 (inverted, normal: >1)",
    ],
    questions: [{
      question: "What is the recommended initial screening test for HIV?",
      options: ["Western blot", "4th generation Ag/Ab combination immunoassay", "HIV RNA PCR", "CD4 count"],
      correctAnswer: 1,
      hint: "This test detects both HIV antibodies AND p24 antigen, reducing the window period.",
    }],
    explanation: "CDC-recommended HIV testing algorithm: (1) 4th gen Ag/Ab combo assay (detects p24 antigen + HIV-1/2 antibodies — window period ~2 weeks). (2) If reactive → HIV-1/HIV-2 differentiation immunoassay. (3) If indeterminate → HIV-1 RNA (NAT). Western blot is no longer recommended as confirmatory. CD4 <200 = AIDS-defining.",
    reference: "Janeway's Immunobiology, 10th Ed.; CDC HIV Testing Guidelines.",
  },
  {
    id: "imm-004",
    title: "Anaphylaxis (Type I Hypersensitivity)",
    department: "Immunology / Serology",
    difficulty: "Intermediate",
    patientAge: 12,
    patientGender: "Child",
    clinicalPresentation: "Urticaria, angioedema (lip/tongue swelling), wheezing, hypotension, and tachycardia within 15 minutes of eating peanuts.",
    history: "Known peanut allergy. Accidentally ingested peanut-containing food.",
    sampleType: "Blood (serum)",
    laboratoryFindings: [
      "Serum tryptase: 45 ng/mL (elevated, normal: <11.4 — confirms mast cell degranulation)",
      "Total IgE: 850 IU/mL (elevated)",
      "Specific IgE (peanut): 42 kU/L (strongly positive, Class 4)",
      "Skin prick test (later): 12 mm wheal to peanut extract",
      "Histamine: Elevated (if measured within 60 min)",
    ],
    questions: [{
      question: "What type of hypersensitivity reaction is anaphylaxis?",
      options: ["Type I (immediate/IgE-mediated)", "Type II (cytotoxic)", "Type III (immune complex)", "Type IV (delayed/cell-mediated)"],
      correctAnswer: 0,
      hint: "IgE antibodies bound to mast cells/basophils are cross-linked by allergen, causing rapid degranulation.",
    }],
    explanation: "Type I hypersensitivity: IgE-mediated immediate reaction. Prior sensitization → allergen-specific IgE binds to FcεRI on mast cells → re-exposure → cross-linking → degranulation → histamine, leukotrienes, prostaglandins release. Serum tryptase confirms mast cell activation (peaks at 1–2 hours, draw within 4 hours). Treatment: IM epinephrine immediately.",
    reference: "Janeway's Immunobiology, 10th Ed.",
  },
  {
    id: "imm-005",
    title: "Celiac Disease",
    department: "Immunology / Serology",
    difficulty: "Beginner",
    patientAge: 8,
    patientGender: "Child",
    clinicalPresentation: "Chronic diarrhea, abdominal bloating, failure to thrive, and iron-deficiency anemia unresponsive to oral iron.",
    history: "Symptoms worsened after introduction of wheat-based foods. Family history of autoimmune diseases.",
    sampleType: "Blood (serum)",
    laboratoryFindings: [
      "Anti-tTG IgA (tissue transglutaminase): 125 U/mL (markedly elevated, normal: <20)",
      "Anti-endomysial antibody (EMA) IgA: Positive",
      "Total IgA: Normal (ruling out IgA deficiency)",
      "Anti-DGP (deamidated gliadin peptide) IgG: Positive",
      "Duodenal biopsy: Villous atrophy, crypt hyperplasia, intraepithelial lymphocytosis (Marsh 3)",
    ],
    questions: [{
      question: "What is the most sensitive and specific serological test for celiac disease?",
      options: ["Anti-gliadin IgA", "Anti-tTG IgA", "Total IgA", "Anti-smooth muscle antibody"],
      correctAnswer: 1,
      hint: "This autoantibody targets the enzyme that deamidates gliadin peptides.",
    }],
    explanation: "Anti-tTG IgA is the preferred initial test for celiac disease (~95% sensitivity, >95% specificity). Important: check total IgA first (IgA deficiency → false-negative IgA-based tests → use IgG-based tests). Anti-EMA IgA is highly specific (~99%) but less sensitive. Gold standard: duodenal biopsy showing villous atrophy. Must test while on gluten-containing diet.",
    reference: "Janeway's Immunobiology, 10th Ed.",
  },
  {
    id: "imm-006",
    title: "Autoimmune Hemolytic Anemia (Warm AIHA)",
    department: "Immunology / Serology",
    difficulty: "Intermediate",
    patientAge: 50,
    patientGender: "Female",
    clinicalPresentation: "Fatigue, pallor, jaundice, and dark urine. Splenomegaly on exam.",
    history: "SLE diagnosed 5 years ago. On hydroxychloroquine.",
    sampleType: "Blood (EDTA + clot)",
    laboratoryFindings: [
      "Hb: 7.5 g/dL (severe anemia)",
      "Reticulocyte count: 12% (elevated — hemolytic)",
      "Peripheral smear: Spherocytes, polychromasia",
      "Direct antiglobulin test (DAT/Coombs): Positive — IgG + C3d",
      "Indirect antiglobulin test (IAT): Positive (autoantibody in serum)",
      "LDH: Elevated, Haptoglobin: Low, Indirect bilirubin: Elevated",
    ],
    questions: [{
      question: "What does a positive DAT with IgG coating indicate?",
      options: [
        "Cold agglutinin disease",
        "Warm autoimmune hemolytic anemia",
        "Drug-induced hemolysis (penicillin type)",
        "Transfusion reaction",
      ],
      correctAnswer: 1,
      hint: "IgG autoantibodies bind RBCs at body temperature (37°C), causing extravascular hemolysis in the spleen.",
    }],
    explanation: "Warm AIHA: IgG autoantibodies bind RBCs at 37°C → DAT positive for IgG ± C3d → splenic macrophages remove antibody-coated RBCs (extravascular hemolysis) → spherocytes. Associated with SLE, CLL, drugs. Cold AIHA: IgM autoantibodies bind at <30°C → DAT positive for C3d only → complement-mediated intravascular hemolysis.",
    reference: "Janeway's Immunobiology, 10th Ed.",
  },
  {
    id: "imm-007",
    title: "Antiphospholipid Syndrome",
    department: "Immunology / Serology",
    difficulty: "Advanced",
    patientAge: 32,
    patientGender: "Female",
    clinicalPresentation: "Recurrent pregnancy losses (3 miscarriages), deep vein thrombosis in left leg at age 28.",
    history: "Known SLE. Unexplained prolonged aPTT.",
    sampleType: "Blood (citrate + serum)",
    laboratoryFindings: [
      "aPTT: 52 sec (prolonged)",
      "aPTT mixing study: Does NOT correct (inhibitor present)",
      "Lupus anticoagulant (dRVVT confirm/screen ratio): Positive",
      "Anti-cardiolipin IgG: 85 GPL (elevated, >40 = significant)",
      "Anti-β2-glycoprotein I IgG: Positive",
      "PT: Normal",
      "Platelet count: 95,000/µL (mild thrombocytopenia)",
    ],
    questions: [{
      question: "Why does lupus anticoagulant cause thrombosis despite prolonging aPTT in vitro?",
      options: [
        "It inhibits antithrombin",
        "It activates platelets directly",
        "In vitro: interferes with phospholipid-dependent clotting tests (prolonged aPTT). In vivo: promotes thrombosis via endothelial activation and complement",
        "It causes Factor V Leiden mutation",
      ],
      correctAnswer: 2,
      hint: "This is a paradox: the antibody is an 'anticoagulant' only in the test tube.",
    }],
    explanation: "Antiphospholipid syndrome: anti-phospholipid antibodies (lupus anticoagulant, anti-cardiolipin, anti-β2GPI) cause thrombosis in vivo but prolong phospholipid-dependent clotting tests (aPTT) in vitro. Diagnosis requires: clinical criteria (thrombosis or pregnancy morbidity) + persistent lab positivity (≥12 weeks apart). Treatment: lifelong anticoagulation (warfarin).",
    reference: "Janeway's Immunobiology, 10th Ed.",
  },
  {
    id: "imm-008",
    title: "Syphilis Screening (RPR/VDRL)",
    department: "Immunology / Serology",
    difficulty: "Beginner",
    patientAge: 35,
    patientGender: "Male",
    clinicalPresentation: "Painless genital ulcer (chancre) for 2 weeks, bilateral inguinal lymphadenopathy.",
    history: "Men who have sex with men (MSM). No prior STI testing.",
    sampleType: "Blood (serum)",
    laboratoryFindings: [
      "RPR (rapid plasma reagin): Reactive, titer 1:32",
      "FTA-ABS (fluorescent treponemal antibody absorbed): Positive",
      "Treponema pallidum particle agglutination (TP-PA): Positive",
      "Dark-field microscopy of chancre: Spirochetes seen",
      "HIV test: Co-testing recommended (and negative in this case)",
    ],
    questions: [{
      question: "What is the role of RPR vs. FTA-ABS in syphilis testing?",
      options: [
        "RPR is confirmatory, FTA-ABS is screening",
        "RPR is non-treponemal (screening + monitoring), FTA-ABS is treponemal (confirmatory)",
        "Both are treponemal tests",
        "Both are non-treponemal tests",
      ],
      correctAnswer: 1,
      hint: "Non-treponemal tests use cardiolipin antigen and decrease with treatment; treponemal tests remain positive for life.",
    }],
    explanation: "Traditional algorithm: Non-treponemal test (RPR/VDRL) for screening → Treponemal test (FTA-ABS/TP-PA) for confirmation. RPR titer used to monitor treatment response (should decline 4-fold by 6–12 months). Treponemal tests remain positive for life (scar marker). Reverse algorithm (used by many labs): treponemal test first → RPR for confirmation and monitoring.",
    reference: "Janeway's Immunobiology, 10th Ed.; CDC STI Guidelines.",
  },
  {
    id: "imm-009",
    title: "Common Variable Immunodeficiency (CVID)",
    department: "Immunology / Serology",
    difficulty: "Advanced",
    patientAge: 25,
    patientGender: "Male",
    clinicalPresentation: "Recurrent sinopulmonary infections (pneumonia 4× in 2 years, chronic sinusitis), and chronic diarrhea (Giardia).",
    history: "Symptoms began in late teens. No family history of immunodeficiency.",
    sampleType: "Blood (serum)",
    laboratoryFindings: [
      "Serum IgG: 180 mg/dL (severely low, normal: 700–1600)",
      "Serum IgA: <7 mg/dL (undetectable)",
      "Serum IgM: 25 mg/dL (low)",
      "CBC: Normal lymphocyte count",
      "Flow cytometry: Normal CD19+ B cells in number, decreased switched memory B cells (CD27+IgD−)",
      "Vaccine responses: Poor antibody response to pneumococcal and tetanus vaccines",
    ],
    questions: [{
      question: "What is the hallmark finding in CVID?",
      options: [
        "Absent B cells",
        "Low immunoglobulins (≥2 classes) with poor vaccine responses despite normal B cell numbers",
        "Low T cells",
        "High IgE",
      ],
      correctAnswer: 1,
      hint: "B cells are present but fail to differentiate into antibody-secreting plasma cells.",
    }],
    explanation: "CVID is the most common symptomatic primary immunodeficiency in adults. Diagnosis: ↓IgG (always) + ↓IgA and/or IgM, impaired vaccine responses, B cells present but functionally defective. Exclude secondary causes (drugs, protein loss, malignancy). Treatment: lifelong immunoglobulin replacement therapy (IVIG/SCIG). Increased risk of autoimmunity, granulomas, and lymphoma.",
    reference: "Janeway's Immunobiology, 10th Ed.",
  },
  {
    id: "imm-010",
    title: "Transplant Rejection (Crossmatch)",
    department: "Immunology / Serology",
    difficulty: "Advanced",
    patientAge: 45,
    patientGender: "Male",
    clinicalPresentation: "Pre-transplant evaluation for kidney transplant. Previous failed transplant and blood transfusions.",
    history: "End-stage renal disease on hemodialysis. Previous cadaveric kidney transplant failed after 2 years (chronic rejection).",
    sampleType: "Blood (serum)",
    laboratoryFindings: [
      "Panel reactive antibody (PRA): 85% (highly sensitized)",
      "HLA antibody screen: Positive — anti-HLA Class I (A2, B44) and Class II (DR7) antibodies",
      "Virtual crossmatch: Incompatible with donor (donor has HLA-A2)",
      "Flow cytometry crossmatch (FCXM): T-cell positive, B-cell positive",
      "CDC complement-dependent lymphocytotoxicity crossmatch: Positive (cell death >20%)",
    ],
    questions: [{
      question: "What does a positive crossmatch mean for transplantation?",
      options: [
        "Transplant can proceed safely",
        "Recipient has preformed antibodies against donor HLA → high risk of hyperacute rejection → contraindication",
        "Only delayed rejection possible",
        "Donor and recipient are ABO incompatible",
      ],
      correctAnswer: 1,
      hint: "Preformed donor-specific antibodies cause immediate complement-mediated graft destruction.",
    }],
    explanation: "Positive crossmatch = recipient has preformed anti-donor HLA antibodies → hyperacute rejection within minutes (complement-mediated vascular thrombosis and graft necrosis). This is an absolute contraindication to transplant. PRA >85% = highly sensitized, difficult to find compatible donor. Desensitization protocols (plasmapheresis, IVIG, rituximab) may be attempted for living donors.",
    reference: "Janeway's Immunobiology, 10th Ed.; ASHI Standards.",
  },
];
