import { LabCase } from "./types";

export const microbiologyCases: LabCase[] = [
  {
    id: "micro-001",
    title: "Urinary Tract Infection",
    department: "Microbiology",
    difficulty: "Beginner",
    patientAge: 34,
    patientGender: "Female",
    clinicalPresentation: "Dysuria, urinary frequency, suprapubic pain, and low-grade fever (38.1°C) for 2 days.",
    history: "Sexually active, no recent antibiotics. One prior UTI episode last year.",
    sampleType: "Mid-stream urine",
    laboratoryFindings: [
      "Gram stain: Gram-negative rods",
      "MacConkey agar: Pink (lactose-fermenting) colonies, >10⁵ CFU/mL",
      "EMB agar: Metallic green sheen",
      "Indole test: Positive",
      "Citrate: Negative",
    ],
    questions: [{
      question: "Which organism is the most probable pathogen?",
      options: ["Klebsiella pneumoniae", "Escherichia coli", "Proteus mirabilis", "Pseudomonas aeruginosa"],
      correctAnswer: 1,
      hint: "This organism is indole-positive and produces a metallic green sheen on EMB agar.",
    }],
    explanation: "E. coli is the most common cause of uncomplicated UTIs (~80%). Lactose fermentation on MacConkey (pink colonies), metallic green sheen on EMB, and indole positivity are classic identification markers. IMViC pattern: ++−−.",
    reference: "Bailey & Scott's Diagnostic Microbiology, 15th Ed.",
  },
  {
    id: "micro-002",
    title: "Community-Acquired Pneumonia",
    department: "Microbiology",
    difficulty: "Beginner",
    patientAge: 65,
    patientGender: "Male",
    clinicalPresentation: "Productive cough with rusty sputum, fever (39.2°C), chest pain, and dyspnea for 3 days.",
    history: "40 pack-year smoker, COPD. CXR shows right lower lobe consolidation.",
    sampleType: "Sputum",
    laboratoryFindings: [
      "Gram stain: Gram-positive lancet-shaped diplococci",
      "Blood agar: α-hemolytic colonies with central depression (draughtsman appearance)",
      "Optochin sensitivity: Sensitive (zone >14 mm)",
      "Bile solubility: Positive",
    ],
    questions: [{
      question: "What is the causative organism?",
      options: ["Streptococcus pyogenes", "Streptococcus pneumoniae", "Staphylococcus aureus", "Haemophilus influenzae"],
      correctAnswer: 1,
      hint: "α-hemolytic, optochin-sensitive, and bile-soluble Gram-positive diplococci.",
    }],
    explanation: "S. pneumoniae is the #1 cause of community-acquired pneumonia. The combination of lancet-shaped Gram-positive diplococci, α-hemolysis, optochin sensitivity, and bile solubility is pathognomonic.",
    reference: "Jawetz, Melnick & Adelberg's Medical Microbiology, 28th Ed.",
  },
  {
    id: "micro-003",
    title: "Surgical Wound Infection (MRSA)",
    department: "Microbiology",
    difficulty: "Intermediate",
    patientAge: 45,
    patientGender: "Male",
    clinicalPresentation: "Post-operative wound erythema, purulent drainage, and fever (38.5°C) 5 days after abdominal surgery.",
    history: "Type 2 diabetes, BMI 32. Elective cholecystectomy.",
    sampleType: "Wound swab",
    laboratoryFindings: [
      "Gram stain: Gram-positive cocci in grape-like clusters",
      "Blood agar: Golden-yellow colonies with β-hemolysis",
      "Mannitol salt agar: Yellow halo (mannitol fermenter)",
      "Catalase: Positive",
      "Coagulase (tube): Positive",
      "Oxacillin screen: Resistant",
    ],
    questions: [{
      question: "What is the most likely identification and resistance profile?",
      options: ["MSSA", "MRSA", "CoNS (methicillin-resistant)", "Enterococcus faecalis"],
      correctAnswer: 1,
      hint: "Coagulase-positive staphylococcus that is oxacillin-resistant.",
    }],
    explanation: "Gram-positive cocci in clusters + catalase positive = Staphylococcus. Coagulase positive = S. aureus. Oxacillin resistance indicates MRSA (mecA gene → PBP2a). Treatment: Vancomycin IV or TMP-SMX for mild cases.",
    reference: "Bailey & Scott's Diagnostic Microbiology, 15th Ed.",
  },
  {
    id: "micro-004",
    title: "Neonatal Meningitis",
    department: "Microbiology",
    difficulty: "Advanced",
    patientAge: 0,
    patientGender: "Neonate",
    clinicalPresentation: "5-day-old neonate with poor feeding, lethargy, bulging fontanelle, and seizures.",
    history: "Full-term vaginal delivery. Mother GBS-negative. CSF: WBC 2500/µL (90% PMN), glucose 15 mg/dL, protein 350 mg/dL.",
    sampleType: "CSF",
    laboratoryFindings: [
      "Gram stain: Gram-negative bacilli",
      "MacConkey agar: Pink mucoid colonies (lactose fermenter)",
      "Indole: Negative",
      "Citrate: Positive",
      "Urease: Positive",
      "Non-motile, string test positive (>5 mm)",
    ],
    questions: [{
      question: "What is the causative organism?",
      options: ["Escherichia coli K1", "Klebsiella pneumoniae", "Listeria monocytogenes", "Group B Streptococcus"],
      correctAnswer: 1,
      hint: "Lactose-fermenting, non-motile, encapsulated GNR with urease positivity and IMViC: −−++.",
    }],
    explanation: "K. pneumoniae is non-motile, urease-positive, citrate-positive, with mucoid capsule. IMViC: −−++. It is the second most common cause of neonatal Gram-negative meningitis after E. coli K1.",
    reference: "Jawetz, Melnick & Adelberg's Medical Microbiology, 28th Ed.",
  },
  {
    id: "micro-005",
    title: "Foodborne Gastroenteritis",
    department: "Microbiology",
    difficulty: "Beginner",
    patientAge: 22,
    patientGender: "Male",
    clinicalPresentation: "Acute watery diarrhea, abdominal cramps, nausea, and low-grade fever after eating undercooked chicken 24 hours ago.",
    history: "Otherwise healthy. Attended a barbecue yesterday.",
    sampleType: "Stool culture",
    laboratoryFindings: [
      "Gram stain: Gram-negative curved rods (gull-wing/S-shaped)",
      "Growth on Campy-BAP at 42°C (microaerophilic)",
      "Oxidase: Positive",
      "Catalase: Positive",
      "Hippurate hydrolysis: Positive",
    ],
    questions: [{
      question: "Which organism is most likely?",
      options: ["Salmonella enteritidis", "Campylobacter jejuni", "Shigella sonnei", "Vibrio cholerae"],
      correctAnswer: 1,
      hint: "Curved Gram-negative rods growing at 42°C under microaerophilic conditions.",
    }],
    explanation: "Campylobacter jejuni is the leading bacterial cause of gastroenteritis worldwide. Characteristic features: curved/spiral GNR, growth at 42°C, microaerophilic, oxidase+, hippurate hydrolysis positive (distinguishes from C. coli).",
    reference: "Bailey & Scott's Diagnostic Microbiology, 15th Ed.",
  },
  {
    id: "micro-006",
    title: "Pharyngitis with Rheumatic Fever Risk",
    department: "Microbiology",
    difficulty: "Beginner",
    patientAge: 8,
    patientGender: "Child",
    clinicalPresentation: "Severe sore throat, odynophagia, fever (39°C), tonsillar exudates, and tender anterior cervical lymphadenopathy.",
    history: "No cough or rhinorrhea. School outbreak reported.",
    sampleType: "Throat swab",
    laboratoryFindings: [
      "Gram stain: Gram-positive cocci in chains",
      "Blood agar: Large zone of β-hemolysis",
      "Catalase: Negative",
      "Bacitracin: Sensitive",
      "PYR test: Positive",
      "Rapid antigen test: Positive for Group A",
    ],
    questions: [{
      question: "What is the causative organism?",
      options: ["Streptococcus pneumoniae", "Streptococcus pyogenes (GAS)", "Streptococcus agalactiae (GBS)", "Corynebacterium diphtheriae"],
      correctAnswer: 1,
      hint: "β-hemolytic, bacitracin-sensitive, PYR-positive streptococcus.",
    }],
    explanation: "S. pyogenes (Group A Streptococcus) causes pharyngitis with potential sequelae of rheumatic fever and post-streptococcal glomerulonephritis. Key markers: β-hemolysis, bacitracin-sensitive, PYR-positive, Lancefield Group A.",
    reference: "Jawetz, Melnick & Adelberg's Medical Microbiology, 28th Ed.",
  },
  {
    id: "micro-007",
    title: "Hospital-Acquired Pneumonia (Ventilator)",
    department: "Microbiology",
    difficulty: "Intermediate",
    patientAge: 58,
    patientGender: "Male",
    clinicalPresentation: "ICU patient on mechanical ventilation for 7 days develops new fever, purulent secretions, and worsening oxygenation.",
    history: "Admitted for polytrauma. Multiple courses of broad-spectrum antibiotics.",
    sampleType: "Bronchoalveolar lavage (BAL)",
    laboratoryFindings: [
      "Gram stain: Gram-negative rods",
      "Blood agar: Blue-green pigment, grape-like odor",
      "MacConkey: Non-lactose fermenter (NLF), colorless colonies",
      "Oxidase: Positive",
      "Growth at 42°C: Positive",
      "TSI: K/K (alkaline/alkaline), no gas, no H₂S",
    ],
    questions: [{
      question: "What is the most likely pathogen?",
      options: ["Acinetobacter baumannii", "Pseudomonas aeruginosa", "Stenotrophomonas maltophilia", "Klebsiella pneumoniae"],
      correctAnswer: 1,
      hint: "Oxidase-positive, non-lactose fermenting GNR with blue-green pigment and fruity odor.",
    }],
    explanation: "Pseudomonas aeruginosa is a major cause of ventilator-associated pneumonia. Key identifiers: pyocyanin (blue-green pigment), grape-like odor, oxidase+, NLF, growth at 42°C. Intrinsically resistant to many antibiotics.",
    reference: "Bailey & Scott's Diagnostic Microbiology, 15th Ed.",
  },
  {
    id: "micro-008",
    title: "Enteric Fever (Typhoid)",
    department: "Microbiology",
    difficulty: "Intermediate",
    patientAge: 30,
    patientGender: "Male",
    clinicalPresentation: "Stepladder fever over 10 days, headache, abdominal pain, constipation followed by diarrhea, rose spots on abdomen.",
    history: "Returned from travel to South Asia 2 weeks ago.",
    sampleType: "Blood culture",
    laboratoryFindings: [
      "Gram stain: Gram-negative bacilli",
      "MacConkey agar: Non-lactose fermenter (NLF), colorless colonies",
      "TSI: K/A with H₂S (black butt), no gas",
      "Citrate: Negative",
      "Urease: Negative",
      "Motile (peritrichous flagella)",
      "Widal test: O titer 1:320, H titer 1:640",
    ],
    questions: [{
      question: "Which organism is causing this enteric fever?",
      options: ["Salmonella typhi", "Salmonella paratyphi A", "Shigella dysenteriae", "Yersinia enterocolitica"],
      correctAnswer: 0,
      hint: "NLF with H₂S on TSI, citrate-negative, urease-negative, and elevated Widal titers.",
    }],
    explanation: "Salmonella typhi causes typhoid fever. Key features: NLF, H₂S on TSI, citrate-negative (unlike other Salmonella), urease-negative. Widal test detects anti-O and anti-H antibodies. Blood culture is the gold standard in week 1.",
    reference: "Jawetz, Melnick & Adelberg's Medical Microbiology, 28th Ed.",
  },
  {
    id: "micro-009",
    title: "Bacterial Meningitis in Adult",
    department: "Microbiology",
    difficulty: "Intermediate",
    patientAge: 20,
    patientGender: "Male",
    clinicalPresentation: "Sudden onset severe headache, neck stiffness, photophobia, petechial rash, and altered consciousness.",
    history: "College student living in dormitory. No vaccination history for meningitis.",
    sampleType: "CSF",
    laboratoryFindings: [
      "CSF appearance: Turbid",
      "CSF WBC: 3000/µL (95% PMN)",
      "CSF glucose: 20 mg/dL (blood glucose 90)",
      "CSF protein: 400 mg/dL",
      "Gram stain: Gram-negative diplococci (kidney-bean shaped, intracellular)",
      "Chocolate agar: Growth in 5% CO₂",
      "Oxidase: Positive",
    ],
    questions: [{
      question: "What is the causative organism?",
      options: ["Streptococcus pneumoniae", "Neisseria meningitidis", "Haemophilus influenzae", "Listeria monocytogenes"],
      correctAnswer: 1,
      hint: "Gram-negative intracellular diplococci in a college student with petechial rash.",
    }],
    explanation: "Neisseria meningitidis is a leading cause of bacterial meningitis in adolescents/young adults in close quarters. Key: Gram-negative kidney-bean diplococci, often intracellular in PMNs, oxidase+, growth on chocolate agar with CO₂. Petechial rash suggests meningococcemia.",
    reference: "Jawetz, Melnick & Adelberg's Medical Microbiology, 28th Ed.",
  },
  {
    id: "micro-010",
    title: "Infective Endocarditis",
    department: "Microbiology",
    difficulty: "Advanced",
    patientAge: 42,
    patientGender: "Male",
    clinicalPresentation: "Prolonged fever, new heart murmur, Janeway lesions on palms, and Osler nodes on fingertips.",
    history: "History of IV drug use. Echocardiography shows tricuspid valve vegetations.",
    sampleType: "Blood culture (3 sets)",
    laboratoryFindings: [
      "Gram stain: Gram-positive cocci in clusters",
      "Blood agar: Golden colonies, β-hemolytic",
      "Catalase: Positive",
      "Coagulase: Positive",
      "All 3 blood culture sets positive within 12 hours",
    ],
    questions: [{
      question: "What is the most likely causative organism in this IV drug user?",
      options: ["Streptococcus viridans", "Staphylococcus aureus", "Enterococcus faecalis", "HACEK organisms"],
      correctAnswer: 1,
      hint: "Most common cause of acute endocarditis in IV drug users, affecting the tricuspid valve.",
    }],
    explanation: "S. aureus is the #1 cause of infective endocarditis in IV drug users, typically affecting the right-sided (tricuspid) valve. Modified Duke criteria require 2 major or 1 major + 3 minor criteria. Three positive blood cultures with a typical organism is a major criterion.",
    reference: "Bailey & Scott's Diagnostic Microbiology, 15th Ed.",
  },
  {
    id: "micro-011",
    title: "Neonatal Sepsis (GBS)",
    department: "Microbiology",
    difficulty: "Intermediate",
    patientAge: 0,
    patientGender: "Neonate",
    clinicalPresentation: "3-day-old neonate with respiratory distress, poor feeding, temperature instability, and hypotension.",
    history: "Premature delivery at 35 weeks. Mother did not receive intrapartum antibiotic prophylaxis. Prolonged rupture of membranes (>18 hours).",
    sampleType: "Blood culture",
    laboratoryFindings: [
      "Gram stain: Gram-positive cocci in short chains",
      "Blood agar: Narrow zone of β-hemolysis",
      "Catalase: Negative",
      "CAMP test: Positive (arrowhead hemolysis)",
      "Hippurate hydrolysis: Positive",
      "Bacitracin: Resistant",
      "Lancefield grouping: Group B",
    ],
    questions: [{
      question: "What is the causative organism?",
      options: ["Streptococcus pyogenes", "Streptococcus agalactiae (GBS)", "Listeria monocytogenes", "Escherichia coli"],
      correctAnswer: 1,
      hint: "CAMP-test positive, hippurate-positive, bacitracin-resistant β-hemolytic streptococcus.",
    }],
    explanation: "S. agalactiae (Group B Streptococcus) is the leading cause of early-onset neonatal sepsis. Identifiers: narrow β-hemolysis, CAMP+, hippurate+, bacitracin-resistant. Maternal screening at 35–37 weeks and intrapartum antibiotics prevent vertical transmission.",
    reference: "Jawetz, Melnick & Adelberg's Medical Microbiology, 28th Ed.",
  },
  {
    id: "micro-012",
    title: "Tuberculous Meningitis",
    department: "Microbiology",
    difficulty: "Advanced",
    patientAge: 35,
    patientGender: "Male",
    clinicalPresentation: "Subacute headache over 2 weeks, low-grade fever, cranial nerve VI palsy, confusion, and weight loss.",
    history: "HIV-positive, CD4 count 150 cells/µL. Emigrated from endemic region.",
    sampleType: "CSF",
    laboratoryFindings: [
      "CSF: Lymphocytic pleocytosis (300 WBC/µL, 85% lymphocytes)",
      "CSF glucose: 25 mg/dL (markedly low)",
      "CSF protein: 250 mg/dL (elevated)",
      "Ziehl-Neelsen stain: Acid-fast bacilli (AFB) seen",
      "Lowenstein-Jensen medium: Rough, buff-colored colonies after 4 weeks",
      "GeneXpert MTB/RIF: Mycobacterium tuberculosis detected, rifampicin-sensitive",
    ],
    questions: [{
      question: "What is the diagnosis?",
      options: ["Cryptococcal meningitis", "Tuberculous meningitis", "Viral meningitis", "Neurosyphilis"],
      correctAnswer: 1,
      hint: "AFB-positive CSF with lymphocytic pleocytosis, low glucose, and high protein in an immunocompromised patient.",
    }],
    explanation: "TB meningitis presents with subacute onset, lymphocytic CSF, very low glucose, and high protein. AFB stain has low sensitivity (~20%) in CSF but GeneXpert improves detection. LJ medium grows rough, buff-colored colonies in 2–8 weeks. Treatment: RIPE regimen + corticosteroids.",
    reference: "Bailey & Scott's Diagnostic Microbiology, 15th Ed.; WHO TB Guidelines.",
  },
  {
    id: "micro-013",
    title: "Antibiotic-Associated Diarrhea",
    department: "Microbiology",
    difficulty: "Intermediate",
    patientAge: 72,
    patientGender: "Female",
    clinicalPresentation: "Profuse watery diarrhea (>10 stools/day), abdominal cramping, fever (38.8°C), and leukocytosis (WBC 22,000/µL) during hospitalization.",
    history: "Received clindamycin for 10 days post hip replacement surgery.",
    sampleType: "Stool",
    laboratoryFindings: [
      "Stool toxin EIA: Positive for toxin A and toxin B",
      "GDH (glutamate dehydrogenase) antigen: Positive",
      "NAAT (PCR): tcdB gene detected",
      "Stool culture on CCFA: Yellow, ground-glass colonies with horse-stable odor",
    ],
    questions: [{
      question: "What organism is responsible?",
      options: ["Clostridium perfringens", "Clostridioides difficile", "Staphylococcus aureus", "Bacillus cereus"],
      correctAnswer: 1,
      hint: "Toxin A/B positive organism causing antibiotic-associated pseudomembranous colitis.",
    }],
    explanation: "C. difficile is the most common cause of healthcare-associated diarrhea. Risk factors: antibiotics (clindamycin, fluoroquinolones, cephalosporins), elderly, hospitalized. Diagnosis: 2-step algorithm (GDH + toxin EIA) or NAAT. Treatment: oral vancomycin or fidaxomicin.",
    reference: "Bailey & Scott's Diagnostic Microbiology, 15th Ed.; IDSA/SHEA C. difficile Guidelines.",
  },
  {
    id: "micro-014",
    title: "Skin and Soft Tissue Infection (Necrotizing Fasciitis)",
    department: "Microbiology",
    difficulty: "Advanced",
    patientAge: 55,
    patientGender: "Male",
    clinicalPresentation: "Rapidly progressing painful erythema of the right lower extremity with crepitus, bullae formation, and systemic toxicity (BP 80/50, HR 130).",
    history: "Uncontrolled diabetes, minor skin abrasion 3 days ago.",
    sampleType: "Deep tissue biopsy / surgical specimen",
    laboratoryFindings: [
      "Gram stain: Mixed flora — Gram-positive cocci in chains and Gram-negative rods",
      "Blood agar: β-hemolytic colonies",
      "Anaerobic culture: Gas-producing organisms",
      "Tissue pathology: Necrosis of fascia with PMN infiltration and bacterial colonies",
    ],
    questions: [{
      question: "What is the most likely diagnosis?",
      options: ["Cellulitis", "Type I (polymicrobial) necrotizing fasciitis", "Gas gangrene (C. perfringens)", "Erysipelas"],
      correctAnswer: 1,
      hint: "Mixed flora with both aerobic and anaerobic organisms causing fascial necrosis with gas production.",
    }],
    explanation: "Type I necrotizing fasciitis is polymicrobial (aerobic + anaerobic synergy), common in diabetics. Crepitus indicates subcutaneous gas. Requires emergent surgical debridement + broad-spectrum antibiotics. Type II is monomicrobial (usually GAS). Mortality is 20–40%.",
    reference: "Bailey & Scott's Diagnostic Microbiology, 15th Ed.",
  },
  {
    id: "micro-015",
    title: "Catheter-Related Bloodstream Infection",
    department: "Microbiology",
    difficulty: "Intermediate",
    patientAge: 60,
    patientGender: "Female",
    clinicalPresentation: "Fever and chills associated with central venous catheter (CVC) in situ for 14 days. No other focus of infection identified.",
    history: "Receiving TPN through subclavian CVC for short bowel syndrome.",
    sampleType: "Paired blood cultures (peripheral + catheter)",
    laboratoryFindings: [
      "Gram stain: Gram-positive cocci in clusters",
      "Blood agar: White, non-hemolytic colonies",
      "Catalase: Positive",
      "Coagulase: Negative",
      "Novobiocin: Sensitive",
      "Differential time to positivity (DTP): Catheter culture positive 2 hours before peripheral",
    ],
    questions: [{
      question: "What is the most likely organism?",
      options: ["Staphylococcus aureus", "Staphylococcus epidermidis", "Enterococcus faecium", "Candida albicans"],
      correctAnswer: 1,
      hint: "Coagulase-negative, novobiocin-sensitive staphylococcus — the most common cause of catheter-related infections.",
    }],
    explanation: "S. epidermidis (CoNS) is the #1 cause of CVC-related bloodstream infections due to biofilm formation on indwelling devices. DTP ≥2 hours suggests catheter as the source. Treatment: catheter removal ± vancomycin. Novobiocin sensitivity distinguishes from S. saprophyticus.",
    reference: "Bailey & Scott's Diagnostic Microbiology, 15th Ed.",
  },
  {
    id: "micro-016",
    title: "Otitis Media in Child",
    department: "Microbiology",
    difficulty: "Beginner",
    patientAge: 3,
    patientGender: "Child",
    clinicalPresentation: "Ear pain, fever (38.5°C), irritability, pulling at right ear. Otoscopic exam shows bulging, erythematous tympanic membrane.",
    history: "Attends daycare. Third episode of otitis media this year.",
    sampleType: "Middle ear fluid (tympanocentesis)",
    laboratoryFindings: [
      "Gram stain: Gram-negative coccobacilli",
      "Chocolate agar: Growth (requires X and V factors)",
      "Blood agar: No growth (satellite phenomenon near S. aureus streak)",
      "β-lactamase: Positive",
    ],
    questions: [{
      question: "What organism is most likely?",
      options: ["Streptococcus pneumoniae", "Moraxella catarrhalis", "Haemophilus influenzae (non-typeable)", "Pseudomonas aeruginosa"],
      correctAnswer: 2,
      hint: "Requires both X (hemin) and V (NAD) factors for growth.",
    }],
    explanation: "Non-typeable H. influenzae is a top-3 cause of otitis media (with S. pneumoniae and M. catarrhalis). Requires X+V factors (chocolate agar), satellite test positive. β-lactamase production is common, requiring amoxicillin-clavulanate.",
    reference: "Jawetz, Melnick & Adelberg's Medical Microbiology, 28th Ed.",
  },
  {
    id: "micro-017",
    title: "Gonorrhea",
    department: "Microbiology",
    difficulty: "Beginner",
    patientAge: 25,
    patientGender: "Male",
    clinicalPresentation: "Purulent urethral discharge and dysuria for 3 days.",
    history: "Sexually active with multiple partners, inconsistent condom use.",
    sampleType: "Urethral swab",
    laboratoryFindings: [
      "Gram stain: Gram-negative intracellular diplococci within PMNs",
      "Thayer-Martin (modified) agar: Oxidase-positive colonies",
      "Sugar fermentation: Glucose only (not maltose, sucrose, or lactose)",
      "NAAT: Positive for Neisseria gonorrhoeae",
    ],
    questions: [{
      question: "What is the diagnosis?",
      options: ["Chlamydia trachomatis urethritis", "Neisseria gonorrhoeae infection", "Ureaplasma urealyticum", "Trichomonas vaginalis"],
      correctAnswer: 1,
      hint: "Gram-negative intracellular diplococci that ferment glucose only.",
    }],
    explanation: "N. gonorrhoeae causes gonorrhea. Gram-negative diplococci seen intracellularly in PMNs on Gram stain of urethral discharge. Grows on selective Thayer-Martin agar. Ferments glucose only (vs. N. meningitidis: glucose + maltose). NAAT is the gold standard for diagnosis.",
    reference: "Jawetz, Melnick & Adelberg's Medical Microbiology, 28th Ed.",
  },
  {
    id: "micro-018",
    title: "Bacillary Dysentery",
    department: "Microbiology",
    difficulty: "Beginner",
    patientAge: 5,
    patientGender: "Child",
    clinicalPresentation: "Bloody mucoid diarrhea (10+ episodes/day), tenesmus, fever (39.5°C), and abdominal cramps for 2 days.",
    history: "Outbreak in daycare center. Poor hand hygiene practices.",
    sampleType: "Stool culture",
    laboratoryFindings: [
      "Gram stain: Gram-negative bacilli",
      "MacConkey agar: Non-lactose fermenter (NLF), colorless colonies",
      "TSI: K/A, no gas, no H₂S",
      "Non-motile",
      "Serotyping: Group A (S. dysenteriae)",
    ],
    questions: [{
      question: "What is the causative organism?",
      options: ["Campylobacter jejuni", "Shigella dysenteriae", "EHEC (E. coli O157:H7)", "Vibrio cholerae"],
      correctAnswer: 1,
      hint: "Non-motile NLF with no gas and no H₂S on TSI causing bloody dysentery.",
    }],
    explanation: "Shigella species cause bacillary dysentery with bloody mucoid stools. Shigella is non-motile, NLF, and produces no gas or H₂S on TSI. Very low infectious dose (10–100 organisms). S. dysenteriae type 1 produces Shiga toxin. Transmitted fecal-oral.",
    reference: "Bailey & Scott's Diagnostic Microbiology, 15th Ed.",
  },
  {
    id: "micro-019",
    title: "Cholera",
    department: "Microbiology",
    difficulty: "Intermediate",
    patientAge: 28,
    patientGender: "Male",
    clinicalPresentation: "Profuse rice-water diarrhea (liters of watery stool), severe dehydration, sunken eyes, poor skin turgor, and muscle cramps.",
    history: "Lives in area with recent flooding and contaminated water supply.",
    sampleType: "Rectal swab / stool",
    laboratoryFindings: [
      "Gram stain: Gram-negative comma-shaped (curved) rods",
      "TCBS agar: Large yellow colonies (sucrose fermenter)",
      "Oxidase: Positive",
      "String test: Positive",
      "Dark-field microscopy: Darting motility",
      "Serotyping: O1, Ogawa serotype",
    ],
    questions: [{
      question: "What organism is causing this epidemic diarrhea?",
      options: ["ETEC", "Vibrio cholerae", "Cryptosporidium parvum", "Giardia lamblia"],
      correctAnswer: 1,
      hint: "Comma-shaped GNR, yellow on TCBS, oxidase-positive, causing rice-water diarrhea.",
    }],
    explanation: "V. cholerae O1/O139 causes cholera via cholera toxin (activates adenylate cyclase → massive secretory diarrhea). Grows as yellow colonies on TCBS (sucrose fermenter). Treatment: aggressive fluid replacement (ORS) ± doxycycline or azithromycin.",
    reference: "Jawetz, Melnick & Adelberg's Medical Microbiology, 28th Ed.",
  },
  {
    id: "micro-020",
    title: "Prosthetic Joint Infection",
    department: "Microbiology",
    difficulty: "Advanced",
    patientAge: 70,
    patientGender: "Female",
    clinicalPresentation: "Chronic pain and limited range of motion in left knee prosthesis implanted 18 months ago. Low-grade fever.",
    history: "Total knee arthroplasty 18 months ago. Gradual onset of symptoms over 3 months.",
    sampleType: "Synovial fluid + periprosthetic tissue (multiple samples)",
    laboratoryFindings: [
      "Synovial fluid WBC: 12,000/µL (85% PMN)",
      "Gram stain: Gram-positive cocci in clusters (seen in 2 of 5 tissue samples)",
      "Prolonged culture (14 days): Growth at day 7",
      "Catalase: Positive",
      "Coagulase: Negative",
      "Biofilm formation assay: Positive",
    ],
    questions: [{
      question: "What is the most likely organism in this chronic prosthetic joint infection?",
      options: ["Staphylococcus aureus", "Cutibacterium acnes", "Staphylococcus epidermidis", "Enterococcus faecalis"],
      correctAnswer: 2,
      hint: "Coagulase-negative staphylococcus forming biofilm on prosthetic material — classic for chronic PJI.",
    }],
    explanation: "S. epidermidis is the most common cause of chronic/late prosthetic joint infection due to biofilm formation on implant surfaces. Multiple tissue samples (≥3–5) are needed for diagnosis. Sonication of removed implants improves culture sensitivity. Treatment: implant exchange + prolonged antibiotics.",
    reference: "Bailey & Scott's Diagnostic Microbiology, 15th Ed.; IDSA PJI Guidelines.",
  },
  {
    id: "micro-021",
    title: "Diphtheria",
    department: "Microbiology",
    difficulty: "Intermediate",
    patientAge: 7,
    patientGender: "Child",
    clinicalPresentation: "Sore throat, low-grade fever, bull-neck swelling, and a grayish-white pseudomembrane over the pharynx.",
    history: "Unvaccinated child from rural area.",
    sampleType: "Throat swab",
    laboratoryFindings: [
      "Gram stain: Gram-positive rods in palisade/Chinese-letter arrangement",
      "Tellurite agar: Black colonies",
      "Loeffler serum slope: Rapid growth, metachromatic granules with Albert stain",
      "Elek test: Positive (toxin-producing strain)",
    ],
    questions: [{
      question: "What is the causative organism?",
      options: ["Streptococcus pyogenes", "Corynebacterium diphtheriae", "Arcanobacterium haemolyticum", "Fusobacterium necrophorum"],
      correctAnswer: 1,
      hint: "Gram-positive rods with metachromatic granules, black on tellurite agar, Elek test positive.",
    }],
    explanation: "C. diphtheriae causes diphtheria. Identified by: Chinese-letter arrangement on Gram stain, metachromatic (volutin) granules, black colonies on potassium tellurite agar. Elek test confirms toxin production. Toxin (encoded by β-phage) causes myocarditis and neuropathy. Treatment: antitoxin + penicillin/erythromycin.",
    reference: "Jawetz, Melnick & Adelberg's Medical Microbiology, 28th Ed.",
  },
  {
    id: "micro-022",
    title: "Fungal Meningitis (Cryptococcus)",
    department: "Microbiology",
    difficulty: "Advanced",
    patientAge: 38,
    patientGender: "Male",
    clinicalPresentation: "Insidious headache over 2 weeks, fever, neck stiffness, and visual changes. Confused but no focal neurological deficits.",
    history: "HIV-positive, CD4 count 45 cells/µL, non-compliant with ART.",
    sampleType: "CSF",
    laboratoryFindings: [
      "CSF: Opening pressure markedly elevated (>30 cm H₂O)",
      "CSF WBC: 50/µL (predominantly lymphocytes)",
      "CSF glucose: 30 mg/dL (low), protein: 100 mg/dL (elevated)",
      "India ink: Encapsulated budding yeast cells with wide clear halo",
      "Cryptococcal antigen (CrAg) lateral flow: Positive (titer 1:1024)",
      "Sabouraud dextrose agar: Mucoid cream-colored colonies",
    ],
    questions: [{
      question: "What is the causative organism?",
      options: ["Candida albicans", "Cryptococcus neoformans", "Histoplasma capsulatum", "Aspergillus fumigatus"],
      correctAnswer: 1,
      hint: "Encapsulated yeast on India ink with positive CrAg in an AIDS patient with meningitis.",
    }],
    explanation: "C. neoformans causes meningitis in severely immunocompromised (CD4 <100). India ink shows encapsulated yeast with wide halo. CrAg (lateral flow assay) is highly sensitive/specific. Treatment: amphotericin B + flucytosine induction → fluconazole maintenance. Serial lumbar punctures for elevated ICP.",
    reference: "Bailey & Scott's Diagnostic Microbiology, 15th Ed.; WHO Cryptococcal Guidelines.",
  },
  {
    id: "micro-023",
    title: "Peptic Ulcer Disease",
    department: "Microbiology",
    difficulty: "Beginner",
    patientAge: 45,
    patientGender: "Male",
    clinicalPresentation: "Epigastric burning pain, worse on empty stomach, relieved by food/antacids, nausea. Endoscopy shows duodenal ulcer.",
    history: "Chronic NSAID use. No alarm features.",
    sampleType: "Gastric biopsy",
    laboratoryFindings: [
      "Gram stain: Gram-negative curved/spiral rods",
      "Rapid urease test (CLO test): Positive (color change to pink within 1 hour)",
      "Urea breath test (¹³C): Positive",
      "Stool antigen: Positive",
      "Culture on Skirrow medium: Microaerophilic growth at 37°C after 5–7 days",
    ],
    questions: [{
      question: "What organism is associated with this peptic ulcer?",
      options: ["Campylobacter jejuni", "Helicobacter pylori", "Vibrio cholerae", "Escherichia coli"],
      correctAnswer: 1,
      hint: "Spiral GNR that is strongly urease-positive and causes gastric/duodenal ulcers.",
    }],
    explanation: "H. pylori colonizes gastric mucosa and causes ~90% of duodenal ulcers. Potent urease producer (converts urea → ammonia to survive acidic pH). Diagnosis: urease test, urea breath test, stool antigen, or histology. Treatment: triple therapy (PPI + clarithromycin + amoxicillin).",
    reference: "Jawetz, Melnick & Adelberg's Medical Microbiology, 28th Ed.",
  },
  {
    id: "micro-024",
    title: "Urinary Tract Infection (Proteus)",
    department: "Microbiology",
    difficulty: "Beginner",
    patientAge: 68,
    patientGender: "Male",
    clinicalPresentation: "Dysuria, cloudy foul-smelling alkaline urine, and flank pain. History of recurrent kidney stones.",
    history: "Benign prostatic hyperplasia with urinary retention. Indwelling catheter for 2 weeks.",
    sampleType: "Urine",
    laboratoryFindings: [
      "Gram stain: Gram-negative rods",
      "MacConkey agar: Non-lactose fermenter (NLF), colorless colonies",
      "Swarming motility on blood agar",
      "TSI: K/A with H₂S, gas produced",
      "Urease: Strongly positive",
      "Indole: Negative",
      "Urine pH: 8.5 (alkaline)",
    ],
    questions: [{
      question: "What organism is causing this complicated UTI?",
      options: ["Escherichia coli", "Klebsiella pneumoniae", "Proteus mirabilis", "Enterobacter cloacae"],
      correctAnswer: 2,
      hint: "Swarming NLF with strong urease activity causing alkaline urine and struvite stones.",
    }],
    explanation: "Proteus mirabilis is a common cause of complicated/catheter-associated UTIs. Key features: swarming motility, strong urease (splits urea → ammonia → alkaline urine → struvite/staghorn stones), NLF, H₂S on TSI, indole-negative. P. vulgaris is indole-positive.",
    reference: "Bailey & Scott's Diagnostic Microbiology, 15th Ed.",
  },
  {
    id: "micro-025",
    title: "Brain Abscess",
    department: "Microbiology",
    difficulty: "Advanced",
    patientAge: 50,
    patientGender: "Male",
    clinicalPresentation: "Progressive headache, fever, focal neurological deficit (left-sided weakness), and seizures over 10 days.",
    history: "Recent dental extraction 3 weeks ago. No immunodeficiency.",
    sampleType: "Brain abscess aspirate",
    laboratoryFindings: [
      "Gram stain: Mixed flora — Gram-positive cocci + Gram-negative rods",
      "Anaerobic culture: Growth of anaerobic streptococci and Fusobacterium spp.",
      "Aerobic culture: Viridans streptococci",
      "CT head: Ring-enhancing lesion with surrounding edema",
    ],
    questions: [{
      question: "What is the most likely source of this polymicrobial brain abscess?",
      options: ["Hematogenous spread from endocarditis", "Odontogenic (dental) origin", "Post-neurosurgical complication", "Otogenic spread"],
      correctAnswer: 1,
      hint: "Recent dental procedure + mixed oral flora (viridans streptococci + anaerobes).",
    }],
    explanation: "Brain abscesses from dental origin are polymicrobial, containing oral flora (viridans streptococci, anaerobic streptococci, Fusobacterium). Contiguous spread from dental infections or post-procedural bacteremia. Treatment: surgical aspiration + metronidazole (anaerobes) + ceftriaxone (aerobes).",
    reference: "Bailey & Scott's Diagnostic Microbiology, 15th Ed.",
  },
  {
    id: "micro-026",
    title: "Whooping Cough",
    department: "Microbiology",
    difficulty: "Intermediate",
    patientAge: 4,
    patientGender: "Child",
    clinicalPresentation: "Paroxysmal cough with inspiratory 'whoop', post-tussive vomiting for 3 weeks. Initial catarrhal phase lasted 1 week.",
    history: "Incomplete vaccination (missed booster). Lymphocytosis (WBC 25,000/µL with 70% lymphocytes).",
    sampleType: "Nasopharyngeal swab",
    laboratoryFindings: [
      "Gram stain: Tiny Gram-negative coccobacilli",
      "Bordet-Gengou agar: Mercury-drop (bisected pearl) colonies after 3–5 days",
      "Regan-Lowe charcoal agar: Similar colony morphology",
      "Direct fluorescent antibody (DFA): Positive",
      "PCR (IS481 target): Positive",
    ],
    questions: [{
      question: "What is the causative organism?",
      options: ["Bordetella pertussis", "Bordetella parapertussis", "Mycoplasma pneumoniae", "Chlamydophila pneumoniae"],
      correctAnswer: 0,
      hint: "Mercury-drop colonies on Bordet-Gengou agar causing paroxysmal cough with whoop.",
    }],
    explanation: "B. pertussis causes whooping cough (pertussis). Grows on Bordet-Gengou (potato-glycerol-blood agar) or Regan-Lowe media. PCR is the preferred diagnostic method. Pertussis toxin promotes lymphocytosis. Treatment: macrolides (azithromycin). Vaccination: DTaP/Tdap prevents disease.",
    reference: "Jawetz, Melnick & Adelberg's Medical Microbiology, 28th Ed.",
  },
  {
    id: "micro-027",
    title: "Brucellosis",
    department: "Microbiology",
    difficulty: "Advanced",
    patientAge: 40,
    patientGender: "Male",
    clinicalPresentation: "Undulant fever (evening rise, morning fall), drenching sweats, arthralgia, hepatosplenomegaly for 4 weeks.",
    history: "Veterinarian who handles cattle and goats. Drinks unpasteurized milk.",
    sampleType: "Blood culture",
    laboratoryFindings: [
      "Blood culture: Positive after prolonged incubation (7 days) with CO₂ enrichment",
      "Gram stain: Tiny Gram-negative coccobacilli",
      "Catalase: Positive",
      "Oxidase: Positive",
      "Urease: Positive (slow)",
      "Standard agglutination test (SAT): Titer ≥1:160",
    ],
    questions: [{
      question: "What is the most likely organism?",
      options: ["Francisella tularensis", "Brucella melitensis", "Coxiella burnetii", "Yersinia pestis"],
      correctAnswer: 1,
      hint: "Tiny GN coccobacilli requiring prolonged incubation, from a veterinarian who drinks raw milk.",
    }],
    explanation: "Brucella melitensis (from goats/sheep) is the most virulent Brucella species. Intracellular pathogen requiring prolonged blood culture incubation (up to 21 days). BSL-3 organism — lab personnel at risk! Treatment: doxycycline + streptomycin/gentamicin for 6 weeks.",
    reference: "Bailey & Scott's Diagnostic Microbiology, 15th Ed.",
  },
  {
    id: "micro-028",
    title: "Candidal Vaginitis",
    department: "Microbiology",
    difficulty: "Beginner",
    patientAge: 29,
    patientGender: "Female",
    clinicalPresentation: "Thick white 'cottage cheese' vaginal discharge, vulvar itching and burning, dysuria.",
    history: "Recent course of broad-spectrum antibiotics for sinusitis. Currently pregnant (second trimester).",
    sampleType: "Vaginal swab",
    laboratoryFindings: [
      "KOH wet mount: Pseudohyphae and budding yeast cells",
      "Gram stain: Gram-positive budding yeast with pseudohyphae",
      "Sabouraud dextrose agar: Cream-colored pasty colonies at 37°C",
      "Germ tube test: Positive (>3 mm at 37°C in 2–3 hours)",
      "CHROMagar Candida: Green colonies",
    ],
    questions: [{
      question: "What is the causative organism?",
      options: ["Candida glabrata", "Candida albicans", "Candida tropicalis", "Candida krusei"],
      correctAnswer: 1,
      hint: "Germ-tube positive Candida species that produces green colonies on CHROMagar.",
    }],
    explanation: "C. albicans is the most common cause of vulvovaginal candidiasis (~90%). Germ tube test (Reynolds-Braude phenomenon) and green colonies on CHROMagar are specific. Risk factors: antibiotics, pregnancy, diabetes, immunosuppression. Treatment: topical azoles or oral fluconazole (not in pregnancy).",
    reference: "Bailey & Scott's Diagnostic Microbiology, 15th Ed.",
  },
  {
    id: "micro-029",
    title: "Tetanus",
    department: "Microbiology",
    difficulty: "Intermediate",
    patientAge: 55,
    patientGender: "Male",
    clinicalPresentation: "Jaw stiffness (trismus/lockjaw), generalized muscle spasms, opisthotonus, and risus sardonicus after stepping on a rusty nail 7 days ago.",
    history: "Farmer, last tetanus booster >15 years ago. Deep puncture wound on foot.",
    sampleType: "Clinical diagnosis (culture not reliable)",
    laboratoryFindings: [
      "Gram stain of wound: Gram-positive rods with terminal round spores (drumstick appearance)",
      "Anaerobic culture: Growth on blood agar anaerobically, swarming",
      "Diagnosis is primarily clinical — lab confirmation is difficult",
      "Spatula test: Positive (jaw reflex spasm on touching posterior pharyngeal wall)",
    ],
    questions: [{
      question: "What toxin-producing organism causes this condition?",
      options: ["Clostridium botulinum", "Clostridium tetani", "Clostridium perfringens", "Bacillus anthracis"],
      correctAnswer: 1,
      hint: "Gram-positive rod with drumstick (terminal) spores producing tetanospasmin.",
    }],
    explanation: "C. tetani produces tetanospasmin, which blocks inhibitory neurotransmitter (glycine/GABA) release → spastic paralysis. Diagnosis is clinical. Drumstick-shaped spores are characteristic. Treatment: tetanus immunoglobulin (TIG) + metronidazole + wound debridement + supportive care. Prevention: DTaP/Td vaccination.",
    reference: "Jawetz, Melnick & Adelberg's Medical Microbiology, 28th Ed.",
  },
  {
    id: "micro-030",
    title: "Aspergillosis (Invasive Pulmonary)",
    department: "Microbiology",
    difficulty: "Advanced",
    patientAge: 52,
    patientGender: "Male",
    clinicalPresentation: "Persistent fever unresponsive to broad-spectrum antibiotics, pleuritic chest pain, hemoptysis, in a neutropenic patient.",
    history: "AML on induction chemotherapy. Absolute neutrophil count (ANC) <100/µL for 12 days.",
    sampleType: "BAL fluid + serum",
    laboratoryFindings: [
      "KOH mount of BAL: Septate hyphae with acute-angle (dichotomous 45°) branching",
      "Lactophenol cotton blue: Septate hyphae, conidiophore with vesicle bearing phialides and chains of conidia",
      "Sabouraud agar: Velvety blue-green colonies with white border",
      "Serum galactomannan (GM) antigen: Positive (index >0.5)",
      "CT chest: Halo sign (ground-glass opacity surrounding nodule)",
    ],
    questions: [{
      question: "What is the causative organism?",
      options: ["Mucor/Rhizopus spp.", "Aspergillus fumigatus", "Pneumocystis jirovecii", "Cryptococcus neoformans"],
      correctAnswer: 1,
      hint: "Septate hyphae with 45° branching + galactomannan positive + halo sign in neutropenic patient.",
    }],
    explanation: "Aspergillus fumigatus is the most common cause of invasive aspergillosis in neutropenic patients. Key: septate hyphae with acute-angle (45°) branching (vs. Mucor: ribbon-like, pauci-septate, 90° branching). Galactomannan is a biomarker. Halo sign on CT is early finding. Treatment: voriconazole.",
    reference: "Bailey & Scott's Diagnostic Microbiology, 15th Ed.",
  },
];
