import { LabCase } from "./types";

export const molecularCases: LabCase[] = [
  {
    id: "mol-001",
    title: "PCR-Based MRSA Detection",
    department: "Molecular Biology / Genetics",
    difficulty: "Beginner",
    patientAge: 55,
    patientGender: "Male",
    clinicalPresentation: "Pre-surgical screening for MRSA nasal carriage before elective cardiac surgery.",
    history: "Scheduled for CABG. Hospital MRSA screening policy.",
    sampleType: "Nasal swab",
    laboratoryFindings: [
      "Rapid real-time PCR (GeneXpert/BD MAX): Targets SCCmec-orfX junction",
      "mecA gene: Detected",
      "Cycle threshold (Ct): 22 (strong positive, Ct <40 = positive)",
      "Internal control: Valid",
      "Result turnaround: 1 hour (vs. 48–72 h for culture)",
    ],
    questions: [{
      question: "What gene does MRSA PCR detect that confers methicillin resistance?",
      options: ["vanA", "mecA", "blaZ", "ermB"],
      correctAnswer: 1,
      hint: "This gene encodes PBP2a (altered penicillin-binding protein) with low affinity for β-lactams.",
    }],
    explanation: "mecA gene encodes PBP2a (penicillin-binding protein 2a) which has low affinity for all β-lactams (penicillins, cephalosporins, carbapenems — except ceftaroline). mecA is carried on the SCCmec mobile genetic element. Rapid PCR detects the SCCmec-orfX junction unique to S. aureus chromosome, avoiding false positives from mecA in CoNS. Low Ct = high bacterial load.",
    reference: "Molecular Cloning: A Laboratory Manual (Sambrook & Russell), 4th Ed.; CLSI M100.",
  },
  {
    id: "mol-002",
    title: "HIV Viral Load Monitoring",
    department: "Molecular Biology / Genetics",
    difficulty: "Intermediate",
    patientAge: 35,
    patientGender: "Male",
    clinicalPresentation: "Routine monitoring of HIV-positive patient on antiretroviral therapy (ART) for 6 months.",
    history: "Diagnosed HIV-positive 1 year ago. Started TDF/FTC/DTG. Baseline viral load: 150,000 copies/mL.",
    sampleType: "Plasma (EDTA)",
    laboratoryFindings: [
      "RT-qPCR for HIV-1 RNA viral load",
      "6-month result: <20 copies/mL (undetectable = target not detected below assay limit)",
      "Previous results: Baseline 150,000 → 3 months: 200 → 6 months: <20",
      "CD4 count: Increased from 250 to 450 cells/µL",
      "Genotypic resistance testing at baseline: No resistance mutations detected",
    ],
    questions: [{
      question: "What does 'undetectable viral load' mean for HIV treatment monitoring?",
      options: [
        "The virus is completely eradicated",
        "Viral RNA is below the lower limit of detection of the assay (typically <20–50 copies/mL), indicating virological suppression",
        "The patient no longer needs ART",
        "There are no CD4 T cells left to infect",
      ],
      correctAnswer: 1,
      hint: "Undetectable ≠ cured. Latent proviral DNA persists in reservoir cells.",
    }],
    explanation: "Undetectable HIV viral load means RNA is below assay detection limit (<20–50 copies/mL) = virological suppression. Goal of ART: achieve undetectable VL within 6 months. This does NOT mean cure — HIV proviral DNA persists in latent CD4+ T cell reservoirs. Undetectable = untransmittable (U=U). Virological failure: confirmed VL >200 copies/mL → genotypic resistance testing → switch regimen.",
    reference: "Molecular Cloning: A Laboratory Manual (Sambrook & Russell); DHHS HIV Treatment Guidelines.",
  },
  {
    id: "mol-003",
    title: "Sanger Sequencing for Mutation Detection",
    department: "Molecular Biology / Genetics",
    difficulty: "Intermediate",
    patientAge: 0,
    patientGender: "Neonate",
    clinicalPresentation: "Newborn screening (NBS) positive for elevated immunoreactive trypsinogen (IRT) — suggestive of cystic fibrosis.",
    history: "Both parents are of Northern European descent. NBS IRT > 99th percentile.",
    sampleType: "Blood (dried blood spot then EDTA)",
    laboratoryFindings: [
      "NBS IRT: Elevated (first and second specimens)",
      "Sweat chloride: 78 mmol/L (diagnostic, >60 mmol/L = CF)",
      "CFTR mutation panel (common mutations): ΔF508 heterozygous (one copy detected)",
      "Second mutation not identified on panel → Sanger sequencing of full CFTR gene",
      "Sanger result: c.1521_1523delCTT (ΔF508) + c.3846G>A (W1282X nonsense mutation)",
      "Compound heterozygote: ΔF508 / W1282X",
    ],
    questions: [{
      question: "Why is Sanger sequencing needed when the standard CFTR panel detects only one mutation?",
      options: [
        "Sanger is cheaper than panels",
        "Standard panels only test common mutations (~23–40); rare mutations require full gene sequencing to identify the second allele",
        "Sanger can detect large deletions",
        "Panels are unreliable",
      ],
      correctAnswer: 1,
      hint: "Over 2,000 CFTR variants exist, but screening panels cover only the most common.",
    }],
    explanation: "CFTR mutation panels detect ~85–90% of CF alleles (common mutations like ΔF508, G551D, etc.). When only one mutation is found but clinical evidence supports CF (elevated sweat chloride), full gene sequencing by Sanger or NGS is needed to find rare variants. ΔF508 (Class II — misfolding) is the most common CF mutation (~70% of alleles). Compound heterozygotes have different mutations on each CFTR allele.",
    reference: "Molecular Cloning: A Laboratory Manual (Sambrook & Russell), 4th Ed.",
  },
  {
    id: "mol-004",
    title: "Next-Generation Sequencing (NGS) — Tumor Profiling",
    department: "Molecular Biology / Genetics",
    difficulty: "Advanced",
    patientAge: 62,
    patientGender: "Female",
    clinicalPresentation: "Stage IV non-small cell lung cancer (NSCLC) — adenocarcinoma subtype. Seeking targeted therapy options.",
    history: "Never-smoker. Brain metastasis at diagnosis. No family cancer history.",
    sampleType: "FFPE tumor tissue + cell-free DNA (liquid biopsy)",
    laboratoryFindings: [
      "NGS panel (>500 genes): Comprehensive genomic profiling",
      "Driver mutation: EGFR exon 19 deletion (L747_P753delinsS) — pathogenic",
      "Co-mutations: TP53 R248W (pathogenic), no KRAS/ALK/ROS1",
      "TMB: 4 mut/Mb (low — unlikely to respond to immunotherapy alone)",
      "MSI status: MSS (microsatellite stable)",
      "PD-L1 TPS: 10% (low expression)",
      "Liquid biopsy (cfDNA): Concordant EGFR exon 19 deletion detected (VAF 12%)",
    ],
    questions: [{
      question: "What targeted therapy is recommended for EGFR exon 19 deletion in NSCLC?",
      options: ["Crizotinib (ALK inhibitor)", "Osimertinib (3rd-gen EGFR TKI)", "Pembrolizumab (anti-PD-1)", "Bevacizumab (anti-VEGF)"],
      correctAnswer: 1,
      hint: "Third-generation EGFR tyrosine kinase inhibitor with CNS penetration — preferred first-line.",
    }],
    explanation: "EGFR exon 19 deletion is the most common sensitizing EGFR mutation in NSCLC (~45% of EGFR-mutant cases). Osimertinib (3rd-gen TKI) is first-line: superior PFS, CNS penetration (important for brain metastases), active against T790M resistance. NGS enables comprehensive profiling in a single test. Liquid biopsy (cfDNA) is used when tissue is unavailable or for monitoring resistance.",
    reference: "Molecular Cloning: A Laboratory Manual; NCCN NSCLC Guidelines.",
  },
  {
    id: "mol-005",
    title: "FISH for HER2 Amplification",
    department: "Molecular Biology / Genetics",
    difficulty: "Intermediate",
    patientAge: 48,
    patientGender: "Female",
    clinicalPresentation: "Breast cancer — core biopsy shows invasive ductal carcinoma. HER2 IHC result is equivocal (2+).",
    history: "Palpable breast mass. Mammography and ultrasound suspicious.",
    sampleType: "FFPE tissue (core biopsy block)",
    laboratoryFindings: [
      "HER2 IHC: 2+ (equivocal — incomplete/weak membrane staining in >10% cells)",
      "FISH ordered for definitive HER2 status",
      "FISH dual-probe: HER2 signals (red) and CEP17 signals (green) counted per cell",
      "Average HER2 signals/cell: 12",
      "Average CEP17 signals/cell: 2.2",
      "HER2/CEP17 ratio: 5.5 (≥2.0 = amplified)",
      "Interpretation: HER2 AMPLIFIED → eligible for trastuzumab",
    ],
    questions: [{
      question: "When is FISH testing required for HER2 in breast cancer?",
      options: [
        "When IHC is 0 or 1+ (negative)",
        "When IHC is 2+ (equivocal)",
        "When IHC is 3+ (positive)",
        "FISH is always required regardless of IHC",
      ],
      correctAnswer: 1,
      hint: "IHC 0/1+ = negative, IHC 3+ = positive, IHC 2+ = needs confirmation by in situ hybridization.",
    }],
    explanation: "ASCO/CAP HER2 testing algorithm: IHC first → 0/1+ = negative (no further testing), 3+ = positive (trastuzumab eligible), 2+ = EQUIVOCAL → reflex to ISH (FISH/CISH/SISH). FISH: HER2/CEP17 ratio ≥2.0 AND/OR average HER2 copy number ≥6.0 = amplified. Dual-probe FISH uses HER2 probe + chromosome 17 centromere (CEP17) to account for polysomy.",
    reference: "Molecular Cloning: A Laboratory Manual; ASCO/CAP HER2 Testing Guidelines.",
  },
  {
    id: "mol-006",
    title: "RT-PCR for COVID-19 Diagnosis",
    department: "Molecular Biology / Genetics",
    difficulty: "Beginner",
    patientAge: 45,
    patientGender: "Female",
    clinicalPresentation: "Fever, cough, anosmia (loss of smell), and myalgia for 3 days.",
    history: "Close contact with confirmed COVID-19 case 5 days ago.",
    sampleType: "Nasopharyngeal swab",
    laboratoryFindings: [
      "RT-qPCR targets: N gene, E gene, RdRp gene",
      "N gene Ct: 18 (strongly positive)",
      "E gene Ct: 19 (strongly positive)",
      "RdRp gene Ct: 20 (strongly positive)",
      "Internal control (RNase P): Ct 28 (valid — human cells collected)",
      "Result: SARS-CoV-2 RNA DETECTED",
    ],
    questions: [{
      question: "Why does COVID-19 PCR require reverse transcriptase (RT) before amplification?",
      options: [
        "To convert DNA to RNA",
        "SARS-CoV-2 is an RNA virus; RT converts viral RNA to cDNA which can then be amplified by PCR",
        "To increase test sensitivity",
        "RT is used for all PCR tests",
      ],
      correctAnswer: 1,
      hint: "Standard PCR amplifies DNA. RNA viruses require an extra step to create a DNA template.",
    }],
    explanation: "SARS-CoV-2 is a positive-sense single-stranded RNA virus. PCR requires a DNA template. Reverse transcriptase (RT) converts viral RNA → complementary DNA (cDNA), which is then amplified by real-time PCR. Low Ct values (<25) indicate high viral load (exponentially more starting template). Multiple gene targets improve sensitivity and specificity. Internal control (human gene like RNase P) validates specimen collection.",
    reference: "Molecular Cloning: A Laboratory Manual (Sambrook & Russell); WHO COVID-19 PCR Protocol.",
  },
  {
    id: "mol-007",
    title: "Gel Electrophoresis Troubleshooting",
    department: "Molecular Biology / Genetics",
    difficulty: "Beginner",
    patientAge: 0,
    patientGender: "Male",
    clinicalPresentation: "Molecular biology lab: PCR product expected at 500 bp. Gel electrophoresis shows unexpected results.",
    history: "Student performing PCR for 16S rRNA gene identification of unknown bacterium.",
    sampleType: "PCR product",
    laboratoryFindings: [
      "1% agarose gel in TAE buffer, stained with ethidium bromide",
      "Lane 1 (DNA ladder): Bands visible at 100, 200, 500, 1000, 2000 bp",
      "Lane 2 (positive control): Single band at 500 bp (expected)",
      "Lane 3 (test sample): Band at 500 bp + additional band at ~1200 bp (non-specific product)",
      "Lane 4 (negative control — no template): No bands (clean)",
    ],
    questions: [{
      question: "What should be done to eliminate the non-specific 1200 bp band?",
      options: [
        "Run the gel longer",
        "Increase annealing temperature or use touchdown PCR to improve primer specificity",
        "Add more template DNA",
        "Use a higher percentage gel",
      ],
      correctAnswer: 1,
      hint: "Non-specific bands indicate primers are annealing to unintended sequences at lower temperatures.",
    }],
    explanation: "Non-specific PCR products result from primers annealing to unintended target sequences at low stringency. Solutions: (1) Increase annealing temperature (2–5°C increments), (2) Use touchdown PCR (start high, decrease gradually), (3) Optimize MgCl₂ concentration (excess promotes non-specific binding), (4) Use hot-start Taq polymerase, (5) Redesign primers with higher Tm and specificity (BLAST check).",
    reference: "Molecular Cloning: A Laboratory Manual (Sambrook & Russell), 4th Ed.",
  },
  {
    id: "mol-008",
    title: "Newborn Screening — Sickle Cell by IEF/HPLC",
    department: "Molecular Biology / Genetics",
    difficulty: "Intermediate",
    patientAge: 0,
    patientGender: "Neonate",
    clinicalPresentation: "Routine newborn screening (NBS) at 48 hours of life.",
    history: "Parents of West African descent. No known hemoglobinopathy in family.",
    sampleType: "Dried blood spot (heel prick)",
    laboratoryFindings: [
      "Isoelectric focusing (IEF): FS pattern (Fetal hemoglobin + Sickle hemoglobin, no HbA)",
      "Confirmatory HPLC: HbF 78%, HbS 20%, HbA 0%, HbA2 2%",
      "Solubility test: Not reliable in neonates (high HbF interferes)",
      "DNA analysis (if needed): βS/βS genotype confirmed",
      "Reticulocyte count: 8% (elevated for age)",
    ],
    questions: [{
      question: "What does an FS pattern on newborn hemoglobin screening indicate?",
      options: [
        "Sickle cell trait (FAS pattern)",
        "Presumptive sickle cell disease — only HbF and HbS present, no HbA",
        "Normal newborn (FA pattern)",
        "Beta-thalassemia trait",
      ],
      correctAnswer: 1,
      hint: "In NBS, F = fetal hemoglobin (predominant), S = sickle hemoglobin, A = adult hemoglobin. No A = disease.",
    }],
    explanation: "Newborn screening patterns: FA = normal (HbF + HbA), FAS = sickle trait (HbF + HbA + HbS), FS = sickle cell disease (no HbA — either HbSS or HbSβ⁰-thal), FSC = HbSC disease. IEF or HPLC detects hemoglobin variants. Solubility test is unreliable in neonates due to high HbF. FS pattern requires confirmatory testing and urgent referral for penicillin prophylaxis (to prevent pneumococcal sepsis).",
    reference: "Molecular Cloning: A Laboratory Manual; Rodak's Hematology, 6th Ed.",
  },
  {
    id: "mol-009",
    title: "Pharmacogenomics — Warfarin Dosing",
    department: "Molecular Biology / Genetics",
    difficulty: "Advanced",
    patientAge: 68,
    patientGender: "Male",
    clinicalPresentation: "New atrial fibrillation, started on warfarin 5 mg daily. After 5 days, INR is supratherapeutic at 5.8 (target: 2–3).",
    history: "No history of liver disease or drug interactions. Low body weight.",
    sampleType: "Blood (EDTA) for pharmacogenomic testing",
    laboratoryFindings: [
      "CYP2C9 genotype: *1/*3 (intermediate metabolizer)",
      "VKORC1 genotype: −1639 A/A (high sensitivity to warfarin)",
      "CYP4F2 genotype: *1/*1 (normal)",
      "Predicted warfarin dose (FDA algorithm): 2.5 mg/day (much lower than standard 5 mg)",
      "Current INR: 5.8 (supratherapeutic → bleeding risk)",
    ],
    questions: [{
      question: "How do CYP2C9 and VKORC1 variants affect warfarin dosing?",
      options: [
        "Both increase warfarin metabolism → higher doses needed",
        "CYP2C9 variants decrease warfarin metabolism (↑drug level); VKORC1 A/A decreases target enzyme production (↑sensitivity) → LOWER doses needed",
        "Only VKORC1 affects dosing; CYP2C9 is irrelevant",
        "These genes only affect warfarin when combined with aspirin",
      ],
      correctAnswer: 1,
      hint: "CYP2C9 metabolizes warfarin (variants = slower clearance); VKORC1 produces the target enzyme.",
    }],
    explanation: "Warfarin pharmacogenomics: CYP2C9 metabolizes S-warfarin (active enantiomer). *2 and *3 variants reduce metabolism → higher drug levels. VKORC1 is warfarin's target enzyme (vitamin K epoxide reductase). VKORC1 −1639 A/A genotype produces less VKORC1 → more sensitive to warfarin → lower dose needed. FDA-approved dosing algorithm incorporates both genes + clinical factors. Pharmacogenomic testing can prevent adverse drug reactions.",
    reference: "Molecular Cloning: A Laboratory Manual; PharmGKB Warfarin Guidelines.",
  },
  {
    id: "mol-010",
    title: "Southern Blot for Fragile X Syndrome",
    department: "Molecular Biology / Genetics",
    difficulty: "Advanced",
    patientAge: 4,
    patientGender: "Male",
    clinicalPresentation: "Intellectual disability, delayed speech, large ears, long face, and macroorchidism (post-pubertal finding in older males).",
    history: "Maternal uncle had intellectual disability. No diagnosis was made.",
    sampleType: "Blood (EDTA)",
    laboratoryFindings: [
      "Standard CGG repeat PCR: Failed to amplify (suggests very large expansion)",
      "Southern blot with methylation analysis:",
      "Normal FMR1: ~30 CGG repeats (5.2 kb fragment with EcoRI/EagI)",
      "Patient result: >200 CGG repeats (large, smeared band >6.5 kb), fully methylated",
      "Interpretation: Full mutation (>200 repeats) with methylation → FMR1 gene silenced",
      "Maternal testing: 80 CGG repeats (premutation carrier, 55–200 repeats)",
    ],
    questions: [{
      question: "Why does Southern blot with methylation analysis remain important for Fragile X diagnosis?",
      options: [
        "It's cheaper than PCR",
        "Standard PCR cannot amplify very large CGG expansions (>200 repeats), and Southern blot also detects methylation status which determines clinical significance",
        "Southern blot is faster",
        "PCR cannot detect any trinucleotide repeats",
      ],
      correctAnswer: 1,
      hint: "Full mutations (>200 CGG) are too large for standard PCR, and methylation determines gene silencing.",
    }],
    explanation: "Fragile X syndrome: FMR1 gene CGG repeat expansion. Normal <45, premutation 55–200, full mutation >200 repeats + methylation → gene silencing → absent FMRP protein → intellectual disability. Standard PCR fails at >200 repeats (GC-rich, large size). Southern blot: (1) detects large expansions, (2) determines methylation status (EagI is methylation-sensitive). Triplet repeat primed PCR (TP-PCR) is newer but Southern blot remains gold standard for full characterization.",
    reference: "Molecular Cloning: A Laboratory Manual (Sambrook & Russell), 4th Ed.",
  },
];
